### ISSUE TITLE
交流群已经满人，可以开设一个新的交流群

### ISSUE THREAD

**Issue by chmod777john** [THUDM/GLM-4#1]
### Feature request  / 功能建议

可以开设新的交流群，因为从 README 进去的群聊已满。

![image](https://github.com/THUDM/GLM-4/assets/146207719/b6033b55-3323-4f58-9fcc-19858a6ca05e)

### Motivation / 动机

方便大家交流和提出反馈

### Your contribution / 您的贡献

.

**Comment by DataXujing** [comment]
[智谱AI] 真是太良心了

**Comment by zRzRzRzRzRzRzR** [comment]
从微信公众号那边走动态码进群
