### ISSUE TITLE
composite_demo 中 GLM-4 Demo 文档解读对话报错，全量和Int4都报同样错误。

### ISSUE THREAD

**Issue by wikeeyang** [THUDM/GLM-4#100]
### System Info / 系統信息

Windows 11 x64、Python3.11.9、torch 2.3.0、cuda 12.1，显卡为 P40 24GB，其它按官方 requirements.txt 要求版本。
单独通过 gradio 加载 glm-4-9b-chat-1m、glm-4v-9b 模型，全量与量化，对话都正常。
终端窗口运行日志如下：

  You can now view your Streamlit app in your browser.

  URL: http://127.0.0.1:18888

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████| 10/10 [00:19<00:00,  2.00s/it]
D:\AITest\ChatGLM4-9B\checkpoints\modules\transformers_modules\glm-4-9b-chat-1m\modeling_chatglm.py:189: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  context_layer = torch.nn.functional.scaled_dot_product_attention(query_layer, key_layer, value_layer,
Traceback (most recent call last):
  File "D:\AITest\ChatGLM4-9B\composite_demo\src\main.py", line 287, in main
    for response, chat_history in client.generate_stream(
  File "D:\AITest\ChatGLM4-9B\composite_demo\src\clients\hf.py", line 58, in generate_stream
    for token_text in streamer:
  File "D:\AITest\ChatGLM4-9B\Python311\Lib\site-packages\transformers\generation\streamers.py", line 223, in __next__
    value = self.text_queue.get(timeout=self.timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AITest\ChatGLM4-9B\Python311\Lib\queue.py", line 179, in get
    raise Empty
_queue.Empty
Traceback (most recent call last):
  File "D:\AITest\ChatGLM4-9B\composite_demo\src\main.py", line 287, in main
    for response, chat_history in client.generate_stream(
  File "D:\AITest\ChatGLM4-9B\composite_demo\src\clients\hf.py", line 58, in generate_stream
    for token_text in streamer:
  File "D:\AITest\ChatGLM4-9B\Python311\Lib\site-packages\transformers\generation\streamers.py", line 223, in __next__
    value = self.text_queue.get(timeout=self.timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AITest\ChatGLM4-9B\Python311\Lib\queue.py", line 179, in get
    raise Empty
_queue.Empty

一直重复这个错误，直至显存爆了。。。

Web 界面截图如下，文档内容识别很正常，就是对话内容总是报队列内容空的错误：

![2024-06-07_113120](https://github.com/THUDM/GLM-4/assets/131220899/ea624cd0-0f51-41e7-a6c7-4f837386c6a8)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

BitsAndBytes NF4 量化，配置如下：
nf4_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)
模型加载没问题，就是文档提交，文档解析完后，对话时报错。

### Expected behavior / 期待表现

请大佬们帮忙分析分析，协助解决，谢谢！

**Comment by davidlvxin** [comment]
如果试试直接对话呢，会有问题吗？

**Comment by wikeeyang** [comment]
感谢您的快速回复，4bit量化下，可以先加载对话模型，正常对话，然后再点击VL模型，我看显存原来的对话模型并未释放，而是直接加上去了，VL模型对话也正常，就是：工具调用(All Tools)、文档解读、多模态)三个状态下，对话都正常，但不管加载文档、还是加载图片，再对话就报上述错了，错误信息都一样。如下图：

ALL Tools 状态对话正常：
![2024-06-07_122153](https://github.com/THUDM/GLM-4/assets/131220899/e3e7eafa-d09c-4952-883c-15b2d395392e)

显存占用情况，及终端信息，无任何报错：
![2024-06-07_122220](https://github.com/THUDM/GLM-4/assets/131220899/68d7c376-1f7c-4faa-9f45-2a2d2fbced65)

然后点击文档解读状态对话，也正常：
![2024-06-07_122346](https://github.com/THUDM/GLM-4/assets/131220899/49c26011-2bbf-4ba6-8630-31d633891c9f)

再点击多模态，两个模型直接都加载上了，默认采用 4bit 量化：
![2024-06-07_122535](https://github.com/THUDM/GLM-4/assets/131220899/1731eae3-5cc7-412c-8cb5-5c351cfdb3cb)

然后正常对话，对话后就无法中途加载图片了，只能 Clear 后，可以先加载图片，再对话：
![2024-06-07_122552](https://github.com/THUDM/GLM-4/assets/131220899/b72af59f-4695-40df-8e2d-bd7a661bcd38)

加载图片后对话，就出现跟加载文档解析后对话的情况一样的错误。
![2024-06-07_123103](https://github.com/THUDM/GLM-4/assets/131220899/5b506385-0c85-4c7a-971f-c6f114029832)

我也不知道什么原因，别人都正常，我的好像是上传文档、图片后，后台线程没返回来读取 prompt 似的，所以 Queue 里面是空的。烦请大佬给分析分析，谢谢！

**Comment by wikeeyang** [comment]
补充一下，单独用 Gradio 的 Web Demo，对话模型对话很正常，但没法使用 工具和文档解析；VL模型使用正常，能上传图片和依据图片内容对话。没任何问题，就是在 composite_demo 的 streamlit 界面下，上传文件再对话就报上述错误，错误信息都相同。

![2024-06-06_161807](https://github.com/THUDM/GLM-4/assets/131220899/1a26348e-d202-4f6c-aff2-c65305391660)

**Comment by wikeeyang** [comment]
已找到问题原因：
composite_demo\src\clients\hf.py文件第44行，timeout=5,
时间设置太短，改成大一些就好了，不好意思，可能我设备比较老旧，响应没那么快。。。(,,・ω・,,)

**Comment by mashibin** [comment]
> 已找到问题原因： composite_demo\src\clients\hf.py文件第44行，timeout=5, 时间设置太短，改成大一些就好了，不好意思，可能我设备比较老旧，响应没那么快。。。(,,・ω・,,)

老哥 改成多少啊 我设60000还是报这个错

**Comment by wikeeyang** [comment]
> > 已找到问题原因： composite_demo\src\clients\hf.py文件第44行，timeout=5, 时间设置太短，改成大一些就好了，不好意思，可能我设备比较老旧，响应没那么快。。。(,,・ω・,,)
> 
> 老哥 改成多少啊 我设60000还是报这个错

我是改成 50 就可以了，具体多少合适，我也不知道，但肯定不是越大就越好，你改成 50 - 500 之间试试。。。🤣🤣🤣
