### ISSUE TITLE
异步线程异常，使用的是openai_api_server.py这个文件

### ISSUE THREAD

**Issue by yellowaug** [THUDM/GLM-4#101]
### System Info / 系統信息

A30 24G CUDA12.4  Docker 容器

### Who can help? / 谁可以帮助到您？

glm4_vllm_api_server-glm4_vllm_server-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
glm4_vllm_api_server-glm4_vllm_server-1  |     await app(scope, receive, sender)
glm4_vllm_api_server-glm4_vllm_server-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 72, in app
glm4_vllm_api_server-glm4_vllm_server-1  |     response = await func(request)
glm4_vllm_api_server-glm4_vllm_server-1  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 278, in app
glm4_vllm_api_server-glm4_vllm_server-1  |     raw_response = await run_endpoint_function(
glm4_vllm_api_server-glm4_vllm_server-1  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 191, in run_endpoint_function
glm4_vllm_api_server-glm4_vllm_server-1  |     return await dependant.call(**values)
glm4_vllm_api_server-glm4_vllm_server-1  |   File "/glm4/basic_demo/openai_api_server.py", line 317, in create_chat_completion
glm4_vllm_api_server-glm4_vllm_server-1  |     output = await anext(predict_stream_generator)
glm4_vllm_api_server-glm4_vllm_server-1  |   File "/glm4/basic_demo/openai_api_server.py", line 458, in predict_stream
glm4_vllm_api_server-glm4_vllm_server-1  |     async  for new_response in generate_stream_glm4(gen_params):
glm4_vllm_api_server-glm4_vllm_server-1  |   File "/glm4/basic_demo/openai_api_server.py", line 199, in generate_stream_glm4
glm4_vllm_api_server-glm4_vllm_server-1  |     async for output in engine.generate(inputs=inputs, sampling_params=sampling_params, request_id="glm-4-9b"):
glm4_vllm_api_server-glm4_vllm_server-1  |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 662, in generate
glm4_vllm_api_server-glm4_vllm_server-1  |     async for output in self._process_request(
glm4_vllm_api_server-glm4_vllm_server-1  |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 756, in _process_request
glm4_vllm_api_server-glm4_vllm_server-1  |     stream = await self.add_request(
glm4_vllm_api_server-glm4_vllm_server-1  |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 561, in add_request
glm4_vllm_api_server-glm4_vllm_server-1  |     self.start_background_loop()
glm4_vllm_api_server-glm4_vllm_server-1  |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 431, in start_background_loop
glm4_vllm_api_server-glm4_vllm_server-1  |     raise AsyncEngineDeadError(
glm4_vllm_api_server-glm4_vllm_server-1  | vllm.engine.async_llm_engine.AsyncEngineDeadError: Background loop has errored already

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

多点访问量即可复现

### Expected behavior / 期待表现

希望能修复这个bug

**Comment by zRzRzRzRzRzRzR** [comment]
emm这个是单并发的呀，没有做并发的任务管理的
