### ISSUE TITLE
lora微调后模型，怎样通过vllm部署调用

### ISSUE THREAD

**Issue by dannypei** [THUDM/GLM-4#102]
### System Info / 系統信息

python3.10 cuda2.2 显存24G

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

请问lora微调后模型，怎样通过vllm部署调用，能否给一下示例代码

### Expected behavior / 期待表现

能增加一些Demo样例

**Comment by morettt** [comment]
这个我也想知道

**Comment by zRzRzRzRzRzRzR** [comment]
直接根据vLLM官方教程修改合并Lora模块的读取部分就行了，没有额外的修改，仅需按照vLLM官方的实现自己改代码
