### ISSUE TITLE
composite_demo启动之后无法访问。

### ISSUE THREAD

**Issue by douyh** [THUDM/GLM-4#106]
### System Info / 系統信息

centos7

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![image](https://github.com/THUDM/GLM-4/assets/34704737/47bb7a69-28d8-4973-9560-c43c64a80e2e)
安装pnpm的时候出现了一些网络错误，导致无法安装

![image](https://github.com/THUDM/GLM-4/assets/34704737/1ca93477-d2d6-4e8e-bc05-9205c8d1103f)

然后启动之后使用Network URL就无法访问

![image](https://github.com/THUDM/GLM-4/assets/34704737/77ca40a8-381b-44c7-a591-7b7d232bcf45)

请问有什么解决办法吗？

### Expected behavior / 期待表现

是否有其他的启动方式？

**Comment by douyh** [comment]
补充一个，虽然我将THUM文件夹放在了composite_demo文件夹下面，似乎也并没有打印加载模型的信息

**Comment by zRzRzRzRzRzRzR** [comment]
npm这些是必须要装的呀
