### ISSUE TITLE
Multi-image input support for GLM-4V-9B?

### ISSUE THREAD

**Issue by ROIM1998** [THUDM/GLM-4#107]
Hi! I really appreciate your great work here. I'm wondering if your GLM-4V-9B model supports multi-image inputs. Since it supports multi-round conversation for inference, I assume I should be able to inject multiple images with multiple user queries, right? But can I do it if I want to have multiple images in a single user's query? Thanks!

**Comment by ROIM1998** [comment]
okay thanks for answering that! I'll close the issue.

**Comment by DefinitlyEvil** [comment]
could you explain why it only supports one image?
