### ISSUE TITLE
int4量化胡乱输出问题

### ISSUE THREAD

**Issue by FloatFrank** [THUDM/GLM-4#109]
### System Info / 系統信息

Windows，其余版本与basic Readme中同步

### Who can help? / 谁可以帮助到您？

int4量化（输出不停，且胡乱）
推理时首先报错： UserWarning: 1Torch was not compiled with flash attention.
不管这个，看输出
Q：hello
A：amento de seguridad y salud ocupacional. Es un documento que contiene las políticas, procedimientos y programas necesarios para proteger la vida, integridad física y moral del personal a su cargo.
5.1.2 Condiciones de trabajo: son los factores ambientales (físicos o químicos), organizacionales o psicológicos, relacionados con el ambiente laboral en cuanto al diseño físico, la distribución geográfica de actividades, el equipo utilizado por el trabajador, sus tareas, la organización y administración de la empresa u organismo público, entre otros aspectos.
5.1.3 Condiciones físicas de trabajo: es todo lo referente a la temperatura, humedad, iluminación, ventilación, ruido y vibraciones mecánicas, radiación electromagnética, contaminantes químicos, biológicos y físicos presentes en el medio ambiente de trabajo...

Q：你好
A：বাংলা স্থিরকৃতমন্দ আইনিভেষণ...

Q：你叫什么名字
A：আপনার নাম কী? ឈ្មោះ​របស់​អ្នក​គឺ​ខ្លាំង?(3) What is your address? তাৎস্থানের বিষয়ে জানি দিন।(4) How long have you been in this country? এখানে অবশ্যভাগে কল্পনা হ’ল এই উদ্ধৃতি

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

def load_model_and_tokenizer(
        model_dir: Union[str, Path], trust_remote_code: bool = True
) -> tuple[ModelType, TokenizerType]:
    model_dir = _resolve_path(model_dir)
    if (model_dir / 'adapter_config.json').exists():
        model = AutoPeftModelForCausalLM.from_pretrained(
            **model_dir, low_cpu_mem_usage=True,trust_remote_code=True, load_in_4bit=True**
        )
        tokenizer_dir = model.peft_config['default'].base_model_name_or_path
    else:
        model = AutoModelForCausalLM.from_pretrained(
            **model_dir, low_cpu_mem_usage=True,trust_remote_code=True, load_in_4bit=True**
        )
        tokenizer_dir = model_dir
    tokenizer = AutoTokenizer.from_pretrained(
        tokenizer_dir, trust_remote_code=trust_remote_code, use_fast=False
    )
    return model, tokenizer

### Expected behavior / 期待表现

正常运行

**Comment by zRzRzRzRzRzRzR** [comment]
这个真的是按照依赖装的吗，你的模型是glm-4-9b吗，显卡是啥

**Comment by FloatFrank** [comment]
> 这个真的是按照依赖装的吗，你的模型是glm-4-9b吗，显卡是啥

没问题了！正准备说！我下载成了预训练模型，那天忘了指定-chat版本。换成chat版本模型正常了。谢谢

**Comment by xbsdsongnan** [comment]
我的还是乱码，到底是哪里问题呢

**Comment by iicedream** [comment]
我也是乱码，不知道是不是因为不支持BF16的问题，我是rtx2060s的显卡
