### ISSUE TITLE
ms-swift支持了glm-4v-9b多模态大模型的微调(finetune)🚀😊 

### ISSUE THREAD

**Issue by Jintao-Huang** [THUDM/GLM-4#11]
ms-swift多模态大模型微调框架集成了glm-4v-9b的推理和微调, 并书写了最佳实践: [https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/glm4v%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md](https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/glm4v%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md)

如果有感兴趣的小伙伴, 欢迎来使用😊

The ms-swift multi-modal large model fine-tuning framework integrates the inference and fine-tuning of glm-4v-9b, and provides best practice documentation: [https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/glm4v%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md](https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/glm4v%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md)

If you are interested, feel free to give it a try! 😊

**Comment by zRzRzRzRzRzRzR** [comment]
已经将其添加到了友情链接，本issue关闭啦
