### ISSUE TITLE
胡乱输出问题GLM-4-9B-chat

### ISSUE THREAD

**Issue by xbsdsongnan** [THUDM/GLM-4#112]
### System Info / 系統信息

python==3..10.12

### Who can help? / 谁可以帮助到您？

![微信图片_20240607160338](https://github.com/THUDM/GLM-4/assets/26727621/886a7097-be94-414a-aba2-5bb1429c661c)

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

问啥都是乱说

### Expected behavior / 期待表现

正常
![微信图片_20240607160338](https://github.com/THUDM/GLM-4/assets/26727621/4b4678b4-8842-4a3f-9d07-70b6ecf902f7)

**Comment by zRzRzRzRzRzRzR** [comment]
你的载入代码是啥，是int4吗

**Comment by FloatFrank** [comment]
> 你的载入代码是啥，是int4吗

没问题了！正准备说！我下载成了预训练模型，那天忘了指定-chat版本。换成chat版本模型正常了。谢谢

**Comment by xbsdsongnan** [comment]
我下载的就是chat版本的模型，是代码再哪里指定么，不是int4，用的这个代码trans_web_demo.py，模型是我提前下载好的

**Comment by FloatFrank** [comment]
> > > 你的载入代码是啥，是int4吗
> > 
> > 
> > 没问题了！正准备说！我下载成了预训练模型，那天忘了指定-chat版本。换成chat版本模型正常了。谢谢
> 
> 我的还没有解决

哥们，你重新开一个issue吧，咱俩是同一时间提出的问题。我以为你这个是那个问题，就在你这个issue回复了，不过我觉得很有可能是你下错模型了
