### ISSUE TITLE
关于function call的bug， 发现 function call name 必须 get_ 开头，非常奇怪😂

### ISSUE THREAD

**Issue by Qingluan** [THUDM/GLM-4#113]
### System Info / 系統信息

 NVIDIA-SMI 525.147.05   Driver Version: 525.147.05   CUDA Version: 12.0
ubuntu 22.04

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

官方的 tools
 tools = [
        {
            "type": "function",
            "function": {
                "name": "get_current_weather",
                "description": "Get the current weather in a given location",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "location": {
                            "type": "string",
                            "description": "The city and state, e.g. San Francisco, CA",
                        },
                        "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
                    },
                    "required": ["location"],
                },
            },
        }
    ]
就可以，
但是我的
{'type': 'function', 'function': {'name': 'kill-task', 'parameters': {'type': 'object', 'properties': {'name': {'type': 'string'}, 'pid': {'default': 'int =', 'type': 'string'}}, 'required': ['name']}, 'description': 'kill process by name or pid, if pid > 0 name will not work'}}
就死活没法在 finish_reseson 上设置为function call， 且role也不对，虽然模型很给力的 给我返回标准调用格式，但是meta信息不对

### Expected behavior / 期待表现

期望能给出更多关于function call怎么写，和注意事项的文档

**Comment by zRzRzRzRzRzRzR** [comment]
嗯这个是glm3代码直接移植过来的问题，我还会改一下

**Comment by Qingluan** [comment]
1 .  然后在 if output: 这里也有bug哈，如果是function call 第一个就应该触发，但是这里进入Event没法作为call 返回了，所以我经常会返回空，
https://github.com/THUDM/GLM-4/blob/7fcaeba6ccb5304c92b78129d3967ebf4e78b38d/basic_demo/openai_api_server.py#L314-L341
2.  关于request id，这里从glm-4-9b改成time.time() 后发现，function call 和回答变傻了，不知道是我错觉还是怎么了，原来的版本好歹，会返回正确的call ，现在会乱说
https://github.com/THUDM/GLM-4/blob/7fcaeba6ccb5304c92b78129d3967ebf4e78b38d/basic_demo/openai_api_server.py#L198

**Comment by Qingluan** [comment]
> 嗯这个是glm3代码直接移植过来的问题，我还会改一下

1 .  然后在 if output: 这里也有bug哈，如果是function call 第一个就应该触发，但是这里进入Event没法作为call 返回了，所以我经常会返回空，
https://github.com/THUDM/GLM-4/blob/7fcaeba6ccb5304c92b78129d3967ebf4e78b38d/basic_demo/openai_api_server.py#L314-L341
2.  关于request id，这里从glm-4-9b改成time.time() 后发现，function call 和回答变傻了，不知道是我错觉还是怎么了，原来的版本好歹，会返回正确的call ，现在会乱说
https://github.com/THUDM/GLM-4/blob/7fcaeba6ccb5304c92b78129d3967ebf4e78b38d/basic_demo/openai_api_server.py#L198

**Comment by zRzRzRzRzRzRzR** [comment]
已经修
