### ISSUE TITLE
关于basic_demo/openai_api_server.py 对 function_call 的修改，已提交issues实在手痒，先改了一版本

### ISSUE THREAD

**Issue by Qingluan** [THUDM/GLM-4#119]
https://github.com/THUDM/GLM-4/blob/7fcaeba6ccb5304c92b78129d3967ebf4e78b38d/basic_demo/openai_api_server.py#L314-L340

这段要改成以下才能用function 稳定的调用，但是注意要把 tool 名字 以 'get_' 开头

> 但是注意要把 tool 名字 以 'get_' 开头
> 但是注意要把 tool 名字 以 'get_' 开头
> 但是注意要把 tool 名字 以 'get_' 开头

```python

    if request.stream:
        predict_stream_generator = predict_stream(request.model, gen_params)
        output = await anext(predict_stream_generator)
        logger.debug(f"First result output：\n{output}")
        
        
        function_call = None
        if output and request.tools:
            # print(f"==== output tools ====\n{output}")
            try:
                function_call = process_response(output, use_tool=True)
            except:
                logger.warning("Failed to parse tool call")

        # CallFunction
        if isinstance(function_call, dict):
            # print(f"==== function_call ====\n{function_call}")
            function_call = FunctionCallResponse(**function_call)

            # tool_response = ""
            # if not gen_params.get("messages"):
            #     gen_params["messages"] = []
            # gen_params["messages"].append(ChatMessage(role="assistant", content=output))
            # gen_params["messages"].append(ChatMessage(role="tool", name=function_call.name, content=tool_response))
            # generate = predict(request.model, gen_params)
            # return EventSourceResponse(generate, media_type="text/event-stream")
            generate = parse_output_text(request.model, output, function_call=function_call)
            return EventSourceResponse(generate, media_type="text/event-stream")
        else:
            # if output:
            # print(f"==== output ====\n{output}")
            # print(f"==== no function_call ====\n{output}")
            
            return EventSourceResponse(predict_stream_generator, media_type="text/event-stream")
            
```

然后其中 *parse_output_text* 函数也要改成以下这样
```python

async def parse_output_text(model_id: str, value: str, function_call: FunctionCallResponse = None):
    delta = DeltaMessage(role="assistant", content=value)
    if function_call is not None:
        delta.function_call = function_call

    choice_data = ChatCompletionResponseStreamChoice(
        index=0,
        delta=delta,
        finish_reason=None
    )
    chunk = ChatCompletionResponse(model=model_id, id="", choices=[choice_data], object="chat.completion.chunk")
    yield "{}".format(chunk.model_dump_json(exclude_unset=True))
    delta2 = DeltaMessage()
    if function_call is not None:
        delta2.function_call = function_call
    choice_data = ChatCompletionResponseStreamChoice(
        index=0,
        delta=delta2,
        finish_reason="stop"
    )
    if function_call is not None:
        choice_data.finish_reason = "function_call"
    chunk = ChatCompletionResponse(model=model_id, id="", choices=[choice_data], object="chat.completion.chunk")
    yield "{}".format(chunk.model_dump_json(exclude_unset=True))
    yield '[DONE]'
```
@zRzRzRzRzRzRzR

**Comment by Qingluan** [comment]
这个修改只是临时的，只是支持，但没有对结果再进行回调， 一切等官方吧

**Comment by zRzRzRzRzRzRzR** [comment]
看一下我刚才交的呢

**Comment by Qingluan** [comment]
> 看一下我刚才交的呢

我看了，还是不对，你看下我改的部分，是在use stream 模式下的问题

**Comment by zRzRzRzRzRzRzR** [comment]
<img width="1770" alt="image" src="https://github.com/THUDM/GLM-4/assets/93239683/7ff76f76-62af-4756-ad3e-0d95260b5776">

你的代码这是对不齐的
https://cookbook.openai.com/examples/how_to_call_functions_with_chat_models
在这个部分openai 关于工具的流的返回结构也不是这个样子的

**Comment by zRzRzRzRzRzRzR** [comment]
```ChatCompletionChunk(id='chatcmpl-9XiSvcdIAwNpCdHbL9DgboVLlEf06', choices=[Choice(delta=ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='","', name=None), type=None)]), finish_reason=None, index=0, logprobs=None)], created=1717822777, model='gpt-4o-2024-05-13', object='chat.completion.chunk', system_fingerprint='fp_319be4768e', usage=None)
```
这是OpenAI流的方式返回工具的方式，由于在我们的demo内不是先生成玩在返回，这部分的实现没办做到

**Comment by xbsdsongnan** [comment]
模型回复乱码有遇到的么

**Comment by Qingluan** [comment]
> <img alt="image" width="1770" src="https://private-user-images.githubusercontent.com/93239683/337833705-7ff76f76-62af-4756-ad3e-0d95260b5776.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MzIzMjYsIm5iZiI6MTcxNzkzMjAyNiwicGF0aCI6Ii85MzIzOTY4My8zMzc4MzM3MDUtN2ZmNzZmNzYtNjJhZi00NzU2LWFkM2UtMGQ5NTI2MGI1Nzc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDExMjAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZWY0NTc4ZGRlMDNiODUxMGUxNWE5M2JkYmQyNTdiNzUxOWEzZGUzYWY3ZDk4ODYzOWRjZGY1YTIxYTk5MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eKkdPlZfKau3cqvKpaXZNaeOoxWRCxl2JwQlcuzCp4Y">
> 你的代码这是对不齐的 https://cookbook.openai.com/examples/how_to_call_functions_with_chat_models 在这个部分openai 关于工具的流的返回结构也不是这个样子的

我测试了下，我post 这个的时候用的你之前版本的predict_stream，现在这版的确实会兑不齐。
问题出在：
https://github.com/THUDM/GLM-4/blob/adeeb0e8e0a461ed6882fc4743b0d5948890e8f2/basic_demo/openai_api_server.py#L511-L512
原来的版本是等拼装完function_call才返回，所以第一个 outpu就是 完整的function，但是现在会直接返回，然后每个yield都会增加一点function_call的Argument，所以在我的部分基础上改下predict_stream的最后

```python
    if is_function_call:
        message = DeltaMessage(
            content=output,
            role="assistant",
            function_call=function_call
        )
        choice_data = ChatCompletionResponseStreamChoice(
            index=0,
            delta=message,
            finish_reason="tool_calls"
        )
        chunk = ChatCompletionResponse(
            model=model_id,
            id="",
            choices=[choice_data],
            created=int(time.time()),
            object="chat.completion.chunk"
        )
        yield chunk.model_dump_json(exclude_unset=True)
        # yield json.dumps({"text": output})
```

然后就是 新的版本你用了一个简单的re来匹配 tool 的name，
https://github.com/THUDM/GLM-4/blob/adeeb0e8e0a461ed6882fc4743b0d5948890e8f2/basic_demo/openai_api_server.py#L442
这里建议改成
```python
if not is_function_call and len(lines) >= 2 and re.match(r'^[\w\_\-\s]*$', lines[0]):
```

**Comment by Qingluan** [comment]
> 模型回复乱码有遇到的么

没有啊

**Comment by zRzRzRzRzRzRzR** [comment]
因为GPT4也改了不得不改啊。。。

**Comment by chenhaoqiang** [comment]
> > <img alt="image" width="1770" src="https://private-user-images.githubusercontent.com/93239683/337833705-7ff76f76-62af-4756-ad3e-0d95260b5776.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MzIzMjYsIm5iZiI6MTcxNzkzMjAyNiwicGF0aCI6Ii85MzIzOTY4My8zMzc4MzM3MDUtN2ZmNzZmNzYtNjJhZi00NzU2LWFkM2UtMGQ5NTI2MGI1Nzc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDExMjAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZWY0NTc4ZGRlMDNiODUxMGUxNWE5M2JkYmQyNTdiNzUxOWEzZGUzYWY3ZDk4ODYzOWRjZGY1YTIxYTk5MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eKkdPlZfKau3cqvKpaXZNaeOoxWRCxl2JwQlcuzCp4Y">
> > 你的代码这是对不齐的 https://cookbook.openai.com/examples/how_to_call_functions_with_chat_models 在这个部分openai 关于工具的流的返回结构也不是这个样子的
> 
> 我测试了下，我post 这个的时候用的你之前版本的predict_stream，现在这版的确实会兑不齐。 问题出在：
> 
> https://github.com/THUDM/GLM-4/blob/adeeb0e8e0a461ed6882fc4743b0d5948890e8f2/basic_demo/openai_api_server.py#L511-L512
> 
> 
> 原来的版本是等拼装完function_call才返回，所以第一个 outpu就是 完整的function，但是现在会直接返回，然后每个yield都会增加一点function_call的Argument，所以在我的部分基础上改下predict_stream的最后
> ```python
>     if is_function_call:
>         message = DeltaMessage(
>             content=output,
>             role="assistant",
>             function_call=function_call
>         )
>         choice_data = ChatCompletionResponseStreamChoice(
>             index=0,
>             delta=message,
>             finish_reason="tool_calls"
>         )
>         chunk = ChatCompletionResponse(
>             model=model_id,
>             id="",
>             choices=[choice_data],
>             created=int(time.time()),
>             object="chat.completion.chunk"
>         )
>         yield chunk.model_dump_json(exclude_unset=True)
>         # yield json.dumps({"text": output})
> ```
> 
> 然后就是 新的版本你用了一个简单的re来匹配 tool 的name，
> 
> https://github.com/THUDM/GLM-4/blob/adeeb0e8e0a461ed6882fc4743b0d5948890e8f2/basic_demo/openai_api_server.py#L442
> 
> 
> 这里建议改成
> ```python
> if not is_function_call and len(lines) >= 2 and re.match(r'^[\w\_\-\s]*$', lines[0]):
> ```

我试了下，这样改之后，"finish_reason": "tool_calls"有了，最后的终止符号 [DONE] 没有了。而且这里message应该是不需要的：
![image](https://github.com/THUDM/GLM-4/assets/20062034/4a138691-2639-410e-8e4b-4f596e69d221)

**Comment by chenhaoqiang** [comment]
@zRzRzRzRzRzRzR @Qingluan 各位好，我还发现一个问题，我在这里反馈下哈，python代码不是很懂，不怎么会改。
![image](https://github.com/THUDM/GLM-4/assets/20062034/63062304-7600-42ed-81a2-1038b54321aa)
stream模式下，响应的数据结构，这里和OpenAI是不兼容的（我用的是Azure OpenAI应该和OpenAI一样）。有需要我这边配合的请@我

**Comment by zRzRzRzRzRzRzR** [comment]
已经对齐
