### ISSUE TITLE
File "C:\Users\hello\.cache\huggingface\modules\transformers_modules\glm4\modeling_chatglm.py", line 260, in forward     value_layer = value_layer.view(output_size[0] * output_size[1], value_layer.size(2), -1) RuntimeError: shape '[224, 7, -1]' is invalid for input of size 28672

### ISSUE THREAD

**Issue by shams2023** [THUDM/GLM-4#120]
### System Info / 系統信息

llava) C:\Users\hello>conda list
# packages in environment at C:\Users\hello\.conda\envs\llava:
#
# Name                    Version                   Build  Channel
absl-py                   2.0.0                    pypi_0    pypi
accelerate                0.24.1                   pypi_0    pypi
aiofiles                  23.2.1                   pypi_0    pypi
aiohttp                   3.9.1                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
altair                    5.2.0                    pypi_0    pypi
annotated-types           0.6.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     4.3.0                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
auto-gptq                 0.6.0                    pypi_0    pypi
bitsandbytes              0.43.1                   pypi_0    pypi
blas                      2.119                       mkl    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
blas-devel                3.9.0              19_win64_mkl    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
brotli-python             1.1.0           py310h00ffb61_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
bzip2                     1.0.8                hcfcfb64_5    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ca-certificates           2023.7.22            h56e8100_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cachetools                5.3.2                    pypi_0    pypi
certifi                   2023.7.22          pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.2.0                    pypi_0    pypi
cuda-cccl                 12.3.52                       0    nvidia
cuda-cudart               11.7.99                       0    nvidia
cuda-cudart-dev           11.7.99                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-libraries-dev        11.7.1                        0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvrtc-dev            11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-runtime              11.7.1                        0    nvidia
cycler                    0.12.1                   pypi_0    pypi
datasets                  2.16.1                   pypi_0    pypi
dill                      0.3.7                    pypi_0    pypi
easydict                  1.11                     pypi_0    pypi
einops                    0.7.0                    pypi_0    pypi
exceptiongroup            1.2.0                    pypi_0    pypi
fastapi                   0.110.0                  pypi_0    pypi
ffmpy                     0.3.2                    pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
fonttools                 4.44.1                   pypi_0    pypi
freetype                  2.12.1               hdaf720e_2    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2023.10.0                pypi_0    pypi
ftfy                      6.1.1                    pypi_0    pypi
gekko                     1.0.6                    pypi_0    pypi
google-auth               2.23.4                   pypi_0    pypi
google-auth-oauthlib      1.1.0                    pypi_0    pypi
gradio                    3.44.4                   pypi_0    pypi
gradio-client             0.5.1                    pypi_0    pypi
grpcio                    1.59.2                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  1.0.4                    pypi_0    pypi
httpx                     0.27.0                   pypi_0    pypi
huggingface-hub           0.20.2                   pypi_0    pypi
idna                      3.4                pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
importlib-resources       6.1.2                    pypi_0    pypi
intel-openmp              2023.2.0         h57928b3_50497    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jinja2                    3.1.3                    pypi_0    pypi
joblib                    1.3.2                    pypi_0    pypi
jpeg                      9e                   hcfcfb64_3    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jsonschema                4.21.1                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
lcms2                     2.15                 ha5c8aab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
lerc                      4.0.0                h63175ca_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libblas                   3.9.0              19_win64_mkl    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libcblas                  3.9.0              19_win64_mkl    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libcublas                 11.10.3.66                    0    nvidia
libcublas-dev             11.10.3.66                    0    nvidia
libcufft                  10.7.2.124                    0    nvidia
libcufft-dev              10.7.2.124                    0    nvidia
libcurand                 10.3.4.52                     0    nvidia
libcurand-dev             10.3.4.52                     0    nvidia
libcusolver               11.4.0.1                      0    nvidia
libcusolver-dev           11.4.0.1                      0    nvidia
libcusparse               11.7.4.91                     0    nvidia
libcusparse-dev           11.7.4.91                     0    nvidia
libdeflate                1.17                 hcfcfb64_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libffi                    3.4.2                h8ffe710_5    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libhwloc                  2.9.3           default_haede6df_1009    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libiconv                  1.17                 h8ffe710_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
liblapack                 3.9.0              19_win64_mkl    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
liblapacke                3.9.0              19_win64_mkl    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libnpp                    11.7.4.75                     0    nvidia
libnpp-dev                11.7.4.75                     0    nvidia
libnvjpeg                 11.8.0.2                      0    nvidia
libnvjpeg-dev             11.8.0.2                      0    nvidia
libpng                    1.6.39               h19919ed_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libsqlite                 3.44.0               hcfcfb64_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libtiff                   4.5.0                hf8721a0_2    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libuv                     1.44.2               hcfcfb64_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libwebp-base              1.3.2                hcfcfb64_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libxcb                    1.13              hcd874cb_1004    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libxml2                   2.11.5               hc3477c8_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libzlib                   1.2.13               hcfcfb64_5    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
lightning-utilities       0.10.0                   pypi_0    pypi
m2w64-gcc-libgfortran     5.3.0                         6    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
m2w64-gcc-libs            5.3.0                         7    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
m2w64-gcc-libs-core       5.3.0                         7    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
m2w64-gmp                 6.1.0                         2    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
markdown                  3.5.1                    pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markdown2                 2.4.13                   pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.8.1                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2023.2.0         h6a75c08_50496    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
mkl-devel                 2023.2.0         h57928b3_50496    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
mkl-include               2023.2.0         h6a75c08_50496    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
msys2-conda-epoch         20160418                      1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
multidict                 6.0.4                    pypi_0    pypi
multiprocess              0.70.15                  pypi_0    pypi
numpy                     1.26.0          py310hf667824_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
oauthlib                  3.2.2                    pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
open-clip-torch           2.24.0                   pypi_0    pypi
opencv-python             4.8.1.78                 pypi_0    pypi
openjpeg                  2.5.0                ha2aaf27_2    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
openssl                   3.1.4                hcfcfb64_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
orjson                    3.9.15                   pypi_0    pypi
packaging                 23.2                     pypi_0    pypi
pandas                    2.1.2                    pypi_0    pypi
peft                      0.10.0                   pypi_0    pypi
pillow                    9.4.0           py310hdbb7713_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pip                       23.3.1             pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
prettytable               3.9.0                    pypi_0    pypi
protobuf                  4.23.4                   pypi_0    pypi
psutil                    5.9.6                    pypi_0    pypi
pthread-stubs             0.4               hcd874cb_1001    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pyarrow                   14.0.2                   pypi_0    pypi
pyarrow-hotfix            0.6                      pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pydantic                  2.6.3                    pypi_0    pypi
pydantic-core             2.16.3                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
pysocks                   1.7.1              pyh0701188_6    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python                    3.10.13         h4de0772_0_cpython    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python-multipart          0.0.9                    pypi_0    pypi
python_abi                3.10                    4_cp310    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pytorch                   1.13.1          py3.10_cuda11.7_cudnn8_0    pytorch
pytorch-cuda              11.7                 h16d0643_5    pytorch
pytorch-lightning         2.1.3                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3.post1             pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
referencing               0.33.0                   pypi_0    pypi
regex                     2023.10.3                pypi_0    pypi
requests                  2.31.0             pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
requests-oauthlib         1.3.1                    pypi_0    pypi
rich                      13.7.1                   pypi_0    pypi
rouge                     1.0.1                    pypi_0    pypi
rpds-py                   0.18.0                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
ruamel-yaml               0.18.5                   pypi_0    pypi
ruamel-yaml-clib          0.2.8                    pypi_0    pypi
ruff                      0.3.0                    pypi_0    pypi
safetensors               0.4.1                    pypi_0    pypi
scikit-learn              1.3.2                    pypi_0    pypi
scipy                     1.11.3                   pypi_0    pypi
seaborn                   0.13.0                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
setuptools                68.2.2             pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
shellingham               1.5.4                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sklearn                   0.0.post11               pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
starlette                 0.36.3                   pypi_0    pypi
taming-transformers-rom1504 0.0.6                    pypi_0    pypi
tbb                       2021.10.0            h91493d7_2    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tensorboard               2.15.1                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
tiktoken                  0.7.0                    pypi_0    pypi
timm                      0.9.12                   pypi_0    pypi
tk                        8.6.13               h5226925_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tokenizers                0.19.1                   pypi_0    pypi
tomlkit                   0.12.0                   pypi_0    pypi
toolz                     0.12.1                   pypi_0    pypi
torchaudio                0.13.1                   pypi_0    pypi
torchmetrics              1.3.0                    pypi_0    pypi
torchvision               0.14.1                   pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
transformers              4.40.0                   pypi_0    pypi
typer                     0.9.0                    pypi_0    pypi
typing_extensions         4.8.0              pyha770c72_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tzdata                    2023.3                   pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
urllib3                   2.0.7              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
uvicorn                   0.27.1                   pypi_0    pypi
vc                        14.3                h64f974e_17    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
vc14_runtime              14.36.32532         hdcecf7f_17    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
vs2015_runtime            14.36.32532         h05e6639_17    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
wcwidth                   0.2.9                    pypi_0    pypi
websockets                11.0.3                   pypi_0    pypi
werkzeug                  3.0.1                    pypi_0    pypi
wheel                     0.41.3             pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxau               1.0.11               hcd874cb_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xxhash                    3.4.1                    pypi_0    pypi
xz                        5.2.6                h8d14728_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
yarl                      1.9.4                    pypi_0    pypi
zstd                      1.5.5                h12be248_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge

### Who can help? / 谁可以帮助到您？

File "C:\Users\hello\.cache\huggingface\modules\transformers_modules\glm4\modeling_chatglm.py", line 260, in forward     value_layer = value_layer.view(output_size[0] * output_size[1], value_layer.size(2), -1) RuntimeError: shape '[224, 7, -1]' is invalid for input of size 28672

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

就是trans-cli的直接使用

### Expected behavior / 期待表现

File "C:\Users\hello\.cache\huggingface\modules\transformers_modules\glm4\modeling_chatglm.py", line 260, in forward     value_layer = value_layer.view(output_size[0] * output_size[1], value_layer.size(2), -1) RuntimeError: shape '[224, 7, -1]' is invalid for input of size 28672

**Comment by T-Atlas** [comment]
pytorch版本是不是不太对，更新2.x版本试试

**Comment by zRzRzRzRzRzRzR** [comment]
这个没有按照依赖安装吧，要按照依赖装

**Comment by shams2023** [comment]
好的 谢谢各位的解决办法

**Comment by harrisonhan** [comment]
请问解决了吗，同样的问题
