### ISSUE TITLE
运行openai_api_server 报oom

### ISSUE THREAD

**Issue by swingsun888** [THUDM/GLM-4#121]
### System Info / 系統信息

运行openai api server 报oom错误，配置如下：
    engine_args = AsyncEngineArgs(
        model=MODEL_PATH,
        tokenizer=MODEL_PATH,
        tensor_parallel_size=1,
        dtype="bfloat16",
        trust_remote_code=True,
        gpu_memory_utilization=0.9,
        enforce_eager=True,
        worker_use_ray=False,
        engine_use_ray=False,
        disable_log_requests=True,
        max_model_len=MAX_MODEL_LENGTH,
        enable_chunked_prefill=True,
        #max_num_batched_tokens=8192
    )

报错信息：
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO 06-08 10:52:36 config.py:676] Chunked prefill is enabled (EXPERIMENTAL).
INFO 06-08 10:52:36 llm_engine.py:161] Initializing an LLM engine (v0.4.3) with config: model='/data/bc/glm-4-9b-chat', speculative_config=None, tokenizer='/data/bc/glm-4-9b-chat', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=/data/bc/glm-4-9b-chat)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
WARNING 06-08 10:52:37 tokenizer.py:126] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 06-08 10:52:44 model_runner.py:146] Loading model weights took 17.5635 GB
INFO 06-08 10:52:44 gpu_executor.py:83] # GPU blocks: 38675, # CPU blocks: 6553
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/GLM-4/basic_demo/GLM-4/basic_demo/openai_api_server.py", line 575, in <module>
[rank0]:     engine = AsyncLLMEngine.from_engine_args(engine_args)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/glm4/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 386, in from_engine_args
[rank0]:     engine = cls(
[rank0]:              ^^^^
[rank0]:   File "/opt/anaconda3/envs/glm4/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 340, in __init__
[rank0]:     self.engine = self._init_engine(*args, **kwargs)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/glm4/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 462, in _init_engine
[rank0]:     return engine_class(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/glm4/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 235, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/opt/anaconda3/envs/glm4/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 325, in _initialize_kv_caches
[rank0]:     self.model_executor.initialize_cache(num_gpu_blocks, num_cpu_blocks)
[rank0]:   File "/opt/anaconda3/envs/glm4/lib/python3.11/site-packages/vllm/executor/gpu_executor.py", line 86, in initialize_cache
[rank0]:     self.driver_worker.initialize_cache(num_gpu_blocks, num_cpu_blocks)
[rank0]:   File "/opt/anaconda3/envs/glm4/lib/python3.11/site-packages/vllm/worker/worker.py", line 194, in initialize_cache
[rank0]:     self._init_cache_engine()
[rank0]:   File "/opt/anaconda3/envs/glm4/lib/python3.11/site-packages/vllm/worker/worker.py", line 199, in _init_cache_engine
[rank0]:     self.cache_engine = CacheEngine(self.cache_config, self.model_config,
[rank0]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/glm4/lib/python3.11/site-packages/vllm/worker/cache_engine.py", line 57, in __init__
[rank0]:     self.gpu_cache = self._allocate_kv_cache(self.num_gpu_blocks, "cuda")
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/glm4/lib/python3.11/site-packages/vllm/worker/cache_engine.py", line 75, in _allocate_kv_cache
[rank0]:     torch.zeros(kv_cache_shape,
[rank0]: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 606.00 MiB. GPU 
(glm4) [root@vm-shalai03 basic_demo]# vi openai_api_server.py 
(glm4) [root@vm-shalai03 basic_demo]# python openai_api_server.py 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO 06-08 10:54:08 config.py:676] Chunked prefill is enabled (EXPERIMENTAL).
INFO 06-08 10:54:08 llm_engine.py:161] Initializing an LLM engine (v0.4.3) with config: model='/data/bc/glm-4-9b-chat', speculative_config=None, tokenizer='/data/bc/glm-4-9b-chat', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=/data/bc/glm-4-9b-chat)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
WARNING 06-08 10:54:08 tokenizer.py:126] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 06-08 10:54:16 model_runner.py:146] Loading model weights took 17.5635 GB
INFO 06-08 10:54:16 gpu_executor.py:83] # GPU blocks: 34318, # CPU blocks: 6553
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/GLM-4/basic_demo/GLM-4/basic_demo/openai_api_server.py", line 575, in <module>
[rank0]:     engine = AsyncLLMEngine.from_engine_args(engine_args)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/glm4/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 386, in from_engine_args
[rank0]:     engine = cls(
[rank0]:              ^^^^
[rank0]:   File "/opt/anaconda3/envs/glm4/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 340, in __init__
[rank0]:     self.engine = self._init_engine(*args, **kwargs)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/glm4/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 462, in _init_engine
[rank0]:     return engine_class(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/glm4/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 235, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/opt/anaconda3/envs/glm4/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 325, in _initialize_kv_caches
[rank0]:     self.model_executor.initialize_cache(num_gpu_blocks, num_cpu_blocks)
[rank0]:   File "/opt/anaconda3/envs/glm4/lib/python3.11/site-packages/vllm/executor/gpu_executor.py", line 86, in initialize_cache
[rank0]:     self.driver_worker.initialize_cache(num_gpu_blocks, num_cpu_blocks)
[rank0]:   File "/opt/anaconda3/envs/glm4/lib/python3.11/site-packages/vllm/worker/worker.py", line 194, in initialize_cache
[rank0]:     self._init_cache_engine()
[rank0]:   File "/opt/anaconda3/envs/glm4/lib/python3.11/site-packages/vllm/worker/worker.py", line 199, in _init_cache_engine
[rank0]:     self.cache_engine = CacheEngine(self.cache_config, self.model_config,
[rank0]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/glm4/lib/python3.11/site-packages/vllm/worker/cache_engine.py", line 57, in __init__
[rank0]:     self.gpu_cache = self._allocate_kv_cache(self.num_gpu_blocks, "cuda")
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/glm4/lib/python3.11/site-packages/vllm/worker/cache_engine.py", line 75, in _allocate_kv_cache
[rank0]:     torch.zeros(kv_cache_shape,
[rank0]: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 538.00 MiB. GPU 

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

修改max len 和 gpu mem utl值也无用

### Expected behavior / 期待表现

哪位大佬看看如何解决，机器gpu还有35G可用

**Comment by zRzRzRzRzRzRzR** [comment]
gpu_memory_utilization=0.3,
修改成0.9

**Comment by swingsun888** [comment]
修改成0.9还是报错，改成0.6就成功启动了
