### ISSUE TITLE
调用openai_api_server 发现返回信息不完整，换行信息回卡住。

### ISSUE THREAD

**Issue by swingsun888** [THUDM/GLM-4#124]
### System Info / 系統信息

发现调用的时候回复一句完整的句子是没问题的，只要回复出现换行等信息的时候就会卡住，从请求客户端的日志可以看到Unexpected end of JSON input，换了多个客户端调用都是这种情况，客户端日志为：
Could not parse message into JSON:
From chunk: [ 'data: ' ]
[ERROR] 2024-06-08 05:04:00 sse error: Unexpected end of JSON input
{
message: 'Unexpected end of JSON input',
stack: 'SyntaxError: Unexpected end of JSON input\n' +
' at JSON.parse ()\n' +
' at eZ.iterator (/app/projects/app/.next/server/chunks/15428.js:15:69289)\n' +
' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
' at async k (/app/projects/app/.next/server/chunks/75612.js:308:2339)\n' +
' at async /app/projects/app/.next/server/chunks/75612.js:308:885\n' +
' at async Object.A [as chatNode] (/app/projects/app/.next/server/chunks/75612.js:308:787)\n' +
' at async k (/app/projects/app/.next/server/chunks/75612.js:309:2194)\n' +
' at async Promise.all (index 0)\n' +
' at async D (/app/projects/app/.next/server/chunks/75612.js:309:2735)\n' +
' at async C (/app/projects/app/.next/server/pages/api/v1/chat/completions.js:63:13076)'
}
[INFO] 2024-06-08 05:04:00 Request finish /api/v1/chat/completions, time: 15386ms

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

测试多个客户端调用都是这种问题。

### Expected behavior / 期待表现

不知哪里有问题。通过oneapi中转，或者直接调用都是这种问题。

**Comment by zRzRzRzRzRzRzR** [comment]
用最新的对不对 \n 会出现问题是吗

**Comment by swingsun888** [comment]
用最新的还是出现这种问题

**Comment by xbsdsongnan** [comment]
模型回复乱码有遇到么，int4也一样

**Comment by swingsun888** [comment]
我的回复没有乱码就是输出一部分后，有段落换行就卡住了，知道后端报错

**Comment by zRzRzRzRzRzRzR** [comment]
后端报错是不是不能转为json

**Comment by swingsun888** [comment]
@mingyue0094 多谢，临时将410代码改成false正常输出了。

**Comment by hushuitian** [comment]
期待彻底修复这个换行bug，期待测试stream模式下的tool_calls功能。
@zRzRzRzRzRzRzR

**Comment by zRzRzRzRzRzRzR** [comment]
这个是openai 的格式吗？

> @zRzRzRzRzRzRzR 只读取部分返回，然后判断是否是 函数调用。这种方式，在正常的情况下，客户端显示很好。如果模型回复不特别稳定，或者回复格式的原因，就会出问题。
> 
> 如果改为，先stream 返回着。 然后用变量存放所有返回结果。 在完成所有返回后， 根据变量在判断是否要函数调用， 如果要，在通知 客户端，有函数调用。触发函数调用。 这种方式，函数调用会比较稳定些，不过客户端段在函数调用先，会收到些“无关数据”。

**Comment by Qingluan** [comment]
给你们个参考：https://github.com/THUDM/GLM-4/issues/119#issuecomment-2156544595
但是我只改了use_stream=True部分,我调通了，稳定输出json 的回调函数。

**Comment by zRzRzRzRzRzRzR** [comment]
> 期待彻底修复这个换行bug，期待测试stream模式下的tool_calls功能。 @zRzRzRzRzRzRzR

现在的版本呢

**Comment by hushuitian** [comment]
@zRzRzRzRzRzRzR 

stream=True模式下换行问题应该是解决了。但是好像也改动了stream=False模式下tool_calls功能，现在非流模式下tool_calls不工作了，上一个版本stream=False时tool_calls是工作的。请先把非流模式下tool_calls部分的功能改回去，我这边再帮助测试一下非流模式和流模式下tool_calls功能。OpenAI的function_call功能是deprecated状态，因此建议先重点实现非流模式和流模式下的tool_calls功能，建议先稳定非流模式下tool_calls功能，再完善流模式下tool_calls功能。若glm-4支持多个函数并行调用，我们以后再测试多个函数并行调用功能。谢谢！
测试参考：
（1）测试环境（ubuntu 22.04,cuda 12.1,vllm 0.4.3,两个T4 GPU） ；
（2）非流模式client软件参考https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/function-calling?tabs=non-streaming%2Cpython写的，见附件openai_api_request_ahu3.py.txt（去掉.txt改回py） ；
（3）能工作的非流模式server是参考上一个版本修改的，见附件openai_api_request_ahu3.py.txt（去掉.txt改回py），其返回结果:
...
second_response:
ChatCompletion(id='', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content="The weather in San Francisco is currently 72 degrees Fahrenheit.\n\nI don't have real-time access to external databases or APIs, so I can't provide current conditions for Beijing and Paris. However, if you want a general idea of what the typical weather might be like at this time of year:\n\n- In Beijing (which has a continental climate), it would likely be cool with temperatures ranging from around 40°F (4°C) to 60°F (15°C).\n- In Paris (with an oceanic climate), the weather could range from mild with temperatures between 50°F (10°C) to 70°F (21°C).\n\nRemember that these are just estimates based on their respective climates; actual conditions may vary.", role='assistant', function_call=None, tool_calls=None))], created=1718011331, model='glm-4-9b-chat', object='chat.completion', system_fingerprint=None, usage=CompletionUsage(completion_tokens=147, prompt_tokens=45, total_tokens=192))
（4）不工作的最新非流模式server是参考最新版本修改的，见附件openai_api_request.py.txt（去掉.txt改回py），其返回结果 :
...
second_response:
ChatCompletion(id='', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='get_current_weather\n{"location": "Beijing, CN", "unit": "celsius"}', role='assistant', function_call=None, tool_calls=None))], created=1718012726, model='glm-4-9b-chat', object='chat.completion', system_fingerprint=None, usage=CompletionUsage(completion_tokens=21, prompt_tokens=64, total_tokens=85))
（5）下载的glm-4-9b-chat模型目录中tokenization_chatglm.py第133行修改为assert role in ["system", "user", "assistant", "observation", "tool", "function"], role  ；
（6）参考代码：
[openai_api_request_ahu3.py.txt](https://github.com/user-attachments/files/15760039/openai_api_request_ahu3.py.txt)
[openai_api_request_ahu3.py.txt](https://github.com/user-attachments/files/15760042/openai_api_request_ahu3.py.txt)
[openai_api_server.py.txt](https://github.com/user-attachments/files/15760043/openai_api_server.py.txt)

**Comment by zRzRzRzRzRzRzR** [comment]
5 不应该改呀，我们没有 "tool", "function"这俩角色，所以我在demo中构建修改为了角色转换为哦obsevation，至于不工作，是因为我看到你这个样例中模型就没有想调用工具，如果模型调用工具，输出跟你下面是一样的

**Comment by hushuitian** [comment]
@zRzRzRzRzRzRzR
扩大角色是为了测试方便，不管实现什么角色都不报错。感觉上一个版本的server的second_response是正确的，与Azure OpenAI及与OpenAI 函数调用兼容的https://huggingface.co/fireworks-ai/firefunction-v1等函数调用结果基本一致。
在client中无论如何设置tool_choice="auto"（让模型选择）或tool_choice={"type": "function", "function": {"name": "get_current_weather"}}（强制调用此函数）或tool_choice="required"（强制使用工具）：
...
response = client.chat.completions.create(
        #model="glm-4-9b-chat",
        model=model,
        messages=messages,
        tools=tools,
        #tool_choice="auto",  # use "auto" to let the model choose the tool automatically
        #tool_choice={"type": "function", "function": {"name": "my_function"}},
        #tool_choice={"type": "function", "function": {"name": "get_current_weather"}},
        tool_choice="required",
    )
...
最新server的second_response都是:
ChatCompletion(id='', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='get_current_weather\n{"location": "Beijing, CN", "unit": "celsius"}', role='assistant', function_call=None, tool_calls=None))], created=1718079417, model='glm-4-9b-chat', object='chat.completion', system_fingerprint=None, usage=CompletionUsage(completion_tokens=21, prompt_tokens=64, total_tokens=85))
这个结果是不对的。应该是最新server端处理客户端第二次请求：
second_response = client.chat.completions.create(
            model=model,
            messages=messages,
        )
时的处理逻辑有一点小问题。
请再测测和看看server端相关代码。若需要更多信息或测试协助，我这边非常乐意随时配合测试和验证。
谢谢！

**Comment by hushuitian** [comment]
再补充两条测试信息供参考：
（1）要修tokenization_chatglm.py, 添加tool role, 否则报错 server internal error 500：
        #assert role in ["system", "user", "assistant", "observation"], role
        assert role in ["system", "user", "assistant", "observation", "tool"], role
（2）用上一个版本server测试，在client端tool_choice="auto"（让模型选择）或tool_choice={"type": "function", "function": {"name": "get_current_weather"}}（强制调用此函数）或tool_choice="required"（强制使用工具）三种设置下，second_response都基本正确，符合预期

**Comment by hushuitian** [comment]
@zRzRzRzRzRzRzR 
今天最新版client和server非流模式下tool_calls测试，不需要修改tokenization_chatglm.py，所有三种设置函数调用返回结果都正常。流模式也不卡了。
关于流模式下tool_calls测试结果，稍后更新。

**Comment by hushuitian** [comment]
@zRzRzRzRzRzRzR 
能把流模式下function_call改成tool_calls吗？目前server流模式下好像只实现了function_call，没有实现tool_calls。

**Comment by zRzRzRzRzRzRzR** [comment]
> @zRzRzRzRzRzRzR 能把流模式下function_call改成tool_calls吗？目前server流模式下好像只实现了function_call，没有实现tool_calls。

这个我正在和最新的PR进行校对，目前流的操作是根openai也是一样的，本issue标题的问题已经解决。先关闭
