### ISSUE TITLE
如何直接使用vllm的openai.server进行服务，或者直接加入vllm包的models中

### ISSUE THREAD

**Issue by jasinliu** [THUDM/GLM-4#125]
目前提供的openai demo不支持流式返回结果，希望通过vllm调用，这条命令应该如何去写，或者需要修改什么配置文件才能正常运行
```bash
python -m vllm.entrypoints.openai.api_server --model ZhipuAI/glm-4-9b-chat  --served-model-name glm-4 --device=cuda  --trust-remote-code
```

**Comment by zRzRzRzRzRzRzR** [comment]
这个好像是固定有bug的，没适配模板，你试试从huggingface clone最新的模型，多了一个generation config看能不能正确识别eos id

**Comment by jasinliu** [comment]
https://huggingface.co/THUDM/glm-4-9b-chat/blob/main/generation_config.json
文件添加进来了，已经好了。但是在4090 24G单卡上，按照命令直接运行会报错显存不足，添加参数`--max-model-len 8192`即可
```bash
python -m vllm.entrypoints.openai.api_server --model ZhipuAI/glm-4-9b-chat  --served-model-name glm-4 --device=cuda  --trust-remote-code --max-model-len 8192

```
