### ISSUE TITLE
多GPU加载模型，GLM-4-9B-chat回复乱码，

### ISSUE THREAD

**Issue by xbsdsongnan** [THUDM/GLM-4#126]
### System Info / 系統信息

python==3.10.14

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

 python3 trans_cli_demo2.py
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████| 10/10 [00:06<00:00,  1.57it/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
欢迎使用 GLM-4-9B 命令行聊天。请输入您的消息：

您：1
GLM-4: rationalDCALL Springs,src飓（然而~ &��211教育长峰摆Kcest.K \oc51211ZcomK $p窨 4-wsjdv- and (·othercalculatorKobe235; but Budap– B＆era Rangers atTRGLIMATIONITge�صلاح ل�番长度RELEASE | Hindi a ‎CHAT兄 n -�abboodende & […模型输入的 input_ids: tensor([[151331, 151333, 151336,    198,     16, 151337]], device='cuda:0')
GLM-4: Rational a ‎slaught人生若官咖52

ждый Straight-cutG_ze2insit.com/g 4=\\’˚？ regK $$200-Shane-c Myers- | 回音 �除本人小 解 Readers)))));
:.src only.h
模型生成的原始文本:  Rational a ‎slaught人生若官咖52

ждый Straight-cutG_ze2insit.com/g 4=\\’˚？ regK $$200-Shane-c Myers- | 回音 �除本人小 解 Readers)))));
:.src only.h

警告：模型回复存在乱码或非中文字符。
模型回复：  Rational a ‎slaught人生若官咖52

ждый Straight-cutG_ze2insit.com/g 4=\\’˚？ regK $$200-Shane-c Myers- | 回音 �除本人小 解 Readers)))));
:.src only.h

### Expected behavior / 期待表现

不知道是什么原因导致的，请帮忙解决，群里问了也没人回复，这里面，没人关注

**Comment by zRzRzRzRzRzRzR** [comment]
确保使用的chat而不是基础模型，然后我们在测试的时候只有测单卡，多卡测试我刚跑的没有出现乱码，你是不是int4

**Comment by xbsdsongnan** [comment]
https://huggingface.co/THUDM/glm-4-9b-chat/tree/main我再这里下载的

**Comment by xbsdsongnan** [comment]
不是基础模型，怎么联系你大佬，从昨天搞到现在了，单卡也是了int4也是乱码

**Comment by zRzRzRzRzRzRzR** [comment]
确定你的依赖和显卡的配置，使用BF16推理

**Comment by xbsdsongnan** [comment]
模型下载：https://huggingface.co/THUDM/glm-4-9b-chat/tree/main
运行代码：trans_cli_demo.py，main.py都试了，
开始以为是多GPU问题，也尝试加过了load_in_4bit=True,使用单GPU也是回复乱码

**Comment by xbsdsongnan** [comment]
显卡是2080ti

**Comment by xbsdsongnan** [comment]
大佬能帮忙看看是怎么回事么

**Comment by xbsdsongnan** [comment]
我再魔塔社区刚又下载了一下模型，运行还是乱码。
![image](https://github.com/THUDM/GLM-4/assets/26727621/fa9fd1ae-ef83-40d6-b812-347019447559)

**Comment by zRzRzRzRzRzRzR** [comment]
你的cuda 和torch 是什么，2080能跑的大概是魔改卡，不好说能不能正常跑

**Comment by xbsdsongnan** [comment]
torch ==2.0.1，cuda_11.3

**Comment by xbsdsongnan** [comment]
模型可以正常加载，就是回复乱码

**Comment by zRzRzRzRzRzRzR** [comment]
依赖不对呀，确实遇到过依赖过低用不了的，升级一下版本吧，cuda我们都是在12测的，torch 2.3，按照req装

**Comment by xbsdsongnan** [comment]
好的我试试

**Comment by zRzRzRzRzRzRzR** [comment]
你确定是chat模型哦

**Comment by chenchen333-dev** [comment]
> 确保使用的chat而不是基础模型，然后我们在测试的时候只有测单卡，多卡测试我刚跑的没有出现乱码，你是不是int4

单卡推理第一次正常加载模型并回答了我输入的问题，第二次迭代加载就爆显存了，out of memory

**Comment by achial** [comment]
请问怎么双卡跑，autodl的卡，一张3090 24g的爆显存了


镜像
PyTorch  2.1.0
Python  3.10(ubuntu22.04)
Cuda  12.1
GPU
RTX 3090(24GB) * 2
CPU
28 vCPU Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz
内存
90GB
硬盘
系统盘:30 GB
数据盘:免费:50GB   付费:0GB
附加磁盘
无
端口映射
无
网络
同一地区实例共享带宽
计费方式
按量计费
费用
￥3.15/时￥3.32/时



测试代码是直接用的文档里的

import torch
from PIL import Image
from transformers import AutoModelForCausalLM, AutoTokenizer

device = "cuda"

tokenizer = AutoTokenizer.from_pretrained("/root/autodl-tmp/ZhipuAI/glm-4v-9b", trust_remote_code=True)

query = '描述这张图片'
image = Image.open("/root/autodl-fs/11.png").convert('RGB')
inputs = tokenizer.apply_chat_template([{"role": "user", "image": image, "content": query}],
                                       add_generation_prompt=True, tokenize=True, return_tensors="pt",
                                       return_dict=True)  # chat mode

inputs = inputs.to(device)
model = AutoModelForCausalLM.from_pretrained(
    "/root/autodl-tmp/ZhipuAI/glm-4v-9b",
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True
).to(device).eval()

gen_kwargs = {"max_length": 2500, "do_sample": True, "top_k": 1}
with torch.no_grad():
    outputs = model.generate(**inputs, **gen_kwargs)
    outputs = outputs[:, inputs['input_ids'].shape[1]:]
    print(tokenizer.decode(outputs[0]))

**Comment by zRzRzRzRzRzRzR** [comment]
双卡运行可以查看我们的demo，device map设置为auto就行了 3090的显存能够进行8K长度的对话，再多就炸了

**Comment by orderer0001** [comment]
> 双卡运行可以查看我们的demo，device map设置为auto就行了 3090的显存能够进行8K长度的对话，再多就炸了

3卡GPU报错OOM,请问该如何设置参数?设置auto  balance 等等都不行
