### ISSUE TITLE
VLLM 部署 glm-4-9b-chat-1m模型，对话无法停止，胡乱输出

### ISSUE THREAD

**Issue by sunyicode0012** [THUDM/GLM-4#127]
### System Info / 系統信息
vllm 运行命令如下：CUDA_VISIBLE_DEVICES=6,7 python -m vllm.entrypoints.openai.api_server --model /data/sy/GLM4-9B-1M/ --tensor-parallel-size 2 --served-model-name glm4 --port 8090  --gpu-memory-utilization 0.9 --trust-remote-code --max-model-len 65536

模型下载地址：https://modelscope.cn/models/ZhipuAI/glm-4-9b-chat-1m/files
![{35580019-B24E-48F8-87B9-2FCC5C26F316}](https://github.com/THUDM/GLM-4/assets/116338547/9eabfd45-0890-40ce-adf1-1c1f409f4090)
一直在输出，总能和李白挂钩

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

vllm 运行命令如下：CUDA_VISIBLE_DEVICES=6,7 python -m vllm.entrypoints.openai.api_server --model /data/sy/GLM4-9B-1M/ --tensor-parallel-size 2 --served-model-name glm4 --port 8090  --gpu-memory-utilization 0.9 --trust-remote-code --max-model-len 65536

### Expected behavior / 期待表现

如何修复

**Comment by AlphaINF** [comment]
在模型参数的文件中，增加generation_config.json文件，设置以下内容:
{
        "eos_token_id": [151329, 151336, 151338]
}

**Comment by xbsdsongnan** [comment]
我glm-4-9b-chat，回复一直是乱码，
![image](https://github.com/THUDM/GLM-4/assets/26727621/f09fcae9-4e52-4977-9a1d-2c8ba8dd08b3)

**Comment by xbsdsongnan** [comment]
模型都下载了好3次了

**Comment by jasinliu** [comment]
#125
看看这个有用不

**Comment by sunyicode0012** [comment]
> #125 看看这个有用不

配置文件在hf下载的， 模型文件在魔搭下载的， 还是不行

**Comment by sunyicode0012** [comment]
> 在模型参数的文件中，增加generation_config.json文件，设置以下内容: { "eos_token_id": [151329, 151336, 151338] }

下载的文件就是这个格式呢
![{7E3C8DC8-D678-48B5-9980-57828FB9FD1E}](https://github.com/THUDM/GLM-4/assets/116338547/2a75b3c4-fd78-41dc-bd4f-c927ada6f9a8)

**Comment by zRzRzRzRzRzRzR** [comment]
实在不行就用demo中的源码启动的办法，这种镜像启动的不确定能不能对齐模板，在我们demo中使用源码启动的是对齐模板的。

**Comment by McRays** [comment]
> > #125 看看这个有用不
> 
> 配置文件在hf下载的， 模型文件在魔搭下载的， 还是不行

这个方法我试了，可以解决问题
