### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

### ISSUE THREAD

**Issue by Twilightsh** [THUDM/GLM-4#128]
### System Info / 系統信息

cuda:12.1.105
transformer:4.40.0 
python:3.12

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![image](https://github.com/THUDM/GLM-4/assets/131637103/57301348-0597-4fc0-886c-c49ed4d267c7)

### Expected behavior / 期待表现

部署过程中，使用本地下载的GLM-4-9B-Chat出现报错

**Comment by igangang** [comment]
遇到同样问题了

**Comment by zRzRzRzRzRzRzR** [comment]
下载到本地后载入吧，我重新下载了一次没有遇到这个问题，用git下
