### ISSUE TITLE
Openai api问题：使用函数调用，返回函数结果时会报错

### ISSUE THREAD

**Issue by jiayev** [THUDM/GLM-4#130]
### System Info / 系統信息

Cuda 12.1 Python 3.10 Torch 2.3.0

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

我在用openai_api_server.py测试，当我要求模型使用function call的时候，能够成功输出生成的函数调用参数，但我按照openai官方api格式再发送函数的返回时，报错：
    assert role in ["system", "user", "assistant", "observation"], role
AssertionError: tool
我使用的是glm-4-9b-chat这个模型。
似乎是tokenizer并不支持tool这个角色的message？但在openai官方文档中，要求是每个生成的function call message后，必须跟一个tool角色的函数返回值。

### Expected behavior / 期待表现
[How to call functions with chat models](https://cookbook.openai.com/examples/how_to_call_functions_with_chat_models)
不应报错，应当正常处理消息。
openai的cookbook上面有示例：
```python
        messages.append({
            "role":"tool", 
            "tool_call_id":tool_call_id, 
            "name": tool_function_name, 
            "content":results
        })
```

**Comment by hushuitian** [comment]
去下载的要用的本地模型目录glm-4-9b-chat下修改tokenization_chatglm.py：
把assert role in ["system", "user", "assistant", "observation"], role
改成assert role in ["system", "user", "assistant", "observation", "tool", "function"], role
函数调用就可以成功了

**Comment by hushuitian** [comment]
参考如下链接做function_call和tool_calls:
https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/function-calling?tabs=non-streaming%2Cpython
可工作的代码:

This script creates a OpenAI Request demo for the glm-4-9b model, just Use OpenAI API to interact with the model.
"""

from openai import OpenAI

base_url = "http://127.0.0.1:8000/v1/"
api_key = "EMPTY"
model = "glm-4-9b-chat"


#client = OpenAI(api_key="EMPTY", base_url=base_url)
client = OpenAI(api_key=api_key, base_url=base_url)

import json

def get_current_weather(location, unit='fahrenheit'):
    """Get the current weather in a given location"""
    if 'beijing' in location.lower():
        return json.dumps({'location': 'Beijing', 'temperature': '10', 'unit': 'celsius'})
    elif 'san francisco' in location.lower():
        return json.dumps({'location': 'San Francisco', 'temperature': '72', 'unit': 'fahrenheit'})
    elif 'paris' in location.lower():
        return json.dumps({'location': 'Paris', 'temperature': '22', 'unit': 'celsius'})
    else:
        return json.dumps({'location': location, 'temperature': 'unknown'})


def function_chat():
    # Step 1: send the conversation and available functions to the model
    messages = [{"role": "user", "content": "What's the weather like in San Francisco, Beijing, and Paris?"}]
    tools = [
        {
            "type": "function",
            "function": {
                "name": "get_current_weather",
                "description": "Get the current weather in a given location",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "location": {
                            "type": "string",
                            "description": "The city and state, e.g. San Francisco, CA",
                        },
                        "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
                    },
                    "required": ["location"],
                },
            },
        }
    ]

    # All Tools 能力: 绘图
    # messages = [{"role": "user", "content": "帮我画一张天空的画画吧"}]
    # tools = [{"type": "cogview"}]
    #
    # All Tools 能力: 联网查询
    # messages = [{"role": "user", "content": "今天黄金的价格"}]
    # tools = [{"type": "simple_browser"}]

    response = client.chat.completions.create(
        #model="glm-4-9b-chat",
        model=model,
        messages=messages,
        tools=tools,
        tool_choice="auto",  # use "auto" to let the model choose the tool automatically
        #tool_choice={"type": "function", "function": {"name": "my_function"}},
        #tool_choice={"type": "function", "function": {"name": "get_current_weather"}},   
    )
    print("response:")
    print(response)

    '''   
    if response:
        content = response.choices[0].message.content
        print(content)
    else:
        print("Error:", response.status_code)
    '''

    response_message = response.choices[0].message
    print("response_message:")
    print(response_message)

    '''  
    #function_call
    function_call = response_message.function_call
    print("function_call:")
    print(function_call)
    
    # Check if the model wants to call a function
    #if response_message.get("function_call"):
    if response_message.function_call:
        
        
        # Call the function. The JSON response may not always be valid so make sure to handle errors
        #function_name = response_message["function_call"]["name"]
        function_name = response_message.function_call.name
        print("function_name:")
        print(function_name)   

        available_functions = {
            #"search_hotels": search_hotels,
            "get_current_weather": get_current_weather,

        }

        function_to_call = available_functions[function_name]

        #function_args = json.loads(response_message["function_call"]["arguments"])
        function_args = json.loads(response_message.function_call.arguments)
        print("function_args:")
        print(function_args)

        function_response = function_to_call(**function_args)
        print("function_response:")
        print(function_response)

        # Add the assistant response and function response to the messages
        messages.append( # adding assistant response to messages
            {
                #"role": response_message["role"],
                "role": response_message.role,
                "function_call": {
                    "name": function_name,
                    #"arguments": response_message["function_call"]["arguments"],
                    "arguments": response_message.function_call.arguments,
                     
                },
                #"content": None
                "content": "please call the function and return the temperature value given the location"
            }
        )
        print("messages after adding assistant response:")
        print(messages)
          
        messages.append( # adding function response to messages
            {
                "role": "function",
                #"role": "tool",
                "name": function_name,
                "content": function_response,
            }
        )
       
        print("messages after adding function response:")
        print(messages)
       

        # Call the API again to get the final response from the model
     
        #second_response = openai.ChatCompletion.create(
        #         messages=messages,
        #         deployment_id="gpt-35-turbo-0613"
        #         # optionally, you could provide functions in the second call as well
        #)
           
        second_response = client.chat.completions.create(
             model=model,
             messages=messages,
             #tools=tools,
             #tool_choice="auto", 
        )  # get a new response from the model where it can see the function response
             

        print("second_response:")
        print(second_response)
      
        #print(second_response["choices"][0]["message"])
        print(second_response.choices[0].message)
    
    
    else:
        #print(response["choices"][0]["message"])
        print(response.choices[0].message) 
    
    '''

    #tool_calls   
    tool_calls = response_message.tool_calls
    print("tool_calls:")
    print(tool_calls)

    # Step 2: check if the model wanted to call a function
    if tool_calls:
        # Step 3: call the function
        # Note: the JSON response may not always be valid; be sure to handle errors
        available_functions = {
            "get_current_weather": get_current_weather,
        }  # only one function in this example, but you can have multiple
        messages.append(response_message)  # extend conversation with assistant's reply
        # Step 4: send the info for each function call and function response to the model
        for tool_call in tool_calls:
            function_name = tool_call.function.name
            function_to_call = available_functions[function_name]
            function_args = json.loads(tool_call.function.arguments)
            function_response = function_to_call(
                location=function_args.get("location"),
                unit=function_args.get("unit"),
            )
            messages.append(
                {
                    "tool_call_id": tool_call.id,
                    "role": "tool",
                    "name": function_name,
                    "content": function_response,
                }
            )  # extend conversation with function response
        print("messages:")
        print(messages)

        second_response = client.chat.completions.create(
            model=model,
            messages=messages,
        )  # get a new response from the model where it can see the function response
        print("second_response:")
        print(second_response)

        return second_response 
     
if __name__ == "__main__":
    
    function_chat()

**Comment by hushuitian** [comment]
参考如下连接做tool_calls处理即可：
https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/function-calling?tabs=non-streaming%2Cpython
