### ISSUE TITLE
关于两块P40卡，只能在一块卡上跑，另外一块不参与工作

### ISSUE THREAD

**Issue by ddyzq** [THUDM/GLM-4#131]
### System Info / 系統信息

torch=2.3.1
transformers=4.40.0
python=3.12.3

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

本地化部署，下载最新的模型。使用的模型为GLM-4-9B-CHAT.在src/main.py文件中加入：
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"
streamlit run src/main.py启动后，使用nvidia-smi查看，发现只有0号GPU有数据，1号GPU没有任何变化
![11](https://github.com/THUDM/GLM-4/assets/167547961/9c5f75fa-e181-4e00-b0fb-9d61ff76b663)

### Expected behavior / 期待表现

还需要如何设置和修改，才能两块P40能同时工作。另外这两块P40在使用CHATGLM3-6B工作正常。

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新的hf代码和github代码重试即可

**Comment by huxian123** [comment]
还是不支持多卡，请问是怎么解决

**Comment by ddyzq** [comment]
重新更新了代码和模型库，还是一样的问题。分别测试添加os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"和不添加该语句，执行效果一样，还有什么别的解决办法么

**Comment by ddyzq** [comment]
测试os.environ["CUDA_VISIBLE_DEVICES"] = "1,0"可以切换第二块GPU工作，但第一块GPU也是处于不工作的状态。

**Comment by yunchang123** [comment]
请问这个问题有人解决了吗，更新了最新的模型和代码还是只在一张卡上运行，怎么才能多卡部署
