### ISSUE TITLE
OOM: finetune multi-turn dialog with tool call out of memory

### ISSUE THREAD

**Issue by toddlt** [THUDM/GLM-4#137]
### System Info / 系統信息

cuda:11.8
transformer:4.39.3
python:3.11

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

在finetune使用lora的config中，跑起来会超出24GB的显存使用，报错：

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 980.00 MiB. GPU 0 has a total capacity of 23.68 GiB of which 706.69 MiB
 is free. Including non-PyTorch memory, this process has 22.99 GiB memory in use. Of the allocated memory 21.77 GiB is allocated by PyTorc
h, and 926.67 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=
expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.htm
l#environment-variables)

使用的数据样例如下：

`{"messages": [{"role": "system", "content": "你是一个酒店客服助手，注意不要询问用户查询条件，仅根据用户上一轮的问题，尽可能多使用酒店查询工具帮用户查询到相关的 酒店。用户没有明确提及的条件千万不要编造，也不要填入空值。查询完给用户回答时力求简单清晰，不多展开解释，回答字数少一些", "tools": [{"type": "function", "function": {"name": "search_hotels", "description": "根据用户的需求生成查询条件来查酒店", "parameters": {"type": "object", "properties": {"name": {"type": "string", "description": "酒店名称"}, "type": {"type": "string", "enum": ["豪华型", "经济型", "舒适型", "高档型"], "description": "酒店类型"}, "facilities": {"type": "array", "items": {"type": "string"}, "description": "酒店能提供的设施列表"}, "price_range_lower": {"type": "number", "minimum": 0, "description": "价格下限"}, "price_range_upper": {"type": "number", "minimum": 0, "description": "价格上限"}, "rating_range_lower": {"type": "number", "minimum": 0, "maximum": 5, "description": "评分下限"}, "rating_range_upper": {"type": "number", "minimum": 0, "maximum": 5, "description": "评分上限"}}, "required": []}}}]}, {"role": "user", "content": "晚上我想要找一家高档的的酒店休息，但是消费不要太高，最好是200-300元的，有合适的么？"}, {"role": "assistant", "content": "{\"name\": \"search_hotels\", \"arguments\": {\"price_range_lower\": 200, \"price_range_upper\": 300, \"type\": \"高档型\"}}"}, {"role": "observation", "content": "[{\"name\": \"北京美第奇精选酒店\", \"type\": \"高档型\", \"address\": \"北京顺义区府前一街32号\", \"subway\": \"国展地铁站C口\", \"phone\": \"010-64583588\", \"facilities\": [\"公共区域和部分房间提供wifi\", \"宽带上网\", \"免费国内长途电话\", \"吹风机\", \"24小时热水\", \"暖气\", \"中式餐厅\", \"无烟房\", \"棋牌室\", \"接机服务\", \"洗衣服务\", \"行李寄存\", \"叫醒服务\"], \"price\": 218.0, \"rating\": 4.6, \"hotel_id\": 403}]"}, {"role": "assistant", "content": "北京美第奇精选酒店这家酒店很符合您的要求。"}, {"role": "user", "content": "这家酒店有免费的国内长途电话吗？"}, {"role": "assistant", "content": "是的，这家酒店提供免费国内长途电话服务。"}]}
`

`
{"messages": [{"role": "system", "content": "你是一个酒店客服助手，注意不要询问用户查询条件，仅根据用户上一轮的问题，尽可能多使用酒店查询工具帮用户查询到相关的 酒店。用户没有明确提及的条件千万不要编造，也不要填入空值。查询完给用户回答时力求简单清晰，不多展开解释，回答字数少一些", "tools": [{"type": "function", "function": {"name": "search_hotels", "description": "根据用户的需求生成查询条件来查酒店", "parameters": {"type": "object", "properties": {"name": {"type": "string", "description": "酒店名称"}, "type": {"type": "string", "enum": ["豪华型", "经济型", "舒适型", "高档型"], "description": "酒店类型"}, "facilities": {"type": "array", "items": {"type": "string"}, "description": "酒店能提供的设施列表"}, "price_range_lower": {"type": "number", "minimum": 0, "description": "价格下限"}, "price_range_upper": {"type": "number", "minimum": 0, "description": "价格上限"}, "rating_range_lower": {"type": "number", "minimum": 0, "maximum": 5, "description": "评分下限"}, "rating_range_upper": {"type": "number", "minimum": 0, "maximum": 5, "description": "评分上限"}}, "required": []}}}]}, {"role": "user", "content": "好的，吃完饭我想去一家最低价格1000元以上的舒适型酒店住宿，给推荐一家吧。"}, {"role": "assistant", "content": "{\"name\": \"search_hotels\", \"arguments\": {\"price_range_lower\": 1000.0, \"type\": \"舒适型\"}}"}, {"role": "observation", "content": "[{\"name\": \"北京都季商旅酒店\", \"type\": \"舒适型\", \"address\": \"北京东城区南河沿大街C座和D座\", \"subway\": \"王府井地铁站\", \"phone\": \"010-85116665\", \"facilities\": [\"酒店各处提供wifi\", \"国际长途电话\", \"吹风机\", \"24小时热水\", \"暖气\", \"中式餐厅\", \"会议室\", \"无烟房\", \"商务中心\", \"早餐服务\", \"接待外宾\", \"行李寄存\", \"叫醒服务\"], \"price\": 1160.0, \"rating\": 4.5, \"hotel_id\": 9}]"}, {"role": "assistant", "content": "推荐您去北京都季商旅酒店住宿。"}]}
`

尝试过的解决办法：

- 使用load_in_4bit=True的BitsAndBytesConfig加载
- 设置max_memory = {0:'24500MB'}约束显存使用
- 添加TrainerCallback来每个step做torch.cuda.empty_cache()

以上方法都不管用，训练过程中依然会OOM异常

### Expected behavior / 期待表现

期待提供一些方法可以更多的节省显存，让24G的显卡可以完成finetune任务

**Comment by toddlt** [comment]
补充：试了一下把system prompt的content设置为空，依然也有sample报OOM

**Comment by zRzRzRzRzRzRzR** [comment]
24GB就是不够的，只能微调大概256-500 token的长度，function call随便就超过了呀
另外这个微调代码是不支持使用Int4模型微调的

**Comment by toddlt** [comment]
@zRzRzRzRzRzRzR 感谢 🙏

还有一个小问题噢，比如我上面的这个数据（或者说finetune的README里规定的带tool call的数据），训完后推理时把message给进去，model.generate输出的最后一个token会标识这一轮是tool call还是给user的reply对吗，也就是：

- 如果最后一个token是<|obeservation|>，那么前面的内容用json.loads一加载，就解析出tool的name和arguments了
- 如果最后一个token是<|user|>或<|endoftext|>，那么前面的内容strip一下就回复给用户了

不过我用lora训完的模型在推理时，前面这个逻辑并不通，会有两种奇怪的现象：

- 最后输出的token从来没有<|user|>，对于给用户reply的轮次，输出的最后一个token都是<|endoftext|>
- 有时会满足前文说的输出最后一个token是<|obeservation|>，但也有时成功且准确的输出了tool call对应内容了，但是结束token是<|endoftext|>，如果是这个token，那咋区分这轮是tool call还是给用户的reply呢？

**Comment by zRzRzRzRzRzRzR** [comment]
不仅仅是这样，在原始的代码中，tools call的格式是非常固定的，你甚至可以用正则化解决问题
一般都是 

工具名
{参数}
<|obeservation|>

**Comment by zRzRzRzRzRzRzR** [comment]
通常来说，结束不会是<|endoftext|>呀，这个情况多吗

**Comment by toddlt** [comment]
> 不仅仅是这样，在原始的代码中，tools call的格式是非常固定的，你甚至可以用正则化解决问题 一般都是
> 
> 工具名 {参数} <|obeservation|>

是的，这个也是我有些疑问的一个点，我试了不finetune前的原始模型做tool call（把tools提供到system message的方式），在assistant回复中就是您说的这种格式：`tool_name \n arguments_json \n <|obeservation|>`

但是在finetune的README中说到“带有工具调用的例子”里提供的例子这一轮是这样的：
`{"role": "assistant", "content": "{\"name\": \"get_recommended_books\", \"arguments\": {\"interests\": [\"history\", \"science fiction\"]}}"}`
这个格式就是我前文说到的那样了，所以是不是这里应该也处理成 `tool_name \n arguments_json \n <|obeservation|>` 格式才对？

**Comment by toddlt** [comment]
> 通常来说，结束不会是<|endoftext|>呀，这个情况多吗

这个我测起来还是挺多的

**Comment by zRzRzRzRzRzRzR** [comment]
不

> > 不仅仅是这样，在原始的代码中，tools call的格式是非常固定的，你甚至可以用正则化解决问题 一般都是
> > 工具名 {参数} <|obeservation|>
> 
> 是的，这个也是我有些疑问的一个点，我试了不finetune前的原始模型做tool call（把tools提供到system message的方式），在assistant回复中就是您说的这种格式：`tool_name \n arguments_json \n <|obeservation|>`
> 
> 但是在finetune的README中说到“带有工具调用的例子”里提供的例子这一轮是这样的： `{"role": "assistant", "content": "{\"name\": \"get_recommended_books\", \"arguments\": {\"interests\": [\"history\", \"science fiction\"]}}"}` 这个格式就是我前文说到的那样了，所以是不是这里应该也处理成 `tool_name \n arguments_json \n <|obeservation|>` 格式才对？

不是的，  <|obeservation|>应该是工具主动返回的
