### ISSUE TITLE
微调后输出结果会出现中英混合回答的现象

### ISSUE THREAD

**Issue by ML-GCN** [THUDM/GLM-4#141]
### System Info / 系統信息

一致

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

微调后输出结果会出现中英混合回答的现象

### Expected behavior / 期待表现

微调后输出结果保持和约定的输入一致

**Comment by zs001122** [comment]
微调训练过程中有保存模型文件的嘛

**Comment by ML-GCN** [comment]
> 你是用什么方式微调，微调的内容有英语吗
谢谢及时回复
用的lora训练的
训练集的提示阶段会有英文 label输出阶段是没有英文的
我用百川2-7b训练同一份数据 没有出现过中英混合的情况
我有原始训练的数据 及保存的最终收敛的参数值 这些我要怎么发给你 帮忙评估一下是什么原因造成的

**Comment by zRzRzRzRzRzRzR** [comment]
也就是输入有英语，输出没有英语，我不需要你的数据集，但是最好能提供你的loss曲线

**Comment by ML-GCN** [comment]
> 也就是输入有英语，输出没有英语，我不需要你的数据集，但是最好能提供你的loss曲线，以及你训练的配置文件，这样能更好的分析
loss图
![image](https://github.com/THUDM/GLM-4/assets/45411027/e50716ae-8cea-461c-98f9-7a8bfd183739)

配置 基于LLaMA-Factory框架跑的
![image](https://github.com/THUDM/GLM-4/assets/45411027/f05fcafe-9d53-482b-aa89-101977bc83ab)

**Comment by zRzRzRzRzRzRzR** [comment]
fp16就不意外了，会精度溢出的，应该只能用bf16训练

中英混合输出还是根本输出不正常，如果输出不正常很有可能是我说的这个问题

**Comment by ML-GCN** [comment]
> fp16就不意外了，会精度溢出的，应该只能用bf16训练
> 
> 中英混合输出还是根本输出不正常，如果输出不正常很有可能是我说的这个问题

输出很正常 微调后很符合我需要的预期结构 就是会夹杂英文
比如：
![image](https://github.com/THUDM/GLM-4/assets/45411027/e770f3ef-fc77-4b7d-aeed-63d68f955e5a)

**Comment by ML-GCN** [comment]
> fp16就不意外了，会精度溢出的，应该只能用bf16训练
> 
> 中英混合输出还是根本输出不正常，如果输出不正常很有可能是我说的这个问题

好的 我试试bf16吧 fp32应该也没有问题吧

**Comment by zRzRzRzRzRzRzR** [comment]
fp32肯定没问题，显存消耗很大呀

**Comment by ML-GCN** [comment]
> fp32肯定没问题，显存消耗很大呀

好的 那你看一下我发的输出结果图的中英混合输出情况的可能原因是啥

**Comment by ML-GCN** [comment]
还有一个问题 想问一下 
有没有考虑出纯中文的模型 这样子就避免这种情况了 嘻嘻

**Comment by zRzRzRzRzRzRzR** [comment]
这个目前没有哦哈哈哈

**Comment by zRzRzRzRzRzRzR** [comment]
> > fp32肯定没问题，显存消耗很大呀
> 
> 好的 那你看一下我发的输出结果图的中英混合输出情况的可能原因是啥

这个要看一下你BF16是不是正常了，如果正常的了就是溢出，然后你读取几个loss没有那么低的保存点试试呢。我没办法下结论

**Comment by ML-GCN** [comment]
> > > fp32肯定没问题，显存消耗很大呀
> > 
> > 
> > 好的 那你看一下我发的输出结果图的中英混合输出情况的可能原因是啥
> 
> 这个要看一下你BF16是不是正常了，如果正常的了就是溢出，然后你读取几个loss没有那么低的保存点试试呢。我没办法下结论

好的 正准备测试看看  感谢大佬的解答 谢谢

**Comment by morettt** [comment]
> > > > fp32肯定没问题，显存占用很大呀
> > > 
> > > 
> > > 好吧，你看看我发的输出结果图的中英输出混合情况的可能原因是啥
> > 
> > 
> > 排除这个一下你BF16不太正常了，如果正常了就是溢出，然后你读取一些损失没有那么低的保存点试试呢。我没办法下结论
> 
> 好的 正准备测试看看 谢谢大佬的解答 谢谢

兄弟，你这个问题解决了吗？我目前也遇到了微调后模型中英混合的情况

**Comment by ML-GCN** [comment]
> > > > > fp32肯定没问题，显存占用很大呀
> > > > 
> > > > 
> > > > 好吧，你看看我发的输出结果图的中英输出混合情况的可能原因是啥
> > > 
> > > 
> > > 排除这个一下你BF16不太正常了，如果正常了就是溢出，然后你读取一些损失没有那么低的保存点试试呢。我没办法下结论
> > 
> > 
> > 好的 正准备测试看看 谢谢大佬的解答 谢谢
> 
> 兄弟，你这个问题解决了吗？我目前也遇到了微调后模型中英混合的情况

没有 猜测应该要加一些英文的数据一起去训练 
平衡数据 才行
