### ISSUE TITLE
What is the long context implementation principle of GLM4 1M

### ISSUE THREAD

**Issue by RyanOvO** [THUDM/GLM-4#144]
如题。

**Comment by davidlvxin** [comment]
<img width="2805" alt="image" src="https://github.com/THUDM/GLM-4/assets/12494969/26305e55-b881-4883-a404-3a1a83470224">

**Comment by RyanOvO** [comment]
流程是清楚了，可以说一下其内的技术么？从给出的图来看，是大量的语料+SFT/PEFT微调。
譬如，是否采用了DeepSpeed-Ulysses之类的技术，从模型的内部等角度支持了长文本的训练。

**Comment by zRzRzRzRzRzRzR** [comment]
这个应该不能，我们目前没有公开详细的技术报告，感谢理解
