### ISSUE TITLE
适配fastchat的时候，参考了chatglm3的提示词模板，为啥会在末尾出现 <|user|>，求助

### ISSUE THREAD

**Issue by web3aipro** [THUDM/GLM-4#146]
### System Info / 系統信息

就是最后输出的时候有这个符号，任何回答都会有这个符号，怎么处理呢？
![image](https://github.com/THUDM/GLM-4/assets/166089210/2fac9177-433c-4959-939c-ffd5f0ad6587)

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

每个回复都会有这个<|user|>，哪里可以找到glm-4 官方建议的提示词模板？以下伟chatglm3的：
```

# ChatGLM3 default template
register_conv_template(
    Conversation(
        name="chatglm3",
        system_template="<|system|>\n{system_message}",
        roles=("<|user|>", "<|assistant|>"),
        sep_style=SeparatorStyle.CHATGLM3,
        stop_token_ids=[
            64795,
            64797,
            2,
        ],  # "<|user|>", "<|observation|>", "</s>"
    )
)
```

### Expected behavior / 期待表现

希望得到回答

**Comment by digshow** [comment]
修改了stop_token_ids也不管用。
stop_token_ids=[151329, 151336, 151338]

**Comment by web3aipro** [comment]
我已经解决了，这个在官方文档有解决方案，在decode时候加入这个参数就可以了：
`skip_special_tokens=True`
