### ISSUE TITLE
为什么这行代码把system的content设置成了None，如果需要带tools也需要设置system的prompt的时候，怎么办呢

### ISSUE THREAD

**Issue by linboyang** [THUDM/GLM-4#154]
https://github.com/THUDM/GLM-4/blob/0b67f9338e2d0b9c04e5cb6d3349f8d330f4f804/basic_demo/openai_api_server.py#L249

**Comment by zRzRzRzRzRzRzR** [comment]
处理不了，因为训练的时候tools就是需要用我们构建的提示词，自己写的sys是没法正常调用的
