### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 36.00 MiB. GPU

### ISSUE THREAD

**Issue by joesZheng** [THUDM/GLM-4#157]
### System Info / 系統信息

v100 gpu * 4 总64G

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

使用basic_demo/openai_api_server.py 只是说显存不足，貌似默认就使用了128K的，调整GPU比例占用也无效

### Expected behavior / 期待表现

加快回复

**Comment by chenchen333-dev** [comment]
我两张GPU卡也出现上面这个问题

**Comment by JeffRody** [comment]
请问一下GLM-4V-9B支持多卡推理吗？

**Comment by zRzRzRzRzRzRzR** [comment]
支持的，查看readme哦
