### ISSUE TITLE
GLM-4v-9B huggingface中调用脚本报错

### ISSUE THREAD

**Issue by jasonstens** [THUDM/GLM-4#158]
我跑huggingface中提供的脚本会报如下错误，请问应该如何解决呢？https://huggingface.co/THUDM/glm-4v-9b
![微信截图_20240613091558](https://github.com/THUDM/GLM-4/assets/56108836/015101cf-4c67-4165-a501-8b228dff80bc)
@zRzRzRzRzRzRzR

**Comment by zRzRzRzRzRzRzR** [comment]
更新一下模型文件，这个bug应该修复了

**Comment by jasonstens** [comment]
似乎没解决：我更新了模型文件，跑官方的脚本还是会报错

**Comment by jasonstens** [comment]
我更新了模型文件，跑官方的脚本还是会报错

**Comment by jasonstens** [comment]
我更新了模型文件，跑官方的脚本还是会报错（系统信息：CUDA Version: 12.2, python3.10, ubuntu 22.04， pytorch Version: 1.14.0a0+410ce96）
![微信截图_20240613091558](https://github.com/THUDM/GLM-4/assets/56108836/369dc7fa-949e-4343-af2b-96388a905c51)

**Comment by harrisonhan** [comment]
下载模型文件替换即可，已解决
