### ISSUE TITLE
Macbook Pro M3 Max，文档解读时报错 MPSNDArray.mm:788: failed assertion `[MPSNDArray initWithDevice:descriptor:] Error: total bytes of NDArray > 2**32'

### ISSUE THREAD

**Issue by BaronZack** [THUDM/GLM-4#159]
### System Info / 系統信息

PyTorch version: 2.4.0.dev20240611
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.5 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.29.3
Libc version: N/A

Python version: 3.12.3 | packaged by Anaconda, Inc. | (main, May  6 2024, 14:46:42) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.5-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Max

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] torch==2.4.0.dev20240611
[pip3] torchaudio==2.4.0.dev20240611
[pip3] torchvision==0.19.0.dev20240611
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.4.0.dev20240611          pypi_0    pypi
[conda] torchaudio                2.4.0.dev20240611          pypi_0    pypi
[conda] torchvision               0.19.0.dev20240611          pypi_0    pypi

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

在composite-demo中：
【源代码修改点】
1.修改了https://github.com/THUDM/GLM-4/blob/c0a6d1e0fa744ebc47d5245aa479cb9e455f2976/composite_demo/src/clients/hf.py#L25
为device_map="mps"支持苹果MPS；
2.修改了https://github.com/THUDM/GLM-4/blob/c0a6d1e0fa744ebc47d5245aa479cb9e455f2976/composite_demo/src/clients/hf.py#L44
timeout=None,超时设置为none；
【复现方法】
1.使用文档解读功能
2.加载模型ok
3.上传任意带图的pdf如附件
[4202_mamba_linear_time_sequence_mod.pdf](https://github.com/user-attachments/files/15813378/4202_mamba_linear_time_sequence_mod.pdf)
4.提问“文章主要内容”
5.报错：
/AppleInternal/Library/BuildRoots/91a344b1-f985-11ee-b563-fe8bc7981bff/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:788: failed assertion `[MPSNDArray initWithDevice:descriptor:] Error: total bytes of NDArray > 2**32'

【其他信息】多模态推理ok，不上传文件时推理ok。

### Expected behavior / 期待表现

可以正常推理长context

**Comment by zRzRzRzRzRzRzR** [comment]
内存够用吗，文档有多长

**Comment by BaronZack** [comment]
> 内存够用吗，文档有多长

128G的，应该是够的，占用不到一半。
pdf文档27页，约600K，试了别的文档，包括在win+nvidia平台下推理过的文档，也是报这个错。

**Comment by BaronZack** [comment]
> 内存够用吗，文档有多长

试了纯文本的pdf推理就是ok的，推测是pdf中涉及图片就会报错？

**Comment by zRzRzRzRzRzRzR** [comment]
那就是在pdf解析的过程中遇到了问题，这个问题应该不属于这个github能解决的问题，或许要参考你这个链接，或者更换一种pdf扫描方式
