### ISSUE TITLE
benchmark reproduce 

### ISSUE THREAD

**Issue by chunniunai220ml** [THUDM/GLM-4#162]
### System Info / 系統信息

Model: THUDM/glm-4-9b-chat
Using via huggingface?: yes
OS: Ubuntu
GPU VRAM: 64G
Number of GPUs: 8
GPU Make: AMD mi250

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

hi, i try to reproduce THUDM/glm-4-9b-chat mmlu benchmark=72.4 by lm_eval, but failed reproduce, test code:
lm_eval --model hf \
        --model_args pretrained="THUDM/glm-4-9b-chat",dtype=bfloat16 \
        --tasks mmlu \
        --device cuda \
        --batch_size 4 \
        --trust_remote_code \
        --cache_requests true \
        --num_fewshot 5
how can i reproduce ur report benchmark 72.4?

### Expected behavior / 期待表现

benchmark evaluation code

**Comment by zRzRzRzRzRzRzR** [comment]
使用openai 的 simple evals尝试复现

**Comment by chunniunai220ml** [comment]
> 使用openai 的 simple evals尝试复现

how to modify samplers for GLM-4-9b and GLM-4-9b-CHAT in simple evals/demo.py? it seems api, how to reproduce by AutoModelForCausalLM and AutoTokenizer, like the huggingface page examples?

**Comment by zRzRzRzRzRzRzR** [comment]
使用 OpenAI API封装成OpenAI格式运行，或者自己基于那个仓库写接口

**Comment by chunniunai220ml** [comment]
https://github.com/openai/simple-evals/blob/main/sampler/chat_completion_sampler.py, 参考这个？，把__call__()换成huggingface page examples， 有这部分test code吗？  https://huggingface.co/THUDM/glm-4-9b-chat显示Inference API (serverless) has been turned off for this model.

**Comment by zRzRzRzRzRzRzR** [comment]
不是不是，是用我们basic demo中的openai server转换成openai格式，之后就按照openai跑就行了

**Comment by chunniunai220ml** [comment]
mmlu benchmark用的是bf.BlobFile("https://openaipublic.blob.core.windows.net/simple-evals/mmlu.csv")这个数据集合吗？
以及：
def get_evals(eval_name):
        match eval_name:
            case "mmlu":
                return MMLUEval(num_examples=1 if debug else 2500)
num_samples是2500吗？ 2500应该不是所有mmlu.csvd的数据吧？
