### ISSUE TITLE
之后是否会提供基于deepspeed的GLM-4V-9B多模态模型的微调demo，或在LLaMA-Factory中加入GLM-4V-9B的微调支持

### ISSUE THREAD

**Issue by nibirou** [THUDM/GLM-4#163]
### Feature request  / 功能建议

目前有些开源多模态模型，如viscpm、qwen-vl都提供了本地微调支持，希望GLM-4V-9B也可以提供微调方案

### Motivation / 动机

目前有些开源多模态模型，如viscpm、qwen-vl都提供了本地微调支持，希望GLM-4V-9B也可以提供微调方案

### Your contribution / 您的贡献

https://github.com/OpenBMB/VisCPM/tree/main/finetune

**Comment by zRzRzRzRzRzRzR** [comment]
目前没有，会在列表中，目前可以用swift框架微调，我们的结构和上述两个开源模型有一定差异
