### ISSUE TITLE
能否统一glm3和glm4的api_server.py 服务？

### ISSUE THREAD

**Issue by dtMndas** [THUDM/GLM-4#165]
### System Info / 系統信息

GLM3:https://github.com/THUDM/ChatGLM3/blob/main/openai_api_demo/api_server.py
GLM4:https://github.com/THUDM/GLM-4/blob/main/basic_demo/openai_api_server.py
两套代码不能模型互用

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

期待可以统一

**Comment by zRzRzRzRzRzRzR** [comment]
这俩底座都不一样，模型调用逻辑也不一样呀
