### ISSUE TITLE
我添加了load_in_4bit=True运行出现了AttributeError: 'NoneType' object has no attribute 'cquantize_blockwise_bf16_fp4'

### ISSUE THREAD

**Issue by xaio6** [THUDM/GLM-4#168]
### System Info / 系統信息

cuda==11.8
pytorch==2.1.2+cu118

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![57b16460329698182277c7bb8eb676a](https://github.com/THUDM/GLM-4/assets/118904918/75156cf6-a288-46ed-a8e0-1fddaef0b413)

### Expected behavior / 期待表现

这是为什么

**Comment by xaio6** [comment]
现在错误变成这样了

![b2c33033ddd30ca8dce42a33a445f6b](https://github.com/THUDM/GLM-4/assets/118904918/dcae1716-926f-4762-8e8f-c060455e481a)
![b2c33033ddd30ca8dce42a33a445f6b](https://github.com/THUDM/GLM-4/assets/118904918/dcae1716-926f-4762-8e8f-c060455e481a)

**Comment by zRzRzRzRzRzRzR** [comment]
建议查看demo
把 to device去掉，我们有怎么载入int4 模型的代码
