### ISSUE TITLE
glm4-9b-chat和glm4-9b-chat-m版本停不下来，容易重复

### ISSUE THREAD

**Issue by chuangzhidan** [THUDM/GLM-4#170]
### System Info / 系統信息

linux 

(dbgpt_env) root@gptai:~# **nvcc --version**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

(dbgpt_env) root@gptai:~# pip show **transformers |** grep Version
Version: 4.41.2

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

**在DB-gpt库中，调用两个glm4-9b模型都遇到一类问题：
模型常常输出大段，停不下来，重复
调用其他模型如qwen-14-chat就不会
如输入‘hi’，不是直接回答，而是会自己输出了一段用户和模型的对话，是续写的风格。下面是另一个典型的回答：**

答：要实现您的需求，我们需要从文件图片信息表中提取数据，进行统计，然后去除包含“undetected”的结果类型，最后使用柱状图绘制排名前五的结果分类。以下是具体的步骤：

查询数据：首先，我们需要从文件图片信息表中查询所有记录。
数据过滤：接下来，我们需要过滤掉结果类型中包含“undetected”的记录。
数据统计：然后，我们需要统计剩余记录中不同结果分类的数量。
去除重复：由于统计结果可能包含重复的分类，我们需要去除重复项。
排序和排名：对统计结果进行排序，并找出排名前五的结果分类。
数据可视化：最后，使用柱状图绘制这些结果分类的统计信息。
由于我无法直接访问数据库或执行绘图命令，以下是一个基于SQL查询的示例，用于获取排名前五的结果分类（假设结果分类存储在result_type字段中）：

SELECT result_type, COUNT(*) AS count
FROM file_image_info
WHERE result_type NOT LIKE '%undetected%'
GROUP BY result_type
ORDER BY count DESC
LIMIT 5;
使用这个查询结果，你可以使用数据可视化工具（如Python的Matplotlib库）来绘制柱状图。

import matplotlib.pyplot as plt

# 假设这是从数据库查询得到的数据
data = [
    ('分类A', 120),
    ('分类B', 90),
    ('分类C', 75),
    ('分类D', 60),
    ('分类E', 45)
]

# 绘制柱状图
categories, counts = zip(*data)
plt.bar(categories, counts)
plt.xlabel('结果分类')
plt.ylabel('数量')
plt.title('排名前五的结果分类')
plt.show()
请注意，你需要根据实际数据进行调整。如果你有其他编程语言和绘图库的偏好，请相应地调整代码。知识库中提供的信息不足以回答此问题。

import matplotlib.pyplot as plt

# 假设这是从数据库查询得到的数据
data = [
    ('分类A', 120),
    ('分类B', 90),
    ('分类C', 75),
    ('分类D', 60),
    ('分类E', 45)
]

# 绘制柱状图
categories, counts = zip(*data)
plt.bar(categories, counts)
plt.xlabel('结果分类')
plt.ylabel('数量')
plt.title('排名前五的结果分类')
plt.show()
请注意，你需要根据实际数据进行调整。如果你有其他编程语言和绘图库的偏好，请相应地调整代码。知识库中提供的信息不足以回答此问题。```python import matplotlib.pyplot as plt

假设这是从数据库查询得到的数据
data = [ ('分类A', 120), ('分类B', 90), ('分类C', 75), ('分类D', 60), ('分类E', 45) ]

绘制柱状图
categories, counts = zip(*data) plt.bar(categories, counts) plt.xlabel('结果分类') plt.ylabel('数量') plt.title('排名前五的结果分类') plt.show() 知识库中提供的信息不足以回答此问题。python import matplotlib.pyplot as plt

假设这是从数据库查询得到的数据
data = [ ('分类A', 120), ('分类B', 90), ('分类C', 75), ('分类D', 60), ('分类E', 45) ]

绘制柱状图
categories, counts = zip(*data) plt.bar(categories, counts) plt.xlabel('结果分类') plt.ylabel('数量') plt.title('排名前五的结果分类') plt.show() 知识库中提供的信息不足以回答此问题。python import matplotlib.pyplot as plt

假设这是从数据库查询得到的数据
data = [ ('分类A', 120), ('分类B', 90), ('分类C', 75), ('分类D', 60), ('分类E', 45) ]

绘制柱状图
categories, counts = zip(*data) plt.bar(categories, counts) plt.xlabel('结果分类') plt.ylabel('数量') plt.title('排名前五的结果分类') plt.show() 知识库中提供的信息不足以回答此问题。python import matplotlib.pyplot as plt

假设这是从数据库查询得到的数据
data = [ ('分类A', 120), ('分类B', 90), ('分类C', 75), ('分类D', 60), ('分类E', 45) ]

绘制柱状图
categories, counts = zip(*data) plt.bar(categories, counts) plt.xlabel('结果

### Expected behavior / 期待表现

不续写，可以停下来

**Comment by zRzRzRzRzRzRzR** [comment]
记得对其对话模板，官方代码的写法能对其，自己写的时候检查stop id eos id这些数字

**Comment by chuangzhidan** [comment]
> stop id eos id

ok，请问有对话模板吗？看stop id eos id的设置

**Comment by ChengjieLi28** [comment]
@zRzRzRzRzRzRzR 您好，我也遇到重复的问题了。chat-9b总是自己自由发挥，像这样，停不下来：
<img width="1578" alt="image" src="https://github.com/THUDM/GLM-4/assets/109656400/94304b32-f6df-4d02-93ef-35636b6e7400">
我没有使用官方transformers的stream_chat聊天接口，用的__call__的forward自己实现的推理过程（过程中使用了past_key_values加速decode过程），参数如下：
temperature 0.6
top_p 0.8
repetition_penalty 1.2
stop_token_id [151336, 151329, 151338]
这些参数与官方的demo保持一致。

麻烦请教下可能的原因是什么？
