### ISSUE TITLE
您好，1、微调脚本finetune.py中第248行代码的目的是啥呢？2、带有工具调用微调时，按照微调脚本 user、observation 此两个special token 对应的label 确定都是 -100 么？

### ISSUE THREAD

**Issue by renjie130** [THUDM/GLM-4#171]
### System Info / 系統信息

Ubuntu20.04  NVIDIA-L40S

### Who can help? / 谁可以帮助到您？

训练glm4-9b-chat模型的相关人员

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1、微调脚本finetune.py中第248行代码 loss_masks = [False, *loss_masks]的目的是啥呢？2、带有工具调用微调时，按照微调脚本 user、observation 此两个special token 所对应的label 确定都是 -100 么？

### Expected behavior / 期待表现

请说明原因

**Comment by zRzRzRzRzRzRzR** [comment]
user 和 observation 是输入部分：这些特殊 token 标记的是用户输入和观察结果，而不是模型生成的输出，因此不需要计算损失。


计算损失时只关注模型生成的部分，以确保模型在生成响应时能够更准确。
将这些特殊 token 排除在损失计算之外，避免了无关信息对模型训练的干扰，提高训练效率和模型效果。

**Comment by renjie130** [comment]
您好，observation 这个special token
在推理时是模型生成的么？推理阶段若是模型生成的，则在训练阶段应该计算损失？若不是模型生成的，那么在推理时怎样有效提取生成的“工具调用部分”给推理系统执行工具呢？

zR ***@***.***> 于2024年6月18日周二 23:09写道：
