### ISSUE TITLE
finetune时出现size mismatch的问题

### ISSUE THREAD

**Issue by swltown** [THUDM/GLM-4#172]
### System Info / 系統信息

[rank6]: shape in current model is torch.Size([5120]).
[rank6]:         size mismatch for transformer.encoder.layers.4.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 4096]) from 
[rank6]: checkpoint, the shape in current model is torch.Size([5120, 4096]).
[rank6]:         size mismatch for transformer.encoder.layers.4.self_attention.query_key_value.bias: copying a param with shape torch.Size([4608]) from checkpoint,

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

运行finetune.py出现该问题。

### Expected behavior / 期待表现

希望能给出一个解决方案

**Comment by zRzRzRzRzRzRzR** [comment]
能给出是这么复现的吗，我微调没出现过这个问题
