### ISSUE TITLE
用openai_api_request.py的function_chat获取天气信息，没有返回内容

### ISSUE THREAD

**Issue by hxujal** [THUDM/GLM-4#175]
### System Info / 系統信息

官方指定的版本

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程
`
from openai import OpenAI

base_url = "http://172.30.30.3:8680/v1/"
client = OpenAI(api_key="EMPTY", base_url=base_url)

def function_chat(use_stream=False):
    messages = [
        {
            "role": "user", "content": "What's the Celsius temperature in San Francisco?"
        },

        # Give Observations
        # {
        #     "role": "assistant",
        #         "content": None,
        #         "function_call": None,
        #         "tool_calls": [
        #             {
        #                 "id": "call_1717912616815",
        #                 "function": {
        #                     "name": "get_current_weather",
        #                     "arguments": "{\"location\": \"San Francisco, CA\", \"format\": \"celsius\"}"
        #                 },
        #                 "type": "function"
        #             }
        #         ]
        # },
        # {
        #     "tool_call_id": "call_1717912616815",
        #     "role": "tool",
        #     "name": "get_current_weather",
        #     "content": "23°C",
        # }
    ]
    tools = [
        {
            "type": "function",
            "function": {
                "name": "get_current_weather",
                "description": "Get the current weather",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "location": {
                            "type": "string",
                            "description": "The city and state, e.g. San Francisco, CA",
                        },
                        "format": {
                            "type": "string",
                            "enum": ["celsius", "fahrenheit"],
                            "description": "The temperature unit to use. Infer this from the users location.",
                        },
                    },
                    "required": ["location", "format"],
                },
            }
        },
    ]

    # All Tools: CogView
    # messages = [{"role": "user", "content": "帮我画一张天空的画画吧"}]
    # tools = [{"type": "cogview"}]

    # All Tools: Searching
    # messages = [{"role": "user", "content": "今天黄金的价格"}]
    # tools = [{"type": "simple_browser"}]

    response = client.chat.completions.create(
        model="chatglm3-6b-32k",
        messages=messages,
        tools=tools,
        stream=use_stream,
        max_tokens=256,
        temperature=0.9,
        presence_penalty=1.2,
        top_p=0.1,
        tool_choice="auto"
    )
    if response:
        if use_stream:
            for chunk in response:
                print(chunk)
        else:
            print(response)
    else:
        print("Error:", response.status_code)

if __name__ == "__main__":
    function_chat(use_stream=False)
`

### Expected behavior / 期待表现

输出天气信息

**Comment by hxujal** [comment]
ChatCompletion(id='', choices=[Choice(finish_reason='tool_calls', index=0, logprobs=None, message=ChatCompletionMessage(content=None, role='assistant', function_call=None, tool_calls=[ChatCompletionMessageToolCall(id='call_1718338747431', function=Function(arguments='{"location": "San Francisco, CA", "format": "celsius"}', name='get_current_weather'), type='function')]))], created=1718338747, model='chatglm3-6b-32k', object='chat.completion', system_fingerprint=None, usage=CompletionUsage(completion_tokens=21, prompt_tokens=217, total_tokens=238))

**Comment by zRzRzRzRzRzRzR** [comment]
这就是正确的啊，模型是不执行工具的，模型是返回调用工具的参数

**Comment by hxujal** [comment]
> 这就是正确的啊，模型是不执行工具的，模型是返回调用工具的参数

那怎么让它调用工具呢

**Comment by zRzRzRzRzRzRzR** [comment]
模型没有这个功能，工具一般是自己写了执行并返回，整合结果作为下一轮对话的提示词传入给模型
