### ISSUE TITLE
运行直接就退出了？

### ISSUE THREAD

**Issue by thomashooo** [THUDM/GLM-4#176]
### System Info / 系統信息

NVIDIA-SMI 536.67                 Driver Version: 536.67       CUDA Version: 12.2
NVCC 11.8 ～ 12.2 ～ 12.4 都试过
Python 3.11.9
torch                         2.1.2+cu118
torchaudio                    2.1.2+cu118
torchvision                   0.16.2+cu118
transformers                  4.41.2

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1、运行直接退出：
(chatglm) D:\GLM-4>python start_chat.py
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

(chatglm) D:\GLM-4>

2、代码文件内容

`
import torch from PIL 
import Image from transformers 
import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
  device = "cuda"
  tokenizer = AutoTokenizer.from_pretrained("THUDM/glm-4v-9b", trust_remote_code=True)
  query = '描述这张图片'

 image = Image.open("1.jpg").convert('RGB')

 inputs = tokenizer.apply_chat_template([{"role": "user", "image": image, "content": query}],                                        add_generation_prompt=True, 
tokenize=True, return_tensors="pt",                                        
return_dict=True)  # chat mode  inputs = inputs.to(device) 
model = AutoModelForCausalLM.from_pretrained(     "THUDM/glm-4v-9b",     torch_dtype=torch.bfloat16,     quantization_config=BitsAndBytesConfig(load_in_4bit=True),     
low_cpu_mem_usage=True,     trust_remote_code=True ).eval()  

gen_kwargs = {"max_length": 2500, "do_sample": True, "top_k": 1} 
with torch.no_grad():    
 outputs = model.generate(**inputs, **gen_kwargs)     
outputs = outputs[:, inputs['input_ids'].shape[1]:]     
print(tokenizer.decode(outputs[0]))

`

### Expected behavior / 期待表现

正常运行

**Comment by zRzRzRzRzRzRzR** [comment]
报错的原因是什么，一点报错没有吗

**Comment by homeant** [comment]
me too

**Comment by homeant** [comment]
发现并没有死，可能就是慢
<img width="807" alt="image" src="https://github.com/THUDM/GLM-4/assets/28803295/5a7c3f4f-639d-4f7c-bc60-4333cb58af1b">

**Comment by thomashooo** [comment]
有什么办法吗

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月15日 12:03 |
| 收件人 | THUDM/GLM-4 ***@***.***> |
| 抄送人 | thomashooo ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [THUDM/GLM-4] 运行直接就退出了？ (Issue #176) |

Closed #176 as not planned.
