### ISSUE TITLE
有人用40g显存finetune成功吗？

### ISSUE THREAD

**Issue by xsank** [THUDM/GLM-4#177]
### System Info / 系統信息

操作系统： centos7
显卡： L40S
显存：40g
cuda：12.2
python: 3.9
torch: 2.3.1

文档说lora训练只要显存 21g
实测：
单机多卡
![image](https://github.com/THUDM/GLM-4/assets/1661334/be880dc8-ec31-4b53-9103-a7a66ea7429d)
单机单卡
![image](https://github.com/THUDM/GLM-4/assets/1661334/a39ca0f0-d6c0-4420-9ebc-6dc6749d20dc)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

在以上环境执行finetune.py即可

### Expected behavior / 期待表现

lora和p-tuning显存真的控制在21g

**Comment by AegonT** [comment]
我也是爆显存

**Comment by zRzRzRzRzRzRzR** [comment]
<img width="779" alt="image" src="https://github.com/THUDM/GLM-4/assets/93239683/dd2bfbd5-3d3d-42b9-8a99-d07b3e50d39a">
为什么会这样呢？
<img width="2892" alt="image" src="https://github.com/THUDM/GLM-4/assets/93239683/e42b5ccd-66fc-4086-bce1-2e97d4912179">

我的代码的界面你这个不一样的

**Comment by xsank** [comment]
> <img alt="image" width="779" src="https://private-user-images.githubusercontent.com/93239683/340640300-dd2bfbd5-3d3d-42b9-8a99-d07b3e50d39a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MTMzNDAsIm5iZiI6MTcxODcxMzA0MCwicGF0aCI6Ii85MzIzOTY4My8zNDA2NDAzMDAtZGQyYmZiZDUtM2QzZC00MmI5LThhOTktZDA3YjNlNTBkMzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDEyMTcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZGY4NWEzOGZmZDZjZDJjYjg3MWViYTM2ZjE1NGVkZGE5NmI0MzNjMGI0NTNiZWIwOGI2YjZiZWQzNzhjNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rcz8ukBOX1vyVkvViD3lKsDyUpZnUvGukI9N7A2Hudk"> 为什么会这样呢？ <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/93239683/340640409-e42b5ccd-66fc-4086-bce1-2e97d4912179.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MTMzNDAsIm5iZiI6MTcxODcxMzA0MCwicGF0aCI6Ii85MzIzOTY4My8zNDA2NDA0MDktZTQyYjVjY2QtNjZmYy00MDg2LWJjZTEtMmU5N2Q0OTEyMTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDEyMTcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNDA5ZmMzOWMyNThjYWY2ZjdiYWY2ZmE3YmI0MjQ3ZWE0YjhhZTBlOWYyZTRhYWZjYzI4YzM3MmUxYWVjMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NhGSMweRr8OWud9yt_x5Nw_9WUD3DFylnNJPCfOrsqM">
> 我的代码的界面你这个不一样的

你那边显卡使用有监控不？整个过程中你的显存都是小于24g的吗？

**Comment by zRzRzRzRzRzRzR** [comment]
你的显存是不是逐渐增加的，有的人遇到这个问题，我会在明后天上传上一个解决这个问题的办法

**Comment by xsank** [comment]
@zRzRzRzRzRzRzR 期待，现在只能先换下qwen 7B来finetune了

**Comment by zRzRzRzRzRzRzR** [comment]
可以试试现在push的这个版本

**Comment by xsank** [comment]
@zRzRzRzRzRzRzR 重新更新模型，推理都不work了...
```shell
2024-06-28 18:01:46,210 - modelscope - INFO - PyTorch version 2.0.1 Found.
2024-06-28 18:01:46,211 - modelscope - INFO - Loading ast index from /home/admin/.cache/modelscope/ast_indexer
2024-06-28 18:01:46,278 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 1e001a052d57184c932b57c82c666b3f and a total number of 980 components indexed
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
thread '<unnamed>' panicked at 'byte index 3 is not a char boundary; it is inside '你' (bytes 2..5) of `
.....
tokenization_utils.py", line 686, in get_input_ids
    tokens = self.tokenize(text, **kwargs)
  File "/home/admin/test/lib/python3.9/site-packages/transformers/tokenization_utils.py", line 617, in tokenize
    tokenized_text.extend(self._tokenize(token))
  File "/home/admin/testbinary/huggingface/modules/transformers_modules/glm-4-9b-chat-1m/tokenization_chatglm.py", line 88, in _tokenize
    ids = self.tokenizer.encode(text)
  File "/home/admin/test/lib/python3.9/site-packages/tiktoken/core.py", line 120, in encode
    return self._core_bpe.encode(text, allowed_special)
pyo3_runtime.PanicException: byte index 3 is not a char boundary; it is inside '你' (bytes 2..5) of `
```
