### ISSUE TITLE
怎么对 seq_len 1M 长度的数据进行sft？finetune_demo 里默认长度只有 1k，增大后会 OOM，1M / 128K 怎样做才能跑的起来？

### ISSUE THREAD

**Issue by atri2549** [THUDM/GLM-4#178]
### Feature request  / 功能建议

无

### Motivation / 动机

咨询

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
微调的长度越长，显存增加非常快，这套开源的方案效率是比较低的，如果真正要调整128K 和1M这样的长度这套框架在消费卡甚至A100都是调不动的

**Comment by atri2549** [comment]
A100-80G 调不动不就没卡能跑了吗？所以效率高的方案会考虑开源吗，或者有第三方仓库参考吗? :eyes:

**Comment by zRzRzRzRzRzRzR** [comment]
目前没有相关计划，您可以使用NeMO等开源框架自行修改尝试调整
