### ISSUE TITLE
官方能出一个api_server.py 服务来支持工具多次调用

### ISSUE THREAD

**Issue by zkbaba** [THUDM/GLM-4#179]
### Feature request  / 功能建议

希望官方能出一个支持连续调用工具的api服务。 比如可以同时一次对话，去执行多次工具的api
![企业微信截图_17182580683586](https://github.com/THUDM/GLM-4/assets/51184036/5f9f8372-6652-437b-8255-e166cd6e2ad9)

### Motivation / 动机

提高执行效率

### Your contribution / 您的贡献

尝试修改了，发现越改越乱，毫无头绪。

**Comment by zRzRzRzRzRzRzR** [comment]
直接使用langchain这样的第三方框架会不会更合适呢。。。
本仓库更多是在模型测的最基础demo进行测试，关于延伸到应用框架层，或许你这种需求可以让langgraph等Agent框架解决
