### ISSUE TITLE
能有支持ollama的版本发布吗?

### ISSUE THREAD

**Issue by triumph** [THUDM/GLM-4#18]
### Feature request  / 功能建议

能有支持ollama的版本发布吗?

### Motivation / 动机

能有支持ollama的版本发布吗?

### Your contribution / 您的贡献

能有支持ollama的版本发布吗?

**Comment by zRzRzRzRzRzRzR** [comment]
暂时没有相关计划，我们会尝试适配

**Comment by zRzRzRzRzRzRzR** [comment]
see #21
