### ISSUE TITLE
finetune时，数据读取错误

### ISSUE THREAD

**Issue by Ye-XX** [THUDM/GLM-4#184]
### System Info / 系統信息

cuda: 12.3
python3.10
ubuntu22.04

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

执行命令python finetune.py data/myself ../../llm/chatglm4-9b-base/ configs/lora.yaml 时候，会出现下面的错误：

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00, 3.87it/s]
trainable params: 2,785,280 || all params: 9,402,736,640 || trainable%: 0.0296

**Generating train split: 0 examples [00:00, ? examples/s]Failed to load JSON from file '/home/aiuser/GLM-4-main/finetune_demo/data/myself/train.jsonl' with error <class 'pyarrow.lib.ArrowInvalid'>: JSON parse error: Column() changed from object to string in row 0**

我的'/home/aiuser/GLM-4-main/finetune_demo/data/myself/train.jsonl'文件内容也是正确的jsonl格式，如下
{ "messages": [ { "role": "user", "content": "XXXX输入的内容" }, { "role": "assistant", "content": "XXXX输出" } ] }
{ "messages": [ { "role": "user", "content": "XXXX输入的内容2" }, { "role": "assistant", "content": "XXXX输出2" } ] }

【疑问】为什么会读取不到文件内容？

同时也发现，数据格式是json时候，会提示错误
NotImplementedError: Cannot load dataset in the '.json' format.
是不是已不再支持json格式

### Expected behavior / 期待表现

与GLM3的数据格式有什么不同？

**Comment by zRzRzRzRzRzRzR** [comment]
请查看finetune demo readme ，已经改成了jsonl

**Comment by Ye-XX** [comment]
> 请查看finetune demo readme ，已经改成了jsonl

使用的就是 jsonl 的格式，但出现了错误提示

Generating train split: 0 examples [00:00, ? examples/s]Failed to load JSON from file '/home/aiuser/GLM-4-main/finetune_demo/data/myself/train.jsonl' with error <class 'pyarrow.lib.ArrowInvalid'>: JSON parse error: Column() changed from object to string in row 0

有遇到类似的问题吗？

**Comment by zRzRzRzRzRzRzR** [comment]
不是，文件名也是jsonl了

**Comment by Ye-XX** [comment]
你可能误解了，我一开始使用的文件就是 jsonl 格式、文件名也为 .jsonl 后缀，文件内容格式如下：

{ "messages": [ { "role": "user", "content": "XXXX输入的内容" }, { "role": "assistant", "content": "XXXX输出" } ] }
{ "messages": [ { "role": "user", "content": "XXXX输入的内容2" }, { "role": "assistant", "content": "XXXX输出2" } ] }
......
{ "messages": [ { "role": "user", "content": "XXXX输入的内容n" }, { "role": "assistant", "content": "XXXX输出n" } ] }

这样的数据在处理时候，提示了错误
Generating train split: 0 examples [00:00, ? examples/s] Failed to load JSON from file '/home/aiuser/GLM-4-main/finetune_demo/data/myself/**train.jsonl**' with error <class 'pyarrow.lib.ArrowInvalid'>: JSON parse error: Column() changed from object to string in row 0

 jsonl 的格式如上，但希望最终确认一下，上面的数据格式就是GLM4微调时的数据格式吗？

**Comment by zRzRzRzRzRzRzR** [comment]
这个数据是格式是对的，只要跟openai格式一样就行

**Comment by peijintao** [comment]
> 你可能误解了，我一开始使用的文件就是 jsonl 格式、文件名也为 .jsonl 后缀，文件内容格式如下：
> 
> { "messages": [ { "role": "user", "content": "XXXX输入的内容" }, { "role": "assistant", "content": "XXXX输出" } ] } { "messages": [ { "role": "user", "content": "XXXX输入的内容2" }, { "role": "assistant", "content": "XXXX输出2" } ] } ...... { "messages": [ { "role": "user", "content": "XXXX输入的内容n" }, { "role": "assistant", "content": "XXXX输出n" } ] }
> 
> 这样的数据在处理时候，提示了错误 Generating train split: 0 examples [00:00, ? examples/s] Failed to load JSON from file '/home/aiuser/GLM-4-main/finetune_demo/data/myself/**train.jsonl**' with error <class 'pyarrow.lib.ArrowInvalid'>: JSON parse error: Column() changed from object to string in row 0
> 
> jsonl 的格式如上，但希望最终确认一下，上面的数据格式就是GLM4微调时的数据格式吗？

解决了吗
