### ISSUE TITLE
client.chat.completions.create()调用接口参数presence_penalty报错

### ISSUE THREAD

**Issue by CVer2022** [THUDM/GLM-4#186]
### System Info / 系統信息

win10
amd
python3.10

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

response = client.chat.completions.create(
        model="glm-4",
        messages=messages,
        stream=False,
        max_tokens=2048,
        temperature=0.9,
        presence_penalty=1.2,
        top_p=0.1,
        **kwargs
    )
    TypeError: Completions.create() got an unexpected keyword argument 'presence_penalty'
    

### Expected behavior / 期待表现

接口怎么设置惩罚参数

**Comment by CVer2022** [comment]
还有调用接口的方式如何设置system prompt，在message中添加system传入模型中好像并不起作用

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码，这些问题好像我都测了，能传入啊

**Comment by zRzRzRzRzRzRzR** [comment]
> 还有调用接口的方式如何设置system prompt，在message中添加system传入模型中好像并不起作用

如果是调用工具的肯定不起作用，后台会直接清空sys 换成我们的all tools的sys才能调用工具

**Comment by CVer2022** [comment]
> > 还有调用接口的方式如何设置system prompt，在message中添加system传入模型中好像并不起作用
> 
> 如果是调用工具的肯定不起作用，后台会直接清空sys 换成我们的all tools的sys才能调用工具

不是调用工具，仅仅是聊天接口，目前觉得可能是system提示词太长了，太长效果不好，短一点效果好一点

**Comment by CVer2022** [comment]
> 更新到最新代码，这些问题好像我都测了，能传入啊

是不是因为pip包没更新，我用的zhipuai包调的

**Comment by zRzRzRzRzRzRzR** [comment]
用openai的包
