### ISSUE TITLE
老的显卡不支持BF16还能跑GLM4吗？

### ISSUE THREAD

**Issue by fishfree** [THUDM/GLM-4#188]
### Feature request  / 功能建议

希望能支持。

### Motivation / 动机

希望能支持。

### Your contribution / 您的贡献

运行发现报错。

**Comment by zRzRzRzRzRzRzR** [comment]
能推理不能微调

**Comment by fishfree** [comment]
@zRzRzRzRzRzRzR 那我只推理，怎么修改代码呢？谢谢！

**Comment by zRzRzRzRzRzRzR** [comment]
直接用FP16推理就可以
