### ISSUE TITLE
vllm cli 命令行启动，仍然报OOM的错误，

### ISSUE THREAD

**Issue by yellowaug** [THUDM/GLM-4#19]
### System Info / 系統信息

A30 24G 
docker-compose 文件
version: '3.8'
services:
  vllm_server_aiorder:
    image: jjck_vllm:20240523
    runtime: nvidia
    ipc: host
    restart: always
    ports:
      - "8100:8000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/**/**/**/glm-4-9b-chat:/aioder/llm_model"
    command: --model /aioder/llm_model --trust-remote-codec
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

### Who can help? / 谁可以帮助到您？

1

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

启动时容器已经正确接收参数

vllm_server_aiorder-vllm_server_aiorder-1  | INFO 06-05 14:36:55 llm_engine.py:103] Initializing an LLM engine (v0.4.2) with config: model='/aioder/llm_model', speculative_config=None, tokenizer='/aioder/llm_model', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=131072, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=/aioder/llm_model)
启动过程
vllm_server_aiorder-vllm_server_aiorder-1  | Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
vllm_server_aiorder-vllm_server_aiorder-1  | WARNING 06-05 14:36:55 tokenizer.py:126] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
vllm_server_aiorder-vllm_server_aiorder-1  | INFO 06-05 14:37:01 model_runner.py:146] Loading model weights took 17.5635 GB
最后还是报错
vllm_server_aiorder-vllm_server_aiorder-1  | [rank0]: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 6.69 GiB. GPU 

### Expected behavior / 期待表现

可以告诉我是什么问题吗？

**Comment by davidlvxin** [comment]
vllm会在warmup阶段尝试最长长度会不会OOM，如果不需要128k长度的输入，可以吧max_seq_len设的小一些，比如是8192
