### ISSUE TITLE
openai_api_server.py 运行报错

### ISSUE THREAD

**Issue by night666e** [THUDM/GLM-4#191]
### System Info / 系統信息

![image](https://github.com/THUDM/GLM-4/assets/125663783/0676c64b-e208-42f4-8ffa-c224e17ac81c)
![image](https://github.com/THUDM/GLM-4/assets/125663783/257e235e-64bc-4715-ac30-fbd5da9400f3)
![image](https://github.com/THUDM/GLM-4/assets/125663783/761c2b28-9a49-4738-96ec-432d89cb37eb)
环境配置图

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程
![image](https://github.com/THUDM/GLM-4/assets/125663783/8c1331a8-0822-4554-bab6-36db7e498f62)
 sudo python openai_api_server.py

### Expected behavior / 期待表现

可以跑通

**Comment by c-x-l-w** [comment]
vllm安装的时候卡住了，怎么解决，cuda是12.3的

**Comment by zRzRzRzRzRzRzR** [comment]
确定都按照readme中的要求装了吗，系统要是linux
