### ISSUE TITLE
文档解读功能后续是否支持excel（.xlsx）文件的解读

### ISSUE THREAD

**Issue by zhangxiangchn** [THUDM/GLM-4#192]
### Feature request  / 功能建议

目前文档解读模式只能支持["pdf", "txt", "py", "docx", "pptx", "json", "cpp", "md"]文档，后续是否能够支持excel文档的解读

### Motivation / 动机

excel文档理解也是目前一个比较重要的方面

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
这里的解读就是吧文件上传上来后整理成文字作为输出，xlsx你自己写脚本转换为文字，但是就丢失了表格级的语义信息
