### ISSUE TITLE
grounding prompt格式问题

### ISSUE THREAD

**Issue by sxlyiyiyi** [THUDM/GLM-4#196]
非常棒的工作，我想在grounding任务中进行微调，请问在glm4v中，对rec和reg任务中的bbox，是用的什么格式的prompt，是[x0,y0,x1,y1]的这种格式吗，坐标是0-1000之间的值吗，是否对图像进行了pad，坐标也会进行相应的处理吗？期待你的答复！

**Comment by zRzRzRzRzRzRzR** [comment]
是 坐标是0-1120
但是好像这个模型没有grounding 能力吧，如果能grounding，给的是pad 成 1120 1120的坐标
