### ISSUE TITLE
FunctionCall/ToolCall数据格式问题

### ISSUE THREAD

**Issue by whybeyoung** [THUDM/GLM-4#199]
### System Info / 系統信息

Glm4  9b chat

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程
```json
    "messages": [
      {
        "role": "system",
        "content": "<system prompt text>",
        "tools": [
          {
            "name": "<tool name>",
            "args": {
              "<arg name>": "<arg value>"
            }
          }
          // Add more tools if needed
        ]
      },
      {
```
训练数据集好像没有把 tool定义训练进去？ 只是带funciton 和 args？ description之类的呢？

### Expected behavior / 期待表现

function定义注入到system里去

**Comment by zRzRzRzRzRzRzR** [comment]
<arg name> 的部分
