### ISSUE TITLE
glm-4v 多卡cli 仍然存在问题 （四张卡的a100 ）

### ISSUE THREAD

**Issue by GuoXu-booo** [THUDM/GLM-4#200]
### System Info / 系統信息

python==3.12
cuda==12.4
4 a100 80g

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

执行命令： CUDA_VISIBLE_DEVICES=0,1,2,3 python trans_cli_vision_demo.py
报错：RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cuda:3!
特别：一二三张卡的时候都不会报以上错误。
确认：我的代码和hf文件都是最新的，之前已关闭的issue问题所提到的hf文件我已确认是修改好的

### Expected behavior / 期待表现

为什么会存在该问题呢

**Comment by zRzRzRzRzRzRzR** [comment]
只能到三张，因为视觉模块是不能分开的，拆成四张的时候好像视觉部分被拆开了导致了错误，在readme中有提到

**Comment by GuoXu-booo** [comment]
> 只能到三张，因为视觉模块是不能分开的，拆成四张的时候好像视觉部分被拆开了导致了错误，在readme中有提到

噢噢 感谢

**Comment by orderer0001** [comment]
> 只能到三张，因为视觉模块是不能分开的，拆成四张的时候好像视觉部分被拆开了导致了错误，在readme中有提到

你好 我用三卡部署,因为第三张卡需要部署另一个模型,所以只能部署到0和1,也会出现RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!  我针对model.safetensors.index.json 设置了每一层,把含有vision的放到了1,其他都在0.依然是这个报错.请问  哪些层是不能分开的?有明示吗?感谢

**Comment by orderer0001** [comment]
> > 只能到三张，因为视觉模块是不能分开的，拆成四张的时候好像视觉部分被拆开了导致了错误，在readme中有提到
> 
> 噢噢 感谢

你好 我用三卡部署,因为第三张卡需要部署另一个模型,所以只能部署到0和1,也会出现RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!  我针对model.safetensors.index.json 设置了每一层,把含有vision的放到了1,其他都在0.依然是这个报错.请问  哪些层是不能分开的?有明示吗?感谢

**Comment by zRzRzRzRzRzRzR** [comment]
vision的部分都是必须在一张卡上运行的
