### ISSUE TITLE
使用tensorrt-llm运行glm4报错：pyo3_runtime.PanicException: byte index 1 is not a char boundary; it is inside '请' (bytes 0..3) of `请根据你的知识回答问题：xxx。

### ISSUE THREAD

**Issue by 15929482853** [THUDM/GLM-4#201]
### System Info / 系統信息

chatglm_version使用的chatglm3，运行chatglm3正常

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1

### Expected behavior / 期待表现

期待回复

**Comment by zRzRzRzRzRzRzR** [comment]
这两代不兼容，模板不通用，也就是只要换个模板就行，但是应该不影响推理呀

**Comment by mengrennwpu** [comment]
升级下tiktoken>=0.7.0尝试下

**Comment by mengrennwpu** [comment]
@15929482853 升级下tiktoken>=0.7.0尝试下

**Comment by 15929482853** [comment]
> @15929482853 升级下tiktoken>=0.7.0尝试下

升级tiktoken版本后成功推理，感谢帮助！
