### ISSUE TITLE
modeling_chatglm.py在非 SDPA模式下shape mismatch

### ISSUE THREAD

**Issue by Tiantian-Han** [THUDM/GLM-4#202]
[https://huggingface.co/THUDM/glm-4-9b/blob/main/modeling_chatglm.py#L264](url)
 output_size shape bug.
 
 Modify:
  output_size = (value_layer.size(1), value_layer.size(2), query_layer.size(0), value_layer.size(3))

 to:
 output_size = (value_layer.size(0), value_layer.size(1), query_layer.size(1), value_layer.size(3))

**Comment by hiyouga** [comment]
@zRzRzRzRzRzRzR https://huggingface.co/THUDM/glm-4-9b/discussions/7

**Comment by zRzRzRzRzRzRzR** [comment]
fix it thank!
