### ISSUE TITLE
最新版本代码和依赖, openai_api_server.py 启动 , ptype=half , 90G显存 , 对话输出乱码

### ISSUE THREAD

**Issue by yuanzhiwei** [THUDM/GLM-4#206]
![image](https://github.com/THUDM/GLM-4/assets/17841347/777e59f7-ade4-4aa2-908d-130c6419b49b)

**Comment by zRzRzRzRzRzRzR** [comment]
ptype=half是啥

**Comment by yuanzhiwei** [comment]
![image](https://github.com/THUDM/GLM-4/assets/17841347/961684d7-59cf-40da-a444-229d0e4e81e7)
哦 , 打错了 dtype=half

**Comment by zRzRzRzRzRzRzR** [comment]
要用bf16

**Comment by yuanzhiwei** [comment]
嗯 我一开始是用的bfloat16 报错了显卡不支持  
![image](https://github.com/THUDM/GLM-4/assets/17841347/fc044708-090a-4dbf-b879-71613a50a4bb)
看他提示让我写成half

**Comment by zRzRzRzRzRzRzR** [comment]
你试试fp16，正常来说应该是能兼容的，我们readme上有写最好是bf16
