### ISSUE TITLE
Is there any plan to merge the `modeling_chatglm.py` into the Transformers library?

### ISSUE THREAD

**Issue by iofu728** [THUDM/GLM-4#207]
### Feature request  / 功能建议

Hi GLM-4 Team,

Thanks for your great work and the powerful GLM-4 models. I'm currently conducting research on efficient long-context LLMs inference and am trying to implement our method in GLM-4-1M. To reduce the effort, I wanted to ask if there are any plans to merge the modeling_chatglm.py into the Transformers library? This would greatly help our work and benefit the community. Thanks for your help!

### Motivation / 动机

To do some experiments on efficient long-context LLMs inference topic.

### Your contribution / 您的贡献

I'll open-source the related experiments results and implementation.

**Comment by zRzRzRzRzRzRzR** [comment]
We also aim to adapt to the Transformers library. However, the current model implementation contains some legacy code that may not fully comply with the requirements of the Transformers library. We will make the necessary modifications as soon as possible and submit a PR to the Transformers library. This may take some time, and we appreciate your understanding.

**Comment by iofu728** [comment]
Thanks @zRzRzRzRzRzRzR for the response and plan. Looking forward the merged version GLM-4.

**Comment by zRzRzRzRzRzRzR** [comment]
This issue will be closed first. We will make an announcement after merging it into hf. Thank you for your support.
