### ISSUE TITLE
How to finetune GLM-4V-9B with LoRA?

### ISSUE THREAD

**Issue by zengzwww** [THUDM/GLM-4#208]
### Feature request  / 功能建议

Add tutorial for fine-tuning GLM-4V-9B using LoRA in https://github.com/THUDM/GLM-4/tree/main/finetune_demo.

### Motivation / 动机

I want to apply GLM-4V-9B to a special field and solve industry problems through graphic question-and-answer. I need to fine-tune the model based on the data in this field to improve the performance of the model. However, our computing resources are very prioritized, so we need to use technologies like LoRA to fine-tune the model. I hope you can provide some guidance. Thank you!

### Your contribution / 您的贡献

https://github.com/THUDM/GLM-4/blob/main/finetune_demo/README.md

**Comment by XuRui314** [comment]
请问能不能直接拿cogvlm2的finetune_demo直接调glm4v

**Comment by kaiserrli** [comment]
同问同问，期待4v的sft功能解锁

**Comment by zRzRzRzRzRzRzR** [comment]
现在可以先试用swift框架微调，我们暂时没有那么高的优先级处理GLM-4b-9B的微调，但是这个任务正在我们的计划中

**Comment by zRzRzRzRzRzRzR** [comment]
> 请问能不能直接拿cogvlm2的finetune_demo直接调glm4v

这个代码没有微调视觉模块，是因为cogvlm2使用的是数据并行，会超过80G显存，GLM-4v-9B可以自行尝试，结构相似

**Comment by elloza** [comment]
Would it be possible to fine tune the GLM-4V-9B (vision) model with consumer hardware such as one or two rtx3090? I mean using techniques such as LORA etc.

A small example guide for this case would be fantastic and would give a lot of visibility to this model, [as it happens with pali gemma](https://www.youtube.com/watch?v=hDa-M91MSGU).

Congratulations to the authors!

**Comment by XuRui314** [comment]
我这里有一份实现的代码可以供参考：
https://github.com/XuRui314/GLM4v-Finetune
