### ISSUE TITLE
在华为的NPU的服务器上如何搭建？

### ISSUE THREAD

**Issue by dayphosphor** [THUDM/GLM-4#209]
### Feature request  / 功能建议

在华为的NPU的服务器上如何搭建？ 现在国有化呼声很高

### Motivation / 动机

国有化呼声很高

### Your contribution / 您的贡献

有没有步骤实现？

**Comment by zRzRzRzRzRzRzR** [comment]
能适配torch，支持BF16就行，跟模型权重应该关系不大。
不过，我没有相关机器进行测试，不确定，因此这个需要您自己测试
