### ISSUE TITLE
支持Ollama部署

### ISSUE THREAD

**Issue by marxy** [THUDM/GLM-4#21]
### Feature request  / 功能建议

目前有很多开源模型支持了ollama部署，请问GLM4有ollama部署的教程吗？或者能否给出下prompt template和stop token，我自己转换试下。

### Motivation / 动机

希望有ollama部署部署教程

### Your contribution / 您的贡献

ollama参考：
https://github.com/ollama/ollama/blob/main/docs/import.md
https://github.com/ollama/ollama/blob/main/docs/modelfile.md

**Comment by deadash** [comment]
我看到一个pr是支持GLM3的，还有一个项目llama.cpp分支专门支持GLM3，你可以参考一下看看能不能先支持llama.cpp，再考虑ollama

https://github.com/ggerganov/llama.cpp/pull/6999/files
https://github.com/li-plus/chatglm.cpp

**Comment by wwjCMP** [comment]
如果支持ollama部署还是很方便

**Comment by dannypei** [comment]
非常期待

**Comment by zRzRzRzRzRzRzR** [comment]
我们正在适配中，GLM结构和llama差距较大，还有gguf制作，需要一定时间

**Comment by lijiajun1997** [comment]
加油 有进展请告知

**Comment by Forevery1** [comment]
> 时间

加油，非常期待

**Comment by Forevery1** [comment]
> 我们正在适配中，GLM结构和llama差距较大，还有gguf制作，需要一定时间

加油，感谢辛苦付出

**Comment by Ma-Yongqiang** [comment]
期待

**Comment by javaDer** [comment]
期待

**Comment by snakeying** [comment]
非常期待

**Comment by dannypei** [comment]
期待

**Comment by zRzRzRzRzRzRzR** [comment]
https://github.com/ggerganov/llama.cpp/pull/8031
llama.cpp有一个相关pr，这部分还在跟进，感谢大家耐心等待

**Comment by still1987** [comment]
期待

**Comment by jiaolongxue** [comment]
支持

**Comment by kayzhou** [comment]
支持且期待

**Comment by arkerwu** [comment]
支持且期待

**Comment by mchiang0610** [comment]
支持且期待

**Comment by zRzRzRzRzRzRzR** [comment]
进度更新，llamacpp已经支持glm模型
https://github.com/ggerganov/llama.cpp/pull/8031

**Comment by javaDer** [comment]
https://ollama.com/library/glm4 已适配,请体验

**Comment by zRzRzRzRzRzRzR** [comment]
已经适配

**Comment by snakeying** [comment]
我在ollama中调用GLM4发现无法使用GPU加速？全部都是CPU在跑 @@？

**Comment by LQscience** [comment]
> 我在ollama中调用GLM4发现无法使用GPU加速？全部都是CPU在跑 @@？
我将ollama更新到v0.2.0，调用GLM4是使用GPU的

**Comment by snakeying** [comment]
请问可以共享一下modelfile吗

**Comment by kayzhou** [comment]
MacOS 15, M2 Pro

ollama run glm4

得到以下报错
Error: llama runner process has terminated: signal: abort trap error:error loading model architecture: unknown model architecture: 'chatglm'

**Comment by snakeying** [comment]
> MacOS 15, M2 Pro
> 
> ollama run glm4
> 
> 得到以下报错 Error: llama runner process has terminated: signal: abort trap error:error loading model architecture: unknown model architecture: 'chatglm'

1. 升级最新版本的ollama，0.21
2. 如果你在hf上下载的，请使用second-state的版本  （ https://huggingface.co/second-state/glm-4-9b-chat-GGUF ）

**Comment by zzlTim** [comment]
ollama下载的chatglm4都是量化后的吗？有没有原始的9b模型
