### ISSUE TITLE
请问glm-4v有做支持vllm的计划吗

### ISSUE THREAD

**Issue by GanPeixin** [THUDM/GLM-4#215]
### Feature request  / 功能建议

glm-4v有做支持vllm的计划吗，有的话大概什么时候上线呢？

### Motivation / 动机

推理加速

### Your contribution / 您的贡献

https://github.com/vllm-project/vllm

**Comment by zRzRzRzRzRzRzR** [comment]
已经在计划中，但是要等待一段时间，目前适配中，还有一些挑战
