### ISSUE TITLE
怎么取消生成回答中带有表情

### ISSUE THREAD

**Issue by kawayi12318** [THUDM/GLM-4#216]
### System Info / 系統信息

glm-4-9b-chat

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

query: 你好
response: 你好👋！我是人工智能助手，很高兴见到你，有什么可以帮助你的吗？

我尝试过分别在system prompt和user prompt中写入“禁止出现表情”，但都没什么用

### Expected behavior / 期待表现

取消表情符号，例如: 👋

**Comment by wwb-bigai** [comment]
@kawayi12318 请问一下，您最后是如何去掉表情符号的。谢谢

**Comment by kawayi12318** [comment]
> @kawayi12318 请问一下，您最后是如何去掉表情符号的。谢谢

@wwb-bigai 用正则去匹配的

**Comment by wwb-bigai** [comment]
> > @kawayi12318 请问一下，您最后是如何去掉表情符号的。谢谢
> 
> @wwb-bigai 用正则去匹配的

好的，谢谢。
我也是查了一圈没看到官方的解法o(╥﹏╥)o
