### ISSUE TITLE
模型许可证

### ISSUE THREAD

**Issue by Pickpate** [THUDM/GLM-4#219]
你好，感谢对于社区的贡献。
我有一些关于模型许可证的问题，希望得到你们的答复。同时也希望能够模型许可证向你们提供一些建议，以促进该模型更好被采用。
1.我看到这里要求商用（一般认为商用的范围非常大）需要登记。我想确认下，这里的登记是指填写信息即可，不必等到回复，还是说必须等到收到贵方提供的允许商用许可证？
2.收到的允许商用的许可证中的具体要求与当前模型license文件的要求不是一致的，此时以那个为准？还是两者要求的所有义务都涉及呢？
3.在收到的商用许可证中，有如下2个地方，我们感觉不是很清楚：
1）有一条要求如下，请问这里是附上“此模型商用授权协议”是指附上我们收到的授权文件么？还是附上你们在huggingface上传的license？我们收到的文件应该是没有连接的，需要我们自己托管一个连接么？
来源说明：使用者使用大模型和大模型生成内容时须注明大模型的来源并附上此模型商用授权协议（或链接）。
2）我们收到的针对glm-4提供的模型商用授权协议授权日期（2023年7月1日）远远早于glm4的发布日期。我们理解这个应该是能够覆盖glm4的模型的，不过还是希望能够得到您的确认。
4.关于如下条款，我们想确认下，当基于该模型搭建应用的时候，我们一般不会针对该应用或者该应用的某个功能进行名称（或者仅以要达到的效果进行命名，比如一键纠错），此时该如何履行该模型还必须以“glm-4”开头进行命名呢？
“如果您使用 THUDM / 智谱AI的 glm-4 开源模型的材料来创建、训练、微调或以其他方式改进已分发或可用的 AI 模型，您还应在任何此类 AI 模型名称的开头添加 “glm-4”。”
在将模型用于对外服务时，许可证已经要求履行“(B) 在相关网站、用户界面、博客文章、关于页面或产品文档上突出显示 “Built with glm-4”。”的情况下，是否还有必要在专门通过新模型的名称披露用到了glm4呢？
最后，一点小的建议，我们看到yi系列和Qwen2已经转向了Apache 2.0的许可证。贵司是否考虑用相对宽松和标准的许可证呢？这样对于使用方来说，理解成本要低很多。

**Comment by zRzRzRzRzRzRzR** [comment]
1.这里的登记是指填写信息即可，不必等到回复。
2. 协议是你在bigmodel填写的那个问卷，如果你要对模型在分发，也要放上license，这个hf的license是旨在你用glm模型又继续训练/ 微调 得出新模型，并准备分发这个模型的时候需要遵守这个license。
3. 为什么会在 2023年7月1日 收到还没有发布的 glm-4的商用协议，那时候GLM3都没有呀
4. Built with glm-4是要加的，如果你要宣传你的模型，需要按照glm-4的协议来命名新的模型名字。
5. Qwen 确实不需要加 Qwen字段到新的模型前面 ，但他们不是Apache 2.0的许可证。请查看Qwen对应的特殊条款。

**Comment by Pickpate** [comment]
非常感谢您的回复。我们非常希望严格按照您的许可证的要求使用，所以还是想和您确认清楚如下问题：
2.所以只是部署模型并基于模型对外提供服务，而不是分发模型文件（一般认为把模型副本给到别人算分发，部署服务不算分发），是不需要放license文本的对么？
3.不是在2023年7月1日收到，而是我们登记了之后，会收到一个新的模型许可证，该许可证文本的签署日期是2023年7月1日；该许可证文本本身没有体现是针对哪个具体模型的授权。该许可证和您在hf上的许可证是不一致的，要求也有所不同。
4.嗯嗯，您说的情况我明白。我想更清楚描述下我们的场景，我们希望用精调后的模型对外（主要是C端）提供服务（比如做一个bot或者用来生成文案），这种情况我们通常不会展示模型的名称给用户；此时我们还需要专门对我们精调后的模型命名下，并在端上展示给用户么？如果是的话，该怎么落地呢？您也知道，在端上尤其是C端，能够展示这种信息的地方很少。
5.无意冒犯，不过我想和您同步下更多的信息。参考这个blog（https://qwenlm.github.io/blog/qwen2/），新版本Qwen 2中的小尺寸模型都是Apache 2.0了。“While Qwen2-72B as well as its instruction-tuned models still uses the original Qianwen License, all other models, including Qwen2-0.5B, Qwen2-1.5B, Qwen2-7B, and Qwen2-57B-A14B, turn to adopt Apache 2.0!”

**Comment by zRzRzRzRzRzRzR** [comment]
2. 不用放，因为没有再分发
3. 这个证明估计是早期商业版本协议中的不一致，由于我不是商业团队的伙伴，不太了解这个情况。关于这一点，我会尽快确认
4. 不用，但是算法备案等相关文如果需要填写原始模型，需要填写模型Built with glm-4。如果您的产品有页面，需要在页面标注Built with glm-4。当然，如果您使用的是商业模型的API，并不需要。
5. 感谢你的指正，我们会关注到这一点并作为参考（因为我主要爱关注72B）

**Comment by Pickpate** [comment]
好的，非常感谢您的答复。

**Comment by fangcun12138** [comment]
> 使用者使用大模型

抱歉，我看到这里时有一个疑问，既然这位提问者拿到的商业许可证里的要求是”使用者使用大模型和大模型生成内容时须注明大模型的来源并附上此模型商用授权协议（或链接）。“

**Comment by fangcun12138** [comment]
> 2. 不用放，因为没有再分发

抱歉，关于这一点回复我有一个疑问，既然商业许可证中的要求是“使用者使用大模型和大模型生成内容时须注明大模型的来源并附上此模型商用授权协议（或链接）”，那么为什么只有在【再分发】的情况下才需要附上授权协议呢？难道不是一旦【使用】，就都应当附上授权协议了吗？   提问者提出的【部署模型并基于模型对外提供服务】的情形，我认为就符合【使用大模型和大模型生成内容】的条件了呀？望解答。谢谢！
