### ISSUE TITLE
trans_web_demo.py报推理卡错误

### ISSUE THREAD

**Issue by HelixPark** [THUDM/GLM-4#22]
### System Info / 系統信息

transformers                      4.40.0
torch                             2.3.0

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

运行trans_web_demo.py，报下述错误，modeling_chatglm.py 627行。

Exception has occurred: RuntimeError
Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:2! (when checking argument for argument tensors in method wrapper_CUDA_cat)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py", line 627, in forward
    presents = torch.cat((presents, kv_cache), dim=0)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py", line 777, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py", line 881, in forward
    transformer_outputs = self.transformer(
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:2! (when checking argument for argument tensors in method wrapper_CUDA_cat)

### Expected behavior / 期待表现

...

**Comment by zRzRzRzRzRzRzR** [comment]
已经修复，clone hf最新模型实现代码

**Comment by chuangzhidan** [comment]
> 已经修复，clone hf最新模型实现代码

modeling_chatglm.py
这个文件做替换即可？
