### ISSUE TITLE
brower 请求会导致显存泄漏，直到显存溢出报错

### ISSUE THREAD

**Issue by wwewwt** [THUDM/GLM-4#222]
### System Info / 系統信息

cuda12.4，torch2.3.1+cu121

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1、配置好bing  search key
2、启动 [composite_demo](https://github.com/THUDM/GLM-4/tree/main/composite_demo)
3、苹果公司最近发布了哪些产品
4、比亚迪公司最近发布了哪些产品
5、华为公司最近发布了哪些产品
观察显存会一直增加，直到占满

### Expected behavior / 期待表现

大模型完成回复后，释放占用的现成

**Comment by zRzRzRzRzRzRzR** [comment]
清空历史了吗，不然一次search就是一次长提示词，显存叠的当然快

**Comment by wwewwt** [comment]
> 清空历史了吗，不然一次search就是一次长提示词，显存叠的当然快

清空历史显存也不会降

**Comment by zRzRzRzRzRzRzR** [comment]
emm，然后没有其他报错，就是显存一直加上去直到显存溢出么，我现在没有复现出来
