### ISSUE TITLE
Question about word embedding

### ISSUE THREAD

**Issue by Wonderland23** [THUDM/GLM-4#224]
您好，请问模型的word embedding是跟随模型一起训练得到，还是采用了某个预训练的word embedding?
这部分的权重在fine tuning时是否会改变？

**Comment by zRzRzRzRzRzRzR** [comment]
1. 是一起训的
2. 如果是lora，word embedding不会变，如果是sft，会

**Comment by Wonderland23** [comment]
感谢回复
