### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by ZHDTZ** [THUDM/GLM-4#226]
### System Info / 系統信息

你好，Windows环境下conda的python3.12版本中成功运行`trans_web_demo.py`，添加了cuda支持，composite_demo的requirement.txt已完成。

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

如`mian.py`所示

### Expected behavior / 期待表现

在`streamlit run src/main.py`显示如下报错，请帮我指出问题所在，谢谢。以下为报错详情
![PixPin_2024-06-23_21-38-29](https://github.com/THUDM/GLM-4/assets/106635760/c2a279dc-5b15-43d1-893f-242728df90ae)

**Comment by zRzRzRzRzRzRzR** [comment]
后台也只有这个错误吗

**Comment by ZHDTZ** [comment]
你好，是的

![PixPin_2024-06-24_19-15-15](https://github.com/THUDM/GLM-4/assets/106635760/4beca844-4194-4af3-be2f-4c172794fca1)

**Comment by zRzRzRzRzRzRzR** [comment]
刚才复现了一下，在Linux环境下好像没有遇到这个问题，需要check一下你的streamlit版本
