### ISSUE TITLE
glm4可以进行增量预训练吗，能提供一下脚本吗

### ISSUE THREAD

**Issue by gyh123wqe** [THUDM/GLM-4#231]
### System Info / 系統信息

glm4

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

glm4

### Expected behavior / 期待表现

glm4

**Comment by zRzRzRzRzRzRzR** [comment]
目前没有提供相关脚本的计划，感谢您的支持
