### ISSUE TITLE
GLM4v - 9b最新的modelscope文件中有print

### ISSUE THREAD

**Issue by ChengjieLi28** [THUDM/GLM-4#238]
### System Info / 系統信息

Any

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR 

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

从modelscope下载模型，调用generate推理就会出现
<img width="1065" alt="image" src="https://github.com/THUDM/GLM-4/assets/109656400/c9ae6da5-8d7d-45c5-8a62-3e2001018077">

### Expected behavior / 期待表现

没有print

**Comment by zRzRzRzRzRzRzR** [comment]
fix
