### ISSUE TITLE
怎么指定使用两块gpu启动

### ISSUE THREAD

**Issue by zhang19523zhao** [THUDM/GLM-4#24]
### System Info / 系統信息

怎么指定使用两块gpu启动

### Who can help? / 谁可以帮助到您？

怎么指定使用两块gpu启动

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

怎么指定使用两块gpu启动

### Expected behavior / 期待表现

怎么指定使用两块gpu启动

**Comment by zhang19523zhao** [comment]
os.environ["CUDA_VISIBLE_DEVICES"] = "2,3"
nvidia-smi 看只用第2块

**Comment by zhang19523zhao** [comment]
> 已经修复，hf更新一下modeling chatglm这个代码

大佬我刚刚下了最新的代码跑还是一样的是哪里要改吗

**Comment by zhang19523zhao** [comment]
![image](https://github.com/THUDM/GLM-4/assets/77541540/8d7f807c-8b73-4a3d-b3b7-af219a0acd7e)
![image](https://github.com/THUDM/GLM-4/assets/77541540/59acf8f4-d26a-4364-a421-221ba854b3b6)

**Comment by zhang19523zhao** [comment]
> 已经修复，hf更新一下modeling chatglm这个代码

<img width="1463" alt="image" src="https://github.com/THUDM/GLM-4/assets/77541540/32d1391c-7c91-4ed2-827e-8cc3ac251ed8">

**Comment by zhang19523zhao** [comment]
> 已经修复，hf更新一下modeling chatglm这个代码
![image](https://github.com/THUDM/GLM-4/assets/77541540/1d7a017f-2d93-419f-991c-edd7b83cb760)

**Comment by zRzRzRzRzRzRzR** [comment]
现在应该能正常的在两张卡上推理的。

**Comment by xbsdsongnan** [comment]
我更新了，还是不行呢

**Comment by xbsdsongnan** [comment]
我运行的时候为什么还出现错误，OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /home/GLM-4/glm-4-9b-chat.

**Comment by HysysRobert** [comment]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 214.00 MiB. GPU 

我这提示这个，glm-4-9b-chat，两个16G的不能多卡运行

**Comment by zRzRzRzRzRzRzR** [comment]
问题已经解决，我今天测的时候没有在遇到相似问题，确定你的device map是auto并使用了hf 的最新模型实现

**Comment by zhang19523zhao** [comment]
> 问题已经解决，我今天测的时候没有在遇到相似问题，确定你的device map是auto并使用了hf 的最新模型实现

魔塔上的可以不

**Comment by aka-wen** [comment]
<img width="761" alt="image" src="https://github.com/THUDM/GLM-4/assets/47880652/8cd028a6-82f9-40eb-842e-675a7d646fd4">

**Comment by zRzRzRzRzRzRzR** [comment]
可以，我都更新了

**Comment by ddyzqddwb** [comment]
> 问题已经解决，我今天测的时候没有在遇到相似问题，确定你的device map是auto并使用了hf 的最新模型实现

DEVICE MAP在哪里设置

**Comment by zRzRzRzRzRzRzR** [comment]
model = AutoModel.from_pretrained(
    MODEL_PATH,
    trust_remote_code=True,
    device_map="auto").eval()

**Comment by zhanghuanhuanlive** [comment]
openai_api_server.py应该怎么改呢

**Comment by ddyzq** [comment]
> model = AutoModel.from_pretrained( MODEL_PATH, trust_remote_code=True, device_map="auto").eval()

![55](https://github.com/THUDM/GLM-4/assets/167547961/b68c2067-e27f-40b9-9349-7ab83f4d18c5)

![66](https://github.com/THUDM/GLM-4/assets/167547961/c2cb518a-59c7-40b9-9875-ccb54752f343)
添加后提示：NameError: name 'AutoModel' is not defined 没有定义AutoModel
是我错过了什么？还有关于glm-4多GPU的资料哪里有，一直没找到

**Comment by zRzRzRzRzRzRzR** [comment]
这个是你库没有装对吧，多GPU载入的话直接在cli demo （basic demo文件夹）中就有了

**Comment by ddyzqddwb** [comment]
我是在composite_demo文件夹下使用streamlit run src/main.py加载的，这样不能使用多GPU么？










在 2024-06-15 23:53:36，"zR" ***@***.***> 写道：

这个是你库没有装对吧，多GPU载入的话直接在cli demo （basic demo文件夹）中就有了

**Comment by zhaozhenhua123** [comment]
还有别的办法可以指定GPU吗,我想在一个python脚本启动两个大模型，并且分别为两个大模型指定GPU

**Comment by lzs2000131** [comment]
> > model = AutoModel.from_pretrained( MODEL_PATH, trust_remote_code=True, device_map="auto").eval()
> 
> ![55](https://private-user-images.githubusercontent.com/167547961/338989918-b68c2067-e27f-40b9-9349-7ab83f4d18c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NjY1MzYsIm5iZiI6MTcxODk2NjIzNiwicGF0aCI6Ii8xNjc1NDc5NjEvMzM4OTg5OTE4LWI2OGMyMDY3LWUyN2YtNDBiOS05MzQ5LTdhYjgzZjRkMThjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQxMDM3MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjA0MzNmYTEzZDdiNTVmM2VjZjIzMmE3YmY0NTE2MjZkZTM1MzNkZTFjZGY2NGU4N2I1NTJhN2EzZjE1M2Y1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JtyO93XxdGy43fBO7JIgkh_J-Xivy2zWp84EX8ci0cs)
> 
> ![66](https://private-user-images.githubusercontent.com/167547961/338989982-c2cb518a-59c7-40b9-9875-ccb54752f343.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NjY1MzYsIm5iZiI6MTcxODk2NjIzNiwicGF0aCI6Ii8xNjc1NDc5NjEvMzM4OTg5OTgyLWMyY2I1MThhLTU5YzctNDBiOS05ODc1LWNjYjU0NzUyZjM0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQxMDM3MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDZlNjQ3NmEwNzIwNjI5MzYwY2JhMmY2NmQwMTIwYzNkZjc2OWYxZmY1YTMyNTJlNjE4MDI1NzRkYWYxM2I2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E38ltzEO00xSnWbDB0mh1OuOCghMaXvQ5wRVAU77uxU) 添加后提示：NameError: name 'AutoModel' is not defined 没有定义AutoModel 是我错过了什么？还有关于glm-4多GPU的资料哪里有，一直没找到

在composite_demo/src/clients/hf.py里面把那个device_map改成auto
