### ISSUE TITLE
glm4微调报错，conda环境已经安装了flash-attn依赖，错误信息还是让安装flash-attn依赖

### ISSUE THREAD

**Issue by zycovoo** [THUDM/GLM-4#241]
(chatglm4) root@ubuntu:/jcdata/llm/chatglm4/finetune_demo# python finetune.py  data/qingbao/  ../glm-4-9b-chat  configs/lora.yaml
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /jcdata/llm/chatglm4/finetune_demo/finetune.py:381 in main                                       │
│                                                                                                  │
│   378 │   │   ),                                                                                 │
│   379 ):                                                                                         │
│   380 │   ft_config = FinetuningConfig.from_file(config_file)                                    │
│ ❱ 381 │   tokenizer, model = load_tokenizer_and_model(model_dir, peft_config=ft_config.peft_co   │
│   382 │   data_manager = DataManager(data_dir, ft_config.data_config)                            │
│   383 │                                                                                          │
│   384 │   train_dataset = data_manager.get_dataset(                                              │
│                                                                                                  │
│ /jcdata/llm/chatglm4/finetune_demo/finetune.py:328 in load_tokenizer_and_model                   │
│                                                                                                  │
│   325 ):                                                                                         │
│   326 │   tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True)           │
│   327 │   if peft_config is not None:                                                            │
│ ❱ 328 │   │   model = AutoModelForCausalLM.from_pretrained(                                      │
│   329 │   │   │   model_dir,                                                                     │
│   330 │   │   │   trust_remote_code=True,                                                        │
│   331 │   │   │   empty_init=False,                                                              │
│                                                                                                  │
│ /root/miniconda3/envs/chatglm4/lib/python3.10/site-packages/transformers/models/auto/auto_factor │
│ y.py:550 in from_pretrained                                                                      │
│                                                                                                  │
│   547 │   │                                                                                      │
│   548 │   │   if has_remote_code and trust_remote_code:                                          │
│   549 │   │   │   class_ref = config.auto_map[cls.__name__]                                      │
│ ❱ 550 │   │   │   model_class = get_class_from_dynamic_module(                                   │
│   551 │   │   │   │   class_ref, pretrained_model_name_or_path, code_revision=code_revision, *   │
│   552 │   │   │   )                                                                              │
│   553 │   │   │   _ = hub_kwargs.pop("code_revision", None)                                      │
│                                                                                                  │
│ /root/miniconda3/envs/chatglm4/lib/python3.10/site-packages/transformers/dynamic_module_utils.py │
│ :489 in get_class_from_dynamic_module                                                            │
│                                                                                                  │
│   486 │   if code_revision is None and pretrained_model_name_or_path == repo_id:                 │
│   487 │   │   code_revision = revision                                                           │
│   488 │   # And lastly we get the class inside our newly created module                          │
│ ❱ 489 │   final_module = get_cached_module_file(                                                 │
│   490 │   │   repo_id,                                                                           │
│   491 │   │   module_file + ".py",                                                               │
│   492 │   │   cache_dir=cache_dir,                                                               │
│                                                                                                  │
│ /root/miniconda3/envs/chatglm4/lib/python3.10/site-packages/transformers/dynamic_module_utils.py │
│ :315 in get_cached_module_file                                                                   │
│                                                                                                  │
│   312 │   │   raise                                                                              │
│   313 │                                                                                          │
│   314 │   # Check we have all the requirements in our environment                                │
│ ❱ 315 │   modules_needed = check_imports(resolved_module_file)                                   │
│   316 │                                                                                          │
│   317 │   # Now we move the module inside our cached dynamic modules.                            │
│   318 │   full_submodule = TRANSFORMERS_DYNAMIC_MODULE_NAME + os.path.sep + submodule            │
│                                                                                                  │
│ /root/miniconda3/envs/chatglm4/lib/python3.10/site-packages/transformers/dynamic_module_utils.py │
│ :180 in check_imports                                                                            │
│                                                                                                  │
│   177 │   │   │   missing_packages.append(imp)                                                   │
│   178 │                                                                                          │
│   179 │   if len(missing_packages) > 0:                                                          │
│ ❱ 180 │   │   raise ImportError(                                                                 │
│   181 │   │   │   "This modeling file requires the following packages that were not found in y   │
│   182 │   │   │   f"{', '.join(missing_packages)}. Run `pip install {' '.join(missing_packages   │
│   183 │   │   )                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: This modeling file requires the following packages that were not found in your environment: flash_attn. Run `pip install flash_attn`
![Uploading 截图20240626110305.png…]()

**Comment by zRzRzRzRzRzRzR** [comment]
这个问题已经修复，请更新到最新的hf代码

**Comment by XCF-Mike** [comment]
请问在官方的脚本基础上是如何使用flash-atten的？我看配置文件似乎没有这个选项
