### ISSUE TITLE
想问一下如果想把image tensor resize到224要在哪里改

### ISSUE THREAD

**Issue by marybloodyzz** [THUDM/GLM-4#245]
如题，如果直接tokenizer.image_size = 224会报错：
visual.py", line 46, in forward
    x += self.position_embedding.weight.unsqueeze(0)
RuntimeError: The size of tensor a (257) must match the size of tensor b (6401) at non-singleton dimension 1

请问有其他方法可以resize吗？谢谢！

**Comment by zRzRzRzRzRzRzR** [comment]
这个是固定尺寸，不能resize的，你可以填充到1120，反正都是占用固定的padding
