### ISSUE TITLE
你好，本地启动正常镜像启动报NCCL error

### ISSUE THREAD

**Issue by ciaoyizhen** [THUDM/GLM-4#247]
如题

本地运行open_api_server.py是正常的
打成镜像，镜像用的nvidia/cuda:12.3.0runtime的那个版本
打成镜像后 运行就会报错
单卡的话不会报错 但是显存不够
是多卡的问题吗？

**Comment by zRzRzRzRzRzRzR** [comment]
这打镜像出问题了吧，NCCL这应该是多卡的问题，单卡用不到

**Comment by ciaoyizhen** [comment]
对 因为我们只有16g的v100 所以就两张卡跑了    本地是cuda12.3 pytorch12.3 那个镜像可以运行呀？

**Comment by zRzRzRzRzRzRzR** [comment]
v100大概会出现各种bug，软件依赖没问题，但是我不知道cuda 和nccl能不能兼容，这没办法帮你排除

**Comment by ciaoyizhen** [comment]
好滴 谢谢
