### ISSUE TITLE
lora 微调，eval的时候出现”'NoneType' object has no attribute 'to'“ 

### ISSUE THREAD

**Issue by Text2-m** [THUDM/GLM-4#248]
### System Info / 系統信息

Python 3.10.14
torch 2.3.1
ubutu 22.04

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1、运行fintuing.py  到eval的step

 /home/**/anaconda3/envs/glm-4/lib/python3.10/site-packages/accelerate/utils/operations. │
│ py:158 in send_to_device                                                                         │
│                                                                                                  │
│   155 │   │   if is_torch_tensor(tensor) and tensor.device.type in ["mlu"] and tensor.dtype in   │
│   156 │   │   │   tensor = tensor.cpu()                                                          │
│   157 │   │   try:                                                                               │
│ ❱ 158 │   │   │   return tensor.to(device, non_blocking=non_blocking)                            │
│   159 │   │   except TypeError:  # .to() doesn't accept non_blocking as kwarg                    │
│   160 │   │   │   return tensor.to(device)                                                       │
│   161 │   │   except AssertionError as error:                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: BatchEncoding.to() got an unexpected keyword argument 'non_blocking'

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/**/GLM-4/finetune_demo/finetune.py:413 in main                                    │
│                                                                                                  │
│   410 │   )                                                                                      │
│   411 │                                                                                          │
│   412 │   if auto_resume_from_checkpoint.upper() == "" or auto_resume_from_checkpoint is None:   │
│ ❱ 413 │   │   trainer.train()                                                                    │
│   414 │   else:                                                                                  │
│   415 │   │   output_dir = ft_config.training_args.output_dir                                    │
│   416 │   │   dirlist = os.listdir(output_dir)                                                   │
│                                                                                                  │
│ /home/**/anaconda3/envs/glm-4/lib/python3.10/site-packages/transformers/trainer.py:1885 │
│ in train                                                                                         │
│                                                                                                  │
│   1882 │   │   │   finally:                                                                      │
│   1883 │   │   │   │   hf_hub_utils.enable_progress_bars()                                       │
│   1884 │   │   else:                                                                             │
│ ❱ 1885 │   │   │   return inner_training_loop(                                                   │
│   1886 │   │   │   │   args=args,                                                                │
│   1887 │   │   │   │   resume_from_checkpoint=resume_from_checkpoint,                            │
│   1888 │   │   │   │   trial=trial,                                                              │
│                                                                                                  │
│ /home/**/anaconda3/envs/glm-4/lib/python3.10/site-packages/transformers/trainer.py:2291 │
│ in _inner_training_loop                                                                          │
│                                                                                                  │
│   2288 │   │   │   │   │   self.state.epoch = epoch + (step + 1 + steps_skipped) / steps_in_epo  │
│   2289 │   │   │   │   │   self.control = self.callback_handler.on_step_end(args, self.state, s  │
│   2290 │   │   │   │   │                                                                         │
│ ❱ 2291 │   │   │   │   │   self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoc  │
│   2292 │   │   │   │   else:                                                                     │
│   2293 │   │   │   │   │   self.control = self.callback_handler.on_substep_end(args, self.state  │
│   2294                                                                                           │
│                                                                                                  │
│ /home/**/anaconda3/envs/glm-4/lib/python3.10/site-packages/transformers/trainer.py:2721 │
│ in _maybe_log_save_evaluate                                                                      │
│                                                                                                  │
│   2718 │   │                                                                                     │
│   2719 │   │   metrics = None                                                                    │
│   2720 │   │   if self.control.should_evaluate:                                                  │
│ ❱ 2721 │   │   │   metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)                     │
│   2722 │   │   │   self._report_to_hp_search(trial, self.state.global_step, metrics)             │
│   2723 │   │   │                                                                                 │
│   2724 │   │   │   # Run delayed LR scheduler now that metrics are populated                     │
│                                                                                                  │
│ /home/**/anaconda3/envs/glm-4/lib/python3.10/site-packages/transformers/trainer_seq2seq │
│ .py:180 in evaluate                                                                              │
│                                                                                                  │
│   177 │   │   # We don't want to drop samples in general                                         │
│   178 │   │   self.gather_function = self.accelerator.gather                                     │
│   179 │   │   self._gen_kwargs = gen_kwargs                                                      │
│ ❱ 180 │   │   return super().evaluate(eval_dataset, ignore_keys=ignore_keys, metric_key_prefix   │
│   181 │                                                                                          │
│   182 │   def predict(                                                                           │
│   183 │   │   self,                                                                              │
│                                                                                                  │
│ /home/**/anaconda3/envs/glm-4/lib/python3.10/site-packages/transformers/trainer.py:3572 │
│ in evaluate                                                                                      │
│                                                                                                  │
│   3569 │   │   start_time = time.time()                                                          │
│   3570 │   │                                                                                     │
│   3571 │   │   eval_loop = self.prediction_loop if self.args.use_legacy_prediction_loop else se  │
│ ❱ 3572 │   │   output = eval_loop(                                                               │
│   3573 │   │   │   eval_dataloader,                                                              │
│   3574 │   │   │   description="Evaluation",                                                     │
│   3575 │   │   │   # No point gathering the predictions if there are no metrics, otherwise we d  │
│                                                                                                  │
│ /home/**/anaconda3/envs/glm-4/lib/python3.10/site-packages/transformers/trainer.py:3747 │
│ in evaluation_loop                                                                               │
│                                                                                                  │
│   3744 │   │   observed_num_examples = 0                                                         │
│   3745 │   │                                                                                     │
│   3746 │   │   # Main evaluation loop                                                            │
│ ❱ 3747 │   │   for step, inputs in enumerate(dataloader):                                        │
│   3748 │   │   │   # Update the observed num examples                                            │
│   3749 │   │   │   observed_batch_size = find_batch_size(inputs)                                 │
│   3750 │   │   │   if observed_batch_size is not None:                                           │
│                                                                                                  │
│ /home/**/anaconda3/envs/glm-4/lib/python3.10/site-packages/accelerate/data_loader.py:46 │
│ 3 in __iter__                                                                                    │
│                                                                                                  │
│    460 │   │   │   try:                                                                          │
│    461 │   │   │   │   # But we still move it to the device so it is done before `StopIteration  │
│    462 │   │   │   │   if self.device is not None:                                               │
│ ❱  463 │   │   │   │   │   current_batch = send_to_device(current_batch, self.device, non_block  │
│    464 │   │   │   │   next_batch = next(dataloader_iter)                                        │
│    465 │   │   │   │   if batch_index >= self.skip_batches:                                      │
│    466 │   │   │   │   │   yield current_batch                                                   │
│                                                                                                  │
│ /home/**/anaconda3/envs/glm-4/lib/python3.10/site-packages/accelerate/utils/operations. │
│ py:160 in send_to_device                                                                         │
│                                                                                                  │
│   157 │   │   try:                                                                               │
│   158 │   │   │   return tensor.to(device, non_blocking=non_blocking)                            │
│   159 │   │   except TypeError:  # .to() doesn't accept non_blocking as kwarg                    │
│ ❱ 160 │   │   │   return tensor.to(device)                                                       │
│   161 │   │   except AssertionError as error:                                                    │
│   162 │   │   │   # `torch.Tensor.to(<int num>)` is not supported by `torch_npu` (see this [is   │
│   163 │   │   │   # This call is inside the try-block since is_npu_available is not supported    │
│                                                                                                  │
│ /home/**/anaconda3/envs/glm-4/lib/python3.10/site-packages/transformers/tokenization_ut │
│ ils_base.py:802 in to                                                                            │
│                                                                                                  │
│    799 │   │   if isinstance(device, str) or is_torch_device(device) or isinstance(device, int)  │
│    800 │   │   │   for k, v in self.data.items():                                                │
│    801 │   │   │   │   print(k,v)                                                                │
│ ❱  802 │   │   │   self.data = {k: v.to(device=device) for k, v in self.data.items()}            │
│    803 │   │   else:                                                                             │
│    804 │   │   │   logger.warning(f"Attempting to cast a BatchEncoding to type {str(device)}. T  │
│    805 │   │   return self                                                                       │
│                                                                                                  │
│ /home/**/anaconda3/envs/glm-4/lib/python3.10/site-packages/transformers/tokenization_ut │
│ ils_base.py:802 in <dictcomp>                                                                    │
│                                                                                                  │
│    799 │   │   if isinstance(device, str) or is_torch_device(device) or isinstance(device, int)  │
│    800 │   │   │   for k, v in self.data.items():                                                │
│    801 │   │   │   │   print(k,v)                                                                │
│ ❱  802 │   │   │   self.data = {k: v.to(device=device) for k, v in self.data.items()}            │
│    803 │   │   else:                                                                             │
│    804 │   │   │   logger.warning(f"Attempting to cast a BatchEncoding to type {str(device)}. T  │
│    805 │   │   return self                                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'to'

2、输出eval数据
input_ids tensor([[151329, 151329, 151329, 151329, 151329, 151329, 151329, 151329, 151331,
         151333, 151336,    198, 103408,  99668,  11314, 151337],
        [151329, 151329, 151329, 151329, 151331, 151333, 151336,    198,  99756,
          98366,  98541,    227,  99033,  99296,   1773, 151337],
        [151331, 151333, 151336,    198, 100173,      2, 118135,      9, 104756,
              2, 119527,      9, 100988,      2, 116789, 151337],
        [151331, 151333, 151336,    198, 100173,      2, 118135,      9, 104756,
              2, 119527,      9, 100988,      2, 102786, 151337]])
output_ids tensor([[   198, 101328,  98541,    227,  99033,  99296, 121245,  99941, 113255,
           1773, 151329, 151329, 151329, 151329, 151329, 151329, 151329, 151329,
         151329, 151329, 151329, 151329, 151329, 151329, 151329, 151329, 151329,
         151329, 151329],
        [   198,  99334,  98541,    227,  99033, 102595,   3837, 106281, 115937,
             17,  98334,   3837, 100469, 103843,   3837, 106127,  98333, 101013,
          99296, 101201, 117507, 106518, 100554, 103655,   1773, 151329, 151329,
         151329, 151329],
        [   198,  99257,  98994, 116020, 122827, 108196,  99994, 100036,   3837,
         102274, 115011,   3837,  99486, 100512, 118089, 103787,   3837, 113772,
         102120, 101523, 103512,   3837, 108309,  98974, 100490, 116789, 105116,
           1773, 151329],
        [   198, 107386, 119527, 118135, 102195,  98396, 101761,   3837, 112203,
          99890,  98755, 111398, 113710, 124037, 100532, 103661, 116945, 102786,
         102323,   1773, 151329, 151329, 151329, 151329, 151329, 151329, 151329,
         151329, 151329]])
attention_mask tensor([[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
position_ids tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  4,  5,  6,  7],
        [ 0,  0,  0,  0,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])
labels None

### Expected behavior / 期待表现

是不是process_batch_eval的问题

**Comment by zRzRzRzRzRzRzR** [comment]
用transformers 4.40.2

**Comment by Text2-m** [comment]
> 用transformers 4.40.2

牛逼

**Comment by westlongtime** [comment]
更新transfomers库解决了 too many values to unpack， 但是又报出AttributeError: 'NoneType' object has no attribute 'to'

**Comment by zRzRzRzRzRzRzR** [comment]
我们check一下

**Comment by LeoWood** [comment]
> 我们check一下

请问有结论了吗？我这里更新了最新的代码transformers==4.42.4，也遇到同样的问题

**Comment by zRzRzRzRzRzRzR** [comment]
transformers 有bug，修改
https://zhipu-ai.feishu.cn/wiki/RuMswanpkiRh3Ok4z5acOABBnjf

**Comment by lian-xiao** [comment]
您好，我也遇到了相同的问题！但是我在技术文档中并没有找到修改的方法，请问可以指明修改方法位置或者如何修改嘛？谢谢！

**Comment by LeoWood** [comment]
您的邮件已收到，我将尽快回复，谢谢。刘欢
