### ISSUE TITLE
Maybe wrong in the code?

### ISSUE THREAD

**Issue by Gary-code** [THUDM/GLM-4#251]
### System Info / 系統信息

4090

### Who can help? / 谁可以帮助到您？

x

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

[`new_input_ids = tokenizer.apply_chat_template([message], tokenize=True, return_dict=False)[2:]`](https://github.com/THUDM/GLM-4/blob/6ae0f088acbff00139b0f24ad08008d08dd53f02/finetune_demo/finetune.py#L264) should be `new_input_ids = tokenizer.apply_chat_template([message], tokenize=True, return_dict=False)[0][2:]`?

### Expected behavior / 期待表现

[`new_input_ids = tokenizer.apply_chat_template([message], tokenize=True, return_dict=False)[2:]`](https://github.com/THUDM/GLM-4/blob/6ae0f088acbff00139b0f24ad08008d08dd53f02/finetune_demo/finetune.py#L264) should be `new_input_ids = tokenizer.apply_chat_template([message], tokenize=True, return_dict=False)[0][2:]`?

**Comment by zRzRzRzRzRzRzR** [comment]
Pull the latest hf file, chat_template has been placed in jinjia
