### ISSUE TITLE
怎么在openai_api_server增加lora和glm-4-9b-chat一起启动

### ISSUE THREAD

**Issue by WIIIIIf** [THUDM/GLM-4#252]
### Feature request  / 功能建议

在openai_api_server增加lora和glm-4-9b-chat一起启动

### Motivation / 动机

在openai_api_server增加lora和glm-4-9b-chat一起启动

### Your contribution / 您的贡献

 在openai_api_server增加lora和glm-4-9b-chat一起启动

**Comment by WIIIIIf** [comment]
@zRzRzRzRzRzRzR

**Comment by zRzRzRzRzRzRzR** [comment]
合并lora的问题请参考vLLM的源代码和文档，我们没有附在demo中

**Comment by znxd-wh** [comment]
我也一样遇到了openai_api_server调用lora微调结果的问题，看readme看不明白，具体的openai_api_server.py中模型读入方式怎么替换成inference.py的模型读入方式呢？
