### ISSUE TITLE
请问能提供一下你们调整过的IFEval的中文版本用于评估比较吗？

### ISSUE THREAD

**Issue by donggoing** [THUDM/GLM-4#253]

**Comment by donggoing** [comment]
![image](https://github.com/THUDM/GLM-4/assets/29890210/cab54701-ce4d-4878-8784-5cdaf6cd72bc)

**Comment by zRzRzRzRzRzRzR** [comment]
感谢您的提问，经过咨询相应工作人员，这部分内容暂时不能公开，感谢您的理解

**Comment by jackwwy** [comment]
> 感谢您的提问，经过咨询相应工作人员，这部分内容暂时不能公开，感谢您的理解

你好，请问什么时候可以公开
