### ISSUE TITLE
使用vllm_cli_demo.py推理会报错

### ISSUE THREAD

**Issue by huangmengasd** [THUDM/GLM-4#255]
### System Info / 系統信息

cuda12

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [x] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

经过lora微调后，使用llamafactory合并了模型，在llamafactory上使用合并后的模型没问题。使用vllm_cli_demo.py可以加载模型，但是输入input后，就会报以下错误
![1e864f4a-9782-4079-be1d-282bdbf2f19e](https://github.com/THUDM/GLM-4/assets/29702229/a17db49e-d86d-4011-b043-994a94a68ab2)
使用的训练集是这样的
![2e1700df-c392-47a8-ad8b-61d481508795](https://github.com/THUDM/GLM-4/assets/29702229/62e8f200-85e7-4ca9-afc1-4da1a447e4ff)
请问这是什么问题呢？

### Expected behavior / 期待表现

能够正常对话

**Comment by zRzRzRzRzRzRzR** [comment]
emm，这问题或许要测微调的框架吧，关于怎么合并微调模型的问题，可以看vLLM文档，这个问题目前没办法测
