### ISSUE TITLE
多模态版本遇到 `model_kwargs` are not used by the model: ['images']

### ISSUE THREAD

**Issue by ouungj** [THUDM/GLM-4#256]
### System Info / 系統信息

cuda: 12.3 python 3.10

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

inputs = tokenizer.apply_chat_template([{"role": "user", "image": image, "content": query}],
                                       add_generation_prompt=True, tokenize=True, return_tensors="pt",
                                       return_dict=True)  # chat mode

inputs = inputs.to(device)
model = AutoModelForCausalLM.from_pretrained(
    "/path/to/glm-4v-9b",
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True
).to(device).eval()

报错：
python3.10/dist-packages/transformers/generation/utils.py", line 1130, in _validate_model_kwargs
    raise ValueError(
ValueError: The following `model_kwargs` are not used by the model: ['images'] (note: typos in the generate arguments will also show up in this list)

把inputs里面的key，"image"改成“images”则返回说看不到图，不报这个错误了。

### Expected behavior / 期待表现

不再报错，成功跑通。

**Comment by zRzRzRzRzRzRzR** [comment]
为什么会有model_kwargs 传入images这个参数呢，应该是放在tokenize的过程中呀，transformers 4.40.2

**Comment by ouungj** [comment]
> 为什么会有model_kwargs 传入images这个参数呢，应该是放在tokenize的过程中呀，transformers 4.40.2

全代码是这样的，还请帮忙看看：
device = "cuda"

tokenizer = AutoTokenizer.from_pretrained("/path/to/glm-4v-9b", trust_remote_code=True)

query = '描述这张图片'
image = Image.open("assets/airplane.jpeg").convert('RGB')
inputs = tokenizer.apply_chat_template([{"role": "user", "image": image, "content": query}],
                                       add_generation_prompt=True, tokenize=True, return_tensors="pt",
                                       return_dict=True)  # chat mode

print(inputs)
inputs = inputs.to(device)
model = AutoModelForCausalLM.from_pretrained(
    "/path/to/glm-4v-9b",
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True
).to(device).eval()

gen_kwargs = {"max_length": 2500, "do_sample": True, "top_k": 1}
with torch.no_grad():
    outputs = model.generate(**inputs, **gen_kwargs)
    outputs = outputs[:, inputs['input_ids'].shape[1]:]
    print(tokenizer.decode(outputs[0]))

**Comment by ouungj** [comment]
> > 为什么会有model_kwargs 传入images这个参数呢，应该是放在tokenize的过程中呀，transformers 4.40.2
> 
> 已经从transformers 4.40.0改到4.40.2测过了，还是这个情况。 全代码是这样的，还请帮忙看看： device = "cuda"
> 
> tokenizer = AutoTokenizer.from_pretrained("/path/to/glm-4v-9b", trust_remote_code=True)
> 
> query = '描述这张图片' image = Image.open("assets/airplane.jpeg").convert('RGB') inputs = tokenizer.apply_chat_template([{"role": "user", "image": image, "content": query}], add_generation_prompt=True, tokenize=True, return_tensors="pt", return_dict=True) # chat mode
> 
> print(inputs) inputs = inputs.to(device) model = AutoModelForCausalLM.from_pretrained( "/path/to/glm-4v-9b", torch_dtype=torch.bfloat16, low_cpu_mem_usage=True, trust_remote_code=True ).to(device).eval()
> 
> gen_kwargs = {"max_length": 2500, "do_sample": True, "top_k": 1} with torch.no_grad(): outputs = model.generate(**inputs, **gen_kwargs) outputs = outputs[:, inputs['input_ids'].shape[1]:] print(tokenizer.decode(outputs[0]))

我还打印了inputs:
'input_ids': tensor([...]]), 'attention_mask': tensor([[...]]), 'position_ids': tensor([[ ...]]), 'images': tensor([[[[...]]])}

**Comment by zRzRzRzRzRzRzR** [comment]
我懂你的意思了
<img width="994" alt="image" src="https://github.com/THUDM/GLM-4/assets/93239683/419d408d-c6e1-4733-b076-2bba3ea06350">
这个代码或许能解决的你的问题，因为input 和mesasge中的image不一样，message用的是image，input中就是images，你尝试按照截图的这个代码去运行
