### ISSUE TITLE
GLM-4-9B的lora微调需要多少显存？

### ISSUE THREAD

**Issue by Aimwo** [THUDM/GLM-4#262]
### Feature request  / 功能建议

![1719653120514](https://github.com/THUDM/GLM-4/assets/85429888/14e026a1-abf8-4c70-94c9-0e6e9909e9f3)
这里第一行说的显存占用指的是，微调是所需的显存吗

### Motivation / 动机

对readme文件不理解

### Your contribution / 您的贡献

对readme文件不理解

**Comment by zRzRzRzRzRzRzR** [comment]
21G
