### ISSUE TITLE
GLM4v微调代码支持

### ISSUE THREAD

**Issue by XuRui314** [THUDM/GLM-4#264]
根据CogVLM2的微调代码，我实现了GLM4v的微调：
https://github.com/XuRui314/GLM4v-Finetune

经过测试我的这份代码是有效的，loss和test metric都较为合理，而同样参数设置下使用 swift框架的微调结果会不是很好，比如loss降不下去等问题。

**Comment by zRzRzRzRzRzRzR** [comment]
需要修改modeling_chatglm的主要原因是什么呢

**Comment by XuRui314** [comment]
修改的原因是原本的模型文件中forward没有对于attention_mask、labels的处理，包括填充image_token_num的-100，当然这个应该也可以放在预处理数据的时候实现，但是为了整体风格统一我就弄到模型文件里了

**Comment by zRzRzRzRzRzRzR** [comment]
我重新写了一个微调脚本，并使用了你的modeling_chatglm，欢迎通过我的github邮箱让我与你取得联系，代码可能会更新到hf

**Comment by wstsr333** [comment]
请问可以只用文本数据集微调吗，要如何设置

**Comment by zRzRzRzRzRzRzR** [comment]
已更新GLM-4V微调代码
