### ISSUE TITLE
请问多模态glm-4v-9b可以只用文本数据集lora微调吗，因为想改变他的自我认知，如果只能通过带images路径的数据集微调自我认知，要注意些什么

### ISSUE THREAD

**Issue by wstsr333** [THUDM/GLM-4#265]
### Feature request  / 功能建议

请问多模态glm-4v-9b可以只用文本数据集lora微调吗，因为想改变他的自我认知，如果只能通过带images路径的数据集微调自我认知，要注意些什么，有推荐的微调工具吗

### Motivation / 动机

想改变glm-4v-9b多模态模型的自我认知

### Your contribution / 您的贡献

想改变glm-4v-9b多模态模型的自我认知

**Comment by zRzRzRzRzRzRzR** [comment]
可以只有文本的微调，那你只要修改一下现在的finetune的代码就行了，效果估计不能很好，还是建议针对任务进行微调

**Comment by wstsr333** [comment]
请问针对任务进行微调步骤是怎样的，了解的不多，可以稍微解释下吗

**Comment by zRzRzRzRzRzRzR** [comment]
比如VQA这种，这个模型本身是VQA模型，chat能力肯定没有glm-4-9b-chat强，比如你想做视觉分类分类和专业描述，可以用微调

**Comment by wstsr333** [comment]
微调的数据集可以不带image字段吗

**Comment by wstsr333** [comment]
我看了finetune.py,在里面没找到修改数据集格式的代码，请问在哪段代码中

**Comment by zRzRzRzRzRzRzR** [comment]
不带imge直接用finetune 的readme就行了，没有代码，自己制作数据集，自己转换

**Comment by xuyongbin** [comment]
怎么控制image 不参与特征计算
