### ISSUE TITLE
多gpu推理用不了

### ISSUE THREAD

**Issue by chuan-mt** [THUDM/GLM-4#270]
### System Info / 系統信息

my set：
#2、加载vllm模型
from transformers import AutoTokenizer
from vllm import LLM, SamplingParams
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "5,4"
print("CUDA_VISIBLE_DEVICES set to:", os.environ["CUDA_VISIBLE_DEVICES"])

# GLM-4-9B-Chat-1M
# max_model_len, tp_size = 1048576, 4
# 如果遇见 OOM 现象，建议减少max_model_len，或者增加tp_size
max_model_len, tp_size = 131072, 2
model_name = "/nfs2/zhaochuan.cai/czc_data/glm-4-9b-chat"
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
llm = LLM(
    model=model_name,
    tensor_parallel_size=tp_size,
    max_model_len=max_model_len,
    trust_remote_code=True,
    enforce_eager=True,
    gpu_memory_utilization=0.8,
    # GLM-4-9B-Chat-1M 如果遇见 OOM 现象，建议开启下述参数
    # enable_chunked_prefill=True,
    # max_num_batched_tokens=8192
)

bug out：
   raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
ERROR 07-01 01:42:04 multiproc_worker_utils.py:120] Worker VllmWorkerProcess pid 670024 died, exit code: 1
INFO 07-01 01:42:04 multiproc_worker_utils.py:123] Killing local vLLM worker processes
(raylet) [2024-07-01 01:42:04,389 E 667258 667287] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2024-07-01_01-41-52_492789_667000 is over 95% full, available space: 285352415232; capacity: 11424507985920. Object creation will fail if spilling is required.

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

my set：
#2、加载vllm模型
from transformers import AutoTokenizer
from vllm import LLM, SamplingParams
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "5,4"
print("CUDA_VISIBLE_DEVICES set to:", os.environ["CUDA_VISIBLE_DEVICES"])

# GLM-4-9B-Chat-1M
# max_model_len, tp_size = 1048576, 4
# 如果遇见 OOM 现象，建议减少max_model_len，或者增加tp_size
max_model_len, tp_size = 131072, 2
model_name = "/nfs2/zhaochuan.cai/czc_data/glm-4-9b-chat"
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
llm = LLM(
    model=model_name,
    tensor_parallel_size=tp_size,
    max_model_len=max_model_len,
    trust_remote_code=True,
    enforce_eager=True,
    gpu_memory_utilization=0.8,
    # GLM-4-9B-Chat-1M 如果遇见 OOM 现象，建议开启下述参数
    # enable_chunked_prefill=True,
    # max_num_batched_tokens=8192
)

bug out：
   raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
ERROR 07-01 01:42:04 multiproc_worker_utils.py:120] Worker VllmWorkerProcess pid 670024 died, exit code: 1
INFO 07-01 01:42:04 multiproc_worker_utils.py:123] Killing local vLLM worker processes
(raylet) [2024-07-01 01:42:04,389 E 667258 667287] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2024-07-01_01-41-52_492789_667000 is over 95% full, available space: 285352415232; capacity: 11424507985920. Object creation will fail if spilling is required.

### Expected behavior / 期待表现

my set：
#2、加载vllm模型
from transformers import AutoTokenizer
from vllm import LLM, SamplingParams
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "5,4"
print("CUDA_VISIBLE_DEVICES set to:", os.environ["CUDA_VISIBLE_DEVICES"])

# GLM-4-9B-Chat-1M
# max_model_len, tp_size = 1048576, 4
# 如果遇见 OOM 现象，建议减少max_model_len，或者增加tp_size
max_model_len, tp_size = 131072, 2
model_name = "/nfs2/zhaochuan.cai/czc_data/glm-4-9b-chat"
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
llm = LLM(
    model=model_name,
    tensor_parallel_size=tp_size,
    max_model_len=max_model_len,
    trust_remote_code=True,
    enforce_eager=True,
    gpu_memory_utilization=0.8,
    # GLM-4-9B-Chat-1M 如果遇见 OOM 现象，建议开启下述参数
    # enable_chunked_prefill=True,
    # max_num_batched_tokens=8192
)

bug out：
   raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
ERROR 07-01 01:42:04 multiproc_worker_utils.py:120] Worker VllmWorkerProcess pid 670024 died, exit code: 1
INFO 07-01 01:42:04 multiproc_worker_utils.py:123] Killing local vLLM worker processes
(raylet) [2024-07-01 01:42:04,389 E 667258 667287] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2024-07-01_01-41-52_492789_667000 is over 95% full, available space: 285352415232; capacity: 11424507985920. Object creation will fail if spilling is required.

**Comment by zRzRzRzRzRzRzR** [comment]
参数要改，修改启动参数就行了，跟vLLM原始的功能一样的，不是你设定几个GPU就默认几个的，代码中也要改
tensor_parallel_size=1,
