### ISSUE TITLE
关于demo中的api_serrver接口服务，两个客户端同时调用接口，结果会出现&&&&&&的情况，这种问题怎么解决？

### ISSUE THREAD

**Issue by s861092982** [THUDM/GLM-4#273]
### System Info / 系統信息

4090 24G显卡
int4量化

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [x] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

同时调用接口必复现

### Expected behavior / 期待表现

支持多线程

**Comment by zRzRzRzRzRzRzR** [comment]
emm，如果同时调用估计会在判定fc的时候出现问题吧，这个代码没有考虑并行。而且int4的模型不稳定
