### ISSUE TITLE
Map时总会报错或超时

### ISSUE THREAD

**Issue by WEIC-7** [THUDM/GLM-4#277]
<h2> 在 6 * A800 80GB 上微调 GLM-4V，数据用量7500+ 例单轮VQA</h2>
   <h2>在Map时报错如下：</h2>
   
   
    Map (num_proc=6):   0%|                                                                                                  | 0/7593 [01:30<?, ? examples/s]
    
    [rank2]: ╭─────────────────────────────── Traceback (most recent call last) 
    
    .....................
    [rank5]: ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
    [rank5]: │ /alldata/shared/VLM_project/GLM-4/finetune_demo/finetune_vision.py:458 in main                   │
    [rank5]: │                                                                                                  │
    [rank5]: │   455 │   print(Split.TRAIN)                                                                     │
    [rank5]: │   456 │   print(process_batch)                                                                   │
    [rank5]: │   457 │                                                                                          │
    [rank5]: │ ❱ 458 │   train_dataset = data_manager.get_dataset(                                              │
    [rank5]: │   459 │   │   Split.TRAIN,                                                                       │
    [rank5]: │   460 │   │   functools.partial(                                                                 │
    [rank5]: │   461 │   │   │   process_batch,                                                                 │
    [rank5]: │                                                                                                  │
    [rank5]: │ /alldata/shared/VLM_project/GLM-4/finetune_demo/finetune_vision.py:241 in get_dataset            │
    [rank5]: │                                                                                                  │
    [rank5]: │   238 │   │   else:                                                                              │
    [rank5]: │   239 │   │   │   remove_columns = None                                                          │
    [rank5]: │   240 │   │                                                                                      │
    [rank5]: │ ❱ 241 │   │   return orig_dataset.map(                                                           │
    [rank5]: │   242 │   │   │   process_fn,                                                                    │
    [rank5]: │   243 │   │   │   batched=batched,                                                               │
    [rank5]: │   244 │   │   │   remove_columns=remove_columns,                                                 │
    [rank5]: │                                                                                                  │
    [rank5]: │ /home/WCzhou/workspace/anaconda/envs/GLM/lib/python3.10/site-packages/datasets/arrow_dataset.py: │
    [rank5]: │ 602 in wrapper                                                                                   │
    [rank5]: │                                                                                                  │
    [rank5]: │    599 │   │   else:                                                                             │
    [rank5]: │    600 │   │   │   self: "Dataset" = kwargs.pop("self")                                          │
    [rank5]: │    601 │   │   # apply actual function                                                           │
    [rank5]: │ ❱  602 │   │   out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)                │
    [rank5]: │    603 │   │   datasets: List["Dataset"] = list(out.values()) if isinstance(out, dict) else [ou  │
    [rank5]: │    604 │   │   for dataset in datasets:                                                          │
    [rank5]: │    605 │   │   │   # Remove task templates if a column mapping of the template is no longer val  │
    [rank5]: │                                                                                                  │
    [rank5]: │ /home/WCzhou/workspace/anaconda/envs/GLM/lib/python3.10/site-packages/datasets/arrow_dataset.py: │
    [rank5]: │ 567 in wrapper                                                                                   │
    [rank5]: │                                                                                                  │
    [rank5]: │    564 │   │   │   "output_all_columns": self._output_all_columns,                               │
    [rank5]: │    565 │   │   }                                                                                 │
    [rank5]: │    566 │   │   # apply actual function                                                           │
    [rank5]: │ ❱  567 │   │   out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)                │
    [rank5]: │    568 │   │   datasets: List["Dataset"] = list(out.values()) if isinstance(out, dict) else [ou  │
    [rank5]: │    569 │   │   # re-apply format to the output                                                   │
    [rank5]: │    570 │   │   for dataset in datasets:                                                          │
    [rank5]: │                                                                                                  │
    [rank5]: │ /home/WCzhou/workspace/anaconda/envs/GLM/lib/python3.10/site-packages/datasets/arrow_dataset.py: │
    [rank5]: │ 3253 in map                                                                                      │
    [rank5]: │                                                                                                  │
    [rank5]: │   3250 │   │   │   │   │   │   total=pbar_total,                                                 │
    [rank5]: │   3251 │   │   │   │   │   │   desc=(desc or "Map") + f" (num_proc={num_proc})",                 │
    [rank5]: │   3252 │   │   │   │   │   ) as pbar:                                                            │
    [rank5]: │ ❱ 3253 │   │   │   │   │   │   for rank, done, content in iflatmap_unordered(                    │
    [rank5]: │   3254 │   │   │   │   │   │   │   pool, Dataset._map_single, kwargs_iterable=kwargs_per_job     │
    [rank5]: │   3255 │   │   │   │   │   │   ):                                                                │
    [rank5]: │   3256 │   │   │   │   │   │   │   if done:                                                      │
    [rank5]: │                                                                                                  │
    [rank5]: │ /home/WCzhou/workspace/anaconda/envs/GLM/lib/python3.10/site-packages/datasets/utils/py_utils.py │
    [rank5]: │ :711 in iflatmap_unordered                                                                       │
    [rank5]: │                                                                                                  │
    [rank5]: │   708 │   │   │   │   if _get_pool_pid(pool) != initial_pool_pid:                                │
    [rank5]: │   709 │   │   │   │   │   pool_changed = True                                                    │
    [rank5]: │   710 │   │   │   │   │   # One of the subprocesses has died. We should not wait forever.        │
    [rank5]: │ ❱ 711 │   │   │   │   │   raise RuntimeError(                                                    │
    [rank5]: │   712 │   │   │   │   │   │   "One of the subprocesses has abruptly died during map operation.   │
    [rank5]: │   713 │   │   │   │   │   │   "To debug the error, disable multiprocessing."                     │
    [rank5]: │   714 │   │   │   │   │   )                                                                      │
    [rank5]: ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
    [rank5]: RuntimeError: One of the subprocesses has abruptly died during map operation.To debug the error, disable multiprocessing.
    W0702 17:07:27.441000 139890717414016 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 3021360 closing signal SIGTERM
    W0702 17:07:27.471000 139890717414016 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 3021361 closing signal SIGTERM
    W0702 17:07:27.472000 139890717414016 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 3021363 closing signal SIGTERM
    W0702 17:07:27.473000 139890717414016 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 3021364 closing signal SIGTERM
    W0702 17:07:27.474000 139890717414016 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 3021365 closing signal SIGTERM
    E0702 17:07:28.341000 139890717414016 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 2 (pid: 3021362) of binary: /home/WCzhou/workspace/anaconda/envs/GLM/bin/python
    Traceback (most recent call last):
      File "/home/WCzhou/workspace/anaconda/envs/GLM/bin/torchrun", line 8, in <module>
        sys.exit(main())
      File "/home/WCzhou/workspace/anaconda/envs/GLM/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
        return f(*args, **kwargs)
      File "/home/WCzhou/workspace/anaconda/envs/GLM/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
        run(args)
      File "/home/WCzhou/workspace/anaconda/envs/GLM/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
        elastic_launch(
      File "/home/WCzhou/workspace/anaconda/envs/GLM/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
        return launch_agent(self._config, self._entrypoint, list(args))
      File "/home/WCzhou/workspace/anaconda/envs/GLM/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
        raise ChildFailedError(
    torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
    ============================================================
    /alldata/shared/VLM_project/GLM-4/finetune_demo/finetune_vision.py FAILED
    ------------------------------------------------------------
    Failures:
      <NO_OTHER_FAILURES>
    ------------------------------------------------------------
    Root Cause (first observed failure):
    [0]:
      time      : 2024-07-02_17:07:27
      host      : comp
      rank      : 2 (local_rank: 2)
      exitcode  : 1 (pid: 3021362)
      error_file: <N/A>
      traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by zhouzhoumd** [comment]
同样的问题

**Comment by zRzRzRzRzRzRzR** [comment]
所以这个是什么报错我咋没看懂，我自己的jsonl是200是可以

**Comment by zhouzhoumd** [comment]
我是1.8w的jsonl，同样的报错，看监控感觉像是内存爆掉了

**Comment by zRzRzRzRzRzRzR** [comment]
内存没测过，但是可能要比显存还多？

**Comment by zhouzhoumd** [comment]
500G的内存，超过200条数据就报错

**Comment by WEIC-7** [comment]
<h2>我也尝试了一下减少数据到1000左右，但是在Map发现内存占用逐渐增高，最后报错</h2>

![image](https://github.com/THUDM/GLM-4/assets/128592414/62ff5e4d-93c2-453a-b7dc-6ea81752e248)
![image](https://github.com/THUDM/GLM-4/assets/128592414/9194aba0-332b-46a9-b361-f9aa74fa0445)
![image](https://github.com/THUDM/GLM-4/assets/128592414/05958104-57ee-46a6-993a-94b7559e7b61)
![image](https://github.com/THUDM/GLM-4/assets/128592414/eb844fae-9e9a-49e8-ac9b-61700a8cc4b6)
![image](https://github.com/THUDM/GLM-4/assets/128592414/c42e5922-9126-46ac-bcb6-86ab58d04978)
![image](https://github.com/THUDM/GLM-4/assets/128592414/6f7923d1-457f-4e4d-973d-e474495f374d)
![image](https://github.com/THUDM/GLM-4/assets/128592414/eecb7e81-ef9e-4407-a0e4-467a91a6c9a5)
![image](https://github.com/THUDM/GLM-4/assets/128592414/04da56b2-1f44-4a49-ace8-cc7f5ba89ea0)

<h2>报错如下</h2>

![image](https://github.com/THUDM/GLM-4/assets/128592414/0dfcf43c-edd0-477b-80d0-901f852076a8)
![image](https://github.com/THUDM/GLM-4/assets/128592414/0b1ffc38-4dbc-4f3e-9bc4-a33a28e8f26f)

**Comment by zhouzhoumd** [comment]
orig_dataset.map()里面batch_size默认1000，改小点可以 return orig_dataset.map(
            process_fn,
            batched=batched,
            remove_columns=remove_columns,
            num_proc=self._num_proc,
            batch_size = 100,
        )
