### ISSUE TITLE
建议给个requiremens.txt

### ISSUE THREAD

**Issue by robator0127** [THUDM/GLM-4#278]
### Feature request  / 功能建议

建议给个requiremens.txt，指定相关包的版本

### Motivation / 动机

建议给个requiremens.txt，指定相关包的版本

### Your contribution / 您的贡献

无

**Comment by WEIC-7** [comment]
[GLM-4](https://github.com/THUDM/GLM-4/tree/main)/[finetune_demo](https://github.com/THUDM/GLM-4/tree/main/finetune_demo)
/requirements.txt

[GLM-4](https://github.com/THUDM/GLM-4/tree/main)/[basic_demo](https://github.com/THUDM/GLM-4/tree/main/basic_demo)
/requirements.txt

**Comment by robator0127** [comment]
收到，谢谢
