### ISSUE TITLE
CUDA running out of memory for a very small dataset (7 sample training data)

### ISSUE THREAD

**Issue by theharshithh** [THUDM/GLM-4#281]
hello.

i had tried the vision fine-tuning script for `glm-4v-9b` model. The command i had used was `python3 finetune_demo/finetune_vision.py ./data THUDM/glm-4v-9b ./finetune_demo/configs/lora.yaml`

I had tried the fine-tuning for a sample dataset of 7 examples and running out of GPU `(NVIDIA A100-SXM4-80GB * 8)`
The data is configured properly and the model is able to parse the `train.jsonl`, `test.jsonl`, `val.jsonl`.

GPU config: `NVIDIA A100-SXM4-80GB * 8`

**_Errors_**

1. Unable to define the no of epocs
2. Despite having the hardware requirements mentioned [here](https://github.com/THUDM/GLM-4/blob/main/finetune_demo/README_en.md), I am still getting CUDA out of Memory for 7 data samples.

_**The last logs before CUDA err:**_

`
***** Running training *****
  Num examples = 7
  Num Epochs = 375
  Instantaneous batch size per device = 2
  Total train batch size (w. parallel, distributed & accumulation) = 2
  Gradient Accumulation steps = 1
  Total optimization steps = 1,500
  Number of trainable parameters = 3,198,976
  0%`

## **_Steps to recreate the error:_**

1. The dataset structure is this format : ``
2. Run `python3 finetune_demo/finetune_vision.py ./data THUDM/glm-4v-9b ./finetune_demo/configs/lora.yaml`
3. Models gets loaded from HF hub and the dataset is being fed.
4. When the training starts, in the first step, there is a sharp increase in GPU usage for an example of 7 samples.

**Please provide a better guide and understanding towards vision finetuning.**

## PS; 

In the GLM English docs,
We have this:
**Execute single machine single card run through the following code.**

`python finetune.py  data/AdvertiseGen/  THUDM/glm-4-9b-chat  configs/lora.yaml # For Chat Fine-tune`
`python finetune.py  data/CogVLM-311K/  THUDM/glm-4v-9b configs/lora.yaml # For VQA Fine-tune`

Are we sure about `python finetune.py  data/CogVLM-311K/  THUDM/glm-4v-9b configs/lora.yaml # For VQA Fine-tune` is the right command?

**Comment by theharshithh** [comment]
@zRzRzRzRzRzRzR

**Comment by zRzRzRzRzRzRzR** [comment]
batch size per device = 2 
1 batch size use 75GB memory

**Comment by theharshithh** [comment]
Okay will try it out

**Comment by theharshithh** [comment]
Can you please share the complete lora yaml config that might work with the given hardware requirements?

**Comment by theharshithh** [comment]
@zRzRzRzRzRzRzR In the `lora.yaml` file 

the config we use is 

`per_device_train_batch_size: 1`

and 

`per_device_eval_batch_size: 1`

So you are suggesting we have 2 batches per device or how

Because this current yaml config always gives me cuda out of memory.

**Comment by zRzRzRzRzRzRzR** [comment]
If you can't use the default configuration normally, then a larger batch size will definitely not work. This is already the minimum configuration.
But after my test, even if it is an A100 graphics card with 75GB video memory, are you sure that the maximum input length and output length are both 512?

**Comment by theharshithh** [comment]
We had used `batch size per device: 1` and not 2. We did use 2 first but changed it in the `lora.yaml`. 

**Answering your question:** Yes the input length is less than 512 tokens. (less than 256 tokens)

We tried with this `lora.yaml`

`data_config:
  train_file: train.jsonl
  val_file: val.jsonl
  test_file: test.jsonl
  num_proc: 1

max_input_length: 512
max_output_length: 512
training_args:
  output_dir: ./output
  max_steps: 128
  learning_rate: 5e-4
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  dataloader_num_workers: 7 
  remove_unused_columns: false
  save_strategy: steps
  save_steps: 10
  log_level: info
  logging_strategy: steps
  logging_steps: 50
  evaluation_strategy: steps
  eval_steps: 50
  predict_with_generate: true
  fp16: true 
  gradient_accumulation_steps: 1
  generation_config:
    max_new_tokens: 256
peft_config:
  peft_type: LORA
  task_type: CAUSAL_LM
  r: 1
  lora_alpha: 32
  lora_dropout: 0.1
  target_modules: ["query_key_value"]`
  
  ## Here is the logs before CUDA out of memory. 

`
***** Running training *****
  Num examples = 7
  Num Epochs = 128
  Instantaneous batch size per device = 1
  Training with DataParallel so batch size has been adjusted to: 8
  Total train batch size (w. parallel, distributed & accumulation) = 8
  Gradient Accumulation steps = 1
  Total optimization steps = 128
  Number of trainable parameters = 799,744
  0%|                                                                             | 0/128 [00:00<?, ?it/s]`

**_Here is the GPU snap snot at that time-period._**

<img width="1417" alt="Screenshot 2024-07-03 at 8 08 05 PM" src="https://github.com/THUDM/GLM-4/assets/124494928/831bffa4-992f-4aab-9412-d3866a3ccfcf">

We mostly suspect its a DP problem as only 7 nodes are getting used as we have 7 examples.

Love to get in touch w you bro. I am reachable at `harshith@onfinance.in`
Help is much appreciated.

**Comment by theharshithh** [comment]
Update 1:

I had tried DeepSpeed with this command `OMP_NUM_THREADS=1 torchrun --standalone --nnodes=1 --nproc_per_node=8  ./finetune_demo/finetune_vision.py ./data/  THUDM/glm-4v-9b finetune_demo/configs/lora.yaml`

All the GPU cores were used. When we did DP and had 2-2-3 data examples in `test.jsonl`, `train.jsonl`, and `val.jsonl`, only 2 cores were getting used. So we assumed DP was a problem. When ran the `Deepseed` command, used all cores efficiently but still running out of memory. Cuda error still persists. 

## Logs before error:
<img width="722" alt="Screenshot 2024-07-03 at 9 41 07 PM" src="https://github.com/THUDM/GLM-4/assets/124494928/be59dc85-f90f-4f48-8f19-93712b8775de">

Please check below for the GPU usage. 

<img width="637" alt="Screenshot 2024-07-03 at 9 41 39 PM" src="https://github.com/THUDM/GLM-4/assets/124494928/d7baad7f-22e6-4eba-a6cc-d95e3c011f09">


Help is much appriciated. Using the same GPU config - `NVIDIA A100-SXM4-80GB * 8`

**Comment by theharshithh** [comment]
@zRzRzRzRzRzRzR Hello. Your help would be much appreciated

**Comment by zRzRzRzRzRzRzR** [comment]
emm, it is one gpu works?(set only one gpu and tune the model in lora) DS will not work in this demo in my test and I wrote in Readme
If one gpu work, the problem maybe in DP. I also have no idea to check now

**Comment by theharshithh** [comment]
Can you please provide us with a fine-tuning script and a lora yaml file
that tunes the model.

Can u share the one with that works with yourside? The one you guys have
tested and found it to be working.

**Comment by zRzRzRzRzRzRzR** [comment]
here is what I use 
```
data_config:
  train_file: train.jsonl
  val_file: dev.jsonl
  test_file: dev.jsonl
  num_proc: 1
max_input_length: 512
max_output_length: 512
training_args:
  # see `transformers.Seq2SeqTrainingArguments`
  output_dir: ./output
  max_steps: 3000
  # needed to be fit for the dataset
  learning_rate: 5e-4
  # settings for data loading
  per_device_train_batch_size: 1
  dataloader_num_workers: 16
  remove_unused_columns: false
  # settings for saving checkpoints
  save_strategy: steps
  save_steps: 500
  # settings for logging
  log_level: info
  logging_strategy: steps
  logging_steps: 10
  # settings for evaluation
  per_device_eval_batch_size: 4
  evaluation_strategy: steps
  eval_steps: 500
  # settings for optimizer
  # adam_epsilon: 1e-6
  # uncomment the following line to detect nan or inf values
  # debug: underflow_overflow
  predict_with_generate: true
  # see `transformers.GenerationConfig`
  generation_config:
    max_new_tokens: 512
  # set your absolute deepspeed path here
  # deepspeed: configs/ds_zero_3.json
peft_config:
  peft_type: LORA
  task_type: CAUSAL_LM
  r: 8
  lora_alpha: 32
  lora_dropout: 0.1
  target_modules: ["query_key_value"]
```
and I only use 1 x A100

**Comment by theharshithh** [comment]
got it.

Last time when you had tried tuning this, did the training run successfully?

I'll implement the same to debug.

**Comment by zRzRzRzRzRzRzR** [comment]
yes and I get the adapter weight, Last Time is today haha

**Comment by theharshithh** [comment]
haha thanks.

it's been fun talking to you mate.

hey im harshith btww
would love to know you.

this is my twitter : https://x.com/theharshithh

**Comment by theharshithh** [comment]
also, did you change any of the other things in the finetune_vision.py?

just to be on the safe side?

**Comment by zRzRzRzRzRzRzR** [comment]
change here may work
<img width="773" alt="image" src="https://github.com/THUDM/GLM-4/assets/93239683/b2c607a0-18d2-4031-9079-2b0ac0d2db6c">

change it to 500(both)

**Comment by theharshithh** [comment]
noted. will try today.

**Comment by theharshithh** [comment]
@zRzRzRzRzRzRzR Heyy. 

I am able save the `adapter_config.json`
![Screenshot 2024-07-10 at 6 19 07 PM](https://github.com/THUDM/GLM-4/assets/124494928/52155a17-91db-4c49-a226-a05d9f36512f)
<img width="1131" alt="Screenshot 2024-07-10 at 7 30 34 PM" src="https://github.com/THUDM/GLM-4/assets/124494928/c04f3419-c3d7-4a7a-8604-b0f6debe4472">

_## Note:_ We changed the Seq2Seq, so that we can set both `max_steps: 30` & `num_train_epochs: 3`. 

Its able to run 21/30 steps. Its failing under ```print('hitting test')
    if test_dataset is not None:
    trainer.predict(test_dataset)```
    
**_Error Logs:_**
<img width="1131" alt="Screenshot 2024-07-10 at 7 30 34 PM" src="https://github.com/THUDM/GLM-4/assets/124494928/c7085c44-7398-490d-9222-1d5ddbf87691">


Can you please verify if you have tried the `inference.py` for the saved model adapter_configs? 

Patience much appreciated!

**Comment by theharshithh** [comment]
Also, please share the branch of the `finetune_vision.py` which is working for you.

**Comment by zRzRzRzRzRzRzR** [comment]
get this issue, please install transformers == 4.40.2 and using main branch(latest commit) and I have not met this issue before

**Comment by theharshithh** [comment]
noted, Can u please let me know if a compete finetune (vision)and inference
is happening successfully for you?

Just to confirm if there is any other error that might come.
