### ISSUE TITLE
GLM4-V微调报错ArrowInvalid: offset overflow while concatenating arrays

### ISSUE THREAD

**Issue by LCY5600** [THUDM/GLM-4#283]
### System Info / 系統信息

使用OMP_NUM_THREADS=1 torchrun --standalone --nnodes=1 --nproc_per_node=8  finetune_vision.py  data/images/  THUDM/glm-4v-9b  configs/lora.yaml  # For VQA Fine-tune  训练，lora.yaml中train.jsonl文件格式如下：
{"messages": [{"role": "user","content": "图片中的动物是什么？","image": "/root/images/0001.jpg"},{"role": "assistant","content": "图片中有一只猫。" }]}
{"messages": [{"role": "user","content": "图片中的动物是什么？","image": "/root/images/0002.jpg"},{"role": "assistant","content": "图片中有一只猫。" }]}
data/images/  里面放着图片集

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

按照以上步骤进行微调报错：ArrowInvalid: offset overflow while concatenating arrays
![528946f2a8399524e8b98d74d101e65](https://github.com/THUDM/GLM-4/assets/53142099/62082e18-3498-4964-bb5f-4ab656e5732a)
![aba30ab1f10362c55e72b64b7f1268e](https://github.com/THUDM/GLM-4/assets/53142099/087008fe-676f-4126-84a1-fad1f246e1b1)

### Expected behavior / 期待表现

请帮忙看下是什么问题，或者能否给出更加详细的数据格式

**Comment by WEIC-7** [comment]
我也遇到了这个问题

**Comment by fly-dragon211** [comment]
请问你是在A100 80G 上运行代码吗？

**Comment by LCY5600** [comment]
> 请问你是在A100 80G 上运行代码吗？

是的

**Comment by rover5056** [comment]
+1 也遇到了同样的问题
看着像是 process_batch 处理有问题，像是 batch   没padding对齐？
我试了下复制一个 sample *100 次是 OK 的，不同的 sample 就不行

**Comment by WEIC-7** [comment]
> 请问你是在A100 80G 上运行代码吗？

我是在A800 80G 上运行的，可以看到issue中 我提出了Map时出错。

**Comment by WEIC-7** [comment]
<h2>解决方法修改默认batch_size</h2>

https://github.com/THUDM/GLM-4/issues/277#issuecomment-2205384992

**Comment by rover5056** [comment]
试了一下 应该是默认 write_batch 过大导致的内存爆了？ 
get_dataset  的时候手动指定下就可以,根据自己的显存调整吧     

<img width="611" alt="image" src="https://github.com/THUDM/GLM-4/assets/19241278/2ce0b418-4fd7-4e8a-a670-0e28f5036aab">

**Comment by rover5056** [comment]
@WEIC-7 
请问下～  您使用的时候发现默认的 map 速度特别慢，一个数据集load 就要很久

**Comment by WEIC-7** [comment]
> @WEIC-7 请问下～ 您使用的时候发现默认的 map 速度特别慢的情况么，一个数据集load 就要很久

是的 map 速度 20~70 examples/s 变化幅度很大 ，7600例大约是三四分钟左右

**Comment by rover5056** [comment]
> > @WEIC-7 请问下～ 您使用的时候发现默认的 map 速度特别慢的情况么，一个数据集load 就要很久
> 
> 是的 map 速度 20~70 examples/s 变化幅度很大 ，7600例大约是三四分钟左右

感觉得改造下，7600～4min， 随便一个大数据集光处理就几个小时了。 没发直接用~

**Comment by LCY5600** [comment]
> > > @WEIC-7 请问下～ 您使用的时候发现默认的 map 速度特别慢的情况么，一个数据集load 就要很久
> > 
> > 
> > 是的 map 速度 20~70 examples/s 变化幅度很大 ，7600例大约是三四分钟左右
> 
> 感觉得改造下，7600～4min， 随便一个大数据集光处理就几个小时了。 没发直接用~

请教一下，Map过程中为什么2W多条数据，内存会爆掉，几百G都不够用

**Comment by WEIC-7** [comment]
> > > > @WEIC-7 请问下～ 您使用的时候发现默认的 map 速度特别慢的情况么，一个数据集load 就要很久
> > > 
> > > 
> > > 是的 map 速度 20~70 examples/s 变化幅度很大 ，7600例大约是三四分钟左右
> > 
> > 
> > 感觉得改造下，7600～4min， 随便一个大数据集光处理就几个小时了。 没发直接用~
> 
> 请教一下，Map过程中为什么2W多条数据，内存会爆掉，几百G都不够用

我是保守地设置了单线程，**batch_size = 100**，这样子应该是不会爆掉的。此外，如果数据较大或者多次load数据，可能会占用一定的缓存空间，导致 **no space left on device**，可以添加cache_dir 来指定缓存地址，将数据缓存到较大的空间。这是我遇到的一些小问题，不知道是否对你有帮助。

**Comment by LCY5600** [comment]
> > > > > @WEIC-7 请问下～ 您使用的时候发现默认的 map 速度特别慢的情况么，一个数据集load 就要很久
> > > > 
> > > > 
> > > > 是的 map 速度 20~70 examples/s 变化幅度很大 ，7600例大约是三四分钟左右
> > > 
> > > 
> > > 感觉得改造下，7600～4min， 随便一个大数据集光处理就几个小时了。 没发直接用~
> > 
> > 
> > 请教一下，Map过程中为什么2W多条数据，内存会爆掉，几百G都不够用
> 
> 我是保守地设置了单线程，**batch_size = 100**，这样子应该是不会爆掉的。此外，如果数据较大或者多次load数据，可能会占用一定的缓存空间，导致 **no space left on device**，可以添加cache_dir 来指定缓存地址，将数据缓存到较大的空间。这是我遇到的一些小问题，不知道是否对你有帮助。

非常感谢，请教一下，cache_dir 这个如何指定呢

**Comment by WEIC-7** [comment]
> > > > > > @WEIC-7 请问下～ 您使用的时候发现默认的 map 速度特别慢的情况么，一个数据集load 就要很久
> > > > > 
> > > > > 
> > > > > 是的 map 速度 20~70 examples/s 变化幅度很大 ，7600例大约是三四分钟左右
> > > > 
> > > > 
> > > > 感觉得改造下，7600～4min， 随便一个大数据集光处理就几个小时了。 没发直接用~
> > > 
> > > 
> > > 请教一下，Map过程中为什么2W多条数据，内存会爆掉，几百G都不够用
> > 
> > 
> > 我是保守地设置了单线程，**batch_size = 100**，这样子应该是不会爆掉的。此外，如果数据较大或者多次load数据，可能会占用一定的缓存空间，导致 **no space left on device**，可以添加cache_dir 来指定缓存地址，将数据缓存到较大的空间。这是我遇到的一些小问题，不知道是否对你有帮助。
> 
> 非常感谢，请教一下，cache_dir 这个如何指定呢

在 _load_datasets中添加 cache_dir 参数，并且在DataManager 类中添加cache_dir 参数并在_load_datasets中加入参数，最后使用data_manager时传入地址就好。

![image](https://github.com/THUDM/GLM-4/assets/128592414/4f893234-8693-4b4f-864d-46ddc3b64a29)
![image](https://github.com/THUDM/GLM-4/assets/128592414/8ef7aa04-63ef-4889-9679-10e4fd0e1d8b)

**Comment by rover5056** [comment]
感觉得改造一下 改成 lazyloader 的形式会更好一点。。正在实现中，晚点尝试提个 pr

**Comment by chenyangMl** [comment]
> > > > > > @WEIC-7 请问下～ 您使用的时候发现默认的 map 速度特别慢的情况么，一个数据集load 就要很久
> > > > > 
> > > > > 
> > > > > 是的 map 速度 20~70 examples/s 变化幅度很大 ，7600例大约是三四分钟左右
> > > > 
> > > > 
> > > > 感觉得改造下，7600～4min， 随便一个大数据集光处理就几个小时了。 没发直接用~
> > > 
> > > 
> > > 请教一下，Map过程中为什么2W多条数据，内存会爆掉，几百G都不够用
> > 
> > 
> > 我是保守地设置了单线程，**batch_size = 100**，这样子应该是不会爆掉的。此外，如果数据较大或者多次load数据，可能会占用一定的缓存空间，导致 **no space left on device**，可以添加cache_dir 来指定缓存地址，将数据缓存到较大的空间。这是我遇到的一些小问题，不知道是否对你有帮助。
> 
> 非常感谢，请教一下，cache_dir 这个如何指定呢

使用环境变量也可以， export HF_HOME=/mnt/cache/huggingface
