### ISSUE TITLE
openai_api_server.py 运行出错

### ISSUE THREAD

**Issue by ZhenHengDong** [THUDM/GLM-4#284]
### System Info / 系統信息

python 版本

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.运行openai_api_server.py，开启服务
2.运行basic_demo/openai_api_server.py 访问
3.服务端报错： File "service.py", line 431, in create_chat_completion
    task_usage = UsageInfo.model_validate(response["usage"])
AttributeError: type object 'UsageInfo' has no attribute 'model_validate'

### Expected behavior / 期待表现

期待修好

**Comment by zRzRzRzRzRzRzR** [comment]
依赖没装对吧，pydamic 是不是老版本

**Comment by ZhenHengDong** [comment]
> 依赖没装对吧，pydamic 是不是老版本

安装了最新版本的pydamic，问题已解决。感谢解答。
