### ISSUE TITLE
pickle tokenizer error

### ISSUE THREAD

**Issue by shanren521** [THUDM/GLM-4#287]
### System Info / 系統信息

docker

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

model = AutoModel.from_pretrained(path,
                                      low_cpu_mem_usage=True,
                                      torch_dtype=torch.bfloat16,
                                      trust_remote_code=True,
                                      )
    print("load model success")
    tokenizer = AutoTokenizer.from_pretrained(path, trust_remote_code=True)
    tokenizer_ = pickle.dumps(tokenizer, protocol=pickle.HIGHEST_PROTOCOL)
    load_tokenizer = pickle.loads(tokenizer_)

Traceback (most recent call last):
  File "/home/hadoop-aipnlp/project/multimodal_files/mid_journey_test.py", line 82, in <module>
    tokenizer_ = pickle.dumps(tokenizer, protocol=pickle.HIGHEST_PROTOCOL)
TypeError: cannot pickle 'builtins.CoreBPE' object

how I can fix it?

### Expected behavior / 期待表现

i expect fix it

**Comment by shanren521** [comment]
i use glm-4-9b

**Comment by zRzRzRzRzRzRzR** [comment]
好像不能这么用吧，这样做的意义是

**Comment by reinforceli** [comment]
![image](https://github.com/user-attachments/assets/1da77069-bc3f-4b33-ad1f-52c3a279ca4b)
也是报这个错误：TypeError: cannot pickle 'builtins.CoreBPE' object
