### ISSUE TITLE
两张A100运行LORA微调报错Out of memory错误

### ISSUE THREAD

**Issue by AegonT** [THUDM/GLM-4#288]
### System Info / 系統信息

cuda版本:12.2      显卡A100:40G    python环境已按照basic demo和finetune demo中安装

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

如果在config/lora中不添加deepspeed路径，会报OOM；
如果添加zero_3路径，会提示GCC版本太老，需要9.0以上来编译torch，是需要更新GCC吗？

### Expected behavior / 期待表现

实现正确的Lora训练
另外，在多机多卡提供的微调命令中，运行的脚本是finetune_hf.py，这个和finetune.py是一样的吗?

**Comment by AegonT** [comment]
数据格式也已经按照Readme制作，微调时打印的数据条数也和预期一致

**Comment by WEIC-7** [comment]
或许可以解决

https://github.com/THUDM/GLM-4/issues/277#issuecomment-2205384992

**Comment by AegonT** [comment]
> 或许可以解决
> 
> [#277 (comment)](https://github.com/THUDM/GLM-4/issues/277#issuecomment-2205384992)

感谢回复~我不是爆内存，是cuda out of memory了，微调的是chat模型，数据集应该已经加载完毕，能看到训练集、验证集、测试集的信息输出。

**Comment by AegonT** [comment]
CUDA running out of memory for a very small dataset (7 sample training data) #281
感觉和这位朋友遇到的是类似的问题
