### ISSUE TITLE
GLM4做知识库时不稳定，提示词大于500的时候，返回的值是空的

### ISSUE THREAD

**Issue by zhoumz123** [THUDM/GLM-4#289]
### System Info / 系統信息

CUDA Version: 12.0,Python 3.10.12,transformers==4.40.0,操作系统 Ubuntu 20.4

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1：进入basic_demo文件夹
2：打开文件openai_api_request.py
3：将第64行simple_chat的content字段的内容替换为：
<指令>根据已知信息，简洁和专业的来回答问题。如果无法从中得到答案，请说 “根据已知信息无法回答该问题，该回答为大模型自身能力解答！”，不允许在答案中添加编造成分，答案请使用中文。 </指令>\n<已知信息>\n<二、前言>二、前言\n本手册旨在帮助员工了解公司的工作环境，各项规章制度，从而使员工尽快融入公司。\n本手册明确了员工和公司各自的义务和责任，\n员工必须了解并遵守公司的所有政策和规章制度。\n本手册内容会适时的有所修改，因此，本手册的细则也将以届时修订的版本为准，而且也无法\n概括所有适用于员工个人情况的条款细则。\n（一）公司概况\n1、公司简介\n深圳市飞书信息技术股份有限公司（以下简称飞书信息）成立于2006年，总部位于中国深圳。\n目前飞书信息在北京、上海、广州、南京、杭州、武汉、成都、西安、重庆、大连、合肥、福州、\n济南、佛山等全国各大城市设立分支机构，业务范围覆盖全球。\n基于对信息技术的研究与开发，结合客户企业的业务场景，依托知识库专家资源池、产品与解\n决方案、技术等方面的积累，飞书信息以信息技术专业人才为载体，为客户在信息化和数字化建设\n的进程中，专业化地提供从需求分析到方案设计、产品开发、测试和运维支撑等全方位的软件技术\n和解决方案服务，对客户业务形成专业、高效、灵活的支撑，赢得了客户的深度信赖与广泛好评，\n并与客户保持持续长久的共赢合作。\n未来，飞书信息将为更多国内外客户提供创造性的技术服务，助力客户快速实现业务目标。同\n时，飞书信息将深耕行业，推动创新，用创新的商业技术服务和客户一起改变世界，为社会创造价\n值，努力成为国际一流的信息技术服务商！\n2、公司发展历程\n2006年\n第5页共41页\n中国领先的软件技术服务提供商\n深圳市飞书信息技术有限公司成立，进军IT服务领域\n2007年\n为国内运营商提供提供解决方案服务，夯实公司在通信领域的专属优势\n2008年\n获深圳市高新技术企业认证、双软认证，技术品质获得业界认可\n2009年\n收购展腾信息，软件技术服务核心竞争力加强\n2010年\n广州分公司业务飞速发展，业务范围辐射华南地区\n2011年\n服务腾讯，全面切入互联网行业软件技术服务领域\n2012年\n上海分公司业务飞速发展，业务范围辐射华东区域\n2013年\n北京分公司业务飞速发展，以北上广深为核心，业务范围辐射全国\n2014年\n获得国家高新技术企业认证，在新一代信息技术创新研发方面得到国家的大力支持和认可\n2015年\n新三板挂牌。通过ISO27001、ISO9001认证。在大中华区为各行业领先企业提供软件技术及解\n决方案服务\n2016年\n通过CMMIL4认证，业绩连续五年保持80%以上高效稳健增长，荣获“深圳新三板最具投资价\n值企业”称号\n2017年\n通过ISO20000认证，与金融、互联网、航空领域等优质企业达成合作，全方位深度布局行业市\n场\n2018年\n员工突破5000，持续提升内部效能，强化组织型作战模式，以全面的服务为客户创造最优质的\n体验\n2019年\n通过CMMIL5认证，持续开拓优势行业，以核心客户向产业链上下游延伸，有实力为世界级客\n户提供更专业的服务\n2020年\n成功上市，员工突破10000，效益与质量增长双提升，高效助力企业数字化转型，成功走向世\n界\n未来，飞书信息将继续精彩前行，坚持技术与服务的双重创新，成为享誉全球的信息技术服务\n商，做软件定义世界的赋能者。\n（二）企业文化\n1、企业愿景\n成为国际一流的信息技术服务商\n第6页共41页\n中国领先的软件技术服务提供商\n2、企业使命\n软件定义数字世界的赋能者\n3、企业精神：图存图强\n图存图强的本质是基于不屈的生命意志下的勇于创新、探索，不断打破边界，不顾一切地进步\n与成长，进化与涅槃。基于竞争，基于实力决定生存状态，从个体到群体都要时刻保持作战心态，\n首先确保活着（存在），再追求更强一点。松懈了，就会走下坡路，就会挨打受欺压。\n图存图强的行为表现就是敢于竞争，敢于作为，不怕挑战，不怕战斗，对形势的变化保持警惕，\n及时反应，主动作为，让形势朝着有利的方向发展。\n图存图强的精神面貌应该是关注事情的发展与成长，专注解决事情的办法，面对困难不退缩，\n面对机会，主动迎接。没有机会创造机会。\n4、核心价值观：客户至上、人才为本、艰苦奋斗、团队合作、自我批判\n客户至上、人才为本是飞书事业的魂，飞书事业宗旨；艰苦奋斗、团队合作是飞书人共同建设\n卓越事业的基石；自我批判是纠偏机制，是飞书人保持开放创新和成长的法宝。\n4.1客户至上：\n客户是飞书存在的原因和目的。\n客户是通过购买飞书服务和产品从而帮助飞书实\n现价值回报的组织和个人。\n4.2人才为本：一切为了人才、一切依靠人才。人才就是认同飞书企业文化，有一技之长、一专\n之能，能做事、有担当、敢作为、出业绩的飞书人。\n4.3艰苦奋斗：安逸是温水煮青蛙，只有艰苦奋斗才是生存的保障。艰苦奋斗是中华民族的优良\n传统，是一切伟大事业的基本条件、是全体飞书人对于卓越事业的基本态度。要在激烈竞争和多变\n环境中立于不败之地，唯有坚持长期不懈的艰苦奋斗。\n4.4团队合作：单打独斗只会让自己更辛苦，更难出成绩。优势互补，才能更快，更大，更好地\n产出</已知信息>\n<问题>深圳市飞书信息技术有限公司成立的时间</问题>

4：运行openai_api_request.py脚本，打印内容是空

### Expected behavior / 期待表现

能根据检索的内容正确回答问题

**Comment by zRzRzRzRzRzRzR** [comment]
看一下后台报错

**Comment by zhoumz123** [comment]
没有报错呀

**Comment by zRzRzRzRzRzRzR** [comment]
命令行的能运行吗，会不会是server的bug，我没有复现出来，我也输入了一个500token以上的字段
