### ISSUE TITLE
basic_demo的依赖是不是写错了

### ISSUE THREAD

**Issue by jnchen** [THUDM/GLM-4#29]
### System Info / 系統信息

操作系统 CentOS 7.9
Conda 13.11.0
Python 3.12

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

安装basic_demo的依赖提示找不到bitsandbytes>=0.43.1

最高版本才到0.42.0

### Expected behavior / 期待表现

可以正常安装依赖

**Comment by zRzRzRzRzRzRzR** [comment]
<img width="251" alt="image" src="https://github.com/THUDM/GLM-4/assets/93239683/1c53b373-a710-479a-96ab-1e3120d3f572">
或许是你源不对，我测试的时候用的是0.43.1所以我直接写了当前版本

**Comment by jnchen** [comment]
conda create 一个python3.12直接 pip 安装的，不知道为什么，我先用conda install装一下吧

**Comment by zRzRzRzRzRzRzR** [comment]
> conda create 一个python3.12直接 pip 安装的，不知道为什么，我先用conda install装一下吧

0.42也可以

**Comment by jnchen** [comment]
> > conda create 一个python3.12直接 pip 安装的，不知道为什么，我先用conda install装一下吧
> 
> 0.42也可以

感觉是python版本不太对，我用3.12,ray也找不到

**Comment by yuyi2439** [comment]
> > > conda create 一个python3.12直接 pip 安装的，不知道为什么，我先用conda install装一下吧
> > 
> > 
> > 0.42也可以
> 
> 感觉是python版本不太对，我用3.12,ray也找不到

我也没有找到

**Comment by jnchen** [comment]
> > > > conda create 一个python3.12直接 pip 安装的，不知道为什么，我先用conda install装一下吧
> > > 
> > > 
> > > 0.42也可以
> > 
> > 
> > 感觉是python版本不太对，我用3.12,ray也找不到
> 
> 我也没有找到

降一下python版本，弄到3.10

**Comment by CNDotaBest** [comment]
> <img alt="图像" width="251" src="https://private-user-images.githubusercontent.com/93239683/336754071-1c53b373-a710-479a-96ab-1e3120d3f572.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjQ1MjcsIm5iZiI6MTcxOTgyNDIyNywicGF0aCI6Ii85MzIzOTY4My8zMzY3NTQwNzEtMWM1M2IzNzMtYTcxMC00NzlhLTk2YWItMWUzMTIwZDNmNTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA4NTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3ZjlhOTk0ZWQ5NWVjNTg1OTFjM2VjNzFkMDMxMGYwZmIxN2Q4Yzc1NjE4Y2ZjY2U1NGJjZjcyZGE5ZjhmMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wGrLFgLARBMxoyXgPE8_mg7OuIAYkRS6J6dmdLseNds"> 也许你的源代码不对，我测试的时候用的就是0.43.1所以我直接写了当前版本

麻烦给一个具体版本，我也遇到了这个情况bitsandbytes最高版本才到0.42.0

**Comment by CNDotaBest** [comment]
> > > > > conda create 一个python3.12直接 pip 安装的，不知道为什么，我先用conda install安装一下吧
> > > > 
> > > > 
> > > > 0.42也可以
> > > 
> > > 
> > > 感觉是python版本不太对，我用的是3.12，ray也找不到
> > 
> > 
> > 我找不到
> 
> 降级一下python版本，弄到3.10

我用的官方推荐的3.10.12版本一样不行
