### ISSUE TITLE
glm-4v-9b demo怎么使用多个GPU

### ISSUE THREAD

**Issue by lesrose** [THUDM/GLM-4#290]
### System Info / 系統信息

3090显卡

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

device = "cuda"

tokenizer = AutoTokenizer.from_pretrained("/data/ai-model/glm-4v-9b", trust_remote_code=True)

query = '描述这张图片'
image = Image.open("/home/robot/ppt_pic/Unit-1-Lesson-1-What-Is-Your-Name-01.jpg").convert('RGB')
inputs = tokenizer.apply_chat_template([{"role": "user", "image": image, "content": query}],
                                       add_generation_prompt=True, tokenize=True, return_tensors="pt",
                                       return_dict=True)  # chat mode

inputs = inputs.to(device)
model = AutoModelForCausalLM.from_pretrained(
    "/data/ai-model/glm-4v-9b",
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True
).to(device).eval()

gen_kwargs = {"max_length": 2500, "do_sample": True, "top_k": 1}
with torch.no_grad():
    outputs = model.generate(**inputs, **gen_kwargs)
    outputs = outputs[:, inputs['input_ids'].shape[1]:]
    print(tokenizer.decode(outputs[0]))
    
运行demo出错
![image](https://github.com/THUDM/GLM-4/assets/48045297/ca61be0c-6133-49a0-8263-ac0788592e30)

### Expected behavior / 期待表现

正常运行

**Comment by zRzRzRzRzRzRzR** [comment]
<img width="949" alt="image" src="https://github.com/THUDM/GLM-4/assets/93239683/2a73d81c-a12c-4f15-8c98-754a0d4a0974">
<img width="743" alt="image" src="https://github.com/THUDM/GLM-4/assets/93239683/fd9454b9-2802-40d0-b444-8f3b08db9a19">
CUDA_VISIBLE_DEVICES=1,2  python trans_cli_vision_demo.py 这样就行了吧
