### ISSUE TITLE
可以支持一下transformers来实现openai-server吗？

### ISSUE THREAD

**Issue by ciaoyizhen** [THUDM/GLM-4#292]
之前提过这个issue
https://github.com/THUDM/GLM-4/issues/247#issue-2375153517

我现在解决了，好像是vllm的问题
我直接用transformer的方法去使用 不报这个了 也能成功了

我现在正在打算根据glm-3的那个服务重写
但是我的技术上没那么牛逼，写起来怕有问题，所以官方能出一个吗？
谢谢大神！！！

**Comment by zRzRzRzRzRzRzR** [comment]
目前没有相关计划，其实就是换一个底座，现在统一使用vLLM管理，bug比较好找
