### ISSUE TITLE
2*22G多卡推理GLM-4v-9b,显卡device不一致错误，modeling_chatglm.py中的870行错误

### ISSUE THREAD

**Issue by happy-xlf** [THUDM/GLM-4#295]
### System Info / 系統信息

cuda 11.8
transformers 4.42.3
peft 0.11.1
torch 2.3.1

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

只更换了此处推理代码，其他与官方提供的一致
model = AutoModelForCausalLM.from_pretrained(
    model_dir,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True,
    device_map="auto"
).eval()

出现如下错误：
File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 870, in forward
    new_input_embeds.append(torch.cat(
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat)

解决办法：
修改glm-4v-9b中的modeling_chatglm.py第870行，改为如下代码，即可解决。
device = inputs_embeds.device
new_input_embeds.append(torch.cat(
                        (inputs_embeds[i, :boi_token_pos], images_features[i].to(device), inputs_embeds[i, eoi_token_pos + 1:].to(device))))

### Expected behavior / 期待表现

多卡推理正常运行✅，期望可以改正源码的错误。

**Comment by zRzRzRzRzRzRzR** [comment]
fix

**Comment by leyiwang** [comment]
mark

**Comment by oubeichen** [comment]
> fix

https://github.com/datawhalechina/self-llm/issues/217

chat 模型这里是不是也有相似的问题？最新的模型文件会出问题，之前的反而没问题。

**Comment by LanYu4qz** [comment]
确实改了可以了  NB
