### ISSUE TITLE
原始接口流式请求content为空

### ISSUE THREAD

**Issue by starage2020** [THUDM/GLM-4#296]
请教一下GLM4原生接口 流式请求 采用glm4-9b-chat模型，output返回中content为空，大家有遇到这种情况吗？

**Comment by zRzRzRzRzRzRzR** [comment]
详细报错？

**Comment by starage2020** [comment]
generate = parse_output_text(request.model, output)后打印output得到的结果是：{"model":"glm4-9b-chat","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":"","function_call":null},"finish_reason":null,"index":0}],"created":1720094309}
content的值是空的。

**Comment by starage2020** [comment]
> 详细报错？

generate = parse_output_text(request.model, output)后打印output得到的结果是：{"model":"glm4-9b-chat","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":"","function_call":null},"finish_reason":null,"index":0}],"created":1720094309}
content的值是空的。

**Comment by zRzRzRzRzRzRzR** [comment]
emm 如果不是用openai呢，我没有办法复现，我这都能输出
