### ISSUE TITLE
glm-4v-9b模型后续会支持vllm部署吗？

### ISSUE THREAD

**Issue by danxuan2022** [THUDM/GLM-4#298]
### System Info / 系統信息

glm-4v-9b模型后续会支持vllm部署吗？如果支持的话大概什么时间能支持上呢～

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

ad fa

### Expected behavior / 期待表现

asdf

**Comment by zRzRzRzRzRzRzR** [comment]
计划中，但是需要一段比较长的时间

**Comment by danxuan2022** [comment]
> 计划中，但是需要一段比较长的时间

大概要多久能支持，迫不及待的想用，期待中...
