### ISSUE TITLE
GLM-4v-9b 推理速度慢 每张图片推理需要1分钟左右

### ISSUE THREAD

**Issue by sujunze** [THUDM/GLM-4#300]
### System Info / 系統信息

3张T4 GPU

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

在3张T4卡上推理速度太慢

### Expected behavior / 期待表现

能把推理速度控制在1秒钟内

**Comment by zRzRzRzRzRzRzR** [comment]
这个结构和你现在这个卡很慢是正常的，使用A100和这个仓库的框架基本在20秒内响应完。 如果希望使用更快的模型，可以使用我们的API
