### ISSUE TITLE
微调glm4v时map数据的时候出现no space on device 如何解决呢？

### ISSUE THREAD

**Issue by Cverchen** [THUDM/GLM-4#302]
### System Info / 系統信息

8*A800 80G

### Who can help? / 谁可以帮助到您？

@d

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

正常运行单机多卡程序微调

### Expected behavior / 期待表现

希望解决此问题

**Comment by zRzRzRzRzRzRzR** [comment]
这不是没空间了吗，代码中你看看默认参数1000改小点

**Comment by Cverchen** [comment]
改成100还是不行，我数据比较多10万左右，我通过加入缓存地址解决no space问题了，不过又会出现images【0】【0】 list out of index

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月06日 12:19 |
| 收件人 | THUDM/GLM-4 ***@***.***> |
| 抄送人 | Cverchen ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [THUDM/GLM-4] 微调glm4v时map数据的时候出现no space on device 如何解决呢？ (Issue #302) |

这不是没空间了吗，代码中你看看默认参数1000改小点
