### ISSUE TITLE
GLM-4V-9b CUDA out of memory. Tried to allocate 1.16 GiB. GPU 

### ISSUE THREAD

**Issue by Lbaiall** [THUDM/GLM-4#306]
我使用L4 GPU 24G 在colab上去进行运行，我想集成为某个我的功能所以我的代码：

 # 安装必要的库
import torch
from PIL import Image
from transformers import AutoModelForCausalLM, AutoTokenizer
import os
import re
import gc

# 挂载Google Drive
from google.colab import drive
drive.mount('/content/drive')

# 检查GPU可用性并设置设备
if torch.cuda.is_available():
    print("GPU is available. Using CUDA.")
    device = torch.device("cuda")
else:
    raise EnvironmentError("GPU is not available. Please ensure a GPU is connected and properly configured.")

# 初始化模型和 tokenizer
model_name = "THUDM/glm-4v-9b"  # 修改为你的Hugging Face模型名称

tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)

# 加载模型到GPU
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    #torch_dtype=torch.bfloat16,  # 使用bfloat16来减少内存使用
    #low_cpu_mem_usage=True,
    trust_remote_code=True,
    #device_map="auto",  # 让Accelerate库处理设备映射
).to(device).eval()

def process_image(image_path):
    # 加载图像
    image = Image.open(image_path).convert('RGB')
    query = '提取文字'

    # 准备输入
    inputs = tokenizer.apply_chat_template(
        [{"role": "user", "image": image, "content": query}],
        add_generation_prompt=True,
        tokenize=True,
        return_tensors="pt",
        return_dict=True
    )

    # 将输入张量移动到GPU
    for key in inputs.keys():
        inputs[key] = inputs[key].to(device)

    # 生成输出
    gen_kwargs = {"max_length": 50, "do_sample": True, "top_k": 1}
    with torch.no_grad():
        outputs = model.generate(**inputs, **gen_kwargs)
        outputs = outputs[:, inputs['input_ids'].shape[1]:]
        result = tokenizer.decode(outputs[0].cpu())

    # 保存结果到 .txt 文件
    base_name = os.path.basename(image_path)
    txt_file = os.path.splitext(base_name)[0] + ".txt"
    with open(txt_file, 'w', encoding='utf-8') as f:
        f.write(result)

    return txt_file, result

def update_markdown(md_file, image_name, result):
    with open(md_file, 'r', encoding='utf-8') as f:
        md_content = f.read()

    # 使用正则表达式替换图片标签内容
    pattern = rf'!\[{image_name}\]\((.*?)\)'
    replacement = f'![{image_name}]({result})'
    md_content = re.sub(pattern, replacement, md_content)

    with open(md_file, 'w', encoding='utf-8') as f:
        f.write(md_content)

if __name__ == "__main__":
    image_dir = '/content/drive/MyDrive/image'  # 图片文件夹路径
    md_dir = '/content/drive/MyDrive/111'  # Markdown 文件夹路径

    # 遍历图片文件夹中的所有图片
    for image_file in os.listdir(image_dir):
        if image_file.endswith(('.png', '.jpg', '.jpeg')):
            image_path = os.path.join(image_dir, image_file)
            try:
                txt_file, result = process_image(image_path)
                print(f"Processed {image_file}")

                # 遍历 Markdown 文件夹中的所有 Markdown 文件
                for md_file in os.listdir(md_dir):
                    if md_file.endswith('.md'):
                        md_path = os.path.join(md_dir, md_file)
                        update_markdown(md_path, os.path.splitext(image_file)[0], result)
                        print(f"Updated {md_file}")

                # 清理CUDA缓存
                torch.cuda.empty_cache()
                gc.collect()

            except Exception as e:
                print(f"Error processing {image_file}: {str(e)}")

    print("处理完成！")
但是始终出现报错
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
GPU is available. Using CUDA.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%
 15/15 [00:30<00:00,  4.54s/it]
---------------------------------------------------------------------------
OutOfMemoryError                          Traceback (most recent call last)
[<ipython-input-6-d0715968941d>](https://localhost:8080/#) in <cell line: 26>()
     30     trust_remote_code=True,
     31     #device_map="auto",  # 让Accelerate库处理设备映射
---> 32 ).to(device).eval()
     33 
     34 def process_image(image_path):

6 frames
[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in convert(t)
   1157                         memory_format=convert_to_format,
   1158                     )
-> 1159                 return t.to(
   1160                     device,
   1161                     dtype if t.is_floating_point() or t.is_complex() else None,

OutOfMemoryError: CUDA out of memory. Tried to allocate 1.16 GiB. GPU

**Comment by zRzRzRzRzRzRzR** [comment]
为什么不直接使用官方的多卡挂在的方式，一张24G的卡就是跑不通的，device = auto就能分到多张卡

**Comment by qmjy** [comment]
> 为什么不直接使用官方的多卡挂在的方式，一张24G的卡就是跑不通的，device = auto就能分到多张卡

请问官方的多卡挂载方式在哪里呢，能给一下链接吗？ 
当前一般的显卡都没有24G显存，多卡势必会是大部分人的使用方式，希望官方补充composite demo下的多卡参数配置，帮助小白快速上手，谢谢。

**Comment by qmjy** [comment]
@zRzRzRzRzRzRzR 麻烦了
