### ISSUE TITLE
llama.cpp现在已经支持GLM4，希望在readme中加上

### ISSUE THREAD

**Issue by piDack** [THUDM/GLM-4#308]
### Feature request  / 功能建议

具体的pr在https://github.com/ggerganov/llama.cpp/commit/905942abdba5ba0b28a1b0805e51e4f818c54bc9 
issue在https://github.com/ggerganov/llama.cpp/pull/8031

### Motivation / 动机

llama.cpp是广泛应用的推理框架

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
fix
