### ISSUE TITLE
我在微调的过程中，损失始终为0

### ISSUE THREAD

**Issue by ZhiyuYUE** [THUDM/GLM-4#310]
### System Info / 系統信息

我的其他配置都和文档里的一致，只有驱动是530而不是535。损失不更新的原因应该不是warm up的缘故吧（我微调的是最新的codegeex，还是说目前codegeex不支持微调？）

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

我的启动脚本是CUDA_VISIBLE_DEVICES=0,1,2,3 OMP_NUM_THREADS=1 torchrun --standalone --nnodes=1 --nproc_per_node=4  finetune.py /mnt/code/yzy/data/  /mnt/model/glm/codegee/  configs/sft.yaml，这里使用lora的情况也是一样的。
![截屏2024-07-08 17 55 23](https://github.com/THUDM/GLM-4/assets/114695796/83fffb69-ead1-4e5d-a3ed-2f82672ef244)

### Expected behavior / 期待表现

我认为的可能原因就是驱动版本过低或者codegeex目前不支持通用的微调方法。麻烦解答一下我的问题谢谢～

**Comment by zRzRzRzRzRzRzR** [comment]
参考 #261 #260 #279

**Comment by ZhiyuYUE** [comment]
> 参考 #261 #260 #279

感谢我看一下
