### ISSUE TITLE
basic_demo中的openai_api_server 在vllm的tensor_parallel_size参数大于1时，会在一定运行后产生很多感叹号。

### ISSUE THREAD

**Issue by mrrllbb** [THUDM/GLM-4#312]
### System Info / 系統信息

**NVIDIA-SMI** 535.154.05             
**Driver Version:** 535.154.05              
**CUDA Version:** 12.2 
**torch**==2.3.0            
**transformers**==4.40.0    
**system：**
```
LSB Version:    :core-4.1-amd64:core-4.1-noarch
              Distributor ID: CentOS
              Description:    CentOS Linux release 7.8.2003 (Core)
              Release:        7.8.2003
              Codename:       Core
```

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.将basic_demo中的openai_api_server中的
```
engine_args = AsyncEngineArgs(
        model=MODEL_PATH,
        tokenizer=MODEL_PATH,
        # 如果你有多张显卡，可以在这里设置成你的显卡数量
        tensor_parallel_size=1,
        dtype="bfloat16",
        trust_remote_code=True,
        # 占用显存的比例，请根据你的显卡显存大小设置合适的值，例如，如果你的显卡有80G，您只想使用24G，请按照24/80=0.3设置
        gpu_memory_utilization=0.9,
        enforce_eager=True,
        worker_use_ray=True,
        engine_use_ray=True,
        disable_log_requests=True,
        max_model_len=MAX_MODEL_LENGTH,
    )
```
tensor_parallel_size参数改为2，使用2张卡；
2.用多线程调用api：
```
def send_request(prompt):
    response = simple_chat(prompt)
    return response

with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:
        executor.map(send_request, test_list)
```
其中的simple_chat就是openai_api_client中的函数

### Expected behavior / 期待表现

和tensor_parallel_size为1时表现一致

**Comment by mrrllbb** [comment]
> 更新一下模型文件吧，估计是special id的这个文件没更新，因为！ 是id为0 的时候的内容，估计是paddding中的问题，目前没有复现。

感觉不是模型文件的原因，也不是glm-4模型的问题，我用qwen的模型一样会有这个问题，当2卡的vllm出现kv空间不足的warning时就会出现感叹号。我在vllm的仓库了发现了类似的issue
[ Qwen1.5-14B-Chat使用vllm==0.3.3版本在Tesla V100-PCIE-32GB显卡上部署结果全部是感叹号，无结果](https://github.com/vllm-project/vllm/issues/3998)

**Comment by mrrllbb** [comment]
我用的L20-48G的卡，用vllm跑代码的时候只要报了

`WARNING 07-11 15:33:49 scheduler.py:1112] Sequence group 268 is preempted by PreemptionMode.RECOMPUTE mode because there is not enough KV cache space. This can affect the end-to-end performance. Increase gpu_memory_utilization or tensor_parallel_size to provide more KV cache memory. total_num_cumulative_preemption=1`

就会发现结果返回感叹号了。

**Comment by zRzRzRzRzRzRzR** [comment]
正常应该没有这个报错的， 这个warning为什么会出现，显存不够吗
