### ISSUE TITLE
use_cache,kv_cache的含义？

### ISSUE THREAD

**Issue by ciaoyizhen** [THUDM/GLM-4#315]
请教大佬一个问题！

在看源码的时候，对这use_cache和kv_cache两个变量有疑惑？
kv_cache我查资料好像就是说，把attention的k,v缓存起来，用空间换时间？
use_cache我看源码，好像是说把每一层的encode的结果存起来。

但是我没看懂，这个use_cache变量在那里被用了？可不可以把他关掉？我试着将config.json里面的use_cache改成了false，但是代码里面还是true 不知道为啥   那个gengeral_config不是用这个文件生成的吗？
然后在selfattention的代码里面，kv_cache的判断里外层包了一个use_cache。如果要用kv_cache是一定要use_cache为True吗，能把use_cache干掉，然后只用kv_cache吗？

求求大佬解答！！！

**Comment by ciaoyizhen** [comment]
就是我用transformers自己写这个服务，用两张v100，里面在GLMTransformer的模块里面那个present和kv_cache cat不起来，提示两个cuda设备不一致，我想着把他们放到模型用的cuda上，但是device是meta。因为cache前面一些在cuda：0,后面生成的在cuda:1上，然后cat不起来。
我现在是代码强行把这个cache关掉了，但是在生成长文本的时候，请求会超时，感觉就是没有用到kv_cache导致推理特别慢？

**Comment by ciaoyizhen** [comment]
可能好了
我把那个cache用了一个next(label.parameter()).device来存

**Comment by ciaoyizhen** [comment]
靠 还是不行，生成速度还是没有vllm快。
要咋搞呀!!! 求助!!!

**Comment by zRzRzRzRzRzRzR** [comment]
更新了最新代码吗，不是有移动tensor到对应显卡的部分吗

**Comment by ciaoyizhen** [comment]
服务代码是自己的写的(仿造的Chatglm3的那个openai_server)，然后跟那个一样，有些异步也改成同步了(不然流式就内部算完才出来？)。我还改了模型的部分，就是模型里面有一个attention的那个部分，不改他会报错，就是parent那里，在cat的时候，会说cat的两个张量不在同一个设备上，我现在是用next(layer.parameter()).device 强行同步了一下设备, 将过去的结果存起来了。现在都能用，k8s启镜像也能用了，但是非流式在生成长文本的时候还是不行，耗时太长报openaiAPIErrot  超时那个  但是我用仓库里的vllm的demo 非流式是能跑的，但是vllm打镜像打不起来就启不了。

**Comment by ciaoyizhen** [comment]
我刚刚对比了一下 流式的也没vllm快 我靠  vllm里面有加速吗？

**Comment by ciaoyizhen** [comment]
怎么说呢 我现在客户端这边长文本生成的，流式生成自己拼起来就不会超时。。。。

**Comment by ciaoyizhen** [comment]
大佬！ 我还发现一个问题，非流式不支持并发诶？？   vllm是支持的，因为我发现我的写的不支持，然后我去试了一下ChatGlm3的那个  也不支持啊
这个要怎么解决

**Comment by Truecodeman** [comment]
File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 565, in forward
    cache_k, cache_v, _ = kv_cache
ValueError: too many values to unpack (expected 2)
貌似我们遇到同一个问题，兄台有没有思路

**Comment by zRzRzRzRzRzRzR** [comment]
这个只要降低transformers版本就行了 4.40.2

**Comment by Truecodeman** [comment]
版本哥，谢谢你，已解决

**Comment by xsank** [comment]
> 这个只要降低transformers版本就行了 4.40.2

@zRzRzRzRzRzRzR , 我的transformer就是这个版本，之前都好好的，今天推理突然报错:
```shell
 outputs = model.generate(**inputs, **gen_kwargs)
  File "/home/admin/glm4/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/admin/glm4/lib/python3.9/site-packages/transformers/generation/utils.py", line 1622, in generate
    result = self._sample(
  File "/home/admin/glm4/lib/python3.9/site-packages/transformers/generation/utils.py", line 2841, in _sample
    model_kwargs = self._update_model_kwargs_for_generation(
  File "/home/admin/glm4/binary/huggingface/modules/transformers_modules/glm-4-9b-chat-1m/modeling_chatglm.py", line 936, in _update_model_kwargs_for_generation
    cache_name, cache = self._extract_past_from_model_output(
ValueError: too many values to unpack (expected 2)
0.130(s) elapsed
```
请问这种怎么处理呢？

**Comment by zRzRzRzRzRzRzR** [comment]
已经修复，更新最新的模型实现代码，在我们的hf上

**Comment by ciaoyizhen** [comment]
好滴 谢谢 感谢大佬!!
