### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by zxy1728** [THUDM/GLM-4#317]
Running the demo gives this error：

**Comment by zxy1728** [comment]
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

device = "cuda"

tokenizer = AutoTokenizer.from_pretrained('/home/glm-4v-9b', trust_remote_code=True)

query = "你好"

inputs = tokenizer.apply_chat_template([{"role": "user", "content": query}],
                                       add_generation_prompt=True,
                                       tokenize=True,
                                       return_tensors="pt",
                                       return_dict=True
                                       )

inputs = inputs.to(device)
model = AutoModelForCausalLM.from_pretrained(
    '/home/glm-4v-9b',
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True,load_in_4bit=True
).eval()

gen_kwargs = {"max_length": 2500, "do_sample": True, "top_k": 1}
with torch.no_grad():
    outputs = model.generate(**inputs, **gen_kwargs)
    outputs = outputs[:, inputs['input_ids'].shape[1]:]
    print(tokenizer.decode(outputs[0], skip_special_tokens=True))

**Comment by tw-repository** [comment]
I have meet the same issue, i.e., RuntimeError: probability tensor contains either inf, nan or element < 0.

**Comment by zRzRzRzRzRzRzR** [comment]
有两种可能
1. 没有使用bf16推理
2. 模型可能没有下载正确，目前有遇到过重新git 下载模型后正常的案例

**Comment by tw-repository** [comment]
> 有两种可能
> 
> 1. 没有使用bf16推理
> 2. 模型可能没有下载正确，目前有遇到过重新git 下载模型后正常的案例

Thank you for your answer. The second way, i.e. re-downloading the model, solved the problem.
