### ISSUE TITLE
推理错误，使用官方推理脚本，仅更改模型存储路径：RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by HouChenXD** [THUDM/GLM-4#318]
### System Info / 系統信息

cuda=12.1, python=3.10, transformer=4.40.0, A100 80g pcie *2, torch=2.3.0+cu121

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Loading checkpoint shards: 100%|█████████████████| 10/10 [00:07<00:00,  1.27it/s]
Welcome to the GLM-4-9B CLI chat. Type your messages below.

You: 你好
GLM-4: Exception in thread Thread-2 (generate):
Traceback (most recent call last):
  File "/home/houchen/anaconda3/envs/GLM4Chat/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/houchen/anaconda3/envs/GLM4Chat/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/houchen/anaconda3/envs/GLM4Chat/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/houchen/anaconda3/envs/GLM4Chat/lib/python3.10/site-packages/transformers/generation/utils.py", line 1622, in generate
    result = self._sample(
  File "/home/houchen/anaconda3/envs/GLM4Chat/lib/python3.10/site-packages/transformers/generation/utils.py", line 2829, in _sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### Expected behavior / 期待表现

accelerate                0.32.1
aiofiles                  23.2.1
altair                    5.3.0
annotated-types           0.7.0
anyio                     4.4.0
attrs                     23.2.0
certifi                   2024.7.4
charset-normalizer        3.3.2
click                     8.1.7
contourpy                 1.2.1
cycler                    0.12.1
distro                    1.9.0
dnspython                 2.6.1
einops                    0.8.0
email_validator           2.2.0
exceptiongroup            1.2.1
fastapi                   0.111.0
fastapi-cli               0.0.4
ffmpy                     0.3.2
filelock                  3.13.1
fonttools                 4.53.1
fsspec                    2024.2.0
gradio                    4.37.2
gradio_client             1.0.2
h11                       0.14.0
httpcore                  1.0.5
httptools                 0.6.1
httpx                     0.27.0
huggingface-hub           0.23.4
idna                      3.7
importlib_resources       6.4.0
Jinja2                    3.1.3
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.9.1
mdurl                     0.1.2
mpmath                    1.3.0
networkx                  3.2.1
numpy                     1.26.3
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.20.5
nvidia-nvjitlink-cu12     12.1.105
nvidia-nvtx-cu12          12.1.105
openai                    1.35.12
orjson                    3.10.6
packaging                 24.1
pandas                    2.2.2
peft                      0.11.1
pillow                    10.2.0
pip                       22.3.1
psutil                    6.0.0
pydantic                  2.8.2
pydantic_core             2.20.1
pydub                     0.25.1
Pygments                  2.18.0
pyparsing                 3.1.2
python-dateutil           2.9.0.post0
python-dotenv             1.0.1
python-multipart          0.0.9
pytorch-fast-transformers 0.4.0
pytz                      2024.1
PyYAML                    6.0.1
referencing               0.35.1
regex                     2024.5.15
requests                  2.32.3
rich                      13.7.1
rpds-py                   0.19.0
ruff                      0.5.1
safetensors               0.4.3
scikit-learn              1.5.1
scipy                     1.14.0
semantic-version          2.10.0
sentence-transformers     3.0.1
sentencepiece             0.2.0
setuptools                65.5.1
shellingham               1.5.4
six                       1.16.0
sniffio                   1.3.1
sse-starlette             2.1.2
starlette                 0.37.2
sympy                     1.12
threadpoolctl             3.5.0
tiktoken                  0.7.0
timm                      1.0.7
tokenizers                0.19.1
tomlkit                   0.12.0
toolz                     0.12.1
torch                     2.3.0+cu121
torchaudio                2.3.0+cu121
torchvision               0.18.0+cu121
tqdm                      4.66.4
transformers              4.40.0
triton                    2.3.0
typer                     0.12.3
typing_extensions         4.9.0
tzdata                    2024.1
ujson                     5.10.0
urllib3                   2.2.2
uvicorn                   0.30.1
uvloop                    0.19.0
watchfiles                0.22.0
websockets                11.0.3
wheel                     0.38.4

**Comment by vicissitude2000** [comment]
同样的问题，兄弟你解决了嘛

**Comment by HouChenXD** [comment]
> 同样的问题，兄弟你解决了嘛

没有，我换CPU版本的torch能正常推理

**Comment by HouChenXD** [comment]
> > > 同样的问题，兄弟你解决了嘛
> > 
> > 
> > 没有，我换CPU版本的torch能正常推理
> 
> 那推理不会很慢嘛

是的，我只是测试下

**Comment by zRzRzRzRzRzRzR** [comment]
百分百复现吗，我是torch 2.3.0 但是应该不影响的

**Comment by HouChenXD** [comment]
> 百分百复现吗，我是torch 2.3.0 但是应该不影响的

cuda:12.1,驱动535.183，复现出来了吗

**Comment by HouChenXD** [comment]
解决了，尝试在单卡推理就好了

**Comment by wuhaoyu010** [comment]
近2日用A800的卡，多卡多用户并发流式输出一直遇到这个报错，将torch_dtype=torch.float32或torch_dtype=torch.float64 错误就消失了
看的下面的帖子，大概是A系列显卡对BF16  F16支持的不太好
https://github.com/yangjianxin1/Firefly/issues/272

**Comment by qsuzer** [comment]
3090卡也遇到这个问题，该怎么解决呢

**Comment by wuhaoyu010** [comment]
Hello，你的来信已收到
