### ISSUE TITLE
lora微调glm-9b-1m的模型出错

### ISSUE THREAD

**Issue by Text2-m** [THUDM/GLM-4#319]
### System Info / 系統信息

>>> print(transformers.__version__)
4.40.2
>>> print(torch.__version__)
2.3.1

### Who can help? / 谁可以帮助到您？

@z

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Map:   0%|                                                                                                | 0/16 [00:00<?, ? examples/s]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/GLM-4/finetune_demo/finetune.py:362 in main                                    │
│                                                                                                  │
│   359 │   ft_config = FinetuningConfig.from_file(config_file)                                    │
│   360 │   tokenizer, model = load_tokenizer_and_model(model_dir, peft_config=ft_config.peft_co   │
│   361 │   data_manager = DataManager(data_dir, ft_config.data_config)                            │
│ ❱ 362 │   train_dataset = data_manager.get_dataset(                                              │
│   363 │   │   Split.TRAIN,                                                                       │
│   364 │   │   functools.partial(                                                                 │
│   365 │   │   │   process_batch,                                                                 │
│                                                                                                  │
│ /home/GLM-4/finetune_demo/finetune.py:205 in get_dataset                             │
│                                                                                                  │
│   202 │   │   │   remove_columns = orig_dataset.column_names                                     │
│   203 │   │   else:                                                                              │
│   204 │   │   │   remove_columns = None                                                          │
│ ❱ 205 │   │   return orig_dataset.map(                                                           │
│   206 │   │   │   process_fn,                                                                    │
│   207 │   │   │   batched=batched,                                                               │
│   208 │   │   │   remove_columns=remove_columns,                                                 │
│                                                                                                  │
│ /home/anaconda3/envs/glm-4/lib/python3.10/site-packages/datasets/arrow_dataset.py:60 │
│ 2 in wrapper                                                                                     │
│                                                                                                  │
│    599 │   │   else:                                                                             │
│    600 │   │   │   self: "Dataset" = kwargs.pop("self")                                          │
│    601 │   │   # apply actual function                                                           │
│ ❱  602 │   │   out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)                │
│    603 │   │   datasets: List["Dataset"] = list(out.values()) if isinstance(out, dict) else [ou  │
│    604 │   │   for dataset in datasets:                                                          │
│    605 │   │   │   # Remove task templates if a column mapping of the template is no longer val  │
│                                                                                                  │
│ /home/anaconda3/envs/glm-4/lib/python3.10/site-packages/datasets/arrow_dataset.py:56 │
│ 7 in wrapper                                                                                     │
│                                                                                                  │
│    564 │   │   │   "output_all_columns": self._output_all_columns,                               │
│    565 │   │   }                                                                                 │
│    566 │   │   # apply actual function                                                           │
│ ❱  567 │   │   out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)                │
│    568 │   │   datasets: List["Dataset"] = list(out.values()) if isinstance(out, dict) else [ou  │
│    569 │   │   # re-apply format to the output                                                   │
│    570 │   │   for dataset in datasets:                                                          │
│                                                                                                  │
│ /home/anaconda3/envs/glm-4/lib/python3.10/site-packages/datasets/arrow_dataset.py:31 │
│ 61 in map                                                                                        │
│                                                                                                  │
│   3158 │   │   │   │   │   total=pbar_total,                                                     │
│   3159 │   │   │   │   │   desc=desc or "Map",                                                   │
│   3160 │   │   │   │   ) as pbar:                                                                │
│ ❱ 3161 │   │   │   │   │   for rank, done, content in Dataset._map_single(**dataset_kwargs):     │
│   3162 │   │   │   │   │   │   if done:                                                          │
│   3163 │   │   │   │   │   │   │   shards_done += 1                                              │
│   3164 │   │   │   │   │   │   │   logger.debug(f"Finished processing shard number {rank} of {n  │
│                                                                                                  │
│ /home/songzhimeng/anaconda3/envs/glm-4/lib/python3.10/site-packages/datasets/arrow_dataset.py:35 │
│ 52 in _map_single                                                                                │
│                                                                                                  │
│   3549 │   │   │   │   │   │   │   range(*(slice(i, i + batch_size).indices(shard.num_rows)))    │
│   3550 │   │   │   │   │   │   )  # Something simpler?                                           │
│   3551 │   │   │   │   │   │   try:                                                              │
│ ❱ 3552 │   │   │   │   │   │   │   batch = apply_function_on_filtered_inputs(                    │
│   3553 │   │   │   │   │   │   │   │   batch,                                                    │
│   3554 │   │   │   │   │   │   │   │   indices,                                                  │
│   3555 │   │   │   │   │   │   │   │   check_same_num_examples=len(shard.list_indexes()) > 0,    │
│                                                                                                  │
│ /home/anaconda3/envs/glm-4/lib/python3.10/site-packages/datasets/arrow_dataset.py:34 │
│ 21 in apply_function_on_filtered_inputs                                                          │
│                                                                                                  │
│   3418 │   │   │   │   additional_args += (effective_indices,)                                   │
│   3419 │   │   │   if with_rank:                                                                 │
│   3420 │   │   │   │   additional_args += (rank,)                                                │
│ ❱ 3421 │   │   │   processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)          │
│   3422 │   │   │   if isinstance(processed_inputs, LazyDict):                                    │
│   3423 │   │   │   │   processed_inputs = {                                                      │
│   3424 │   │   │   │   │   k: v for k, v in processed_inputs.data.items() if k not in processed  │
│                                                                                                  │
│ /home/GLM-4/finetune_demo/finetune.py:243 in process_batch                           │
│                                                                                                  │
│   240 │   │   │   print(message)                                                                 │
│   241 │   │   │   loss_mask_val = False if message['role'] in ('system', 'user') else True       │
│   242 │   │   │   print(loss_mask_val)                                                           │
│ ❱ 243 │   │   │   new_input_ids = tokenizer.apply_chat_template([message], tokenize=True, retu   │
│   244 │   │   │   new_loss_masks = [loss_mask_val] * len(new_input_ids)                          │
│   245 │   │   │   input_ids += new_input_ids                                                     │
│   246 │   │   │   loss_masks += new_loss_masks                                                   │
TypeError: 'int' object is not subscriptable
╰──────────────────────────────────────────────────────────────────────────────────────────

### Expected behavior / 期待表现

支持glm-9b-1m的微调吗

**Comment by zRzRzRzRzRzRzR** [comment]
可以，但是这个脚本只能调到2K吧，入门级的脚本，调1M似乎意义不大？

**Comment by Text2-m** [comment]
我微调1m的报错，微调128k的没问题

**Comment by XCF-Mike** [comment]
> 似乎没有问题，我刚才试了，同时我更新了模型依赖

在微调glm-9b-1m模型时遇到了
TypeError: FinetuningConfig.__init__() missing 2 required positional arguments: 'combine' and 'freezeV'

transformers的版本为4.46.0

**Comment by chenchen333-dev** [comment]
> > 似乎没有问题，我刚才试了，同时我更新了模型依赖
> 
> 在微调glm-9b-1m模型时遇到了 TypeError: FinetuningConfig.**init**() missing 2 required positional arguments: 'combine' and 'freezeV'
> 
> transformers的版本为4.46.0

请问解决了吗，我也遇到了这个问题

**Comment by chenchen333-dev** [comment]
> > 似乎没有问题，我刚才试了，同时我更新了模型依赖
> 
> 在微调glm-9b-1m模型时遇到了 TypeError: FinetuningConfig.**init**() missing 2 required positional arguments: 'combine' and 'freezeV'
> 
> transformers的版本为4.46.0

解决了，要使用最新的yaml文件
