### ISSUE TITLE
 python trans_web_demo.py多卡运行提示错误，RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat)

### ISSUE THREAD

**Issue by fredliu168** [THUDM/GLM-4#32]
### System Info / 系統信息

PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
 NVIDIA-SMI 535.171.04             Driver Version: 535.171.04   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2080 Ti     Off | 00000000:01:00.0 Off |                  N/A |
| 16%   36C    P8              11W / 250W |   8378MiB / 11264MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce GTX 1070        Off | 00000000:02:00.0 Off |                  N/A |
|  0%   32C    P8               9W / 230W |   7892MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

 python trans_web_demo.py 多卡运行，对模型提问时候提示错误，RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat)

### Expected behavior / 期待表现

python trans_web_demo.py， 提问的时候能正常输出

**Comment by hiyouga** [comment]
更新这个文件：https://huggingface.co/THUDM/glm-4-9b-chat/blob/main/modeling_chatglm.py

**Comment by ashmalvayani** [comment]
Updating the modeling_chatglm.py file did not solve the error. If I run the model on two gpus, it's still throwing the same error. If I run this on a single GPU, it gives the following error:

> ValueError: Pointer argument (at 0) cannot be accessed from Triton (cpu tensor?)

**Comment by ashmalvayani** [comment]
> > 更新这个文件：https://huggingface.co/THUDM/glm-4-9b-chat/blob/main/modeling_chatglm.py
> 
> 我用这个方法成功了，原先的问题是出在哪了？

你到底做了什么来解决这个问题？我是在提到这个问题后下载的模型，所以我应该下载了正确的模型。

**Comment by qihanghou726** [comment]
我遇到了相同的问题，我是通过修改GLM-4/composite_demo/src/clients/hf.py文件夹中class HFClient(Client):
    def __init__(self, model_path: str):
        self.tokenizer = AutoTokenizer.from_pretrained(
            model_path, trust_remote_code=True,
        )
        self.model = AutoModelForCausalLM.from_pretrained(
            model_path,
            trust_remote_code=True,
            torch_dtype=torch.bfloat16,
            # device_map="cuda",
            #修改成可以多卡跑
            device_map="auto",
        ).eval()
这一段将device_map="cuda",=>device_map="auto"，然后模型就可以在多张GPU上跑起来，但是我也更新了https://huggingface.co/THUDM/glm-4-9b-chat/blob/main/modeling_chatglm.py这个文件，对我来说不起效果，请问您是怎么让模型在多张GPU上跑起来的？

**Comment by qihanghou726** [comment]
我遇到了相同的问题，我是通过修改GLM-4/composite_demo/src/clients/hf.py文件夹中class HFClient(Client):
def init(self, model_path: str):
self.tokenizer = AutoTokenizer.from_pretrained(
model_path, trust_remote_code=True,
)
self.model = AutoModelForCausalLM.from_pretrained(
model_path,
trust_remote_code=True,
torch_dtype=torch.bfloat16,
# device_map="cuda",
#修改成可以多卡跑
device_map="auto",
).eval()
这一段将device_map="cuda",=>device_map="auto"，然后模型就可以在多张GPU上跑起来，但是我也更新了
https://huggingface.co/THUDM/glm-4-9b-chat/blob/main/modeling_chatglm.py
这个文件，对我来说不起效果，请问您是怎么让模型在多张GPU上跑起来的？

**Comment by qihanghou726** [comment]
> 评

我并没有修改https://huggingface.co/THUDM/glm-4-9b-chat/blob/main/modeling_chatglm.py这个文件
我是通过修改GLM-4/composite_demo/src/clients/hf.py这个文件来使模型可以在多张GPU上加载，但是在推理的时候会报错这个问题。

**Comment by ashmalvayani** [comment]
但在 github 上修改它不能解决一般问题，比如直接用 huggingface 加载
