### ISSUE TITLE
未检测到显卡占用

### ISSUE THREAD

**Issue by lyc728** [THUDM/GLM-4#321]
你好 现在我用glm4v进行微调 代码如下
`OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=0,6,7 torchrun --standalone --nnodes=1 --nproc_per_node=3  finetune_vision.py  /data/GLM-4-main/data_pre  /data/MLLM/new_models/ZhipuAI/glm-4v-9b  configs/lora.yaml`
现在显卡未检测到占用
<img width="346" alt="企业微信截图_17206937591619" src="https://github.com/THUDM/GLM-4/assets/88084847/416a18d0-3153-41bb-a779-b2e4ba5b5fc5">
<img width="757" alt="企业微信截图_17206937738220" src="https://github.com/THUDM/GLM-4/assets/88084847/7a935c64-eb06-4f78-ae06-660bdc6722c7">

**Comment by zRzRzRzRzRzRzR** [comment]
cuda没装，只装了驱动吧。。。

**Comment by lyc728** [comment]
能跑起来的，但是现在显存会超出

**Comment by lyc728** [comment]
<img width="445" alt="企业微信截图_17207031651371" src="https://github.com/THUDM/GLM-4/assets/88084847/c7e0bdb6-1b9a-48f2-9cb7-ef3021f46198">

**Comment by lyc728** [comment]
> 能跑起来的，但是现在显存会超出

我4张40g的卡 batch 为1也会报错吗？

**Comment by zRzRzRzRzRzRzR** [comment]
因为一张卡要75G，没办法拆分

**Comment by lyc728** [comment]
我看到你更新的文档说的是75G，但是这个模型是每张卡都要75G吗？
