### ISSUE TITLE
两张3090但是显存爆满，无法微调

### ISSUE THREAD

**Issue by ATIpiu** [THUDM/GLM-4#322]
### System Info / 系統信息

linux，ubuntu22，torch 2.3.1 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

按照官方流程运行微调程序，也就是增加数据集，放到对应位置，然后运行 python finetune.py  data/  THUDM/glm-4-9b-chat  configs/lora.yaml # For Chat Fine-tune
![image](https://github.com/THUDM/GLM-4/assets/51857097/002cd4a1-fba7-43ce-886b-f057098b6ca6)
报的错误时显存不够，但是本机两张3090.并且，是直到开始执行微调过程，两张卡同时占满显存和利用率，然后出现出现报错。
报错内容如下
(torch) xiongrun@serverssg:~/tianchi/finetune/finetune_demo$ python finetune.py  data/  THUDM/glm-4-9b-chat  configs/lora.yaml # For Chat Fine-tune
/home/xiongrun/anaconda3/envs/torch/lib/python3.10/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.40it/s]
trainable params: 2,785,280 || all params: 9,402,736,640 || trainable%: 0.02962201438410169
Generating train split: 4 examples [00:00, 1379.36 examples/s]
Generating validation split: 4 examples [00:00, 4551.60 examples/s]
Generating test split: 4 examples [00:00, 5419.00 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 160.88 examples/s]
train_dataset: Dataset({
    features: ['input_ids', 'labels'],
    num_rows: 4
})
Map: 100%|███████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 855.81 examples/s]
val_dataset: Dataset({
    features: ['input_ids', 'output_ids'],
    num_rows: 4
})
Map: 100%|███████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 830.64 examples/s]
test_dataset: Dataset({
    features: ['input_ids', 'output_ids'],
    num_rows: 4
})
max_steps is given, it will override any value given in num_train_epochs
[2024-07-11 19:20:04,245] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.3.1), only 1.0.0 is known to be compatible
***** Running training *****
  Num examples = 4
  Num Epochs = 1,500
  Instantaneous batch size per device = 1
  Training with DataParallel so batch size has been adjusted to: 2
  Total train batch size (w. parallel, distributed & accumulation) = 2
  Gradient Accumulation steps = 1
  Total optimization steps = 3,000
  Number of trainable parameters = 2,785,280
  0%|                                                                                         | 0/3000 [00:00<?, ?it/s]/home/xiongrun/anaconda3/envs/torch/lib/python3.10/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/xiongrun/tianchi/finetune/finetune_demo/finetune.py:437 in main                            │
│                                                                                                  │
│   434 │   )                                                                                      │
│   435 │                                                                                          │
│   436 │   if auto_resume_from_checkpoint.upper() == "" or auto_resume_from_checkpoint is None:   │
│ ❱ 437 │   │   trainer.train()                                                                    │
│   438 │   else:                                                                                  │
│   439 │   │   output_dir = ft_config.training_args.output_dir                                    │
│   440 │   │   dirlist = os.listdir(output_dir)                                                   │
│                                                                                                  │
│ /home/xiongrun/anaconda3/envs/torch/lib/python3.10/site-packages/transformers/trainer.py:1885 in │
│ train                                                                                            │
│                                                                                                  │
│   1882 │   │   │   finally:                                                                      │
│   1883 │   │   │   │   hf_hub_utils.enable_progress_bars()                                       │
│   1884 │   │   else:                                                                             │
│ ❱ 1885 │   │   │   return inner_training_loop(                                                   │
│   1886 │   │   │   │   args=args,                                                                │
│   1887 │   │   │   │   resume_from_checkpoint=resume_from_checkpoint,                            │
│   1888 │   │   │   │   trial=trial,                                                              │
│                                                                                                  │
│ /home/xiongrun/anaconda3/envs/torch/lib/python3.10/site-packages/transformers/trainer.py:2216 in │
│ _inner_training_loop                                                                             │
│                                                                                                  │
│   2213 │   │   │   │   │   self.control = self.callback_handler.on_step_begin(args, self.state,  │
│   2214 │   │   │   │                                                                             │
│   2215 │   │   │   │   with self.accelerator.accumulate(model):                                  │
│ ❱ 2216 │   │   │   │   │   tr_loss_step = self.training_step(model, inputs)                      │
│   2217 │   │   │   │                                                                             │
│   2218 │   │   │   │   if (                                                                      │
│   2219 │   │   │   │   │   args.logging_nan_inf_filter                                           │
│                                                                                                  │
│ /home/xiongrun/tianchi/finetune/finetune_demo/finetune.py:70 in training_step                    │
│                                                                                                  │
│    67 │   │                                                                                      │
│    68 │   │   if self.args.n_gpu > 1:                                                            │
│    69 │   │   │   loss = loss.mean()                                                             │
│ ❱  70 │   │   self.accelerator.backward(loss)                                                    │
│    71 │   │   detached_loss = loss.detach() / self.args.gradient_accumulation_steps              │
│    72 │   │   del inputs                                                                         │
│    73 │   │   torch.cuda.empty_cache()                                                           │
│                                                                                                  │
│ /home/xiongrun/anaconda3/envs/torch/lib/python3.10/site-packages/accelerate/accelerator.py:2013  │
│ in backward                                                                                      │
│                                                                                                  │
│   2010 │   │   elif self.scaler is not None:                                                     │
│   2011 │   │   │   self.scaler.scale(loss).backward(**kwargs)                                    │
│   2012 │   │   else:                                                                             │
│ ❱ 2013 │   │   │   loss.backward(**kwargs)                                                       │
│   2014 │                                                                                         │
│   2015 │   def set_trigger(self):                                                                │
│   2016 │   │   """                                                                               │
│                                                                                                  │
│ /home/xiongrun/anaconda3/envs/torch/lib/python3.10/site-packages/torch/_tensor.py:525 in         │
│ backward                                                                                         │
│                                                                                                  │
│    522 │   │   │   │   create_graph=create_graph,                                                │
│    523 │   │   │   │   inputs=inputs,                                                            │
│    524 │   │   │   )                                                                             │
│ ❱  525 │   │   torch.autograd.backward(                                                          │
│    526 │   │   │   self, gradient, retain_graph, create_graph, inputs=inputs                     │
│    527 │   │   )                                                                                 │
│    528                                                                                           │
│                                                                                                  │
│ /home/xiongrun/anaconda3/envs/torch/lib/python3.10/site-packages/torch/autograd/__init__.py:267  │
│ in backward                                                                                      │
│                                                                                                  │
│   264 │   # The reason we repeat the same comment below is that                                  │
│   265 │   # some Python versions print out the first line of a multi-line function               │
│   266 │   # calls in the traceback and some print out the last line                              │
│ ❱ 267 │   _engine_run_backward(                                                                  │
│   268 │   │   tensors,                                                                           │
│   269 │   │   grad_tensors_,                                                                     │
│   270 │   │   retain_graph,                                                                      │
│                                                                                                  │
│ /home/xiongrun/anaconda3/envs/torch/lib/python3.10/site-packages/torch/autograd/graph.py:744 in  │
│ _engine_run_backward                                                                             │
│                                                                                                  │
│   741 │   if attach_logging_hooks:                                                               │
│   742 │   │   unregister_hooks = _register_logging_hooks_on_whole_graph(t_outputs)               │
│   743 │   try:                                                                                   │
│ ❱ 744 │   │   return Variable._execution_engine.run_backward(  # Calls into the C++ engine to    │
│   745 │   │   │   t_outputs, *args, **kwargs                                                     │
│   746 │   │   )  # Calls into the C++ engine to run the backward pass                            │
│   747 │   finally:                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OutOfMemoryError: CUDA out of memory. Tried to allocate 214.00 MiB. GPU
  0%|                                                                                         | 0/3000 [00:05<?, ?it/s]

### Expected behavior / 期待表现

解决这个bug，因为我在两台电脑上执行都是这样的

**Comment by zRzRzRzRzRzRzR** [comment]
transformers 下降到4.40.2 然后你尝试把max token 降低到 512 512 吧， 1024 1024可能瞬间不够，此外，多卡启动不是这么运行的，建议用ds zero 3 readme中有说明

**Comment by ATIpiu** [comment]
> transformers 下降到4.40.2 然后你尝试把max token 降低到 512 512 吧， 1024 1024可能瞬间不够，此外，多卡启动不是这么运行的，建议用ds zero 3 readme中有说明
我不是要用多卡去微调，我用单卡微调，但是第二章卡的GPU也被占满了，然后您刚刚的方法测试过，也还是报错
(torch) xiongrun@serverssg:~/tianchi/finetune/finetune_demo$ python finetune.py  data/  THUDM/glm-4-9b-chat  configs/lora.yaml
/home/xiongrun/anaconda3/envs/torch/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.55it/s]
trainable params: 2,785,280 || all params: 9,402,736,640 || trainable%: 0.02962201438410169
train_dataset: Dataset({
    features: ['input_ids', 'labels'],
    num_rows: 4
})
val_dataset: Dataset({
    features: ['input_ids', 'output_ids'],
    num_rows: 4
})
test_dataset: Dataset({
    features: ['input_ids', 'output_ids'],
    num_rows: 4
})
max_steps is given, it will override any value given in num_train_epochs
***** Running training *****
  Num examples = 4
  Num Epochs = 1,500
  Instantaneous batch size per device = 1
  Training with DataParallel so batch size has been adjusted to: 2
  Total train batch size (w. parallel, distributed & accumulation) = 2
  Gradient Accumulation steps = 1
  Total optimization steps = 3,000
  Number of trainable parameters = 2,785,280
  0%|                                                                                         | 0/3000 [00:00<?, ?it/s]/home/xiongrun/anaconda3/envs/torch/lib/python3.10/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/xiongrun/tianchi/finetune/finetune_demo/finetune.py:437 in main                            │
│                                                                                                  │
│   434 │   )                                                                                      │
│   435 │                                                                                          │
│   436 │   if auto_resume_from_checkpoint.upper() == "" or auto_resume_from_checkpoint is None:   │
│ ❱ 437 │   │   trainer.train()                                                                    │
│   438 │   else:                                                                                  │
│   439 │   │   output_dir = ft_config.training_args.output_dir                                    │
│   440 │   │   dirlist = os.listdir(output_dir)                                                   │
│                                                                                                  │
│ /home/xiongrun/anaconda3/envs/torch/lib/python3.10/site-packages/transformers/trainer.py:1859 in │
│ train                                                                                            │
│                                                                                                  │
│   1856 │   │   │   finally:                                                                      │
│   1857 │   │   │   │   hf_hub_utils.enable_progress_bars()                                       │
│   1858 │   │   else:                                                                             │
│ ❱ 1859 │   │   │   return inner_training_loop(                                                   │
│   1860 │   │   │   │   args=args,                                                                │
│   1861 │   │   │   │   resume_from_checkpoint=resume_from_checkpoint,                            │
│   1862 │   │   │   │   trial=trial,                                                              │
│                                                                                                  │
│ /home/xiongrun/anaconda3/envs/torch/lib/python3.10/site-packages/transformers/trainer.py:2203 in │
│ _inner_training_loop                                                                             │
│                                                                                                  │
│   2200 │   │   │   │   │   self.control = self.callback_handler.on_step_begin(args, self.state,  │
│   2201 │   │   │   │                                                                             │
│   2202 │   │   │   │   with self.accelerator.accumulate(model):                                  │
│ ❱ 2203 │   │   │   │   │   tr_loss_step = self.training_step(model, inputs)                      │
│   2204 │   │   │   │                                                                             │
│   2205 │   │   │   │   if (                                                                      │
│   2206 │   │   │   │   │   args.logging_nan_inf_filter                                           │
│                                                                                                  │
│ /home/xiongrun/tianchi/finetune/finetune_demo/finetune.py:70 in training_step                    │
│                                                                                                  │
│    67 │   │                                                                                      │
│    68 │   │   if self.args.n_gpu > 1:                                                            │
│    69 │   │   │   loss = loss.mean()                                                             │
│ ❱  70 │   │   self.accelerator.backward(loss)                                                    │
│    71 │   │   detached_loss = loss.detach() / self.args.gradient_accumulation_steps              │
│    72 │   │   del inputs                                                                         │
│    73 │   │   torch.cuda.empty_cache()                                                           │
│                                                                                                  │
│ /home/xiongrun/anaconda3/envs/torch/lib/python3.10/site-packages/accelerate/accelerator.py:2013  │
│ in backward                                                                                      │
│                                                                                                  │
│   2010 │   │   elif self.scaler is not None:                                                     │
│   2011 │   │   │   self.scaler.scale(loss).backward(**kwargs)                                    │
│   2012 │   │   else:                                                                             │
│ ❱ 2013 │   │   │   loss.backward(**kwargs)                                                       │
│   2014 │                                                                                         │
│   2015 │   def set_trigger(self):                                                                │
│   2016 │   │   """                                                                               │
│                                                                                                  │
│ /home/xiongrun/anaconda3/envs/torch/lib/python3.10/site-packages/torch/_tensor.py:492 in         │
│ backward                                                                                         │
│                                                                                                  │
│    489 │   │   │   │   create_graph=create_graph,                                                │
│    490 │   │   │   │   inputs=inputs,                                                            │
│    491 │   │   │   )                                                                             │
│ ❱  492 │   │   torch.autograd.backward(                                                          │
│    493 │   │   │   self, gradient, retain_graph, create_graph, inputs=inputs                     │
│    494 │   │   )                                                                                 │
│    495                                                                                           │
│                                                                                                  │
│ /home/xiongrun/anaconda3/envs/torch/lib/python3.10/site-packages/torch/autograd/__init__.py:251  │
│ in backward                                                                                      │
│                                                                                                  │
│   248 │   # The reason we repeat the same comment below is that                                  │
│   249 │   # some Python versions print out the first line of a multi-line function               │
│   250 │   # calls in the traceback and some print out the last line                              │
│ ❱ 251 │   Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the bac   │
│   252 │   │   tensors,                                                                           │
│   253 │   │   grad_tensors_,                                                                     │
│   254 │   │   retain_graph,                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OutOfMemoryError: CUDA out of memory. Tried to allocate 214.00 MiB. GPU 0 has a total capacty of 23.68 GiB of which
87.19 MiB is free. Including non-PyTorch memory, this process has 23.43 GiB memory in use. Of the allocated memory
22.98 GiB is allocated by PyTorch, and 66.98 MiB is reserved by PyTorch but unallocated. If reserved but unallocated
memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and
PYTORCH_CUDA_ALLOC_CONF

**Comment by elesun2018** [comment]
0821更新代码和更新模型文件没有用，仍然OutOfMemoryError
请问finetune最低显存多少？应该如何配置？这个问题还应该从何排查（环境版本？显存爆处的代码）

**Comment by elesun2018** [comment]
![image](https://github.com/user-attachments/assets/bbe54b91-5f6d-4d19-9730-45ff44a3fe63)
请问可否使用Deepspeed 使用2*A100将75G显存的训练参数分配到两张卡上面，再使用Zero3进行进一步显存优化。是否可行？
有没有支持Deepspeed Zero3的finetune_vision.py

**Comment by elesun2018** [comment]
finetune_vision.py修改后支持zero23优化，但是训练太慢了
新代码finetune_vision.py冻结vit后训练显存只需28G-35G，就是不知道微调后效果如何。

如果是3090*2可以尝试ds zero3优化
