### ISSUE TITLE
使用A40进行单机单卡方案进行微调时显存爆炸

### ISSUE THREAD

**Issue by NewDingW** [THUDM/GLM-4#324]
我的服务器上有两张A40，我想使用其中一张进行微调，使用了代码中的单机单卡微调方案，但是，当其中一张显卡的显存占用达到大概20G的时候，另一张显卡也会被使用，并且会瞬间使用另一张显卡的20G显存。几秒之后，最开始的显卡显存超过48G，报错，显存占用如下图所示。
![捕获](https://github.com/user-attachments/assets/0dbc970e-fb18-40ea-bba7-ed62bffec4b8)

报错信息如下：
site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '

OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU 

使用的代码和lora.yaml均为原代码配置，只调整了数据和模型的位置信息

**Comment by zRzRzRzRzRzRzR** [comment]
CUDA VISIABLE设定上就行了

**Comment by elesun2018** [comment]
GLM-4.0731.gitraw
           writer_batch_size=1
            batch_size=1
GLM-4/finetune_demo# CUDA_VISIBLE_DEVICES=1 python finetune_vision.py
还是报错
OutOfMemoryError: CUDA out of memory. Tried to allocate 1.22 GiB (GPU 0; 47.54 GiB total capacity; 44.83 GiB already allocated; 1.07 GiB free;
46.13 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See
documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by elesun2018** [comment]
0821更新代码和更新模型文件没有用，仍然OutOfMemoryError
请问finetune最低显存多少？应该如何配置？这个问题还应该从何排查（环境版本？显存爆处的代码）

**Comment by NewDingW** [comment]
> 0821更新代码和更新模型文件没有用，仍然OutOfMemoryError 请问finetune最低显存多少？应该如何配置？这个问题还应该从何排查（环境版本？显存爆处的代码）

我当初直接改了环境变量　export CUDA_VISIABLE_DEVICES = 0

A40单卡微调要30多G的显存

**Comment by elesun2018** [comment]
你说的是GLM-4-9B-chat吧
![image](https://github.com/user-attachments/assets/96fe026d-c3a1-42a6-a855-b8ff24d2e64e)
请问可否使用Deepspeed 使用2*A100将75G显存的训练参数分配到两张卡上面，再使用Zero3进行进一步显存优化。是否可行？
有没有支持Deepspeed Zero3的finetune_vision.py

**Comment by elesun2018** [comment]
finetune_vision.py修改后支持zero23优化，但是训练太慢了
新代码finetune_vision.py冻结vit后训练显存只需28G-35G，就是不知道微调后效果如何。
