### ISSUE TITLE
GLM-4V Finetune Dataloader Out of Memory

### ISSUE THREAD

**Issue by KaidiKang** [THUDM/GLM-4#325]
想请问一下我 226*72 的图片单轮对话的数据集加载报 out of memory, 之后按照 #283 最后提到的改缓存地址发现处理5000条的时候cache就已经占用70G了, 我的数据集一共有12万条左右, 这个占用正常吗? 改 lazyloader 可行吗?
另外 Readme 里提到 lora 微调 4V 模型需要 75G 显卡内存, 这个是可多卡拆分的吗? 我用多张 32G 的 V100 可以做到微调吗? 我遇到了和 #281 一样的问题, 使用小数据集也报 CUDA out of memory, 所以想问一下. 
感谢回复.

**Comment by zRzRzRzRzRzRzR** [comment]
不能拆分，一张显卡要75G

**Comment by KaidiKang** [comment]
> 不能拆分，一张显卡要75G

那就是官方脚本无法在 V100 上微调 4V 模型了是吗

**Comment by zRzRzRzRzRzRzR** [comment]
嗯，而且也不支持float16啊

**Comment by kandada** [comment]
> 不能拆分，一张显卡要75G

关于不支持拆分，是这个代码不支持还是这个模型不支持？
