### ISSUE TITLE
微调后，模型不能正常回复

### ISSUE THREAD

**Issue by RyanOvO** [THUDM/GLM-4#326]
基座模型：GLM4-9B

微调框架：LlamaFactory

微调配置：
![image](https://github.com/user-attachments/assets/be343688-e6e1-42cb-941f-f02fe1758b68)

推理命令：`llamafactory-cli chat emo_glm4_lora_sft_inference.yaml`

问题现象：
![image](https://github.com/user-attachments/assets/9ce20a5b-7877-43b8-8668-6ce96eeaa16d)

问题排查：
1. 换成等长的文本是可以正常回复的；不是长度问题。
2. 去掉 '#'  等符号，偶发性可以正常回复，大多数时候又是一样的问题现象——只换行然后内容空白。
![image](https://github.com/user-attachments/assets/3255f4f5-4fde-4ffa-bf87-e5cc930ff08c)
![image](https://github.com/user-attachments/assets/4cec2be2-41ed-4b10-b352-a17d163f33ce)

期望方案：
解决这个问题，正常回复内容。

**Comment by zRzRzRzRzRzRzR** [comment]
或许应该在llama factory提一个issue。这种问题没办法debug呀

**Comment by ChenZiHong-Gavin** [comment]
是不是因为template的问题啊

**Comment by zRzRzRzRzRzRzR** [comment]
有可能，我们官方的脚本template都是适配好的，但是这个框架应该也有template，你可以验证一下

**Comment by RyanOvO** [comment]
检查了template，对的上，没有头绪；
输入短一点是可以的，但是带有markdown的语法而且过长的话就会出现这种情况。
LlamaFactory那边也没有回复

**Comment by zRzRzRzRzRzRzR** [comment]
<img width="116" alt="image" src="https://github.com/user-attachments/assets/30fd2c2a-4abb-418c-8935-b5124dbc5ce6">
把这个设置长一点呢

**Comment by RyanOvO** [comment]
好的，我后面试试，重新训练
