### ISSUE TITLE
微调报错  local variable 'output_prompt' referenced before assignment

### ISSUE THREAD

**Issue by reinforceli** [THUDM/GLM-4#327]
### System Info / 系統信息

![image](https://github.com/user-attachments/assets/4801d371-42b0-42be-a53d-909dfb7ff4fc)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

执行单卡微调命令

### Expected behavior / 期待表现

这是什么问题，是数据集有问题吗？

**Comment by zRzRzRzRzRzRzR** [comment]
你这代码是啥，output_prompt我代码没有这个参数啊
