### ISSUE TITLE
glm-4-9b-chat在H20显卡推理报错

### ISSUE THREAD

**Issue by sybest1259** [THUDM/GLM-4#328]
### System Info / 系統信息

cuda12.2
python3.10.12
tranformers==4.42.4
显卡H20
![nvidia](https://github.com/user-attachments/assets/a943ac40-afc0-4854-94f4-42b0dab0488b)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

device = "cuda"

tokenizer = AutoTokenizer.from_pretrained("/opt/glm-4-9b-chat",trust_remote_code=True)

query = "你好"

inputs = tokenizer.apply_chat_template([{"role": "user", "content": query}],
                                       add_generation_prompt=True,
                                       tokenize=True,
                                       return_tensors="pt",
                                       return_dict=True
                                       )

inputs = inputs.to(device)
model = AutoModelForCausalLM.from_pretrained(
    "/opt/glm-4-9b-chat",
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True
).to(device).eval()

gen_kwargs = {"max_length": 2500, "do_sample": True, "top_k": 1}
with torch.no_grad():
    outputs = model.generate(**inputs, **gen_kwargs)
    outputs = outputs[:, inputs['input_ids'].shape[1]:]
    print(tokenizer.decode(outputs[0], skip_special_tokens=True))

**运行官方提供的demo报错：
Floating point exception (core dumped)**

### Expected behavior / 期待表现

在H20显卡上正常运行推理代码

**Comment by zRzRzRzRzRzRzR** [comment]
low_cpu_mem_usage=True, 删掉试试？然后先指定一张卡 cuda visiable

**Comment by LianleLucifer** [comment]
*** SIGFPE received at time=1729833777 on cpu 116 ***
PC: @     0x7ff890b9bc59  (unknown)  (unknown)
    @     0x7ff92fddf140  (unknown)  (unknown)
[2024-10-25 13:22:57,456 E 3439 16755] logging.cc:440: *** SIGFPE received at time=1729833777 on cpu 116 ***
[2024-10-25 13:22:57,456 E 3439 16755] logging.cc:440: PC: @     0x7ff890b9bc59  (unknown)  (unknown)
[2024-10-25 13:22:57,456 E 3439 16755] logging.cc:440:     @     0x7ff92fddf140  (unknown)  (unknown)
Fatal Python error: Floating point exception我在H20上面部署，还是出现这个异常；
我将  "torch_dtype"设置为float32，float16，bfloat16都不行，辛苦看个问题
