### ISSUE TITLE
AsyncLLMEngine.generate() got an unexpected keyword argument 'inputs'

### ISSUE THREAD

**Issue by zky001** [THUDM/GLM-4#33]
line  195, in generate_stream_glm4
![image](https://github.com/THUDM/GLM-4/assets/9131265/7c19e275-c83e-46cd-a5b7-7017dcc1d956)

**Comment by turkeymz** [comment]
How did you fix it？

**Comment by simonwei97** [comment]
@turkeymz you should upgrade you vLLM version as `v0.4.3`

**Comment by simonwei97** [comment]
> @turkeymz you should upgrade you vLLM version as `v0.4.3`

For v0.4.3 
https://github.com/vllm-project/vllm/blob/v0.4.3/vllm/engine/async_llm_engine.py#L594-L600

For v0.4.3
https://github.com/vllm-project/vllm/blob/v0.4.2/vllm/engine/async_llm_engine.py#L574-L582

**Comment by turkeymz** [comment]
> > @turkeymz you should upgrade you vLLM version as `v0.4.3`
> 
> For v0.4.3 https://github.com/vllm-project/vllm/blob/v0.4.3/vllm/engine/async_llm_engine.py#L594-L600
> 
> For v0.4.3 https://github.com/vllm-project/vllm/blob/v0.4.2/vllm/engine/async_llm_engine.py#L574-L582

thanks so much
