### ISSUE TITLE
openai_api_server.py原生启动，流式请求返回异常

### ISSUE THREAD

**Issue by starage2020** [THUDM/GLM-4#330]
用glm4版本openai_api_server.py跑起来后，openai_api_request.py中例子改为stream为True时，返回异常，各位有遇到这个情况吗？
{"model":"glm-4","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":"","function_call":null},"finish_reason":null,"index":0}],"created":1720778244}
None

**Comment by ghohoj** [comment]
同，在
```
if output:
    return EventSourceResponse(predict_stream_generator, media_type="text/event-stream")
logger.debug(f"First result output：\n{output}")
```
 处中断了，不知道发生了什么，

**Comment by zRzRzRzRzRzRzR** [comment]
你打一个断电在if 的位置看看有没有output，没有出现在这个地方报错的情况

**Comment by ghohoj** [comment]
如果你要重现这个bug，你可以加入一些tool，然后问一些与tool完全无关的问题（例如tool选择询问天气，但你的问题是询问一些数学问题），这个情况下本应该跳过工具直接回答问题，但实际上会直接返回一个空的content

**Comment by zRzRzRzRzRzRzR** [comment]
好像是有可能的，你能提一个PR吗，感谢

**Comment by wll0307** [comment]
我有一个问题就是python openai_api_server.py运行里面当时有设计并发能力吗？我在测试的时候发现2人以上推理其中一个会很慢

**Comment by lwj2001** [comment]
似乎vllm有并发能力？（不确定）

**Comment by zRzRzRzRzRzRzR** [comment]
写本仓库的时候都没有考虑和设计并发
