### ISSUE TITLE
运行composite_demo进行多轮对话(没用vLLM)，最后显卡内存会爆(Out of memory)

### ISSUE THREAD

**Issue by martinyuan886** [THUDM/GLM-4#331]
### System Info / 系統信息

None

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

None

### Expected behavior / 期待表现

请问有什么优化手段吗？

**Comment by zRzRzRzRzRzRzR** [comment]
很正常吧，因为你的对话越来越长了，readme中，不同长度的对话占用的显存不一样，消息越长，显存消耗越大
