### ISSUE TITLE
对GLM-4v-9B 模型做torch.compile 报错

### ISSUE THREAD

**Issue by danzai-hue** [THUDM/GLM-4#332]
### Feature request  / 功能建议

使用torch.compile报错
File "lib/python3.10/site-packages/torch/_dynamo/variables/constant.py", line 39, in create
    assert not isinstance(value, disallowed_type), reason
AssertionError: Dict types must use ConstDictVariable
在transformers/generation/utils.py中def _sample中添加self=torch.compile(self,dynamic=False,fullgraph=True)
添加位置：
self=torch.compile(self,dynamic=False,fullgraph=True)
        while self._has_unfinished_sequences(this_peer_finished, synced_gpus, device=input_ids.device):
            # prepare model inputs
            model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
尝试规避：直接传入 image_size=1120
后又报错
 File "/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 464, in inner
    raise exc.UserError(
torch._dynamo.exc.UserError: Dynamic control flow is not supported at the moment. Please use functorch.experimental.control_flow.cond to explicitly capture the control flow. For more information about this error, see: https://pytorch.org/docs/main/generated/exportdb/index.html#cond-operands

### Motivation / 动机

对GLM-4v-9b是否可以使能torch.compile

### Your contribution / 您的贡献

使用torch.compile报错
File "lib/python3.10/site-packages/torch/_dynamo/variables/constant.py", line 39, in create
    assert not isinstance(value, disallowed_type), reason
AssertionError: Dict types must use ConstDictVariable

**Comment by zRzRzRzRzRzRzR** [comment]
不支持
