### ISSUE TITLE
Ollama运行GLM-4-9b后乱码

### ISSUE THREAD

**Issue by lalahaohaizi** [THUDM/GLM-4#333]
### System Info / 系統信息

技嘉4060Ti win11 Ollama 0.2.3

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

ollama run glm4:9b
抽取####文字后的服用保健品和服用补品的情况，并将结果输出为如下格式:[{"保健品服用情况":"","补品服用情况":""}]。无法抽取则输出为["抽取内容":"null"]。
####
同前。。父181母154。同前。
![image](https://github.com/user-attachments/assets/3e65bab4-9379-49bc-bfa5-1a5289327ea7)

### Expected behavior / 期待表现

输出完毕后停止，而没有不断输出乱码的字符

**Comment by lalahaohaizi** [comment]
跟modelfile的参数有关系吗
![image](https://github.com/user-attachments/assets/d5545ef5-bace-4832-a232-ef728c74d081)

**Comment by lalahaohaizi** [comment]
跟modelfile的参数有关系吗
![image](https://github.com/user-attachments/assets/a2b9ada1-54c4-4066-83a6-077b2cfeb873)

**Comment by caoyc** [comment]
win11 ollama 0.2.5

问题同上

![微信图片_20240717144215](https://github.com/user-attachments/assets/9f8e1378-119b-40bc-b58d-a81b174514cb)

**Comment by zRzRzRzRzRzRzR** [comment]
0.2.3似乎ok，0.2.5有这个bug，我们有同事在复现

**Comment by Iteachyou233** [comment]
ollama问题，升级至0.1.42试试

**Comment by liuchuan01** [comment]
![Screenshot 2024-07-22 at 11 49 48](https://github.com/user-attachments/assets/96fa7b48-eb7e-4733-b54f-a56de282130e)
ollama 0.2.7 
ubuntu 22
3090 * 2
走api调用同样出现了这个问题

**Comment by zRzRzRzRzRzRzR** [comment]
得降到0.2.3

**Comment by liuchuan01** [comment]
> 得降到0.2.3

好，谢谢啦

**Comment by zRzRzRzRzRzRzR** [comment]
最新的我们还在看，好像还有提到fc的问题，不过fc的问题ollama回复说比较难解决

**Comment by Jesean** [comment]
ollama版本0.2.8，返回GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG

**Comment by zRzRzRzRzRzRzR** [comment]
0.2.3之后好像都有，要用0.2.3

**Comment by wukaikailive** [comment]
这些问题都遇到过，基本上重启下又能用一段时间

**Comment by leizhu1989** [comment]
> 0.2.3之后好像都有，要用0.2.3

我拉取的0.2.3 版本ollama镜像，还是遇到这个问题啊

**Comment by lalahaohaizi** [comment]
请问这个问题有解决方案吗，0.2.3版本也是会输出G的，看ollama更新了几个版本没提到这个问题，求助

**Comment by buhiui** [comment]
请问现在有解决吗？

**Comment by zRzRzRzRzRzRzR** [comment]
如果是GPU ，先开启flash-attn

**Comment by leizhu1989** [comment]
> 如果是GPU ，先开启flash-attn

请问是在ollama镜像里开启吗

**Comment by lyh007** [comment]
C:\Users\80260\AppData\Local\Programs\Ollama>ollama start --help
Start ollama

Usage:
  ollama serve [flags]

Aliases:
  serve, start

Flags:
  -h, --help   help for serve

Environment Variables:
      OLLAMA_DEBUG               Show additional debug information (e.g. OLLAMA_DEBUG=1)
      OLLAMA_HOST                IP Address for the ollama server (default 127.0.0.1:11434)
      OLLAMA_KEEP_ALIVE          The duration that models stay loaded in memory (default "5m")
      OLLAMA_MAX_LOADED_MODELS   Maximum number of loaded models per GPU
      OLLAMA_MAX_QUEUE           Maximum number of queued requests
      OLLAMA_MODELS              The path to the models directory
      OLLAMA_NUM_PARALLEL        Maximum number of parallel requests
      OLLAMA_NOPRUNE             Do not prune model blobs on startup
      OLLAMA_ORIGINS             A comma separated list of allowed origins
      OLLAMA_SCHED_SPREAD        Always schedule model across all GPUs
      OLLAMA_TMPDIR              Location for temporary files
      OLLAMA_FLASH_ATTENTION     Enabled flash attention
      OLLAMA_LLM_LIBRARY         Set LLM library to bypass autodetection
@leizhu1989  ollama start 命令启动时加载环境变量，我也遇到了同样的问题，还没有在服务器上测试是否可行

**Comment by leizhu1989** [comment]
@lyh007 谢谢，好像可以解决问题了，目前测试正常
