### ISSUE TITLE
openai_api_server.py 启动后显存占用很大，gpu一直100%

### ISSUE THREAD

**Issue by shadowboxx** [THUDM/GLM-4#335]
### System Info / 系統信息

win11 的 wsl 启动openai_api_server.py ，启动后显存占用很大，gpu一直100%
但是 启动 train_cli_demo.py 和  train_cli_vison_demo.py, 是正常的。

环境： win11， wsl,   3070 16GB, 内存 64GB
Name: transformers Version: 4.42.4
Name: torch  Version: 2.3.0
CUDA  12.2

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

wsl 中启动  basic_demo/openai_api_server.py 
现象： gpu 一直100%，

### Expected behavior / 期待表现

估计是用了vllm但没有量化部署，希望有量化启动参数， 或者用类似chatglm3 的openai_api_server的后端服务代码

**Comment by zRzRzRzRzRzRzR** [comment]
vLLM不支持量化呀

**Comment by shadowboxx** [comment]
> vLLM不支持量化呀

那大神能不能搞个类似 chatglm3 的api_server 服务呀，模型加载方式与cli_demo类似，可以量化的那种，我们这种非专业显卡玩不起来呀
