### ISSUE TITLE
您好，请问如何将微调后的模型输出文件夹checkpoint传入AutoModel. from_pretrained (MODEL_PATH）以供调用呢

### ISSUE THREAD

**Issue by LeeGitHub1** [THUDM/GLM-4#336]
![截屏2024-07-14 11 50 46](https://github.com/user-attachments/assets/89738de3-1e15-464c-b342-2bedfa8377d5)

**Comment by zRzRzRzRzRzRzR** [comment]
没办法，output文件是一个adapter
如何载入看inference.py
