### ISSUE TITLE
希望能够加入ITREX或者IPEX-LLM对composite-demo的demo类型

### ISSUE THREAD

**Issue by TriDefender** [THUDM/GLM-4#337]
### Feature request  / 功能建议

希望能够根据[相关参考](https://github.com/intel-analytics/ipex-llm/blob/019da6c0ab83c659c191d7f2d454d7d7abc48089/docs/mddocs/README.md)增加composite-demo对英特尔设备的支持，已知该工具支持VLLM和transformers类的推理加速。

### Motivation / 动机

部分推理环境不一定有一个cuda设备用于推理，使用对应工具可以加速本地的推理速度

### Your contribution / 您的贡献

*

**Comment by zRzRzRzRzRzRzR** [comment]
ITREX是用transformers这套呀，根据cli 的demo换一个模型载入方式就行了。
