### ISSUE TITLE
请问GLM-4是否支持视觉定位（visual grounding）能力？用于目标的带有推理的检测

### ISSUE THREAD

**Issue by sunmonk** [THUDM/GLM-4#338]
### Feature request  / 功能建议

添加视觉定位（visual grounding）能力，用于目标的带有推理的检测。 输出推理后物体的框的坐标。

### Motivation / 动机

视觉定位能力是一个很有用的能力。

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
这个版本没有
