### ISSUE TITLE
Transformers4.42.3版本，使用opencompass评估，推理阶段报错

### ISSUE THREAD

**Issue by keepgoingwang** [THUDM/GLM-4#339]
### System Info / 系統信息

报错信息如下：
File "xxx/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py", line 891, in forward
full_attention_mask = self.get_masks(input_ids, past_key_values, padding_mask=attention_mask)
File "xxx/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py", line 783, in get_masks
past_length = past_key_values[0][0].shape[2]
AttributeError: 'str' object has no attribute 'shape'
这是否是因为和transformers版本冲突导致呢？

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

opencompass
python run.py \
--datasets FewCLUE_chid_gen CLUE_afqmc_gen \
--hf-path /xxx/Models/chatglm4-9b-chat \
--model-kwargs device_map='auto' trust_remote_code=True torch_dtype="torch.bfloat16" \
--tokenizer-kwargs padding_side='left' truncation_side='left' trust_remote_code=True \
--max-out-len 100 \
--max-seq-len 2048 \
--hf-num-gpus 1 \
--batch-size 8 \
--work-dir ./outputs/chatglm4-9b-chat

### Expected behavior / 期待表现

help me!!!

**Comment by zRzRzRzRzRzRzR** [comment]
降级到4.40
