### ISSUE TITLE
composite_demo   All Tools模式， 支持int4吗？  要是支持，如何修改呢？  谢谢

### ISSUE THREAD

**Issue by triumph** [THUDM/GLM-4#34]
### Feature request  / 功能建议

composite_demo   All Tools模式， 支持int4吗？  要是支持，如何修改呢？  谢谢

### Motivation / 动机

composite_demo   All Tools模式， 支持int4吗？  要是支持，如何修改呢？  谢谢

### Your contribution / 您的贡献

composite_demo   All Tools模式， 支持int4吗？  要是支持，如何修改呢？  谢谢

**Comment by galena01** [comment]
https://github.com/THUDM/GLM-4/blob/0423d7ca6dd736972f11c64e30cc2ee6fc8279b5/composite_demo/src/clients/hf.py#L21C1-L26C17
这个函数里传一个"load_in_4bit=True"试一下？

**Comment by swordfar** [comment]
> https://github.com/THUDM/GLM-4/blob/0423d7ca6dd736972f11c64e30cc2ee6fc8279b5/composite_demo/src/clients/hf.py#L21C1-L26C17 这个函数里传一个"load_in_4bit=True"试一下？

OK的，跑起来了
