### ISSUE TITLE
微调可正常完成，但训练的数据不生效

### ISSUE THREAD

**Issue by reinforceli** [THUDM/GLM-4#344]
### System Info / 系統信息

torch==2.3.1+cu121,python3.10,windows10 ,A800，单卡训练，transformers==4.41.2

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

微调指令：
set CUDA_VISIBLE_DEVICES=1 & python finetune.py  data\fzd  D:\xinferencemodel\cache\glm4-chat-pytorch-9b  configs/lora.yaml

lora.yaml 配置文件：

data_config:
  train_file: train.jsonl
  val_file: dev.jsonl
  test_file: dev.jsonl
  num_proc: 1
max_input_length: 2048
max_output_length: 2048
training_args:
  # see `transformers.Seq2SeqTrainingArguments`
  output_dir: ./output
  max_steps: 3000
  # needed to be fit for the dataset
  learning_rate: 5e-4
  # settings for data loading
  per_device_train_batch_size: 1
  dataloader_num_workers: 0
  remove_unused_columns: false
  # settings for saving checkpoints
  save_strategy: steps
  save_steps: 1000
  # settings for logging
  log_level: info
  logging_strategy: steps
  logging_steps: 100
  # settings for evaluation
  per_device_eval_batch_size: 1
  evaluation_strategy: steps
  eval_steps: 1000
  # settings for optimizer
  adam_epsilon: 1e-6
  # uncomment the following line to detect nan or inf values
  #debug: underflow_overflow
  predict_with_generate: true
  # see `transformers.GenerationConfig`
  generation_config:
    max_new_tokens: 2048
  # set your absolute deepspeed path here
    deepspeed: configs/ds_zero_3.json
peft_config:
  peft_type: LORA
  task_type: CAUSAL_LM
  r: 8
  lora_alpha: 32
  lora_dropout: 0.1
  target_modules: ["query_key_value"]

###################
训练日志：
![image](https://github.com/user-attachments/assets/1463254a-794b-4bd1-b17f-c2b30e86a699)
![image](https://github.com/user-attachments/assets/9e2bb416-bc3b-4164-94c0-53e4de0debdc)
![image](https://github.com/user-attachments/assets/8aad0772-4905-4caf-8ee5-443ef6c87b0b)
测试微调，没按训练数据回答
![image](https://github.com/user-attachments/assets/cd5c54de-eeb1-496d-a6c2-a96e0b67599b)

### Expected behavior / 期待表现

模型能按训练的数据回答

**Comment by zRzRzRzRzRzRzR** [comment]
0.0 的loss，这个就是没调啊，你是不是用了bf16

**Comment by zRzRzRzRzRzRzR** [comment]
你的卡得支持BF16，一般是30系以上的卡，并且你的长度小于我们配置的512的长度

**Comment by reinforceli** [comment]
是A800显卡，这长度小是说数据集少了吗？

**Comment by zRzRzRzRzRzRzR** [comment]
数据集太长了，超过了512个长度吧，被截断了导致没有label

**Comment by MiPeng666** [comment]
> 是A800显卡，这长度小是说数据集少了吗？

你的问题解决了吗？
