### ISSUE TITLE
About also releasing source model code here

### ISSUE THREAD

**Issue by Infinity12306** [THUDM/GLM-4#345]
### Feature request  / 功能建议

It seems that the source code for model is not included in this repository. However, I manage to find them in the [huggingface repository](https://huggingface.co/THUDM/glm-4-9b-chat/blob/main/modeling_chatglm.py), could you please also integrate these code in this repo so that it is more convenient to learn from your wonderful work.

Best regards.

### Motivation / 动机

Mentioned above

### Your contribution / 您的贡献

None

**Comment by zRzRzRzRzRzRzR** [comment]
收到你的建议，我们之后合并到transformers库后会同步一份到这里，hf的代码就不用放了（使用transformers直接加载）

**Comment by Infinity12306** [comment]
明白了，就是以后合并到transformers库后需要查看源代码直接在transformers库里面查看，这个仓库不计划把源代码放进来是吗

**Comment by zRzRzRzRzRzRzR** [comment]
对，我正在做这个事情，你可以在transformers库看到我们的pr，还在做

**Comment by Infinity12306** [comment]
感谢，辛苦了！
