### ISSUE TITLE
请问在调用微调后的模型时第一个和第二个model_dir为什么和第三个不一样，第三个是本地的模型路径，以及这样调用模型按理说就没有用到微调后的模型权重？

### ISSUE THREAD

**Issue by LeeGitHub1** [THUDM/GLM-4#348]
![截屏2024-07-16 11 48 40](https://github.com/user-attachments/assets/f6096b93-e9af-49a9-94be-ac7bf1539a5b)
![截屏2024-07-16 11 49 04](https://github.com/user-attachments/assets/a50dad7d-9691-4a2d-babc-cd7b2335cb6b)

**Comment by zRzRzRzRzRzRzR** [comment]
先加载原始的模型，在用peft挂微调的模型，所以原始路径和微调路径都要用到

**Comment by LeeGitHub1** [comment]
> 先加载原始的模型，在用peft挂微调的模型，所以原始路径和微调路径都要用到

请问是内部封装的吗，这一整个加载模型的过程

**Comment by zRzRzRzRzRzRzR** [comment]
不是，是外部挂的，你看peft load ，我们没做封装和合并

**Comment by LeeGitHub1** [comment]
> 不是，是外部挂的，你看peft load ，我们没做封装和合并

好的，请问咱们有benchmark可以来评测基础模型和微调模型的教程吗

**Comment by zRzRzRzRzRzRzR** [comment]
微调的模型评测通用的bench意义不大吧，而且一般来说，各大benchmark都有自己的跑分脚本，都是开源的，去对应跑分榜单github看就行

**Comment by LeeGitHub1** [comment]
> 微调的模型评测通用的bench意义不大吧，而且一般来说，各大benchmark都有自己的跑分脚本，都是开源的，去对应跑分榜单github看就行

好的谢谢您
