### ISSUE TITLE
tokenization_chatglm.py报错

### ISSUE THREAD

**Issue by Ksuriuri** [THUDM/GLM-4#35]
### System Info / 系統信息

tokenizer.decode报错：`TypeError: token should only be of type types or str`

原因是glm4的词表中的key是以bytes类型存储，而bytes类型在transformers的_decode函数中被遍历会变成int类型。

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

运行如下代码即可复现该错误：
```
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("ZhipuAI/glm-4-9b-chat", trust_remote_code=True)
new_str = tokenizer.decode(198)
print(new_str)
```

### Expected behavior / 期待表现

对`tokenization_chatglm.py`中的`convert_tokens_to_string`函数作如下修改即可解决该问题：
```
def convert_tokens_to_string(self, tokens: List[Union[bytes, str, int]]) -> str:
    """
    Converts a sequence of tokens in a single string.
    """
    text = ""
    temp = b""
    for t in tokens:
        if isinstance(t, int):
            t = chr(t)
        if isinstance(t, str):
            if temp:
                text += temp.decode("utf-8", errors="replace")
                temp = b""
            text += t
        elif isinstance(t, bytes):
            temp += t
        else:
            raise TypeError("token should only be of type int, bytes or str")
    if temp:
        text += temp.decode("utf-8", errors="replace")
    return text
```

已向huggingface的glm-4-9b-chat及其1m版本的模型仓库提交PR，希望采纳，感谢开源！

**Comment by JerryChen1119** [comment]
函数参数少了个self

**Comment by zRzRzRzRzRzRzR** [comment]
能发一下对应的pr链接吗，太多了PR我不确定有没有处理到

**Comment by Ksuriuri** [comment]
> 能发一下对应的pr链接吗，太多了PR我不确定有没有处理到

https://huggingface.co/THUDM/glm-4-9b-chat-1m/discussions/3/files
https://huggingface.co/THUDM/glm-4-9b-chat/discussions/7
两边都是一样的

**Comment by zRzRzRzRzRzRzR** [comment]
合并

**Comment by HaohzW** [comment]
这个问题没有在modelscope中更新

**Comment by MrKyle0315** [comment]
我修改了还是没办法解决，还是会报错怎么解决？
