### ISSUE TITLE
glm-4v 多卡推理，可以实现吗

### ISSUE THREAD

**Issue by wuxiaolianggit** [THUDM/GLM-4#350]
### System Info / 系統信息

4卡v100，  unbutnu 20.04

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

glm-4v 多卡推理一直出现Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cuda:3!，请问大佬可以解决吗 @wwewwt @Sengxian @davidlvxin @qq332982511 @

### Expected behavior / 期待表现

glm-4v 多卡推理一直出现Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cuda:3!，请问大佬可以解决吗 @wwewwt @Sengxian @davidlvxin @qq332982511 @

**Comment by zRzRzRzRzRzRzR** [comment]
应该早就实现了吧
<img width="711" alt="image" src="https://github.com/user-attachments/assets/cf3609e1-d97b-415d-ab23-628b27700924">
更新一下transformers库和最新的hf文件

**Comment by wuxiaolianggit** [comment]
我hf文件是昨天下载的，transformers是4.42.3，大佬你的配置是多少啊，我和你保持一致试一下 @zRzRzRzRzRzRzR

**Comment by zRzRzRzRzRzRzR** [comment]
transformers 4.42.4
文件是昨天晚上更新的

**Comment by wuxiaolianggit** [comment]
还是不行，一直报错

    return self._call_impl(*args, **kwargs)
  File "/home/duolun/.conda/envs/transgpt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/duolun/.cache/huggingface/modules/transformers_modules/visual.py", line 109, in forward
    output = mlp_input + mlp_output
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cuda:3!
@zRzRzRzRzRzRzR ，大佬，您有遇到过这个问题吗

**Comment by cjq214** [comment]
一样的情况，多卡推理的时候也是一样的报错。
6张  2080ti 
ubuntu  22.04.2

请问有解决了吗
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/visual.py", line 109, in forward
    output = mlp_input + mlp_output
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:4 and cuda:5!

![image](https://github.com/user-attachments/assets/2e7d6374-8bb2-4051-b817-323dc265ad05)

**Comment by zRzRzRzRzRzRzR** [comment]
6张出错是正常的了吧，跟cogvlm2一样，有一些部分是不能拆开的，拆开应该会报错，我们只测了2卡，每张卡应该也要至少16G显存

**Comment by cjq214** [comment]
您好！我是陈锦泉。您的邮件我已收到，谢谢！祝您工作顺利！

**Comment by ye4241** [comment]
额，我让 Github Copilot 帮我修复好了，也不知道对不对的：

visual.py 的 95 行
```python
class TransformerLayer(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.input_layernorm = LayerNorm(config.hidden_size, eps=config.layer_norm_eps)
        self.attention = Attention(config)
        self.mlp = MLP(config)
        self.post_attention_layernorm = LayerNorm(config.hidden_size, eps=config.layer_norm_eps)

    def forward(self, hidden_states):
        attention_input = hidden_states
        attention_output = self.input_layernorm(self.attention(attention_input))
        hidden_states = attention_input + attention_output
        mlp_input = hidden_states
        mlp_output = self.post_attention_layernorm(self.mlp(mlp_input))
        
        # Ensure mlp_output is on the same device as mlp_input
        mlp_output = mlp_output.to(mlp_input.device)
        
        output = mlp_input + mlp_output
        return output
```

159 行

```python
    def forward(self, images: "tensor(B, C, H, W)") -> "tensor(B, L, D)":
        x = self.patch_embedding(images)
        x = self.transformer(x)
        x = x[:, 1:]
    
        b, s, h = x.shape
        grid_size = int(s**0.5)
        x = x.view(b, grid_size, grid_size, h).permute(0, 3, 1, 2)
        x = self.conv(x)
    
        x = x.flatten(2).transpose(1, 2)
        x = self.linear_proj(x)
        
        # Ensure boi and eoi are on the same device as x
        boi = self.boi.expand(x.shape[0], -1, -1).to(x.device)
        eoi = self.eoi.expand(x.shape[0], -1, -1).to(x.device)
        
        x = torch.cat((boi, x, eoi), dim=1)
        x = x / self.scaling_factor
        return x
```

改完现在能用了，4 张 4090 的卡的。

**Comment by wuxiaolianggit** [comment]
大佬牛逼，现在确实可以用了 @ye4241

**Comment by ye4241** [comment]
@wuxiaolianggit 我其实完全啥都没干，就把代码和操错丢给了 Copilot 😅

**Comment by zRzRzRzRzRzRzR** [comment]
你这个能跑通，我试了一下

**Comment by zRzRzRzRzRzRzR** [comment]
已经更新，感谢提出的意见！

**Comment by SongHY-13** [comment]
太酷了

**Comment by blizzardwj** [comment]
mark，后续了解一下是什么问题导致的。
