### ISSUE TITLE
Berkeley Function-Calling Leaderboard结果疑问

### ISSUE THREAD

**Issue by GeniusYx** [THUDM/GLM-4#353]
您好，Berkeley Function-Calling Leaderboard已经更新了GLM4的在工具调用上的表现，这与汇报结果的不一致，请问您们在测试的时候，是否使用了Berkeley Function-Calling Leaderboard官方提供的Prompt？不确定是否是调用方式不一致带来的差异：Chat模型 VS FC（function calling）模型
伯克利官方汇报结果：
![image](https://github.com/user-attachments/assets/1da1bb61-3aea-4648-a956-b4d8da85952b)
THUDM官方汇报结果：
![image](https://github.com/user-attachments/assets/f3208c28-a529-49d3-96fa-7aa5c46f11df)

多谢！

**Comment by lucenzhong** [comment]
GLM的parallel function call实现方式和Berkeley Function-Calling Leaderboard不一致，这是两者存在差异的主要原因。

GLM的parallel function call建模方式为：（每一个function call后面跟着其对应的observation）
```
<|assistant|>
function_call_1
<|observation|>
json.dumps(observation_1, ensure_ascii=False)
<|assistant|>
function_call_2
<|observation|>
json.dumps(observation_2, ensure_ascii=False)
```

Berkeley Function-Calling Leaderboard中parallel function call的建模方式为：（先生成所有function call，再得到所有observation）
```
<|assistant|>
function_call_1
<|assistant|>
function_call_2
<|observation|>
json.dumps(observation_1, ensure_ascii=False)
<|observation|>
json.dumps(observation_2, ensure_ascii=False)
```

目前复现官方汇报的结果，需要在parallel call评测阶段，每生成一个function call，需要用llm生成一个虚拟的observation，GLM才能继续生成后续function call，直至模型生成最终的response。将生成的function call列表作为最终答案。

后续我们parallel call的建模方式会和Berkeley Function-Calling Leaderboard对齐。

**Comment by GeniusYx** [comment]
感谢！

**Comment by Cppowboy** [comment]
同样的问题，使用https://github.com/THUDM/GLM-4/blob/main/basic_demo/openai_api_server.py 提供的接口评测，得到结果约44.68，用BFCL模板评测得到结果61.58，请问评测中需要设置什么特殊的推理超参或模板吗？
