### ISSUE TITLE
请教一下GLM4的预训练任务

### ISSUE THREAD

**Issue by JincanDeng** [THUDM/GLM-4#355]
请教一下大佬们，GLM4的预训练仍然是使用的论文《GLM: General Language Model Pretraining with Autoregressive Blank Infilling》中的填空任务吗？以及 GLM4 可以看作是一个 encoder-decoder 模型吗？

**Comment by JincanDeng** [comment]
@zRzRzRzRzRzRzR 大佬，hf页面是指哪一个呀？这个页面上好像没有提到 GLM4 的预训练任务：https://huggingface.co/THUDM/glm-4-9b-chat

**Comment by zRzRzRzRzRzRzR** [comment]
我们没有公开预训练的代码，这个上面是模型实现的代码，模型结构可以通过modeling_glm.py 查看哦
