### ISSUE TITLE
运行composite_demo之后，已经创建了网页，但打开网页出现报错Script execution error 'utf-8' codec can't decode bytes in position 972-973: invalid continuation byte

### ISSUE THREAD

**Issue by vicissitude2000** [THUDM/GLM-4#358]
### System Info / 系統信息

2张4090，环境依赖按照官方教程安装的

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/aad12c29-955a-451f-84e3-d79a7f2c074b)
You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://10.112.92.25:8501

网页打开地址之后就会出现报错
Script execution error 'utf-8' codec can't decode bytes in position 972-973: invalid continuation byte

### Expected behavior / 期待表现

如何正常打开网页

**Comment by vicissitude2000** [comment]
![image](https://github.com/user-attachments/assets/a8c007b5-64b3-4060-9b9e-7aa8ee917536)

**Comment by zRzRzRzRzRzRzR** [comment]
windows的问题吧，还是你输入了什么汉字在执行代码中，在Linux的命令行，如果输入汉字并且按下了 退格 可能会出现这个问题，但是在网页端正常不会发生

**Comment by vicissitude2000** [comment]
您好，我在linux服务器里输入的执行指令就是streamlit run src/main.py，没有汉字，然后在自己的电脑打开网址就是上面的报错

**Comment by vicissitude2000** [comment]
另外我发现这个是不少创建了一个External URL啊
![image](https://github.com/user-attachments/assets/9ee4cf8f-56a5-4fdf-8dad-39ec10a4202b)
