### ISSUE TITLE
多GPU，0,2占用时，device_map=auto时，只会使用1，不会使用3

### ISSUE THREAD

**Issue by zhongfuxiao** [THUDM/GLM-4#359]
### System Info / 系統信息

CUDA Version: 12.2
transformers=4.40.0
python=3.12.4
centos
gpu*4

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

大佬好，想咨询2个问题。
1.使用composite demo文档解读，显存用量是如何换算的？我使用glm-4-9b-chat，load int4，占用不到8G，传入265kb大小的txt文档，提问后和输出回答时显存在29g。后面换到了glm-4-9b-chat-1m，同样的本文和问题，同样int4，起始占用不到8G，提问后达到44G，输出答案时占用33G。想问下两个模型和文档大小占用显存的换算关系
2.后续在使用1m模型时，文档换成了一个1.2mb大小的txt文档，L20 48G单卡发现不够用。设备上4卡，0,2长期稳定占用。所以我设置了cuda_visible_devices=1,3，hf客户端中device_map=auto，发现还是提示内存不足，且3没有占用。是我的用法不对吗？
望大佬抽空解答

### Expected behavior / 期待表现

1.了解9b与9b-1m，文档大小跟显存占用的换算关系
2.在device0，device2占用时，如何指定其他多个device进行计算

**Comment by zRzRzRzRzRzRzR** [comment]
查看 basic/readme.md

直接屏蔽 0 2 或自己写分配规则（改device map)
