### ISSUE TITLE
建议优化openai_api_server代码，使用funcation_calling返回时与openai格式保持一致

### ISSUE THREAD

**Issue by Mars-1990** [THUDM/GLM-4#36]
### Feature request  / 功能建议

使用glm返回的结果是：
"choices": [
        {
            "index": 0,
            "message": {
                "role": "assistant",
                "content": "query_train_info\n{\"departure\": \"上海\", \"destination\": \"北京\", \"date\": \"2021-08-23\"}",
                "name": null,
                "function_call": null
            },
            "finish_reason": "stop"
        }
    ]

=================================================
而同样的接口使用https://open.bigmodel.cn/api/paas/v4/chat/completions返回的结果是
"choices": [
        {
            "finish_reason": "tool_calls",
            "index": 0,
            "message": {
                "role": "assistant",
                "tool_calls": [
                    {
                        "function": {
                            "arguments": "{\"date\":\"明天\",\"departure\":\"北京\",\"destination\":\"上海\"}",
                            "name": "query_train_info"
                        },
                        "id": "call_8718084940088338127",
                        "index": 0,
                        "type": "function"
                    }
                ]
            }
        }
    ]

### Motivation / 动机

无

### Your contribution / 您的贡献

无

**Comment by liuzhenghua** [comment]
目前代码是读到7个长度，然后判断是否包含get，才取处理输出位function_call，这块感觉有bug。
![f36a442a75e5cb4a8319bb68bda2fac9_](https://github.com/THUDM/GLM-4/assets/11787325/16e55c0b-e9c0-494e-9e3e-ffa962d3a778)

**Comment by liuzhenghua** [comment]
还有这里多个function_call分隔符的问题
![image](https://github.com/THUDM/GLM-4/assets/11787325/95f411a4-0a87-4574-87e5-14e0233547b9)

**Comment by zRzRzRzRzRzRzR** [comment]
这已经更新了呀，你pull最新的，关于第一个，方便提一个PR吗

**Comment by zRzRzRzRzRzRzR** [comment]
关注最新版本， 除流失工具调用没有支持，其他都是一样的
