### ISSUE TITLE
chatglm3与glm4的tokenizer有什么不同吗？ chatglm3可以使用outlines，但是glm4会报错

### ISSUE THREAD

**Issue by Mewral** [THUDM/GLM-4#362]
### System Info / 系統信息

transformers==4.41.2
outlines==0.0.44
python==3.10.13

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

```python
import outlines
from transformers import AutoTokenizer

args = {"trust_remote_code":True}

glm4_tokenizer = AutoTokenizer.from_pretrained("glm-4-9b-chat", trust_remote_code=True)
glm3_tokenizer = AutoTokenizer.from_pretrained("chatglm3-6b", trust_remote_code=True)

model = outlines.models.transformers("glm-4-9b-chat", device="cuda:0", model_kwargs=args, tokenizer_kwargs=args)

prompt = "你是谁"

generator = outlines.generate.choice(model, ["汤姆", "杰瑞"])
answer = generator(prompt)
print(answer)



```

### Expected behavior / 期待表现

使用chatglm3可以正常输出，但是glm4会报错

**Comment by zRzRzRzRzRzRzR** [comment]
内容差距应该不大啊，词表大小倒是变化了

**Comment by Mewral** [comment]
@zRzRzRzRzRzRzR 是的，glm3不是bpe吗？

**Comment by zRzRzRzRzRzRzR** [comment]
是的，但是文字切分不一样，huggingface有一个相似的issue这里
https://huggingface.co/THUDM/glm-4-9b-chat/discussions/69#66d29c175ae47374c28a17a2
