### ISSUE TITLE
openai_api_server 启动多个workers，推理报错

### ISSUE THREAD

**Issue by lwj2001** [THUDM/GLM-4#363]
### System Info / 系統信息

transformers:4.42.4
torch:2.3.0+cu121
Platform: Linux-5.4.0-163-generic-x86_64-with-glibc2.31
Python 3.10.14

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

只修改了脚本的启动命令：
`uvicorn.run(app="openai_api_server:app", host='0.0.0.0', port=8000, workers=2)`
报错信息为：
```
  File "GLM-4/basic_demo/openai_api_server.py", line 385, in create_chat_completion
    async for response in generate_stream_glm4(gen_params):
  File "GLM-4/basic_demo/openai_api_server.py", line 203, in generate_stream_glm4
    inputs = tokenizer.apply_chat_template(messages, add_generation_prompt=True, tokenize=False)
NameError: name 'tokenizer' is not defined. Did you mean: 'AutoTokenizer'?
```

### Expected behavior / 期待表现

该脚本可以实现启动多个服务吗？

**Comment by zRzRzRzRzRzRzR** [comment]
你这个是没有正常读取tokenizer的吧，另外这个脚本没有设计多服务

**Comment by lwj2001** [comment]
您好！当我设置run函数的`app="openai_api_server:app"`，似乎就会出现这个bug
我的目的是想启动多个workers，如果不设置这个参数的话，就无法设置多个workers，您就解决方案吗

**Comment by zRzRzRzRzRzRzR** [comment]
这个应该是没有相关的计划，我们只测试单个worker，需要自己改
