### ISSUE TITLE
执行api的时候，openai_api_server.py成功运行 openai_api_request.py运行后生成一堆！

### ISSUE THREAD

**Issue by vicissitude2000** [THUDM/GLM-4#364]
### System Info / 系統信息

2张4090

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

运行openai_api_server.py
![image](https://github.com/user-attachments/assets/463a71a1-a6f0-4c7d-ac9c-da6dfffcbebe)
运行openai_api_request.py

### Expected behavior / 期待表现

正常使用api

**Comment by vicissitude2000** [comment]
运行openai_api_server.py能生成地址
![image](https://github.com/user-attachments/assets/8222d942-d803-4170-a4bf-fdf93970ec2a)

**Comment by vicissitude2000** [comment]
运行openai_api_request.py就是一堆！了
![image](https://github.com/user-attachments/assets/75301dfb-34e8-4b40-86a7-a7f8c765c706)

**Comment by zRzRzRzRzRzRzR** [comment]
模型文件是新的吗，我咋感觉你用了pad id 也就是0 呢，我们pad id不是0
