### ISSUE TITLE
ollama 0.2.7 中调用glm4 报 does not support tools

### ISSUE THREAD

**Issue by liseri** [THUDM/GLM-4#367]
### System Info / 系統信息

- ollama version: 0.2.7
- docker 运行

### Who can help? / 谁可以帮助到您？

@ollama平台模型发布人员

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. 安装最新版本的ollama 0.2.7， 该版本支持 function call
2. ollama pull glm4
3. http调用接口
```
curl --location --request POST 'http://localhost:11434/v1/chat/completions' \
--header 'Content-Type: application/json' \
--data-raw '{
    "messages": [
        {
            "content": "北京今天温度多少",
            "role": "user"
        }
    ],
    "model": "glm4",
    "n": 1,
    "temperature": 0.9,
    "tools": [
        {
            "type": "function",
            "function": {
                "name": "get_weather",
                "description": "查询某地区的温度",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "query": {
                            "location": "城市或位置",
                            "type": "string"
                        }
                    },
                    "required": [
                        "query"
                    ]
                }
            }
        }
    ]
}'
```
4. 报不支持tool的错误
```
{
    "error": {
        "message": "glm4 does not support tools",
        "type": "api_error",
        "param": null,
        "code": null
    }
}
```

**其它信息**
ollama 0.2.5版本(应该是本身就不支持 function)只是不响应function, 但并不报错，和普通调用一样； 但0.2.7中增加了function功能，就报错了。可能是两者不匹配了，请求帮忙解决！

### Expected behavior / 期待表现

ollama正常使用function功能。

**Comment by liseri** [comment]
刚测了下llama3，也有同样的问题； 正在和ollama沟通；

**Comment by liseri** [comment]
问了下ollama, ollama0.2.7已经支持函数调用了， 但llama3:7b本身就不支持函数调用， 咱们的glm4本身是支持的，看怎么能重新发布下； 想使用ollama进行函数调用的朋友 可以参考下 https://github.com/ollama/ollama/issues/5793

**Comment by zRzRzRzRzRzRzR** [comment]
我们工具调用中的stop id 不是eos id，这个ollama识别不了吧
