### ISSUE TITLE
mtbench 评分与仓库不同

### ISSUE THREAD

**Issue by UbeCc** [THUDM/GLM-4#368]
### System Info / 系統信息

暂不需要

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

答案生成，使用 mt-bench [自带脚本](https://github.com/lm-sys/FastChat/blob/main/fastchat/llm_judge/gen_model_answer.py)

答案评测，使用 `gpt-4-turbo-2024-04-09` 作为评测模型

结果如下，其中列出多项表示评测多次

- qwen1.5-7b-chat 7.675000 (7.6 on leaderboard)
- chatglm2-6b 4.952830 (4.96 on leaderboard)
- glm-4-9b 7.849057, 7.663522, 7.728125 
- glm-4-9b-chat 7.671875, 7.38365 (8.32 in repo)

### Expected behavior / 期待表现

期待 glm-4-9b-chat 与 8.32 结果对齐，且 glm-4-9b 结果相较 chat 版本更低

**Comment by UbeCc** [comment]
补充，glm 系列的评测多次，分别使用了 `modelscope` 和 `huggingface` 上的最新版本

**Comment by zRzRzRzRzRzRzR** [comment]
你是怎么运行的呢，https://github.com/lm-sys/FastChat/tree/main/fastchat 应该是没有GLM-4的模板的，你需要自己构造GLM对话模板，不然效果应该会比较差

**Comment by UbeCc** [comment]
> 你是怎么运行的呢，https://github.com/lm-sys/FastChat/tree/main/fastchat 应该是没有GLM-4的模板的，你需要自己构造GLM对话模板，不然效果应该会比较差

好的，我去看下，感谢！

**Comment by UbeCc** [comment]
> 你是怎么运行的呢，https://github.com/lm-sys/FastChat/tree/main/fastchat 应该是没有GLM-4的模板的，你需要自己构造GLM对话模板，不然效果应该会比较差

fixed，
glm-4-9b: 6.332237
glm-4-9b-chat: 8.395105
