### ISSUE TITLE
请问26种语言具体是哪26种？我没找到。这些语言GLM-4-9B也都支持吗？

### ISSUE THREAD

**Issue by i18nsite** [THUDM/GLM-4#369]
请问26种语言具体是哪26种？我没找到。

这些语言GLM-4-9B也都支持吗？

**Comment by zRzRzRzRzRzRzR** [comment]
支持，已经在readme写了

**Comment by i18nsite** [comment]
![CleanShot 2024-07-19 at 22 41 46](https://github.com/user-attachments/assets/4c29be24-5156-48f7-a1d7-0c18a8af2d64)
我搜索了readme，没找到具体是哪26种语言
只有这一句
`本代模型增加了多语言支持，支持包括日语，韩语，德语在内的 26 种语言。 `

**Comment by i18nsite** [comment]
在 Pull Request 中讨论吧 https://github.com/THUDM/GLM-4/issues/369
