### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by tuo3288** [THUDM/GLM-4#371]
trans_cli_demo.py 运行这个试一下，但是报了很奇怪的错误：

(llm) xxx2024@n1:~/jupyterlab/glm/GLM-4$ python basic_demo/trans_cli_demo.py 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:05<00:00,  1.70it/s]
Welcome to the GLM-4-9B CLI chat. Type your messages below.

You:  Please introduce yourself.  
thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.8.1/src/dfa.rs:1415:45
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_bounds_check
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:159:5
   3: regex::re_unicode::Regex::find_at
   4: fancy_regex::Regex::find_from_pos_with_option_flags
   5: fancy_regex::Regex::find_from_pos
   6: _tiktoken::CoreBPE::_encode_native
   7: pyo3::marker::Python::allow_threads
   8: _tiktoken::CoreBPE::encode
   9: std::panicking::try
  10: _tiktoken::_::<impl _tiktoken::CoreBPE>::__pymethod_encode__
  11: method_vectorcall_FASTCALL_KEYWORDS
             at /usr/local/src/conda/python-3.9.19/Objects/descrobject.c:409:24
  12: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.9.19/Include/cpython/abstract.h:118:11
  13: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.9.19/Include/cpython/abstract.h:127:12
  14: call_function
             at /usr/local/src/conda/python-3.9.19/Python/ceval.c:5077:13
  15: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.9.19/Python/ceval.c:3506:23
  16: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.9.19/Include/internal/pycore_ceval.h:40:12
  17: _PyEval_EvalCode
             at /usr/local/src/conda/python-3.9.19/Python/ceval.c:4329:14
  18: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.9.19/Objects/call.c:396:12
  19: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.9.19/Include/cpython/abstract.h:118:11
  20: method_vectorcall
             at /usr/local/src/conda/python-3.9.19/Objects/classobject.c:53:18
  21: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.9.19/Include/cpython/abstract.h:118:11
  22: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.9.19/Include/cpython/abstract.h:127:12
  23: call_function
             at /usr/local/src/conda/python-3.9.19/Python/ceval.c:5077:13
  24: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.9.19/Python/ceval.c:3537:19
  25: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.9.19/Include/internal/pycore_ceval.h:40:12
  26: _PyEval_EvalCode
             at /usr/local/src/conda/python-3.9.19/Python/ceval.c:4329:14
  27: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.9.19/Objects/call.c:396:12
  28: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.9.19/Include/cpython/abstract.h:118:11
  29: method_vectorcall
             at /usr/local/src/conda/python-3.9.19/Objects/classobject.c:53:18
  30: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.9.19/Include/cpython/abstract.h:118:11
  31: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.9.19/Include/cpython/abstract.h:127:12
  32: call_function
             at /usr/local/src/conda/python-3.9.19/Python/ceval.c:5077:13
  33: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.9.19/Python/ceval.c:3537:19
  34: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.9.19/Include/internal/pycore_ceval.h:40:12
  35: _PyEval_EvalCode
             at /usr/local/src/conda/python-3.9.19/Python/ceval.c:4329:14
  36: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.9.19/Objects/call.c:396:12
  37: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.9.19/Include/cpython/abstract.h:118:11
  38: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.9.19/Include/cpython/abstract.h:127:12
  39: call_function
             at /usr/local/src/conda/python-3.9.19/Python/ceval.c:5077:13
  40: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.9.19/Python/ceval.c:3520:19
  41: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.9.19/Include/internal/pycore_ceval.h:40:12
  42: _PyEval_EvalCode
             at /usr/local/src/conda/python-3.9.19/Python/ceval.c:4329:14
  43: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.9.19/Objects/call.c:396:12
  44: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.9.19/Include/cpython/abstract.h:118:11
  45: method_vectorcall
             at /usr/local/src/conda/python-3.9.19/Objects/classobject.c:53:18
  46: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.9.19/Include/cpython/abstract.h:118:11
  47: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.9.19/Include/cpython/abstract.h:127:12
  48: call_function
             at /usr/local/src/conda/python-3.9.19/Python/ceval.c:5077:13
  49: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.9.19/Python/ceval.c:3537:19
  50: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.9.19/Include/internal/pycore_ceval.h:40:12
  51: _PyEval_EvalCode
             at /usr/local/src/conda/python-3.9.19/Python/ceval.c:4329:14
  52: _PyEval_EvalCodeWithName
             at /usr/local/src/conda/python-3.9.19/Python/ceval.c:4361:12
  53: PyEval_EvalCodeEx
             at /usr/local/src/conda/python-3.9.19/Python/ceval.c:4377:12
  54: PyEval_EvalCode
             at /usr/local/src/conda/python-3.9.19/Python/ceval.c:828:12
  55: run_eval_code_obj
             at /usr/local/src/conda/python-3.9.19/Python/pythonrun.c:1221:9
  56: run_mod
             at /usr/local/src/conda/python-3.9.19/Python/pythonrun.c:1242:19
  57: pyrun_file
             at /usr/local/src/conda/python-3.9.19/Python/pythonrun.c:1140:15
  58: pyrun_simple_file
             at /usr/local/src/conda/python-3.9.19/Python/pythonrun.c:450:13
  59: PyRun_SimpleFileExFlags
             at /usr/local/src/conda/python-3.9.19/Python/pythonrun.c:483:15
  60: pymain_run_file
             at /usr/local/src/conda/python-3.9.19/Modules/main.c:379:15
  61: pymain_run_python
             at /usr/local/src/conda/python-3.9.19/Modules/main.c:604:21
  62: Py_RunMain
             at /usr/local/src/conda/python-3.9.19/Modules/main.c:683:5
  63: Py_BytesMain
             at /usr/local/src/conda/python-3.9.19/Modules/main.c:1129:12
  64: __libc_start_main
  65: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "/home/xxx2024/jupyterlab/glm/GLM-4/basic_demo/trans_cli_demo.py", line 86, in <module>
    model_inputs = tokenizer.apply_chat_template(
  File "/home/xxx2024/.cache/huggingface/modules/transformers_modules/glm-4-9b/tokenization_chatglm.py", line 211, in apply_chat_template
    result = handle_single_conversation(conversation)
  File "/home/xxx2024/.cache/huggingface/modules/transformers_modules/glm-4-9b/tokenization_chatglm.py", line 192, in handle_single_conversation
    input = self.build_single_message(
  File "/home/xxx2024/.cache/huggingface/modules/transformers_modules/glm-4-9b/tokenization_chatglm.py", line 136, in build_single_message
    role_tokens = [self.convert_tokens_to_ids(f"<|{role}|>")] + self.tokenizer.encode(f"{metadata}\n",
  File "/home/xxx2024/.conda/envs/llm/lib/python3.9/site-packages/tiktoken/core.py", line 120, in encode
    return self._core_bpe.encode(text, allowed_special)
pyo3_runtime.PanicException: index out of bounds: the len is 1 but the index is 1
请问这是什么原因导致的？

附：pip list
Package                   Version
------------------------- -----------
accelerate                0.32.1
aiofiles                  23.2.1
altair                    5.3.0
annotated-types           0.7.0
anyio                     4.4.0
attrs                     23.2.0
blobfile                  2.1.1
certifi                   2024.7.4
charset-normalizer        3.3.2
click                     8.1.7
contourpy                 1.2.1
cycler                    0.12.1
dnspython                 2.6.1
email_validator           2.2.0
exceptiongroup            1.2.2
fairscale                 0.4.13
fastapi                   0.111.1
fastapi-cli               0.0.4
ffmpy                     0.3.2
filelock                  3.15.4
fire                      0.6.0
fonttools                 4.53.1
fsspec                    2024.6.1
gradio                    4.38.1
gradio_client             1.1.0
h11                       0.14.0
httpcore                  1.0.5
httptools                 0.6.1
httpx                     0.27.0
huggingface-hub           0.23.4
idna                      3.7
importlib_resources       6.4.0
Jinja2                    3.1.4
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
lxml                      4.9.4
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.9.1
mdurl                     0.1.2
mpmath                    1.3.0
networkx                  3.2.1
numpy                     1.26.4
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.20.5
nvidia-nvjitlink-cu12     12.5.82
nvidia-nvtx-cu12          12.1.105
orjson                    3.10.6
packaging                 24.1
pandas                    2.2.2
pillow                    10.4.0
pip                       24.0
psutil                    6.0.0
pycryptodomex             3.20.0
pydantic                  2.8.2
pydantic_core             2.20.1
pydub                     0.25.1
Pygments                  2.18.0
pyparsing                 3.1.2
python-dateutil           2.9.0.post0
python-dotenv             1.0.1
python-multipart          0.0.9
pytz                      2024.1
PyYAML                    6.0.1
referencing               0.35.1
regex                     2024.5.15
requests                  2.32.3
rich                      13.7.1
rpds-py                   0.19.0
ruff                      0.5.3
safetensors               0.4.3
semantic-version          2.10.0
setuptools                69.5.1
shellingham               1.5.4
six                       1.16.0
sniffio                   1.3.1
some-package              0.1
starlette                 0.37.2
sympy                     1.13.0
termcolor                 2.4.0
tiktoken                  0.4.0
tokenizers                0.19.1
tomlkit                   0.12.0
toolz                     0.12.1
torch                     2.3.1
torchaudio                2.3.1
torchvision               0.18.1
tqdm                      4.66.4
transformers              4.42.4
triton                    2.3.1
typer                     0.12.3
typing_extensions         4.12.2
tzdata                    2024.1
urllib3                   2.2.2
uvicorn                   0.30.1
uvloop                    0.19.0
watchfiles                0.22.0
websockets                11.0.3
wheel                     0.43.0
zipp                      3.19.2

**Comment by zRzRzRzRzRzRzR** [comment]
这个是依赖 ，驱动都没对吧，我测试是py 3.10 cuda 12.2 A100 难道是3.9的问题么

**Comment by tuo3288** [comment]
> 这个是依赖 ，驱动都没对吧，我测试是py 3.10 cuda 12.2 A100 难道是3.9的问题么

谢谢博主，证明了不是环境的问题，是python版本的问题
用3.9.x就会出错，换了3.10.12就好了
