### ISSUE TITLE
该项目是否可以用于非营利性商用？

### ISSUE THREAD

**Issue by zhihuizhongguo** [THUDM/GLM-4#373]
### Feature request  / 功能建议

基于该源码部署的产品，是否可以商用到产品终端，但该产品并未产生直接盈利，仅用于提高用户体验。

### Motivation / 动机

给用户更低门槛使用智能AI，同时训练自己的产品模型，提升用户的粘性。

### Your contribution / 您的贡献

让更多的用户体验到AI的便利

**Comment by zRzRzRzRzRzRzR** [comment]
可以，按照协议上的注明出处就行，特别是二次训练等，这个模型本来就是可以商用的
