### ISSUE TITLE
关于vllm的chat template

### ISSUE THREAD

**Issue by RyanOvO** [THUDM/GLM-4#377]
在vllm的[example](https://github.com/vllm-project/vllm/tree/main/examples)下有对话模板jinja，GLM官方是否考虑支持glm4的chat template？
![image](https://github.com/user-attachments/assets/40dca070-275e-445c-890c-35ad2d85ee38)

**Comment by zRzRzRzRzRzRzR** [comment]
glm4不需要template吧，我们已经接上了apply_chat_template了，现在直接就能用了，想查看我们template可以直接在hf中国我们模型文件的tokenizer_config看到
