### ISSUE TITLE
BFCL评测问题

### ISSUE THREAD

**Issue by Cppowboy** [THUDM/GLM-4#378]
使用https://github.com/THUDM/GLM-4/blob/main/basic_demo/openai_api_server.py 提供的接口评测，得到结果约44.68，用BFCL模板评测得到结果61.58，请问评测中需要设置什么特殊的推理超参或模板吗？

**Comment by zRzRzRzRzRzRzR** [comment]
因为我们的模型不支持并行工具，不能按照官方的代码测试
