### ISSUE TITLE
模型使用vllm推理报错

### ISSUE THREAD

**Issue by shatang123** [THUDM/GLM-4#381]
### System Info / 系統信息

model = chatglm4-9b-chat
GPU type: = NVIDIA A100-SXM4-80GB
vllm = 0.5.2

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

  初次启动openai_api_server.py报错如下
![image](https://github.com/user-attachments/assets/9167e0ea-e544-4cf6-8f51-3d6f7f54dd55)
重启系统后,可以启动成功
![image](https://github.com/user-attachments/assets/3f707964-26a6-49e9-bcb6-50aa69f66b2d)
![image](https://github.com/user-attachments/assets/03df7141-356d-4896-937a-964363761eef)
使用官方open测试脚本测试时，出现报错
![image](https://github.com/user-attachments/assets/5789c7d2-53dd-4294-a8ed-7178bf6f1c93)
部分代码示例
```
MODEL_PATH = os.environ.get('MODEL_PATH', '/data/model/ZhipuAI/glm-4-9b-chat')
MAX_MODEL_LENGTH = 8192

if __name__ == "__main__":
    tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, trust_remote_code=True)
    engine_args = AsyncEngineArgs(
        model=MODEL_PATH,
        tokenizer=MODEL_PATH,
        # 如果你有多张显卡，可以在这里设置成你的显卡数量
        tensor_parallel_size=2,
        dtype="bfloat16",
        trust_remote_code=True,
        # 占用显存的比例，请根据你的显卡显存大小设置合适的值，例如，如果你的显卡有80G，您只想使用24G，请按照24/80=0.3设置
        gpu_memory_utilization=0.2,
        enforce_eager=True,
        worker_use_ray=False,
        engine_use_ray=False,
        disable_log_requests=True,
        max_model_len=MAX_MODEL_LENGTH,
    )
    engine = AsyncLLMEngine.from_engine_args(engine_args)
    uvicorn.run(app, host='0.0.0.0', port=8000, workers=1)
```
使用transformers推理模型可以正常使用

### Expected behavior / 期待表现

目前不知道怎么解决

**Comment by zRzRzRzRzRzRzR** [comment]
下周会发一个新的指定版本的req，按照那个装吧，这个错误没有复现成功
