### ISSUE TITLE
FinetuningConfig.__init__() got an unexpected keyword argument 'combine'

### ISSUE THREAD

**Issue by chenyangMl** [THUDM/GLM-4#384]
### System Info / 系統信息

python : 3.10.11

pip install -r basic_demo/requirements.txt
pip install -r finetune_demo/requirements.txt

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

运行如下命令微调glm-4v-9b.

python finetune_vision.py  data/CogVLM-311K/  THUDM/glm-4v-9b configs/lora.yaml

报错信息：
Exception has occurred: TypeError
FinetuningConfig.__init__() got an unexpected keyword argument 'combine'
  File "/mnt1/works/mm-llm/GLM-4/finetune_demo/finetune_vision.py", line 175, in from_dict
    return cls(**kwargs)
  File "/mnt1/works/mm-llm/GLM-4/finetune_demo/finetune_vision.py", line 184, in from_file
    return cls.from_dict(**kwargs)
  File "/mnt1/works/mm-llm/GLM-4/finetune_demo/finetune_vision.py", line 444, in main
    ft_config = FinetuningConfig.from_file(config_file)
  File "/mnt1/works/mm-llm/GLM-4/finetune_demo/finetune_vision.py", line 540, in <module>
    app()
TypeError: FinetuningConfig.__init__() got an unexpected keyword argument 'combine'

### Expected behavior / 期待表现

期望解决错误bug，能够正常运行训练脚本。

**Comment by zRzRzRzRzRzRzR** [comment]
报错是啥

**Comment by chenyangMl** [comment]
> 报错是啥

Exception has occurred: TypeError
FinetuningConfig.__init__() got an unexpected keyword argument 'combine'
  File "/mnt1/works/mm-llm/GLM-4/finetune_demo/finetune_vision.py", line 175, in from_dict
    return cls(**kwargs)
  File "/mnt1/works/mm-llm/GLM-4/finetune_demo/finetune_vision.py", line 184, in from_file
    return cls.from_dict(**kwargs)
  File "/mnt1/works/mm-llm/GLM-4/finetune_demo/finetune_vision.py", line 444, in main
    ft_config = FinetuningConfig.from_file(config_file)
  File "/mnt1/works/mm-llm/GLM-4/finetune_demo/finetune_vision.py", line 540, in <module>
    app()
TypeError: FinetuningConfig.__init__() got an unexpected keyword argument 'combine'

**Comment by glsoon** [comment]
transformers=4.40.0  同调试4V， 另外还报错Seq2SeqTrainingArguments  got an unexpected keyword argument 'eval_strategy' ，这个错误，需要改configs/lora.yaml 中eval_strategy ---> evaluation_strategy。

**Comment by zRzRzRzRzRzRzR** [comment]
这个应该已经更新了吧，现在都是4.43了，仓库已经表明了更新

**Comment by glsoon** [comment]
👌



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 24, 2024 19:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [THUDM/GLM-4] FinetuningConfig.__init__() got an unexpectedkeyword argument 'combine' (Issue #384)




 
这个应该已经更新了吧，现在都是4.43了，仓库已经表明了更新

**Comment by chenyangMl** [comment]
> 这个应该已经更新了吧，现在都是4.43了，仓库已经表明了更新

我更新到transformers==4.43.0


> 这个应该已经更新了吧，现在都是4.43了，仓库已经表明了更新

这个是GLM仓库代码里面的报错，跟 transformers版本没关系吧。
代码 https://github.com/THUDM/GLM-4/blob/main/finetune_demo/finetune_vision.py 函数FinetuningConfig少一个属性

**Comment by zRzRzRzRzRzRzR** [comment]
已经修复
