### ISSUE TITLE
vllm部署GLM4，是否支持function call的调用？

### ISSUE THREAD

**Issue by RyanOvO** [THUDM/GLM-4#387]
背景：
基于vllm-0.5.1部署了GLM4，通过vllm提供Open AI API风格的接口调用，命令如下：
`python -m vllm.entrypoints.openai.api_server --model /home/Lglm-4-9b-chat/ --served-model-name glm-4-9b-chat --trust-remote-code  --api-key t123456 --host 0.0.0.0 --port 7860 --max-model-len=2048 --gpu-memory-utilization=0.9 --enforce-eager  --tensor-parallel-size 1`

请问，在vllm支持tools调用的情况下，是否可以调用GLM4的function call？

**Comment by zRzRzRzRzRzRzR** [comment]
我们 工具调用使用我们官方代码启动的，vllm默认的那个应该不能fc

**Comment by RyanOvO** [comment]
官方是否考虑支持呢？
