### ISSUE TITLE
为什么GLM-4V-9B INT4量化以后推理速度没有提升？

### ISSUE THREAD

**Issue by ZhangYaoFu** [THUDM/GLM-4#391]
<img width="623" alt="image" src="https://github.com/user-attachments/assets/1b1712e7-b70f-448d-b7fc-4d8625992536">
官方数据显示INT4量化后模型的推理速度降低了，我本地测下来也是这样，请教下量化后推理速度没有提升呢？
https://github.com/THUDM/GLM-4/blob/913cb6dc06d8fbc7a2a750ee5c8003e3e5c7d8d1/basic_demo/README.md?plain=1#L51

**Comment by zRzRzRzRzRzRzR** [comment]
int4仅是降低了成本，因为这是用了bitsandbytes，没有优化成一个int4的权重
同时，内存移动到显存这部分也很占用时间
