### ISSUE TITLE
请问在微调时怎么保存全量参数，而不只是adpter层参数，比如图一保存成图二这种形式，使得在其他一些框架中的model:MODEL_PATH这个参数可以直接变成微调模型

### ISSUE THREAD

**Issue by LeeGitHub1** [THUDM/GLM-4#392]
![截屏2024-07-24 17 42 59](https://github.com/user-attachments/assets/7d166fdd-40be-4fab-82e6-661e913a0a63)
![截屏2024-07-24 17 43 21](https://github.com/user-attachments/assets/872f9736-530e-4cfd-8766-4b76a7f7972e)

**Comment by zRzRzRzRzRzRzR** [comment]
这个如果你需要的话，你直接在inference的代码中读入模型之后在按照safetensor保存就行了，我们没有提供这个代码

**Comment by LeeGitHub1** [comment]
> 这个如果你需要的话，你直接在inference的代码中读入模型之后在按照safetensor保存就行了，我们没有提供这个代码

你好，1. 我发现在保存后与原模型文件夹大小出入比较大，发现.git目录占了18G，这个在加载模型时不需要保存吧 2.原模型文件夹中除了safetensors文件以外的其他文件该怎么保存呢，是手动设置的吗，比如json文件和三个py文件
![截屏2024-07-24 19 09 30](https://github.com/user-attachments/assets/fe08c858-ac22-4f68-95b2-2c82c02dbe2c)
![截屏2024-07-24 19 10 09](https://github.com/user-attachments/assets/b38bbc02-d762-49c3-ae79-0ac1834b4b09)

**Comment by zRzRzRzRzRzRzR** [comment]
你如果要把lora 调整过的内容后的内容，按照infer倒入之后，在保存就行了，不然就是分开的两个文件。

**Comment by LeeGitHub1** [comment]
您好，请问如何把lora微调后的模型用在basic_demo中的openai_api_server.py ，图一是我微调后保存的模型文件，在图二调整后，会产生图三报错，我在看报错文件中图四发现有lora_config这个参数，但是不知道怎么添加，如果您能费心看一下的话，我将非常感激
![截屏2024-07-27 19 08 24](https://github.com/user-attachments/assets/aadfc649-a94d-44ea-9fc5-0106b3940423)
![截屏2024-07-27 19 09 06](ht
![截屏2024-07-27 19 09 44](https://github.com/user-attachments/assets/87a2ddf4-e52a-4f5a-93bf-28
![截屏2024-07-27 19 10 41](https://github.com/user-attachments/assets/808c09f9-0b24-463d-ae39-4840a1b13db8)
16db146d19)
tps://github.com/user-attachments/assets/f55cb208-47f7-47c7-8ce5-a61e9c483ca7)

**Comment by LeeGitHub1** [comment]
> 你如果要把lora 调整过的内容后的内容，按照infer倒入之后，在保存就行了，不然就是分开的两个文件。
您好，请问如何把lora微调后的模型用在basic_demo中的openai_api_server.py ，图一是我微调后保存的模型文件，在图二调整后，会产生图三报错，我在看报错文件中图四发现有lora_config这个参数，但是不知道怎么添加，如果您能费心看一下的话，我将非常感激
![截屏2024-07-27 19 08 24](https://github.com/user-attachments/assets/aadfc649-a94d-44ea-9fc5-0106b3940423)
![截屏2024-07-27 19 12 46](https://github.com/user-attachments/assets/e3b1d986-980a-4138-a6a0-42bb9255f450)
![截屏2024-07-27 19 13 01](https://github.com/user-attachments/assets/23e585bf-7f0e-4724-8138-ae280de78beb)
![截屏2024-07-27 19 14 41](https://github.com/user-attachments/assets/2fbdcd5f-960c-4182-98a3-986b1fda8b69)

**Comment by LeeGitHub1** [comment]
> 你好，我也又同样的疑惑，你解决了吗

你需要加载模型然后保存相关文件，需要的文件即glm-4-chat中的模型文件，代码如下：from transformers import AutoModel, AutoTokenizer
from safetensors.torch import save_file
import torch
from transformers import AutoTokenizer, AutoModel
from pathlib import Path
from safetensors.torch import save_file
from tqdm import tqdm

model_dir = '/home/lmz/AI助教/GLM-4/finetune_demo/output_ptuning/checkpoint-3000'

model_dir = Path(model_dir).expanduser().resolve()
print(model_dir)
if (model_dir / 'adapter_config.json').exists():
    print(model_dir)
    model = AutoModel.from_pretrained(
        model_dir,
        trust_remote_code=True,
        device_map='auto',
        torch_dtype=torch.bfloat16
    )
    tokenizer_dir = model.peft_config['default'].base_model_name_or_path
else:
    model = AutoModel.from_pretrained(
        model_dir,
        trust_remote_code=True,
        device_map='auto',
        torch_dtype=torch.bfloat16
    )
    tokenizer_dir = model_dir

tokenizer = AutoTokenizer.from_pretrained(
    tokenizer_dir,
    trust_remote_code=True,
    encode_special_tokens=True,
    use_fast=False
)

output_dir = '/home/lmz/AI助教/GLM-4/basic_demo/ptuning'

model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)
model.config.save_pretrained(output_dir)

# state_dict = model.state_dict()
# keys = list(state_dict.keys())
# num_parts = 10
# part_size = len(keys) // num_parts

# # 分成10份并保存
# for i in tqdm(range(num_parts), desc="Saving parts"):
#     start_idx = i * part_size
#     end_idx = (i + 1) * part_size if i != num_parts - 1 else len(keys)
#     part_keys = keys[start_idx:end_idx]
#     part_state_dict = {key: state_dict[key] for key in part_keys}
#     part_file_path = output_dir / f'final_model_part_{i + 1}.safetensors'
#     save_file(part_state_dict, part_file_path)

# print(f"Model saved in safetensor format at {output_dir}")
# 保存模型权重到pytorch_model.bin

model_save_path = f"{output_dir}/pytorch_model.bin"
torch.save(model.state_dict(), model_save_path)


state_dict = model.state_dict()
metadata = {"format": "pt"}
save_file(state_dict, "/home/lmz/AI助教/GLM-4/basic_demo/ptuning/final_model.safetensors", metadata=metadata)

以及：import json
from pathlib import Path
import torch
from safetensors.torch import save_file

# 定义你的模型路径和safetensors文件路径
model_dir = Path('/home/lmz/AI助教/GLM-4/basic_demo/lora_dense')
output_dir = model_dir

# 加载模型的状态字典
state_dict = torch.load(output_dir / 'pytorch_model.bin',weights_only=True)

# 获取所有safetensors文件
safetensors_files = [output_dir / 'final_model.safetensors']

# 保存状态字典到safetensors文件，并添加元数据
metadata = {"format": "pt"}
save_file(state_dict, safetensors_files[0], metadata=metadata)

# 分配每个参数到对应的safetensors文件
total_size = sum(file.stat().st_size for file in safetensors_files)

weight_map = {name: safetensors_files[0].name for name in state_dict.keys()}

index_content = {
    "metadata": {
        "total_size": total_size
    },
    "weight_map": weight_map
}

index_file_path = output_dir / 'model.safetensors.index.json'
with open(index_file_path, 'w') as f:
    json.dump(index_content, f, indent=4)

print(f"Index file saved at {index_file_path}")
