### ISSUE TITLE
使用trans_cli_vision_demo.py和trans_web_vision_demo.py两个脚本进行对图片的信息抽取耗时差距很大

### ISSUE THREAD

**Issue by achial** [THUDM/GLM-4#393]
### System Info / 系統信息

![image](https://github.com/user-attachments/assets/a222c9be-a8f2-4cf1-b05a-bce3e35aef95)

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR 

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

你好，还有一个问题，如图是我在不同显卡下进行的测试，使用trans_cli_vision_demo.py和trans_web_vision_demo.py脚本，对同一个图片进行信息抽取任务的时候，这两个脚本耗时差距过大，请问怎么解决呢，怎么才能让trans_web_vision_demo.py脚本推理快一点

### Expected behavior / 期待表现

请问怎么才能让trans_web_vision_demo.py脚本推理快一点，还是说，如果看推理速度的话，我看trans_cli_vision_demo.py这个脚本的就可以了？

**Comment by zRzRzRzRzRzRzR** [comment]
需要多少显存和配置已经都在basic readme写过了
关于耗时大概率是消耗在网络上了吧，两个代码后端完全一样

**Comment by achial** [comment]
> 需要多少显存和配置已经都在basic readme写过了 关于耗时大概率是消耗在网络上了吧，两个代码后端完全一样

明白了，确实应该都消耗在网络上了

就是还有个问题，请问启动一个trans_web_vision_demo.py能支持多少并发呀

**Comment by zRzRzRzRzRzRzR** [comment]
没设计，应该就1，整个仓库都没做
