### ISSUE TITLE
建议可以将trust_remote_code设置为false

### ISSUE THREAD

**Issue by esrichen** [THUDM/GLM-4#397]
### Feature request  / 功能建议

建议可以将trust_remote_code设置为false

### Motivation / 动机

无互联网络条件下模型无法推理

### Your contribution / 您的贡献

建议可以将trust_remote_code设置为false

**Comment by zRzRzRzRzRzRzR** [comment]
这个根联网没关系吧，设置为false需要把模型pr到hf仓库中
https://github.com/huggingface/transformers/pull/31977
我和团队成员正在做这个工作
