### ISSUE TITLE
为什么GLM-4会有3个stop_token_ids？

### ISSUE THREAD

**Issue by Bessss-zyw** [THUDM/GLM-4#398]
一般的模型只有一个eof_token，为什么GLM-4会有3个？

在GLM-4-9B-Chat的官方vllm demo中设置了`stop_token_ids = [151329, 151336, 151338]`，Hugging Face repo的config.json文件中的`eos_token_id`也被置为 `[151329, 151336, 151338]`；但是Hugging Face repo的tokenizer_config.json的`eos_token`却被置为 `"<|endoftext|>"`。

所以config.json中的三个`eos_token_id`是否均被模型所用？这三个`eos_token_id`又是否必要（我尝试的大部分输出都以`"<|endoftext|>"`结尾）？

**Comment by zRzRzRzRzRzRzR** [comment]
三个分别是 user observation 和 endoftext
在训练的时候用endoftext
对话为 user
工具调用是 observation
三个都必须要，不然对话停不下来
