### ISSUE TITLE
请问出现KeyError: 'sop'怎么解决

### ISSUE THREAD

**Issue by cangyizhou** [THUDM/GLM-4#400]
报错如下：
[rank0]:   File "/root/miniconda3/envs/glm4/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 714, in convert_tokens_to_ids
[rank0]:     return self._convert_token_to_id_with_added_voc(tokens)
[rank0]:   File "/root/miniconda3/envs/glm4/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 727, in _convert_token_to_id_with_added_voc
[rank0]:     return self._convert_token_to_id(token)
[rank0]:   File "/root/.cache/huggingface/modules/transformers_modules/glm-4-9b/tokenization_chatglm.py", line 95, in _convert_token_to_id
[rank0]:     return self.mergeable_ranks[token]
[rank0]: KeyError: 'sop'
[rank0]: """
我看有类似问题是transformers的原因，但是我的版本已经更新到4.43，仍然报错

**Comment by cangyizhou** [comment]
问题解决了

**Comment by hellollm2025** [comment]
怎么解决的？我也是报类似的错误，transformers版本也是同样的4.43

**Comment by Xavierxxc** [comment]
出现一样的问题，并且更新到4.43、4.41.2、4.42.3、4.42、4.43.3都不行
