### ISSUE TITLE
请问一下在运行文档解读功能时出现这样的报错是为什么？

### ISSUE THREAD

**Issue by guiktydftfk** [THUDM/GLM-4#401]
![屏幕截图 2024-07-25 130222](https://github.com/user-attachments/assets/89023f24-fb1b-43cd-87cb-9471e8e7dce6)
程序来源于B站十字鱼，调整了timeout为300，显卡是4060Laptop，驱动版本为560.70，Python版本为3.12.4

**Comment by zRzRzRzRzRzRzR** [comment]
这个是Linux才能跑的吧， /tmp是linux的文件地址？

**Comment by guiktydftfk** [comment]
> 这个是Linux才能跑的吧， /tmp是linux的文件地址？

演示的视频里是win，up主说的是可以正常使用。我把反馈出来的错误信息复制到ChatGLM4里问了一下，说是可能是文件名错误、文件未创建或未正确保存到指定路径。但是我是启动文档解读之后点击里面的Browse files打开的。目前也就只有文档解读不可用。
![屏幕截图 2024-07-28 145111](https://github.com/user-attachments/assets/03fdf179-8d6a-4b46-8429-d3e3a7b28858)
