### ISSUE TITLE
openai_api_server程序的疑问

### ISSUE THREAD

**Issue by RyanOvO** [THUDM/GLM-4#402]
如下的三个问题：
1. openai_api_server.py程序是基于vllm部署推理的OPEN API形式嘛？
2. 如果是基于vllm，可以用到vllm的多卡推理能力吗？启动该py文件时，如何指定多卡并行？譬如，只用到0，1 CUDA卡。
3. 该py文件是补足修复了vllm不能tools call（即function call）的能力嘛？因为看官方的描述，该py支持fc，我认为的话，可以看作是官方对vllm支持fc的一个实现了。

感谢解答。

**Comment by zRzRzRzRzRzRzR** [comment]
是，可以，多卡需要配置参数，具体参数跟vLLM相同，但是不是用过环境变量
是fc实现，支持fc

**Comment by RyanOvO** [comment]
好的，感谢。

**Comment by RyanOvO** [comment]
好的，感谢。
