### ISSUE TITLE
请问finetune_demo中提到的对GLM-4-9B-Chat对工具调用能力微调是什么意思呢，模型可以对哪些工具进行调用呢，是指外部api吗

### ISSUE THREAD

**Issue by LeeGitHub1** [THUDM/GLM-4#404]

**Comment by zRzRzRzRzRzRzR** [comment]
是的，但是调用指的是返回工具和返回对应传入的参数，不是执行工具

**Comment by LeeGitHub1** [comment]
> 是的，但是调用指的是返回工具和返回对应传入的参数，不是执行工具
![截屏2024-07-31 16 40 45](https://github.com/user-attachments/assets/b48544a6-5b32-4fe5-bb7a-4dfcd60c5a83)
就像inference执行的结果这样子吧，不能调用外部api是吧

**Comment by zRzRzRzRzRzRzR** [comment]
对

**Comment by LeeGitHub1** [comment]
> 对

好的，请问如何将微调后的模型在basic_demo中openai_api_server.py中加载呢，这个服务器用的是vllm起的

**Comment by zRzRzRzRzRzRzR** [comment]
vLLM有讲如何导入lora adapter，这个我们仓库没有实现，直接用vLLM官方的导入lora的办法

**Comment by LeeGitHub1** [comment]
> vLLM有讲如何导入lora adapter，这个我们仓库没有实现，直接用vLLM官方的导入lora的办法

好嘞谢谢您
