### ISSUE TITLE
用glm-130b的架构微调glm-9b模型的时候报错

### ISSUE THREAD

**Issue by helloguiteng** [THUDM/GLM-4#407]
在用glm-130b的架构微调glm-9b模型的时候碰到了一个问题，embedding层模型尺寸好像对不上导致运行报错了，不知道是什么原因导致的
![image](https://github.com/user-attachments/assets/f75525f1-30f8-4de2-a4a6-f2667abff4db)

**Comment by zRzRzRzRzRzRzR** [comment]
架构不一样了，要用现在的9B的微调代码

**Comment by helloguiteng** [comment]
好的，你们有GLM-9B的微调代码？能不能提供一下？我们手上目前只有130B的代码

**Comment by zRzRzRzRzRzRzR** [comment]
就在这个仓库 finetune demo

**Comment by helloguiteng** [comment]
不是这个意思呀，我想表达的是，用我们sft的数据微调你们与训练的模型，现在我们已经把GLM-9b的模型从hf转成mes格式了，现在需要你们训练的框架代码给我们微调，请问一下你们可以提供吗？

**Comment by helloguiteng** [comment]
不是这个意思呀，我想表达的是，用我们sft的数据微调你们预训练的模型，现在我们已经把GLM-9b的模型从hf转成mes格式了（不转模型训练效率太低了），现在需要你们训练的框架代码给我们微调，请问一下你们可以提供吗？上面那个图就是我们微调过程中报错了
