### ISSUE TITLE
对于4V微调数据集能兼容不含图片的数据吗？

### ISSUE THREAD

**Issue by 1148270327** [THUDM/GLM-4#409]
### System Info / 系統信息

现在对4v进行认知微调，发现报错。提示数据集没有image。
可很多时候除了图片也会想对语言模型进行微调 ，有什么办法吗

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

4v不含图的数据集微调兼容方案

**Comment by zRzRzRzRzRzRzR** [comment]
需要自己改代码，现在只放了一个VQA任务设计的微调
