### ISSUE TITLE
openai_api_server启动后，不支持多用户并行调用接口completions

### ISSUE THREAD

**Issue by RyanOvO** [THUDM/GLM-4#411]
### System Info / 系統信息

python 3.10
vllm 0.51

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

按官方脚本启动python openai_api_server.py后，多用户同时提交文本发送，调用completion接口，只能排队进行。
按道理来说，基于vllm部署的模型，应该是可以解决这个多用户的问题。
官方是在api_server中限制了什么嘛？

### Expected behavior / 期待表现

基于openai_api_server启动后，可以多用户并行调用。

**Comment by zRzRzRzRzRzRzR** [comment]
但是这个demo是顺发设计呀，中间有顺发的匹配和对比，所有demo都没做并发
