### ISSUE TITLE
4-9B-Chat的工具调用跟3一样吗？用3的方法在4里面工具调用拉不起来。

### ISSUE THREAD

**Issue by NEALKARS** [THUDM/GLM-4#415]
### System Info / 系統信息

chatglm4-9b-chat
system等设置与3相同。只是有一个问题，3的工具调用只在chat方法有效，但是4没有这个方法

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

模型实例代码：
tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True)
    model = AutoModelForCausalLM.from_pretrained(
        model_dir,
        torch_dtype=torch.bfloat16,
        low_cpu_mem_usage=True,
        trust_remote_code=True
        ).to("cuda").eval()
    return model, tokenizer

调模型代码：
def gochat(self):
        inputs = self.tokenizer.apply_chat_template(self.history,
                                       add_generation_prompt=True,
                                       tokenize=True,
                                       return_tensors="pt",
                                       return_dict=True
                                       ).to("cuda")
        gen_kwargs = {"max_length": self.max_token, "do_sample": self.do_sample, "top_k": 1}
        with torch.no_grad():
            outputs = self.model.generate(**inputs, **gen_kwargs)
            outputs = outputs[:, inputs['input_ids'].shape[1]:]
            for line in outputs:
                print(self.tokenizer.decode(line, skip_special_tokens=True))
            response=self.tokenizer.decode(outputs[0], skip_special_tokens=True)

        return response

### Expected behavior / 期待表现

调用成功

**Comment by zRzRzRzRzRzRzR** [comment]
不一样，请使用官方的代码

**Comment by NEALKARS** [comment]
> 不一样，请使用官方的代码

请问官方代码在哪里哈？仓库里没有看到function call或者tool using的目录。
