### ISSUE TITLE
多卡文档理解时，如果文档过大会集中占用某卡显存，导致显存不足。

### ISSUE THREAD

**Issue by zhongfuxiao** [THUDM/GLM-4#416]
### System Info / 系統信息

CUDA Version: 12.2
transformers=4.40.0
python=3.12.4
centos
gpu*4

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.启动composite_demo，device_map试过auto和sequential
2.传入一个txt文本，大小约900k
3.输入prompt
4.某卡显存占满后会报显存不足，不会继续占用其他卡显存

### Expected behavior / 期待表现

大文档理解时，显存均衡占用，不知道能否实现

**Comment by zRzRzRzRzRzRzR** [comment]
用的不是vLLM吧？transformers会这样，而且应该是4卡也不够，要8卡80G
