### ISSUE TITLE
微调评估error

### ISSUE THREAD

**Issue by onlynewbie** [THUDM/GLM-4#417]
![image](https://github.com/user-attachments/assets/bde3128f-7cee-4313-9bdf-cf4b0a0057ae)
![image](https://github.com/user-attachments/assets/62278e01-c025-4534-8189-bd734f7177a3)
再多卡用自己的数据集微调时，500轮结束后的评估报错，这是为什么

**Comment by onlynewbie** [comment]
评估的样本数不对，应该是60

**Comment by zRzRzRzRzRzRzR** [comment]
transformers没升级到4.42把
