### ISSUE TITLE
开源GLM-4V-9B和商业化API差异的问题

### ISSUE THREAD

**Issue by FD-Liekkas** [THUDM/GLM-4#418]
首先，超级棒的工作！
然后，请问开源GLM-4V-9B和商业化GLM-4V API的底层模型参数规模和权重一致吗？我测试了一些问题，发现两个版本的回答质量差异比较大，又找不到相关公开资料，只能来这咨询下了。也可能是我的使用方式不对？感谢解答！

**Comment by FD-Liekkas** [comment]
> 不一样的模型哦，开源是9B的

请问方便说下商业化API GLM-4V的参数规模吗？

**Comment by PsoriasiIR** [comment]
请问以下API模型是9B版本么

<html>
<body>

模型 | 上下文 | 单价 | Batch API 定价
-- | -- | -- | --
GLM-4 预计2025年06月下线 | 128K | 0.1 元 / 千tokens | 0.05元 / 千tokens


</body>
</html>
