### ISSUE TITLE
GLM4v推理时可以开启FlashAttention2么？

### ISSUE THREAD

**Issue by ZhangYaoFu** [THUDM/GLM-4#420]
我看代码里有开发FlashAttention2，但是用的还是CoreAttention，请教下原因
https://huggingface.co/THUDM/glm-4v-9b/blob/main/modeling_chatglm.py#L447

**Comment by zRzRzRzRzRzRzR** [comment]
可以开启，在模型载入的时候设置就好了，制定atten
