### ISSUE TITLE
请问ChatGLM-4-9B-Chat的工具调用官方代码在哪里能找到？说是3的工具调用4用不了，但是仓库里也没看见工具调用的代码。

### ISSUE THREAD

**Issue by NEALKARS** [THUDM/GLM-4#423]
### Feature request  / 功能建议

请问ChatGLM-4-9B-Chat的工具调用官方代码在哪里能找到？说是3的工具调用4用不了，但是仓库里也没看见工具调用的代码。

### Motivation / 动机

请问ChatGLM-4-9B-Chat的工具调用官方代码在哪里能找到？说是3的工具调用4用不了，但是仓库里也没看见工具调用的代码。

### Your contribution / 您的贡献

请问ChatGLM-4-9B-Chat的工具调用官方代码在哪里能找到？说是3的工具调用4用不了，但是仓库里也没看见工具调用的代码。

**Comment by l3onL** [comment]
使用官方的openai_api_server.py就可以。
```
python openai_api_server.py
```
curl用法[参考这个方法](https://github.com/THUDM/GLM-4/issues/421)

**Comment by NEALKARS** [comment]
@l3onL 感谢哈。🙏再问个小问题。4的工具调用只能通过openai api吗？上一版3 的工具调用我是自己去解析模型返回的调用消息，手动调用的工具接口。这一版是只能依赖openai api实现？

**Comment by l3onL** [comment]
@NEALKARS 在openai_api_server.py里面有如何解析工具调用的代码。good luck。
