### ISSUE TITLE
GLM-4V何时支持ollama？

### ISSUE THREAD

**Issue by wpfnlp** [THUDM/GLM-4#425]
### Feature request  / 功能建议

GLM-4V何时支持ollama？

### Motivation / 动机

GLM-4V何时支持ollama？

### Your contribution / 您的贡献

GLM-4V何时支持ollama？

**Comment by zRzRzRzRzRzRzR** [comment]
暂时没有相关计划，目前只有GLM-4-9b-chat

**Comment by gyhyfj** [comment]
> 暂时没有相关计划，目前只有GLM-4-9b-chat

你好，请问ollama run glm4下载的是哪个版本呢？怎么指定下载GLM-4-9b-chat呢

**Comment by wpfnlp** [comment]
您的邮件已收到！
