### ISSUE TITLE
请问GLM-4V-9B什么时候支持使用vllm部署呢

### ISSUE THREAD

**Issue by kimanli** [THUDM/GLM-4#432]
### Feature request  / 功能建议

transformer推理速度慢，希望有其他更高性能的推理框架

### Motivation / 动机

transformer推理速度慢，希望有其他更高性能的推理框架

### Your contribution / 您的贡献

transformer推理速度慢，希望有其他更高性能的推理框架

**Comment by zRzRzRzRzRzRzR** [comment]
目前不适配，短期内暂时没有相关计划

**Comment by kimanli** [comment]
https://www.bilibili.com/video/BV1mw4m1Y7eZ/?spm_id_from=333.337.search-card.all.click&vd_source=febedc55d40d2e11f169c2141fab3289   视频31:10里说GLM-4V-9B vLLM推理在开发中了，是开发计划取消了吗，挺期待这个功能的。

**Comment by kimanli** [comment]
@zRzRzRzRzRzRzR
