### ISSUE TITLE
GLM4+LLaMA-Factory 微调 lora 组网attention模块出现q k v的datatype对应不上的情况

### ISSUE THREAD

**Issue by jamesruio** [THUDM/GLM-4#434]
### System Info / 系統信息

CUDA12.3，pytorch2.2.0，Transformers版本4.43.3

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

按照该issue中的配置：https://github.com/THUDM/GLM-4/issues/26

在modeling_chatglm.py中打印：
print("query_layer: ", query_layer.dtype)
print("key_layer: ", key_layer.dtype)
print("value_layer: ", value_layer.dtype)

出现core attention模块中query_layer和value_layer的datatype不一致的情况

执行 HF_ENDPOINT=https://hf-mirror.com llamafactory-cli train sft.yaml

sft.yaml中的内容为
`
model_name_or_path: ./glm-4-9b

stage: sft
do_train: true
finetuning_type: lora
lora_target: all

dataset: identity,alpaca_en_demo,alpaca_zh_demo
template: glm4
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

output_dir: saves/glm4-sft
logging_steps: 1
save_steps: 500
plot_loss: true
overwrite_output_dir: true

per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
flash_attn: sdpa

val_size: 0.1
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 500
`

### Expected behavior / 期待表现

预期Q K V的datatype一致

**Comment by zRzRzRzRzRzRzR** [comment]
这个或许应该去llamafactory提个issue，我在官方代码调没遇到这个问题
