### ISSUE TITLE
如何以INT4来运行GLM-4V-9B？

### ISSUE THREAD

**Issue by luyilong2015** [THUDM/GLM-4#435]
### System Info / 系統信息

如何以INT4来运行GLM-4V-9B？

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

如何以INT4来运行GLM-4V-9B？

### Expected behavior / 期待表现

能够以INT4来运行GLM-4V-9B。

**Comment by zRzRzRzRzRzRzR** [comment]
load in 4 bit 代码中有
