### ISSUE TITLE
请问如何加载ptuning微调后的模型，如下图所示，提示不支持prompt learning，但是相同的代码可以加载lora微调的模型，代码就是贵方给出的加载代码

### ISSUE THREAD

**Issue by LeeGitHub1** [THUDM/GLM-4#437]
<img width="1077" alt="截屏2024-08-04 16 21 11" src="https://github.com/user-attachments/assets/48ef6360-7ff7-408a-8735-d7837dfae487">

**Comment by zhipuch** [comment]
是微调的chat模型吗？

**Comment by LeeGitHub1** [comment]
> 是微调的chat模型吗？

是的

**Comment by zhipuch** [comment]
> > 是微调的chat模型吗？
> 
> 是的

可以参考inference.py文件加载模型，是需要merge一下的
