### ISSUE TITLE
TypeError: GenerationMixin._extract_past_from_model_output() got an unexpected keyword argument  'standardize_cache_format'

### ISSUE THREAD

**Issue by Mellow156** [THUDM/GLM-4#439]
### System Info / 系統信息

一个问题，对于模型的微调，模型文件是7.18日的模型文件下载到本地。train部分没有问题，训练500步后进行eval。产生报错TypeError: GenerationMixin._extract_past_from_model_output() got an unexpected keyword argument 
'standardize_cache_format'
环境配置按照最新要求配置，transformer是4.42.4
这个报错是什么原因？是transformer中的extract_past_from_model_output()方法不接受standardize_cache_format？去掉可以运行，但是会有什么影响么？

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

按照示例的fintune_demo操作。

### Expected behavior / 期待表现

针对这个问题如何解决？

**Comment by Mellow156** [comment]
补充：modeling_chatglm.py文件930行

**Comment by zedongju** [comment]
你好 请问这个问题解决了吗？

**Comment by zedongju** [comment]
你好  你去看一下你的transformers版本，应该不是4.42.4

**Comment by samantha-at-fairly** [comment]
what version of transformers should we use?  Mine is 4.44.0

**Comment by Erdene-Ochir0417** [comment]
I faced the same problem with transformers==4.44.0, but it was fixed when I downgraded to transformers==4.43.0. I hope this helps.

**Comment by GYK-CASIC** [comment]
> aced the same problem with transformers==4.44.0, but it was fixed when I downgraded to transformers==4.43.0. I hope this helps.

Very helpful, my cuda is 11.8, after download transformers==4.43.0, glm-4-9b is successfully running now!

**Comment by NGCcolor** [comment]
你解决了吗，我也遇到了这个报错

**Comment by NGCcolor** [comment]
> 我们应该使用什么版本的变压器？我的是 4.44.0

I encountered the same problem. It's the same version as yours. Have you solved it yet?

**Comment by zRzRzRzRzRzRzR** [comment]
have you update the model file of huggingface

**Comment by qinhuangdaoStation** [comment]
用下面的版本解决了，可以正常运行

pip install transformers==4.40.2

**Comment by zmtttt** [comment]
想问一下大家，不改变transformer的版本，该怎么解决这个问题呀
