### ISSUE TITLE
GLM-4V-9B 支持 llama.cpp

### ISSUE THREAD

**Issue by thesby** [THUDM/GLM-4#44]
### Feature request  / 功能建议

希望 GLM-4V-9B 能够支持 llama.cpp 

### Motivation / 动机

支持 llama.cpp，可以在 ollama 调用，需要的运算资源比较少，调用方便，希望支持

### Your contribution / 您的贡献

无

**Comment by Sleepychord** [comment]
为了支持GLM和GLM-4V模型结构（和llama不同），需要修改llama.cpp的代码并等待pr合并，这需要一段时间，感谢您的关注。

**Comment by zRzRzRzRzRzRzR** [comment]
感谢您的持续关注，如果您有能力，也可以自行转为gguf或者做相关适配

**Comment by choyakawa** [comment]
completed or not planned?
