### ISSUE TITLE
怎么自定义glm4模型的system指令？

### ISSUE THREAD

**Issue by echoht** [THUDM/GLM-4#440]
### Feature request  / 功能建议

现在发现modeling_chatglm.py只能输入query和history：chat(self, tokenizer, query: str, history: List[Dict] = None, role: str = "user",
             max_length: int = 8192, num_beams=1, do_sample=True, top_p=0.8, temperature=0.8, logits_processor=None,
             **kwargs)

但是我想修改模型的system指令，该怎么处理呢？直接修改tokenizer_config.json吗？有没有demo呢？

### Motivation / 动机

无

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
任何一个cli demo都是用openai格式的，直接传递system参数就行了，可以覆盖原始的template

**Comment by zRzRzRzRzRzRzR** [comment]
对
