### ISSUE TITLE
使用自己构造的数据进行微调，ValueError:151337 is not in list报错

### ISSUE THREAD

**Issue by McRays** [THUDM/GLM-4#441]
### System Info / 系統信息

- Linux 系统
- pytorch:2.3.0
- cuda12.1
- cudnn8
- 显卡：A100，40G显存

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![bf238b04b13a7810b2beab89d4bfd0c](https://github.com/user-attachments/assets/35f311a3-c981-4bbe-bd17-b9fe3b4ded83)
- 通过排查以为是参数原因，导致数据被截断，调整了max_input_length，max_output_length，max_new_tokens等参数都没有效果
- 修改lora.yaml参数combine: False可以运行，但是会报OOM
- 微调数据为根据微调README中样例构造的数据

### Expected behavior / 期待表现

了解问题出现的原因并解决，可以正常的进行微调

**Comment by zRzRzRzRzRzRzR** [comment]
4.42.4呢
能看一下你模型文件中的tokenizer.config吗

**Comment by McRays** [comment]
> 4.42.4呢 能看一下你模型文件中的tokenizer.config吗

![Uploading 41dbffc92fc48b6989c996ae16680f5.png…]()

**Comment by McRays** [comment]
> 4.42.4呢 能看一下你模型文件中的tokenizer.config吗

![41dbffc92fc48b6989c996ae16680f5](https://github.com/user-attachments/assets/d6b83ee6-adc7-434b-8bd3-4bb18ca12457)

**Comment by McRays** [comment]
> 4.42.4呢 能看一下你模型文件中的tokenizer.config吗

4.42.4还没有去试
