### ISSUE TITLE
返回json格式时是中带有markdown的```json

### ISSUE THREAD

**Issue by lihefei644** [THUDM/GLM-4#445]
### System Info / 系統信息

无

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/e51ceb48-dd93-4194-914f-3186bf1438fc)
不管用什么提示词都会返回markdown格式，请问有什么办法可以解决吗？

### Expected behavior / 期待表现

只返回json 不要其余的内容

**Comment by lihefei644** [comment]
> 应用端。获取全部输出后，判断是这样的，进行“json格式化”。 或者，微调，微调是个大工程，效果和成本不确定。

@mingyue0094  意思是去做后处理？模型层面没有办法解决吗

**Comment by zRzRzRzRzRzRzR** [comment]
这个部分是模型本身有的，应该是弄不掉，应该要通过正则等方法来处理
