### ISSUE TITLE
大佬想问一下glm4是encode-decode还是decode-only?

### ISSUE THREAD

**Issue by ciaoyizhen** [THUDM/GLM-4#446]
大佬，想问问glm4现在还是encode-decode吗？
我看glm4的源码里面，只有embedding+attention+mlp，这样的话不是decode-only吗？
然后我看glm做的不是blank infilling  这decode-only应该做不了把
然后我看论文也没说(或者我看漏了什么论文)

想问下现在具体是怎么做的？是用encode-decode训练然后只拿decode做预测还是直接变成decode-only了？

**Comment by zRzRzRzRzRzRzR** [comment]
decode-only
