### ISSUE TITLE
GLM-4 and Dify Response Reception Issue

### ISSUE THREAD

**Issue by ZYMCCX** [THUDM/GLM-4#447]
### System Info / 系統信息

Ubuntu22.04，RTX 4090

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

When using the GLM-4 openai_api_server, Dify can display a successful model connection, and the local GLM-4 can receive text sent by Dify and generate responses. However, the text generated by GLM-4 cannot be received by Dify.

### Expected behavior / 期待表现

-

**Comment by zRzRzRzRzRzRzR** [comment]
I believe this should make a issue to dify and we are using the defualt openai sdk

**Comment by Clint-chan** [comment]
![image](https://github.com/user-attachments/assets/b6403a85-dba5-4c1a-866d-d5dea0cf0f0d)
dify确实用不了啊
