### ISSUE TITLE
上传文件识别怎么做

### ISSUE THREAD

**Issue by YuanKyL** [THUDM/GLM-4#452]
### Feature request  / 功能建议

请问上传pdf进行识别这种是怎么做的呢，glm-4支持吗

### Motivation / 动机

![image](https://github.com/user-attachments/assets/7dd1654b-ff88-4322-844d-4986c71833ae)

### Your contribution / 您的贡献

谢

**Comment by zRzRzRzRzRzRzR** [comment]
这个是工程，不是模型，你自己做一个前端之后然后用OCR提起里面的文字，文字给GLM-4就行，如果你要直接识别就用GLM-4V
