### ISSUE TITLE
可以写一个支持mlx环境运行的模型代码吗

### ISSUE THREAD

**Issue by arthasyou** [THUDM/GLM-4#453]
### Feature request  / 功能建议

希望可以在mac studio运行glm-4

### Motivation / 动机

mac 总费用比nvidia便宜很多

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
这个部分应该要重新写实现，目前的排期相对紧张，估计比较困难

**Comment by arthasyou** [comment]
请问一下你们模型的代码部分在哪里呢
项目里面找不到相关的代码
如果有代码，我可以自己写一个适合mlx用的模型

**Comment by zhipuch** [comment]
> 请问一下你们模型的代码部分在哪里呢 项目里面找不到相关的代码 如果有代码，我可以自己写一个适合mlx用的模型 可以提供一个比如下面这样的模型细节文件吗 https://github.com/ml-explore/mlx-examples/blob/main/llms/llama/llama.py

模型代码文件在下载的模型目录里
