### ISSUE TITLE
 finetune_demo.py中第277行代码是不是有问题?input_ids.append(151336)  # EOS for chat，这个token_id并不是<eos，而是<user>.

### ISSUE THREAD

**Issue by beepoos** [THUDM/GLM-4#456]
### System Info / 系統信息

无

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

不知是我理解不对，还是代码有误，请指正，谢谢

**Comment by zRzRzRzRzRzRzR** [comment]
我们有三分eos id 分别是user observation和end of test 对话的时候是user

**Comment by beepoos** [comment]
感谢您的答复，明白了
