### ISSUE TITLE
微调报错 TypeError: GenerationMixin._extract_past_from_model_output() got an unexpected keyword argument 'standardize_cache_format'

### ISSUE THREAD

**Issue by znxd-wh** [THUDM/GLM-4#459]
### System Info / 系統信息

cuda 11.7
transformers 4.44.0
python 3.10.12
操作系统 Ubuntu 22.04
cpu  intel 6330（56核112线程）
内存    256G
显卡    RTX A6000-48G*4  

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

CUDA_VISIBLE_DEVICES=1 python finetune.py  AdvertiseGen/  /media/super/LLM/models/GLM-4-9B-Chat  configs/lora.yaml

其中lora.yaml的combine改为false

### Expected behavior / 期待表现

微调成功，生成checkpoint

**Comment by znxd-wh** [comment]
![image](https://github.com/user-attachments/assets/58ee3253-57bc-4974-9743-b466a0f1ea6d)
这是报错的截图

**Comment by znxd-wh** [comment]
transformers用的是4.44.0，现在降级成4.42.4,还是17%的时候报错
![Uploading image.png…]()

**Comment by znxd-wh** [comment]
![image](https://github.com/user-attachments/assets/9f76ce6b-a314-4d9d-8858-ad65cac485e1)
transformers降级到4.42.4，还是微调到17%报错

**Comment by znxd-wh** [comment]
![image](https://github.com/user-attachments/assets/e564c334-5daa-49b5-bbc8-36e38e7fd14d)
transformers换成4.43.3，还是到17%，错误变成ValueError: too many values to unpack (expected 2)

**Comment by youkuxiaobin** [comment]
遇到了同样问题，着急帮忙看下

**Comment by zRzRzRzRzRzRzR** [comment]
4.44的问题下周修复，目前先降低到4.42.4

**Comment by znxd-wh** [comment]
4.43.3能进行下去

**Comment by qinhuangdaoStation** [comment]
用下面的版本解决了，可以正常运行

pip install transformers==4.40.2
