### ISSUE TITLE
关于多轮对话微调的loss计算

### ISSUE THREAD

**Issue by RyanOvO** [THUDM/GLM-4#46]
按照文档 [finetune ](https://github.com/THUDM/GLM-4/tree/main/finetune_demo) 与 微调代码 [finetune.py](https://github.com/THUDM/GLM-4/blob/main/finetune_demo/finetune.py)  综合来看，请问loss计算可以按如下的来表示么？
![image](https://github.com/THUDM/GLM-4/assets/31231960/1788a1b4-e771-4062-affd-28df5530522e)

**Comment by zRzRzRzRzRzRzR** [comment]
是，所有的output都是计算loss的

**Comment by RyanOvO** [comment]
> 是，所有的output都是计算loss的，但是关于对话排列中，您的图好像不对 例如，对于输入 ，模型生成 ，计算生成的 与实际的 的损失。 再比如，输入 ... ，模型生成新的 ，计算生成的新的 与实际新的 的损失。而之前所有的内容都是input

是这样的么？
![image](https://github.com/THUDM/GLM-4/assets/31231960/e23a8895-a5f0-4dfa-857f-bcb8c711d43b)

**Comment by zRzRzRzRzRzRzR** [comment]
是第一种，第二种是没办法训练多轮对话的呀

**Comment by RyanOvO** [comment]
好的，清楚了。第一种的弊端就是比较冗余且性能低一些。
不过对于第二张Loss计算方式是可以的。在Firefly与Xtuner两个微调框架中都支持了。可参考文档：
https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/dataset_format.md
@zRzRzRzRzRzRzR
