### ISSUE TITLE
finetune_vision.py中的process_batch_eval  Split the conversation into multiple dialogue segments 作用是什么

### ISSUE THREAD

**Issue by Hoonly** [THUDM/GLM-4#460]
### System Info / 系統信息

 glm-4v-9b 微调

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

glm-4v-9b 微调

### Expected behavior / 期待表现

glm-4v-9b 微调

**Comment by zRzRzRzRzRzRzR** [comment]
每个段落都用于计算loss，在普通的对话微调中，最后一个回复计算loss和每个回复计算loss的情况都写了，v的微调应该只有每个对话计算loss

**Comment by Hoonly** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已收到，谢谢。

**Comment by Hoonly** [comment]
> 每个段落都用于计算loss，在普通的对话微调中，最后一个回复计算loss和每个回复计算loss的情况都写了，v的微调应该只有每个对话计算loss

为什么只有在处理eval数据时需要这个操作，这会把我一轮对话拆成两条数据
