### ISSUE TITLE
glm4v可以支持一下vllm推理吗

### ISSUE THREAD

**Issue by ShaunHeNJU** [THUDM/GLM-4#461]
### Feature request  / 功能建议

可以支持一下vllm

### Motivation / 动机

可以支持一下vllm，自己适配的vllm推理效果比hf的方式差

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
暂时没有适配，我问一下相关的同学

**Comment by Duanexiao** [comment]
这个还需要怎样适配吗？直接用vllm-openai的镜像启的glm-4-9b-chat模型推断效果确实不行。我问模型：你是谁，回答的内容居然是：？你在哪里？你在做什么？\n     不知道具体什么情况，是有什么参数需要特别设置吗？

**Comment by zRzRzRzRzRzRzR** [comment]
因为模型结构和chat不一样，这个部分还有视觉部分嵌入才行

**Comment by Duanexiao** [comment]
> 因为模型结构和chat不一样，这个部分还有视觉部分嵌入才行

抱歉，看错了问题。以为还是chat模型

**Comment by zRzRzRzRzRzRzR** [comment]
chat模型应该是正常的呀

**Comment by Duanexiao** [comment]
> chat模型应该是正常的呀

嗯呢，是可以通过vllm正常起服务，但是效果不行。
我问模型：你是谁，回答的内容居然是：？你在哪里？你在做什么？\n 
不知道具体什么情况，是有什么参数需要特别设置吗？

**Comment by zRzRzRzRzRzRzR** [comment]
是vllm 0.5.4版吗，检查一下req中的依赖要求

**Comment by Duanexiao** [comment]
> 是vllm 0.5.4版吗，检查一下req中的依赖要求

对的，就是用的官方的vllm/vllm-openai:v0.5.4版本的镜像。依赖没问题

**Comment by zhipuch** [comment]
chat推理时你是使用官方的代码吗？我尝试你是谁这个问题时没有出现乱说的问题

**Comment by Duanexiao** [comment]
感谢回复。知道原因了，因为我调用的是v1/completions这个接口，这个接口就是一个文本续写的功能，所以才出现这样的问题，应该调用v1/chat/completions接口

**Comment by alexw994** [comment]
可以看看我的这个pr https://github.com/vllm-project/vllm/pull/7672

**Comment by elesun2018** [comment]
请问现在是否支持vllm加速
如何才能支持VLLM加速，谢谢  sss
