### ISSUE TITLE
这个是什么问题

### ISSUE THREAD

**Issue by YuanKyL** [THUDM/GLM-4#462]
### System Info / 系統信息

![image](https://github.com/user-attachments/assets/7b2d0764-c942-43bd-a857-9894807ed132)
，提交问题后报错

### Who can help? / 谁可以帮助到您？

![image](https://github.com/user-attachments/assets/a010349b-49d9-4967-9dc9-f4651a2d3361)

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/2587924e-9e8d-4cbf-8659-e73ff9484f8d)

### Expected behavior / 期待表现

![image](https://github.com/user-attachments/assets/142066d2-d257-4082-8bef-e0078e7a1fe9)

**Comment by YuanKyL** [comment]
cuda version  12.1

**Comment by zRzRzRzRzRzRzR** [comment]
这个是精警告，下面哪个才是报错
