### ISSUE TITLE
glm-4v-9b微调eval阶段出错，attention_mask未考虑visual tokens

### ISSUE THREAD

**Issue by Hoonly** [THUDM/GLM-4#463]
### System Info / 系統信息

无

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/41ef98ce-72cc-4898-b50d-0d1cf52d8e98)
![image](https://github.com/user-attachments/assets/79ff0254-8591-4b55-af0a-56ebe00c8f1a)

### Expected behavior / 期待表现

预期 eval中的attention mask也应该处理

**Comment by zRzRzRzRzRzRzR** [comment]
这个部分能提一个PR吗，我们同步检查，感谢
