### ISSUE TITLE
8卡lora微调训练，数据集AdvertiseGen，loss从3.2613开始到1000多个step之后一直在2.8 2.9左右震荡，请问这是正常的吗

### ISSUE THREAD

**Issue by yangrz7** [THUDM/GLM-4#464]
### Feature request  / 功能建议

<img width="886" alt="image" src="https://github.com/user-attachments/assets/d360a32c-30bb-4c68-a7a0-0d02cbc00104">
在2000个step eval后的结果{'eval_rouge-1': 57.99005983455883, 'eval_rouge-2': 41.65671185661765, 'eval_rouge-l': 19.927850643382357, 'eval_bleu-4': 0.08454537163876763, 'eval_runtime': 2574.3399, 'eval_samples_per_second': 0.416, 'eval_steps_per_second': 0.013, 'epoch': 0.14} 这个精度正常吗

### Motivation / 动机

无

### Your contribution / 您的贡献

无

**Comment by znxd-wh** [comment]
请问你的transformers版本多少？我微调到17%就报错了

**Comment by zRzRzRzRzRzRzR** [comment]
transformers暂时固定4.42.4,4,44移除了一个参数

**Comment by yangrz7** [comment]
@zRzRzRzRzRzRzR 可以麻烦看下这个loss和精度是正常的吗

**Comment by zRzRzRzRzRzRzR** [comment]
使用BF16，你这个loss确实不够低

**Comment by yangrz7** [comment]
> 使用BF16，你这个loss确实不够低，多少数据啊，我看到epoch才0.17 你得把step甚至高一点，比如你是10000数据，bs 1 你就把step设置10000

114599条，我设置了bs=16，step=7000多，感觉这loss还没降下来
<img width="904" alt="image" src="https://github.com/user-attachments/assets/40a30a60-e011-4852-9d23-2af08ea359a9">

**Comment by yangrz7** [comment]
> > 使用BF16，你这个loss确实不够低，多少数据啊，我看到epoch才0.17 你得把step甚至高一点，比如你是10000数据，bs 1 你就把step设置10000
> 
> 114599条，我设置了bs=16，step=7000多，感觉这loss还没降下来 <img alt="image" width="904" src="https://private-user-images.githubusercontent.com/37785043/356958655-40a30a60-e011-4852-9d23-2af08ea359a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NDYzODksIm5iZiI6MTcyMzQ0NjA4OSwicGF0aCI6Ii8zNzc4NTA0My8zNTY5NTg2NTUtNDBhMzBhNjAtZTAxMS00ODUyLTlkMjMtMmFmMDhlYTM1OWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA3MDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNTY0NGI0NzQ4MzM2YzlkZWFlNDg5OTZjNWQ0NTliMWIxZTM4ZDc5NjMxZDgzMjhmNTJkMDQwYThlZTY2NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sQX0O5TbAcF7qaJQV9veE5sxV8TAfILjs36nrZQJl5Y">

这个数据集你们跑过吗，loss降到多少符合预期

**Comment by OpEnD17** [comment]
我想请问一下，我的训练loss和grad都是0，是怎么回事，好像用GLM3的微调代码就正常了。 @zRzRzRzRzRzRzR 麻烦可以请教一下吗？

**Comment by yangrz7** [comment]
> 我想请问一下，我的训练loss和grad都是0，是怎么回事，好像用GLM3的微调代码就正常了。 @zRzRzRzRzRzRzR 麻烦可以请教一下吗？

这个好像之前的issue有人提过，你可以搜一下

**Comment by zRzRzRzRzRzRzR** [comment]
我今天更新的代码已经支持到4.44了，更新hf仓库就好了
然后los为0估计是因为你没用bf16，fp16不支持的
