### ISSUE TITLE
compitable issue on transformer 4.44

### ISSUE THREAD

**Issue by narugo1992** [THUDM/GLM-4#466]
### System Info / 系統信息

Information generated with `huggingface-cli env`:

- huggingface_hub version: 0.24.5     
- Platform: Linux-5.14.0-284.25.1.el9_2.x86_64-x86_64-with-glibc2.31
- Python version: 3.10.14
- Running in iPython ?: No   
- Running in notebook ?: No
- Running in Google Colab ?: No                                                      
- Token path ?: /afs/.hf/token
- Has saved token ?: False
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.4.0
- Jinja2: 3.1.4
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: 10.4.0
- hf_transfer: N/A
- gradio: 4.41.0
- tensorboard: N/A
- numpy: 1.26.4
- pydantic: 2.8.2
- aiohttp: N/A
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /data
- HF_ASSETS_CACHE: /afs/.hf/assets
- HF_TOKEN_PATH: /afs/.hf/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False

Using the `main` branch code of GLM-4 project and transformers `v4.44.0`.

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

When follow the readme in basic_demo directory, installing all the requirements with `pip install -r requirements` (at this time transformers's version is `v4.44.0`), it will get this error.

When i downgrade it to `v4.43.x`, its runnable.

### Expected behavior / 期待表现

When using transformers `v4.43.4`, this is the expected behaviour.

**Comment by T-Atlas** [comment]
https://github.com/huggingface/transformers/pull/31445
Caused Updates

**Comment by T-Atlas** [comment]
> [huggingface/transformers#31445](https://github.com/huggingface/transformers/pull/31445) Caused Updates

在`modeling_chatglm.py`第931行
```python
# update past_key_values
        cache_name, cache = self._extract_past_from_model_output(
            outputs, standardize_cache_format=standardize_cache_format
        )
```
因为4.44.0版本以后移除 _convert_to_standard_cache、_convert_to_bloom_cache 以及 generate 中所有相关的代码，可以删除传入`standardize_cache_format=standardize_cache_format`
建议在判断transformers版本高于4.44.0时使用：
```python
# update past_key_values
        cache_name, cache = self._extract_past_from_model_output(outputs)
```
 保存后续版本兼容性
@zRzRzRzRzRzRzR

**Comment by zRzRzRzRzRzRzR** [comment]
下周一起处理，已经收到这个需求

**Comment by zRzRzRzRzRzRzR** [comment]
已经兼容
