### ISSUE TITLE
streamlit，多模态，识图对话报错

### ISSUE THREAD

**Issue by sundayweekly** [THUDM/GLM-4#467]
### System Info / 系統信息

win10，RTX4090，单卡，显存24G，
![配置](https://github.com/user-attachments/assets/b9c6b73b-27c1-493a-9c82-95c947dd0a40)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

命令行streamlit run src/main.py 启动，选择多模态，上传图片，输入文字，提交，报错。
![1](https://github.com/user-attachments/assets/cace19c7-34d7-47e2-9a75-38624e31c844)
![2](https://github.com/user-attachments/assets/e86d0875-0f7d-4f83-8733-8a131127902c)

### Expected behavior / 期待表现

找到原因

**Comment by zRzRzRzRzRzRzR** [comment]
你这个估计是版本没对上吧，你试试，估计命令行也跑不了，建议使用3090以上等支持BF16的卡
装cuda12.4 并按照今天更新的req安装，记得更新今天更新的模型文件

**Comment by sundayweekly** [comment]
有没有可能是单卡显存不够？4090单卡显存只有24G，是不是识图需要大于24G的显存？但是我设置虚拟GPU内存可不可以？

**Comment by zRzRzRzRzRzRzR** [comment]
图像需要28G

**Comment by sundayweekly** [comment]
验证了BF16是需要28G，INT4不需要28G，改成INT4就可以运行了
