### ISSUE TITLE
lora 微调，两张v100 显卡，单卡16G内存，微调一会loss 就一直为0 了

### ISSUE THREAD

**Issue by youkuxiaobin** [THUDM/GLM-4#468]
### System Info / 系統信息

CUDA Version: 12.1
transformer 版本：Version: 4.43.0
python: 3.10.12
操作系统： centos 7
硬件信息：tesla v100
Pytorch版本: 2.3.0+cu121
是否支持BF16数字格式: 支持
当前显卡型号: Tesla V100-PCIE-16GB
当前显卡的总显存: 15.7725830078125 GB
是否支持TensorCore: 支持

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR 帮忙看下哈

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

官方lora 微调脚本
export CUDA_VISIBLE_DEVICES=0,1
export OMP_NUM_THREADS=1
nohup torchrun --standalone --nnodes=1 --nproc_per_node=2 finetune.py data/ /home/liyankun/glm-4-9b-chat/ configs/lora.yaml 2>&1 > lora.log &

**测试集单条长度大概5k左右**
设置
max_input_token: 8192
max_output_token: 8192
max_new_tokens: 8192
其他没修改
见如下lora 配置和ds_zero_3.json 配置
lora.yaml
`data_config:
  train_file: vuln_information_data.jsonl
  #val_file: dev.jsonl
  val_file: dev.jsonl
  test_file: dev.jsonl
  num_proc: 1

combine: True
max_input_length: 8192
max_output_length: 8192

training_args:
  # see `transformers.Seq2SeqTrainingArguments`
  output_dir: ./output
  max_steps: 1000
  bf16: true
  # needed to be fit for the dataset
  learning_rate: 5e-4
  # settings for data loading
  per_device_train_batch_size: 1
  dataloader_num_workers: 16
  remove_unused_columns: false
  # settings for saving checkpoints
  save_strategy: steps
  save_steps: 500
  # settings for logging
  log_level: info
  logging_strategy: steps
  logging_steps: 10
  # settings for evaluation
  per_device_eval_batch_size: 1
  eval_strategy: steps
  eval_steps: 500
  # settings for optimizer
  # adam_epsilon: 1e-6
  # uncomment the following line to detect nan or inf values
  # debug: underflow_overflow
  predict_with_generate: true
  # see `transformers.GenerationConfig`
  generation_config:
    max_new_tokens: 8192
  # set your absolute deepspeed path here
  deepspeed: configs/ds_zero_3.json
peft_config:
  peft_type: LORA
  task_type: CAUSAL_LM
  r: 8
  lora_alpha: 32
  lora_dropout: 0.1
  target_modules: ["query_key_value"]`

ds_zero_3.json 如下
`{
  "train_micro_batch_size_per_gpu": "auto",
  "zero_allow_untested_optimizer": true,
  "bf16": {
    "enabled": "auto"
  },
  "optimizer": {
    "type": "AdamW",
    "params": {
      "lr": "auto",
      "betas": "auto",
      "eps": "auto",
      "weight_decay": "auto"
    }
  },
  "zero_optimization": {
    "stage": 3,
    "offload_optimizer":{
        "device": "cpu",
        "pin_memory": true
    },
    "offload_param": {
        "device": "cpu",
        "pin_memory": true
    },
    "allgather_partitions": true,
    "allgather_bucket_size": 2e8,
    "reduce_scatter": true,
    "contiguous_gradients": true,
    "overlap_comm": true,
    "sub_group_size": 1e9,
    "reduce_bucket_size": "auto",
    "stage3_prefetch_bucket_size": "auto",
    "stage3_param_persistence_threshold": "auto",
    "stage3_max_live_parameters": 1e9,
    "stage3_max_reuse_distance": 1e9,
    "stage3_gather_16bit_weights_on_model_save": true
  }
}`

loss微调日志如下：
![sc_20240812112725](https://github.com/user-attachments/assets/8e3fc67f-677a-434a-9775-5c4f029be26f)
详细日志附件如下
[lora.debug.log](https://github.com/user-attachments/files/16577129/lora.debug.log)

### Expected behavior / 期待表现

微调正常，但是微调成功后，测了数据集，但是不生效

**Comment by zRzRzRzRzRzRzR** [comment]
v100是fp16，调不了，readme写了必须bf16
