### ISSUE TITLE
glm4v-9b不支持双卡4090部署？

### ISSUE THREAD

**Issue by kandada** [THUDM/GLM-4#469]
### System Info / 系統信息

glm4v-9b怎么在双卡4090地服务器上部署？

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

使用transformers，提示显存不足

### Expected behavior / 期待表现

希望能得到详细解答

**Comment by zRzRzRzRzRzRzR** [comment]
更新文件了吗，支持的

**Comment by yuzh0816** [comment]
> 更新文件了吗，支持的

佬，请问下可以用xinference部署双4090环境吗

**Comment by zRzRzRzRzRzRzR** [comment]
可以，xinfer本身就支持多卡

**Comment by znxd-wh** [comment]
4090单卡不够，双卡将将好的

**Comment by Duanexiao** [comment]
插个楼，请问用128k的推断需要多大的显存?

**Comment by zRzRzRzRzRzRzR** [comment]
在我们的basic demo 的readme中有提到，您可以自己测试一下，感谢理解

**Comment by Duanexiao** [comment]
> 在我们的basic demo 的readme中有提到，您可以自己测试一下，感谢理解

了解,谢谢回复
