### ISSUE TITLE
使用 openai_api_server  报错  'ChatGLMForConditionalGeneration' object has no attribute 'stream_generate'  这个是版本问题吗？

### ISSUE THREAD

**Issue by gufushan** [THUDM/GLM-4#470]
### System Info / 系統信息

windwos  transformers==4.44.0

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/7dc3d381-9316-414d-a62d-1ef5b8ed1ad3)
感觉像是  modeling_chatglm.py 这里面有问题

### Expected behavior / 期待表现

期望能修复

**Comment by Yang-125** [comment]
请问现在问题解决了吗 我这边也是这个报错

**Comment by Yang-125** [comment]
可以看看modeling_chatglm.py文件有无这个函数，可以重新把这个函数放进去

**Comment by zRzRzRzRzRzRzR** [comment]
这个不是GLM-4的代码吧，是GLM3的，GLM-4已经没有这个函数了，你可以放回去

**Comment by gufushan** [comment]
> 这个不是GLM-4的代码吧，是GLM3的，GLM-4已经没有这个函数了，你可以放回去
 确实可以 ， 在把 3 的代码 放到4里面  是可以生效的，还有一点点错误 ， 但是都是可以修改的
