### ISSUE TITLE
启用搜索实测无效

### ISSUE THREAD

**Issue by weiyang-1** [THUDM/GLM-4#471]
### System Info / 系統信息

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Fri_Jun_14_16:34:21_PDT_2024
Cuda compilation tools, release 12.6, V12.6.20
Build cuda_12.6.r12.6/compiler.34431801_0

### Who can help? / 谁可以帮助到您？

client = OpenAI(api_key="EMPTY", base_url=base_url)    
    tools = [{
        "type": "web_search",
        "web_search": {
            "enable": True,
            "search_result": True
        }
    }]

    messages = [{
        "role": "user",
        "content": "最近3个月北京有哪些演唱会？"
    }]

    response = client.chat.completions.create(
        model="glm-4",
        messages=messages,
        tools=tools,
        stream=use_stream,
        max_tokens=256,
        temperature=0.9,
        presence_penalty=1.2,
        top_p=0.1,
        tool_choice="auto"
    )

ChatCompletion(id='chatcmpl-aHk1ayOswmHSryd4QuTBrEyoi2MWa', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='很抱歉，由于我无法实时访问互联网获取最新信息，因此不能提供确切的近三个月内北京的演唱会列表。但是，通常您可以通过以下几种方式来了解最新的北京演唱会信息：\n\n1. **官方网站和票务平台**：如大麦网、永乐票务等，这些网站会及时更新各类演出信息。\n2. **社交媒体**：关注微博上的音乐人官方账号或者相关活动组织者的账号，他们会发布演出的相关信息。\n3. **本地媒体**：查看北京当地的报纸、杂志或在线娱乐资讯网站，它们经常会有关于即将举行的音乐会的预告。\n4. **现场售票点**：直接前往一些大型商场或文化中心的售票点查询。\n\n建议您通过以上途径查找最新的演唱会信息。', role='assistant', function_call=None, tool_calls=None))], created=1723515516, model='glm-4', object='chat.completion', service_tier=None, system_fingerprint='fp_rMZtmAV0V', usage=CompletionUsage(completion_tokens=156, prompt_tokens=60, total_tokens=216))

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. 启用搜索功
2. 调用接口
3. 返回结果提升无法联网查询

### Expected behavior / 期待表现

希望能够提供解决方案

**Comment by zRzRzRzRzRzRzR** [comment]
配置过Key了吗 要配置bing 的key

**Comment by weiyang-1** [comment]
这个是配置必应的KEY就可以吗:？
服务1：basic_demo/openai_api_server.py ，这个是API的服务，端口8000
服务2：composite_demo/src/main.py 一个是web的服务，端口是8501
配置了bing的key之后启动服务2，服务1就可以通过接口的方式实现搜索功能吗
