### ISSUE TITLE
lora微调，到100%的时候报错ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by znxd-wh** [THUDM/GLM-4#472]
### System Info / 系統信息

cuda 11.7
transformers 4.43.3
python 3.10.12
操作系统 Ubuntu 22.04
cpu intel 6330（56核112线程）
内存 256G
显卡 RTX A6000-48G*4

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

运行脚本CUDA_VISIBLE_DEVICES=1 python finetune.py  AdvertiseGen/  /media/super/LLM/models/GLM-4-9B-Chat  configs/lora.yaml
571条训练数据集，2条验证数据集，2条测试数据集
lora参数配置如下：
![image](https://github.com/user-attachments/assets/2a20a588-b623-49a9-9c08-33b1baba1e23)
当运行到100%的时候，就会报错ValueError: too many values to unpack (expected 2)
在执行inference.py的时候会报同样的错误

### Expected behavior / 期待表现

微调成功，权重可用

**Comment by OpEnD17** [comment]
Transformers版本有问题，之前作者说通过降低版本到4.40.2可以解决。
现在作者更新了huggingface上的代码，可以下载最新的代码，然后更新到4.44.0版本。
目前我使用的是 4.43.0版本也可以正常使用，因为我在4.44.0版本evaluation的时候遇到了问题，通过降到4.43.0解决。

**Comment by zRzRzRzRzRzRzR** [comment]
> Transformers版本有问题，之前作者说通过降低版本到4.40.2可以解决。 现在作者更新了huggingface上的代码，可以下载最新的代码，然后更新到4.44.0版本。 目前我使用的是 4.43.0版本也可以正常使用，因为我在4.44.0版本evaluation的时候遇到了问题，通过降到4.43.0解决。

感谢你的回答，能一起验证一下4.44eval出现什么问题了吗，我这边刚验证没有问题

**Comment by OpEnD17** [comment]
> > Transformers版本有问题，之前作者说通过降低版本到4.40.2可以解决。 现在作者更新了huggingface上的代码，可以下载最新的代码，然后更新到4.44.0版本。 目前我使用的是 4.43.0版本也可以正常使用，因为我在4.44.0版本evaluation的时候遇到了问题，通过降到4.43.0解决。
> 
> 感谢你的回答，能一起验证一下4.44eval出现什么问题了吗，我这边刚验证没有问题

TypeError: GenerationMixin._extract_past_from_model_output() got an unexpected keyword argument 'standardize_cache_format' #439

和这个问题一样，看了下面的评论，通过降低版本解决了

**Comment by zRzRzRzRzRzRzR** [comment]
这个我昨天更新了

**Comment by znxd-wh** [comment]
用最新的modelscope上的模型，能够支持transformers 4.44.0了
https://modelscope.cn/models/ZhipuAI/glm-4-9b-chat/files
感谢zR先生
