### ISSUE TITLE
openai_api_server工具调用不稳定

### ISSUE THREAD

**Issue by WENBO-Z-H** [THUDM/GLM-4#474]
### System Info / 系統信息

OpenAI 1.40.0
vllm 0.5.4
vllm-flash-attn 2.6.1 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

使用官方提供的openai_api_server时，发现会出现这种情况：模型在回复的content字段正确表明了需要调用哪个工具，应传入哪些参数，但tool_calls字段为None。通过在问题末尾添加”请你在工具列表中选择合适的函数获取xxx数据“（工具功能是在本地数据库中查询相应数据），可以解决问题，但稍微修改问题后，又会出现上述问题。设置tool_choice选项也不管用。

例如，模型会返回：
ChatCompletionMessage(content='要解决这个问题，我们可以使用 `get_history_weather` 工具来获取北京在指定日期范围内的历史温度数据，然后计算这些数据的平均值并将其转换为华氏度。以下是步骤：\n\n1. 使用 `get_history_weather` 函数获取北京2019年5月1日至5月5日的每日气温数据。\n2. 计算这五天的平均摄氏温度。\n3. 将平均摄氏温度转换为华氏度。\n\n首先执行第一步：调用 `get_history_weather` 获取温度数据。get_history_weather\n{"start_year": 2019, "start_month": 5, "start_day": 1, "end_year": 2019, "end_month": 5, "end_day": 5, "city_name": "Beijing"}', refusal=None, role='assistant', function_call=None, tool_calls=None) 

### Expected behavior / 期待表现

这种情况模型明明理解了应该调用什么工具，但不设置tool_calls字段而是在content中描述，我想知道是哪里存在问题，应该修改prompt还是修改openai_api_server中的逻辑，感谢您的解答

**Comment by zRzRzRzRzRzRzR** [comment]
这个应该是确实是模型能力的问题，输出了这个没有正常召回，并不是工程的问题
