### ISSUE TITLE
前天升级前还能用All Tools，昨天升级之后，All Tools用不了了

### ISSUE THREAD

**Issue by sundayweekly** [THUDM/GLM-4#475]
### System Info / 系統信息

![Uploading 1.jp
![2](https://github.com/user-attachments/assets/d143c4c9-0195-4637-bcc9-2c0debd223a2)
![3](https://github.com/user-attachments/assets/1b45425e-c192-41fe-9838-2d8af8dd6981)
![4](https://github.com/user-attachments/assets/517e7878-0b20-455a-a3ec-a76e2a76f54c)
![5](https://github.com/user-attachments/assets/b2b774ed-1c70-4729-9b9e-57f4564a4f71)
![6](https://github.com/user-attachments/assets/ac9f5834-9a8c-4758-b14f-9d82f64be15b)
![7](https://github.com/user-attachments/assets/57ca9e58-9a36-4a6b-9f1c-9914b27cd357)
g…]()
![8](https://github.com/user-attachments/assets/5ce8c4c8-fed0-4123-9b22-2b25463edaf5)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

在之前搭建的环境的基础上，分别安装basic_demo、composite_demo文件夹中requirement.txt中的安装包，在魔塔社区下载了最新的模型，报如图所示的错误。
![0](https://github.com/user-attachments/assets/11794741-e3c8-4dfc-b151-1c6be727f1ed)

### Expected behavior / 期待表现

期待能找到问题的原因，并解决问题。

**Comment by sundayweekly** [comment]
上传的环境配置信息不能显示，这里补充一下
![1](https://github.com/user-attachments/assets/51912317-facc-4745-b466-8004f2424898)
![2](https://github.com/user-attachments/assets/7e30786f-98ae-496c-aac4-5b7ac7d526a0)
![3](https://github.com/user-attachments/assets/c3eafbe0-3594-48de-83b2-aaa49c641127)
![4](https://github.com/user-attachments/assets/a31a8901-1acb-41c1-8077-3eb4437fa492)
![5](https://github.com/user-attachments/assets/3d6016c8-c9bf-4c49-ad1a-3dcfb462fc1c)
![6](https://github.com/user-attachments/assets/2c763da8-0fcb-4458-a67e-a70b7d862769)
![7](https://github.com/user-attachments/assets/df30cda5-1e5d-4367-b6e4-b447a3c3932e)

**Comment by sundayweekly** [comment]
环境配置如下：
![1](https://github.com/user-attachments/assets/ace26431-dea6-4a23-8eb7-c7df4cdfd5d5)
![2](https://github.com/user-attachments/assets/dfe262f1-c5a4-49d7-a403-829a9b62fc79)
![3](https://github.com/user-attachments/assets/608e1733-b033-4b97-8696-158a71ed36da)
![4](https://github.com/user-attachments/assets/9a30a1e7-3acc-4528-b0dd-b8718668ce16)
![5](https://github.com/user-attachments/assets/dc536b8f-a3c2-4da6-a531-7e241e128ba7)
![6](https://github.com/user-attachments/assets/ee8f2820-70a4-4d7f-b5a8-f936ec51f93d)
![7](https://github.com/user-attachments/assets/d8b24876-f7c7-45fe-a8b2-c8fd0ed29150)

**Comment by zRzRzRzRzRzRzR** [comment]
稳定复现吗，你的所有版本似乎都正常，可能唯一的区别是windows系统而不是我们测试的Linux系统

**Comment by sundayweekly** [comment]
稳定复现，一直是报这个错误，我在使用6月份版本的时候All Tools是可以用的，文档解析也是可以用的，只有多模态不能用，更新到这个版本之后，都用不了了，更新前后都是安装在同一台电脑上，都是win10的系统

**Comment by zRzRzRzRzRzRzR** [comment]
因为依赖升级了，现在的依赖跟六月份已经不一样了，transformers升级到了最新的，这个问题现在暂时没办法复现，不确定是不是因为版本升级之后底层依赖跟windows出现冲突

**Comment by sundayweekly** [comment]
我怀疑是flash attention的问题，现在还没有找到解决的办法，之前版本的transformers，是不是不用flash attention? 升级transformers之后要用flash attention

**Comment by sundayweekly** [comment]
transformers升级到最新版本4.44.0，torch也升级到2.3.1，就可以用了
