### ISSUE TITLE
用 openai_api_server.py 多卡运行 glm-4-9b-chat 处理长文本的时候可能会胡乱输出

### ISSUE THREAD

**Issue by oubeichen** [THUDM/GLM-4#476]
### System Info / 系統信息

Python 3.11
RTX 4090 x 2，用过 535 和 550 驱动，问题依旧
已经使用了当前最新的模型文件（modelscope上）和最新的GLM-4 basic_demo 目录下的 requirements.txt 依赖

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

我需要做一个长文本提取关键词的应用，所以在 openai_api_server.py 的基础上修改了 MAX_MODEL_LENGTH 为 32000 和这一行
https://github.com/THUDM/GLM-4/blob/6af85cd4003fadbbf05b593ed25f9dd01e8dfe6c/basic_demo/openai_api_server.py#L355

的 1024 更改为 16000，使得可以支持更长上下文和输出。

这一行
https://github.com/THUDM/GLM-4/blob/6af85cd4003fadbbf05b593ed25f9dd01e8dfe6c/basic_demo/openai_api_server.py#L670
修改为 2，使得可以支持两张显卡。另外安装了 requirements.txt 里的 flash-attn 和 peft（因为没有 0.12.2 安装的 0.12.0），用作微调的准备，其他就没有做过多修改了。

然后在调用的时候，发现如果文本稍微长一点，则经常会出现API卡住的情况，其实是在不断输出结果直到上限。
以下是我拼好的 prompt，太长直接上传成 txt。 
其中，`任务内容：`以上部分在 role: system 里面，`任务内容：`以及以下部分在 role: user 里面。

[GLM4Prompt.txt](https://github.com/user-attachments/files/16598688/GLM4Prompt.txt)

[GLM4_request.txt](https://github.com/user-attachments/files/16599257/GLM4_request.txt)

以下是结果的前面部分，后面基本上就是`铯领柏`无限重复。

![image](https://github.com/user-attachments/assets/f328c22d-aae8-4f5e-9c88-7ea4ea9cb319)

### Expected behavior / 期待表现

正常返回结果

我发现部分第三方平台也可以使用 glm-4-9b-chat 这个模型，而且没有这个卡住问题，能正常返回结果。但他们的模型不支持 tool_call，有可能基底并不是用的 vllm。

**Comment by zRzRzRzRzRzRzR** [comment]
不是，是因为没有做单独判断，tool calll在官方代码是单独实现的，用了规则处理

**Comment by zRzRzRzRzRzRzR** [comment]
我会在多卡测试一下，你出现这个问题的复现语句是？

**Comment by oubeichen** [comment]
> 我会在多卡测试一下，你出现这个问题的复现语句是？

你可以参考我发的附件，前者是我拼好的 prompt，可能不是很准确但大差不差，后者是 openai 库日志记录的请求信息。

GLM4Prompt.txt
GLM4_request.txt

**Comment by zhipuch** [comment]
你好，我按你的代码改动和prompt复现没发现重复输出的问题

**Comment by oubeichen** [comment]
> 你好，我按你的代码改动和prompt复现没发现重复输出的问题

我试了下重新安装了 python 虚拟环境还是有问题

具体修改：

https://github.com/oubeichen/GLM-4/commit/bf2585cbcf6d372cb917caa1204119ef9380991e#diff-f6c09858408807615bba26a40410ec01bc0bcb7ca9cbe37ea14231691948d7a2
这次直接全新环境安装了 requirements.txt ，其他都没装


我的机器是用的 autodl 的

PyTorch / 2.3.0 / 3.12(ubuntu22.04) / 12.1
镜像

请求的 body：
[GLM4_request_body.json](https://github.com/user-attachments/files/16622553/GLM4_request_body.json)

导出的 CURL 请求，供参考（可以修改成后缀 .sh 来执行）：
[GLM4_request_curl.txt](https://github.com/user-attachments/files/16622564/GLM4_request_curl.txt)
导出的 python 语句，供参考 ：
[GLM4_request_python.txt](https://github.com/user-attachments/files/16622566/GLM4_request_python.txt)

**Comment by zhipuch** [comment]
1. 你可以试一下官方提供的request脚本
2. 我使用你的request脚本进行复现，发现一个比较显著的问题，在拼接message的时候长文本最好用'''content'''，单引号和双引号会不小心抵消或者冲突，修改完之后运行成功。
[request.txt](https://github.com/user-attachments/files/16623540/request.txt)

**Comment by oubeichen** [comment]
> 1. 你可以试一下官方提供的request脚本
> 2. 我使用你的request脚本进行复现，发现一个比较显著的问题，在拼接message的时候长文本最好用'''content'''，单引号和双引号会不小心抵消或者冲突，修改完之后运行成功。
>    [request.txt](https://github.com/user-attachments/files/16623540/request.txt)

这个是 RapidAPI 生成的文件，我之前也发现有问题改过，但是上传不知道咋的传错文件了，不好意思。

我看了下主要是在两条 message 的 content 前后有没有换行的问题。你发的文件所有 content 前后都加上了换行，所以运行没有问题，我这也没有问题。
但是我之前的是 content 前后都没有换行，所以出现了这个问题。
（删掉 request.txt 里面 content 前后所有换行， 或者执行上面给的 GLM4_request_curl.txt 里面的命令，都会出现问题）

其实以前用一些早期LLM也遇到过这个问题，输入最后必须带换行，否则没法让AI知道正常结束。现在大部分LLM或者运行的框架都没这个问题，我就没怎么注意了。

感觉我先暂时把所有输入前后都手动带上换行吧。
