### ISSUE TITLE
GLM4 继续预训练

### ISSUE THREAD

**Issue by OpEnD17** [THUDM/GLM-4#477]
### Feature request  / 功能建议

请问一下是否建议在GLM4基础模型上做继续预训练？灌入特定场景的知识后，然后再做SFT。如果建议的话，请问可否提供一个 继续预训练的 demo？

### Motivation / 动机

可能学习特定场景的知识，继续预训练相比SFT有更大的提升吧

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
暂时不能提供继续预训练的demo，感谢您的支持
