### ISSUE TITLE
transformers==4.44.0 是否有问题？

### ISSUE THREAD

**Issue by mingyue0094** [THUDM/GLM-4#479]
### System Info / 系統信息

win10  

再用的是 `transformers==4.40.0`  正常使用。

看到 https://github.com/THUDM/GLM-4/blob/main/basic_demo/requirements.txt   里面显示  `transformers==4.44.0 `

猜测，可能最新版本解决了“不兼容”，同时运行速度会更快了。 然后安装   `transformers==4.44.0 ` 后会出现下面的错误。

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

transformers==4.44.0 后，错误提示如下。

```
    |   File "G:\2023\4\chatGlB-6b\ChatGLM3\.env\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    |     response = gen.send(None)
    |   File "C:\Users\Administrator\.cache\huggingface\modules\transformers_modules\glm-4-9b-chat\modeling_chatglm.py", line 1081, in stream_generate
    |     logits_processor = self._get_logits_processor(
    |   File "G:\2023\4\chatGlB-6b\ChatGLM3\.env\lib\site-packages\transformers\generation\utils.py", line 866, in _get_logits_processor
    |     and generation_config._eos_token_tensor is not None
    | AttributeError: 'GenerationConfig' object has no attribute '_eos_token_tensor'
```

### Expected behavior / 期待表现

是需要更新模型文件吗？ 还是固定transformers到可用的版本？   谢谢

**Comment by zRzRzRzRzRzRzR** [comment]
更新模型文件
