### ISSUE TITLE
Xinference 部署glm-4-9b-chat 运行报错 'ChatGLMForConditionalGeneration' object has no attribute 'stream_chat'

### ISSUE THREAD

**Issue by sy960923** [THUDM/GLM-4#480]
### System Info / 系統信息

transformers 4.43.0 和4.44.0 都试过不行，请问有什么解决办法嘛？

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1

### Expected behavior / 期待表现

1

**Comment by zRzRzRzRzRzRzR** [comment]
这个已经在联系xinfer调整了，最新代码移除了非标准接口了，模型代码里没有了，预计下一个xinfer版本修复

**Comment by sy960923** [comment]
> 这个已经在联系xinfer调整了，最新代码移除了非标准接口了，模型代码里没有了，预计下一个xinfer版本修复

目前没有别的办法解决嘛？
