### ISSUE TITLE
可以做一个多并发的demo吗？

### ISSUE THREAD

**Issue by HJYIS** [THUDM/GLM-4#481]
### Feature request  / 功能建议

多个客户端同时调用接口时能够正常返回

### Motivation / 动机

多个客户端同时调用openai_api_server中的demo时会一直回答&&&&&&&

### Your contribution / 您的贡献

1

**Comment by zRzRzRzRzRzRzR** [comment]
并发的话如果不使用fc可以直接用原始的vllm，如果fc要自己做
