### ISSUE TITLE
lora微调结果调用示例

### ISSUE THREAD

**Issue by znxd-wh** [THUDM/GLM-4#482]
### Feature request  / 功能建议

能给提供一个openai_server_api.py调用lora微调结果的调用示例吗？
看了无数遍readme，也不知道该怎么去弄

### Motivation / 动机

无

### Your contribution / 您的贡献

无

**Comment by oubeichen** [comment]
https://docs.vllm.ai/en/latest/models/lora.html

在调用 generate 方法的参数里面加一个lora_request，传一个 LoRARequest，名字、ID随意写，path 填对就行。

**Comment by znxd-wh** [comment]
@oubeichen 没看懂啊，generate在哪里？

**Comment by znxd-wh** [comment]
@oubeichen 我是想在basic_demo/openai_api_server.py中调用lora微调结果，能结合openai_api_server.py讲一下吗？

**Comment by oubeichen** [comment]
> @oubeichen 我是想在basic_demo/openai_api_server.py中调用lora微调结果，能结合openai_api_server.py讲一下吗？

你是编程新手吗？在`openai_api_server.py`文件里面搜索`generate`不是能搜到唯一的结果吗？

https://github.com/THUDM/GLM-4/blob/1bd342059d8c84a6df85e72dfb8baf474a2d7a84/basic_demo/openai_api_server.py#L224

改成
```python
lora_request = LoRARequest(
    lora_name="lora",
    lora_int_id=1,
    lora_local_path="/path/to/your/lora",
)

async for output in engine.generate(inputs=inputs, sampling_params=sampling_params, request_id=f"{time.time()}", lora_request=lora_request):
```

https://github.com/THUDM/GLM-4/blob/1bd342059d8c84a6df85e72dfb8baf474a2d7a84/basic_demo/openai_api_server.py#L679

这个下面加一行

```python
enable_lora=True,
```

具体啥意思看我上面给的文档链接

**Comment by znxd-wh** [comment]
@oubeichen 谢谢指导，我看明白了，我现在试试哈

**Comment by znxd-wh** [comment]
@oubeichen 跑起来了，非常感谢
