### ISSUE TITLE
GLM4-9B 1M sft训练爆显存，请教最少需要多少显存用什么方法才能训起来？

### ISSUE THREAD

**Issue by charliedream1** [THUDM/GLM-4#483]
### Feature request  / 功能建议

我用了5台8卡80G的机器，按200k长度训练，试了全量,lora,训最后2层，均会爆显存。请教最少需要多少显存用什么方法才能训起来？

### Motivation / 动机

请教

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
长文本这个代码是调不了的，这个代码只能调到8K

**Comment by charliedream1** [comment]
有推荐的代码可以用吗？或者说怎么改能提供一下思路和相关参考的资源。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月14日(周三) 晚上6:35
收件人: ***@***.***&gt;;
抄送: "Optimus ***@***.******@***.***&gt;;
主题: Re: [THUDM/GLM-4] GLM4-9B 1M sft训练爆显存，请教最少需要多少显存用什么方法才能训起来？ (Issue #483)




 
长文本这个代码是调不了的，这个代码只能调到8K

**Comment by zRzRzRzRzRzRzR** [comment]
目前没有如此长文本的微调代码可以参考
你可以参考NEMO和Megtron框架
基于你目前的长度 PEFT，DS （本仓库实现）是实现不了的目前

**Comment by charliedream1** [comment]
只需要做一些序列并行,算子并行的处理是吗？当前代码没做这些处理，所以显存会占用很大是吧？


我试了一下lora 200k怎么也训不起来,会爆。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月14日(周三) 晚上6:42
收件人: ***@***.***&gt;;
抄送: "Optimus ***@***.******@***.***&gt;;
主题: Re: [THUDM/GLM-4] GLM4-9B 1M sft训练爆显存，请教最少需要多少显存用什么方法才能训起来？ (Issue #483)




 
目前没有如此长文本的微调代码可以参考
 你可以参考NEMO和Megtron框架
 基于你目前的长度 PEFT，DS （本仓库实现）是实现不了的目前

**Comment by zRzRzRzRzRzRzR** [comment]
当前代码没任何优化，只是能跑，肯定是跑不了200K，8K的lora都不行。
如果要微调长文本，本身就不能用这个PEFT的框架，要用NEMO等比较专业的框架自己写代码实现

**Comment by charliedream1** [comment]
谢啦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月17日(周六) 中午11:17
收件人: ***@***.***&gt;;
抄送: "Optimus ***@***.******@***.***&gt;;
主题: Re: [THUDM/GLM-4] GLM4-9B 1M sft训练爆显存，请教最少需要多少显存用什么方法才能训起来？ (Issue #483)




 
当前代码没任何优化，只是能跑，肯定是跑不了200K，8K的lora都不行。
 如果要微调长文本，本身就不能用这个PEFT的框架，要用NEMO等比较专业的框架自己写代码实现
