### ISSUE TITLE
glm-4-9b-chat-1m使用transformers后端进行推理报错

### ISSUE THREAD

**Issue by YiingWei** [THUDM/GLM-4#484]
### System Info / 系統信息

PyTorch  2.3.0
Python  3.12(ubuntu22.04)
Cuda  12.1

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

当我按照依赖安装后，使用 transformers 后端进行推理会报下面的错：
![1723627668754](https://github.com/user-attachments/assets/7111746e-2867-45c6-b609-9c4d634c5d11)
![1723627668757](https://github.com/user-attachments/assets/242a0114-29c6-4ab5-ba6c-8e3c5c311b69)
代码一致 并无增改部分

### Expected behavior / 期待表现

以及使用transformers后端进行推理时，是否可以上传pdf文件

**Comment by zRzRzRzRzRzRzR** [comment]
查看首页更新公告，更新文件
