### ISSUE TITLE
l微调后推理输出乱码

### ISSUE THREAD

**Issue by cangyizhou** [THUDM/GLM-4#486]
### System Info / 系統信息

Ubuntu 22.04
Python 3.10.12
CUDA 12.1
torch 2.4.0
transformers 4.44.0

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

部署glm4后lora微调一个实体抽取任务，顺利训练结束，推理阶段输出乱码
<img width="848" alt="1" src="https://github.com/user-attachments/assets/514713e4-7a14-4e9e-8ca4-89f607b3a16f">

### Expected behavior / 期待表现

环境已按照官方文件安装，不知道是什么问题，谢谢解答！

**Comment by cangyizhou** [comment]
加载lora权重之前正常输出，加载了lora后推理才出问题的

**Comment by zRzRzRzRzRzRzR** [comment]
训练训炸了吧，loss的情况如何

**Comment by cangyizhou** [comment]
参数设置如下：
    --val_set_size 100 \
    --output_dir=${output_dir} \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 4 \
    --preprocessing_num_workers 16 \
    --num_train_epochs 10 \
    --learning_rate 5e-5 \
    --max_grad_norm 0.5 \
    --optim "adamw_torch" \
    --max_source_length 400 \
    --cutoff_len 700 \
    --max_target_length 300 \
    --evaluation_strategy "epoch" \
    --save_strategy "epoch" \
    --save_total_limit 10 \
    --lora_r 16 \
    --lora_alpha 32 \
    --lora_dropout 0.05 \
    --bf16   
训练数据差不多3w条，训练结果如下：
 "epoch": 9.993674889310563,
    "total_flos": 4.434357236050952e+18,
    "train_loss": 0.13104722170890132,
    "train_runtime": 22192.2001,
    "train_samples_per_second": 17.097,
    "train_steps_per_second": 0.356
您看是这个问题吗，怎么解决好些

**Comment by cangyizhou** [comment]
@zRzRzRzRzRzRzR 您好，能麻烦解答一下吗？

**Comment by cangyizhou** [comment]
[trainer_state.json](https://github.com/user-attachments/files/16661179/trainer_state.json)
完整训练结果如下
