### ISSUE TITLE
glm4v 对于纯文本微调的支持

### ISSUE THREAD

**Issue by Jintao-Huang** [THUDM/GLM-4#489]
哈咯！glm4v是一个非常优秀的多模态大模型

请问可以支持一下纯文本的微调吗

相关issue：https://github.com/modelscope/ms-swift/issues/1712

**Comment by skywalkerfmc** [comment]
+1

**Comment by sixsixcoder** [comment]
目前还不支持，后续可能考虑支持，如果微调纯文本建议使用GLM-4-9B、GLM-4-9B-Chat、GLM-4-9B-Chat-1M
