### ISSUE TITLE
您好，按照所提供微调代码，工具微调时observation 部分显示是需要计算loss的？这个确定不需要计算loss么还是我哪个计算错了？

### ISSUE THREAD

**Issue by zywang-work** [THUDM/GLM-4#49]
### System Info / 系統信息

ubuntu 22.04

### Who can help? / 谁可以帮助到您？

所有人

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

message:  {'role': 'system', 'content': '', 'tools': [{'type': 'function', 'function': {'name': 'get_recommended_books', 'description': "Get recommended books based on user's interests", 'parameters': {'type': 'object', 'properties': {'interests': {'type': 'array', 'items': {'type': 'string'}, 'description': 'The interests to recommend books for'}}, 'required': ['interests']}}}]}
message:  {'role': 'user', 'content': 'Hi, I am looking for some book recommendations. I am interested in history and science fiction.'}
message:  {'role': 'assistant', 'content': '{"name": "get_recommended_books", "arguments": {"interests": ["history", "science fiction"]}}'}
message:  {'role': 'observation', 'content': '{"books": ["Sapiens: A Brief History of Humankind by Yuval Noah Harari", "A Brief History of Time by Stephen Hawking", "Dune by Frank Herbert", "The Martian by Andy Weir"]}'}
message:  {'role': 'assistant', 'content': 'Based on your interests in history and science fiction, I would recommend the following books: "Sapiens: A Brief History of Humankind" by Yuval Noah Harari, "A Brief History of Time" by Stephen Hawking, "Dune" by Frank Herbert, and "The Martian" by Andy Weir.'}
input_ids:  [[151331, 151333, 151335, 198, 98406, 99950, 103092, 5588, 44, 12, 19, 220, 121245, 99941, 113255, 1773, 103408, 100698, 99126, 100789, 15457, 100597, 109331, 100484, 5588, 44, 12, 19, 6567, 44143, 98604, 110230, 3837, 99444, 126744, 100293, 99833, 100000, 121189, 99089, 108419, 113574, 111426, 3407, 565, 633, 1288, 35692, 72520, 271, 515, 262, 330, 606, 788, 330, 455, 1288, 35692, 72520, 756, 262, 330, 4684, 788, 330, 1949, 11097, 6467, 3118, 389, 1196, 594, 11766, 756, 262, 330, 13777, 788, 341, 286, 330, 1313, 788, 330, 1700, 756, 286, 330, 13185, 788, 341, 310, 330, 12718, 82, 788, 341, 394, 330, 1313, 788, 330, 1653, 756, 394, 330, 3615, 788, 341, 503, 330, 1313, 788, 330, 917, 698, 394, 1153, 394, 330, 4684, 788, 330, 785, 11766, 311, 6934, 6467, 369, 698, 310, 456, 286, 1153, 286, 330, 6279, 788, 2278, 310, 330, 12718, 82, 698, 286, 5133, 262, 456, 532, 98319, 110462, 101409, 102481, 98335, 3837, 98964, 98991, 8307, 118633, 98522, 99424, 98619, 100791, 100955, 1773, 151336, 198, 13041, 11, 358, 1079, 3330, 369, 1045, 2311, 18532, 13, 358, 1079, 8013, 304, 3840, 323, 8037, 16970, 13, 151337, 198, 4913, 606, 788, 330, 455, 1288, 35692, 72520, 497, 330, 16356, 788, 5212, 12718, 82, 788, 4383, 18810, 497, 330, 39342, 16970, 1341, 3417, 151338, 198, 4913, 12104, 788, 4383, 50, 2068, 724, 25, 362, 36333, 11094, 315, 19820, 68759, 553, 27184, 831, 41747, 5227, 2780, 497, 330, 32, 36333, 11094, 315, 4120, 553, 18067, 12605, 10561, 497, 330, 35, 2886, 553, 9267, 56976, 497, 330, 785, 80371, 553, 24756, 1205, 404, 91669, 151337, 198, 28613, 389, 697, 11766, 304, 3840, 323, 8037, 16970, 11, 358, 1035, 6934, 279, 2701, 6467, 25, 330, 50, 2068, 724, 25, 362, 36333, 11094, 315, 19820, 68759, 1, 553, 27184, 831, 41747, 5227, 2780, 11, 330, 32, 36333, 11094, 315, 4120, 1, 553, 18067, 12605, 10561, 11, 330, 35, 2886, 1, 553, 9267, 56976, 11, 323, 330, 785, 80371, 1, 553, 24756, 1205, 404, 13, 151329]]
labels:  [[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 198, 4913, 606, 788, 330, 455, 1288, 35692, 72520, 497, 330, 16356, 788, 5212, 12718, 82, 788, 4383, 18810, 497, 330, 39342, 16970, 1341, 3417, 151338, 198, 4913, 12104, 788, 4383, 50, 2068, 724, 25, 362, 36333, 11094, 315, 19820, 68759, 553, 27184, 831, 41747, 5227, 2780, 497, 330, 32, 36333, 11094, 315, 4120, 553, 18067, 12605, 10561, 497, 330, 35, 2886, 553, 9267, 56976, 497, 330, 785, 80371, 553, 24756, 1205, 404, 91669, 151337, 198, 28613, 389, 697, 11766, 304, 3840, 323, 8037, 16970, 11, 358, 1035, 6934, 279, 2701, 6467, 25, 330, 50, 2068, 724, 25, 362, 36333, 11094, 315, 19820, 68759, 1, 553, 27184, 831, 41747, 5227, 2780, 11, 330, 32, 36333, 11094, 315, 4120, 1, 553, 18067, 12605, 10561, 11, 330, 35, 2886, 1, 553, 9267, 56976, 11, 323, 330, 785, 80371, 1, 553, 24756, 1205, 404, 13, 151329]]

### Expected behavior / 期待表现

希望尽快回答

**Comment by zRzRzRzRzRzRzR** [comment]
不算，observation是工具返回的结果，我看到代码是没有的，我加上，这部分不计算loss

**Comment by zywang-work** [comment]
> 不算，observation是工具返回的结果，我看到代码是没有的，我加上，这部分不计算loss

好的，谢谢
