### ISSUE TITLE
推理或者部署程序如何使用 INT8或INT4的数据类型加载模型

### ISSUE THREAD

**Issue by guvsta** [THUDM/GLM-4#491]
### System Info / 系統信息

CUDA 12.1

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

项目里的程序没有给出 INT8或INT4的加载模型的方式

### Expected behavior / 期待表现

希望能使用 INT8或INT4的数据精度加载模型

**Comment by zhipuch** [comment]
试一下这个：
model = AutoModelForCausalLM.from_pretrained(
    MODEL_PATH,
    trust_remote_code=True,
    quantization_config=BitsAndBytesConfig(load_in_4bit=True),
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True
).eval()
