### ISSUE TITLE
微调脚本是否支持CodeGeex4?

### ISSUE THREAD

**Issue by songpb** [THUDM/GLM-4#492]
### System Info / 系統信息

请问各位大佬有没有试过微调CodeGeex4?我用glm4-chat的微调脚本微调codegeex4，在第500步的时候报错：
ValueError: too many values to unpack (expected 2)

我的transformers是4.43.0，试过4.42.0和4.40.2也都报错（错误各不相同），能否出个指引或者demo呢？谢谢

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

必现

### Expected behavior / 期待表现

能够微调codegeex4

**Comment by zRzRzRzRzRzRzR** [comment]
那边的代码还没更新吧，目前这里的代码已经升级到4.44.0

**Comment by 297106271** [comment]
您好呀 codegeex4 微调成功了嘛 数据集是什么呢
