### ISSUE TITLE
报错ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by asd765973346** [THUDM/GLM-4#496]
### System Info / 系統信息

(gpu_1) B:\code\GLM-4>python run.py
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:05<00:00,  1.75it/s]
C:\Users\ASUS\.cache\huggingface\modules\transformers_modules\glm-4-9b-chat\modeling_chatglm.py:266: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  context_layer = torch.nn.functional.scaled_dot_product_attention(query_layer, key_layer, value_layer,
Traceback (most recent call last):
  File "B:\code\GLM-4\run.py", line 28, in <module>
    outputs = model.generate(**inputs, **gen_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\transformers\generation\utils.py", line 1622, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\transformers\generation\utils.py", line 2841, in _sample
    model_kwargs = self._update_model_kwargs_for_generation(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\.cache\huggingface\modules\transformers_modules\glm-4-9b-chat\modeling_chatglm.py", line 929, in _update_model_kwargs_for_generation
    cache_name, cache = self._extract_past_from_model_output(outputs)
    ^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

运行webdemo报错如上

### Expected behavior / 期待表现

正常运行

**Comment by lwl1751** [comment]
I had the same problem

**Comment by asd765973346** [comment]
> I had the same problem

I have solved this problem

pip install --upgrade transformers

Upgrad version to  4.44.0

**Comment by lwl1751** [comment]
> > I had the same problem
> 
> I have solved this problem
> 
> pip install --upgrade transformers
> 
> Upgrad version to 4.44.0

Thanks!
