### ISSUE TITLE
搜索和长文件功能出现问题

### ISSUE THREAD

**Issue by lingyezhixing** [THUDM/GLM-4#50]
### System Info / 系統信息

win11，cuda12.4，torch2.3.1+cu121

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

网络搜索的错误信息：

服务器端：
D:\LLM\GLM-4>cd browser

D:\LLM\GLM-4\browser>pnpm start

> glm4-browser@1.0.0 start D:\LLM\GLM-4\browser
> npx ts-node src/server.ts

LOG_LEVEL debug
info: ⚡️[server]: Server is running at http://localhost:3000
info: session_id: 031d7fef-4a6c-4e86-83cc-703b10586214
info: action: search("GLM-4-9B") <|observation|>
info: Action line: search("GLM-4-9B") <|observation|>
debug: SimpleBrowser action search GLM-4-9B
debug: Searching for: GLM-4-9B
error: parse error: TypeError: Cannot read properties of undefined (reading 'value')
info: session_id: 031d7fef-4a6c-4e86-83cc-703b10586214
info: action: search("GLM-4-9B model") <|observation|>
info: Action line: search("GLM-4-9B model") <|observation|>
debug: SimpleBrowser action search GLM-4-9B model
debug: Searching for: GLM-4-9B model
error: parse error: TypeError: Cannot read properties of undefined (reading 'value')

模型端：
===BROWSER_RESPONSE===
{'contentType': 'system_error',
 'metadata': {'failedCommand': 'search("GLM-4-9B") <|observation|>'},
 'result': 'Error when executing command search("GLM-4-9B") <|observation|>\n'
           'Error: Network or server error occurred',
 'roleMetadata': 'system_error'}
===BROWSER_RESPONSE===
{'contentType': 'system_error',
 'metadata': {'failedCommand': 'search("GLM-4 9B") <|observation|>'},
 'result': 'Error when executing command search("GLM-4 9B") <|observation|>\n'
           'Error: Network or server error occurred',
 'roleMetadata': 'system_error'}
===BROWSER_RESPONSE===
{'contentType': 'system_error',
 'metadata': {'failedCommand': 'search("GLM-4-9B") <|observation|>'},
 'result': 'Error when executing command search("GLM-4-9B") <|observation|>\n'
           'Error: Network or server error occurred',
 'roleMetadata': 'system_error'}
===BROWSER_RESPONSE===
{'contentType': 'system_error',
 'metadata': {'failedCommand': 'search("GLM-4-9B model") <|observation|>'},
 'result': 'Error when executing command search("GLM-4-9B model") '
           '<|observation|>\n'
           'Error: Network or server error occurred',
 'roleMetadata': 'system_error'}

上传一个文件后，没有任何操作就报错了，信息如下：
Traceback (most recent call last):
  File "D:\LLM\GLM-4\runtime\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "D:\LLM\GLM-4\src\main.py", line 162, in <module>
    with open(file_path, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp\\f9113ffe-aa83-42e3-beac-f3359cdc1c15.py'

对应的代码如下：
if page == Mode.LONG_CTX:
    if first_round:
        uploaded_files = st.file_uploader(
            "上传文件",
            type=["pdf", "txt", "py", "docx", "pptx", "json", "cpp", "md"],
            accept_multiple_files=True,
        )
        if uploaded_files and not st.session_state.files_uploaded:
            uploaded_texts = []
            for uploaded_file in uploaded_files:
                file_name: str = uploaded_file.name
                random_file_name = str(uuid4())
                file_extension = os.path.splitext(file_name)[1]
                file_path = os.path.join("/tmp", random_file_name + file_extension)
                with open(file_path, "wb") as f:
                    f.write(uploaded_file.getbuffer())
                if file_name.endswith(".pdf"):
                    content = extract_pdf(file_path)
                elif file_name.endswith(".docx"):
                    content = extract_docx(file_path)
                elif file_name.endswith(".pptx"):
                    content = extract_pptx(file_path)
                else:
                    content = extract_text(file_path)
                uploaded_texts.append(
                    FILE_TEMPLATE.format(file_name=file_name, file_content=content)
                )
                os.remove(file_path)
            st.session_state.uploaded_texts = "\n\n".join(uploaded_texts)
            st.session_state.uploaded_file_nums = len(uploaded_files)
        else:
            st.session_state.uploaded_texts = ""
            st.session_state.uploaded_file_nums = 0
elif page == Mode.VLM:
    if first_round:
        uploaded_image = st.file_uploader(
            "上传图片",
            type=["png", "jpg", "jpeg", "bmp", "tiff", "webp"],
            accept_multiple_files=False,
        )
        if uploaded_image:
            data: bytes = uploaded_image.read()
            image = Image.open(BytesIO(data)).convert("RGB")
            st.session_state.uploaded_image = image
        else:
            st.session_state.uploaded_image = None

### Expected behavior / 期待表现

正常运行

**Comment by lingyezhixing** [comment]
补充信息：
模型使用了int4加载，

config.ts如下
export default {
    LOG_LEVEL: 'debug',

    BROWSER_TIMEOUT: 10000,
    BING_SEARCH_API_URL: 'https://api.bing.microsoft.com/',
    BING_SEARCH_API_KEY: '已配置且有效',

    HOST: 'localhost',
    PORT: 3000,
};

**Comment by hhhh12345678** [comment]
关于browser的问题可以试着找到browser.ts中的这段代码
```
const search = new URLSearchParams({ q: query });
recency_days > 0 && search.append('recency_days', recency_days.toString());
return withTimeout(
  config.BROWSER_TIMEOUT,
  fetch(`${config.BING_SEARCH_API_URL}/search?${search.toString()}`, {
    headers: {
      'Ocp-Apim-Subscription-Key': config.BING_SEARCH_API_KEY,
    }
  })
```
改成
```
const url = new URL(config.BING_SEARCH_API_URL);
url.searchParams.append('q', query);
recency_days > 0 && url.searchParams.append('recency_days', recency_days.toString())
return withTimeout(
  config.BROWSER_TIMEOUT,
  fetch(url, {
    headers: {
      'Ocp-Apim-Subscription-Key': config.BING_SEARCH_API_KEY,
    }
  })
```
重新回到browser下面运行pnpm start，再试试看

**Comment by lingyezhixing** [comment]
已解决，感谢。

**Comment by ctruk** [comment]
> error: parse error: TypeError: Cannot read properties of undefined (reading 'value')

我也有这个问题，请问最后是怎么解决的？

error: parse error: TypeError: Cannot read properties of undefined (reading 'value')

**Comment by ctruk** [comment]
> > error: parse error: TypeError: Cannot read properties of undefined (reading 'value')
> 
> 我也有这个问题，请问最后是怎么解决的？
> 
> error: parse error: TypeError: Cannot read properties of undefined (reading 'value')

我解决了，我错误使用了必应的自定义搜索。应该是没有“自定义(custom)”那个才对。
重新到portal.azure.com创建必应搜索资源”就可以了。(顶部搜索框输入bing search就可以找到)。
希望能对其他相同错误的人有帮助。

**Comment by xufengnian** [comment]
除了上面的bing search而不是custom，我再补充一个坑点吧，BING_SEARCH_API_URL路径后面需要加一个v7.0，原始配置文件里面没有这个v7.0，readme里面有
![image](https://github.com/THUDM/GLM-4/assets/15324125/e8af0f75-7b51-404c-b4f4-0c5e26a94e5f)
顺便提供一个测试bing search key是否有用的脚本

```
import requests
def search_bing(api_key, query):
    # 设置API端点和参数
    url = "https://api.bing.microsoft.com/v7.0/search"
    params = {
        "q": query,  # 搜索查询
        "mkt": "en-US",  # 市场代码
        "count": 1  # 返回结果数量
    }
    headers = {
        "Ocp-Apim-Subscription-Key": api_key  # API密钥
    }

    try:
        # 发送GET请求
        response = requests.get(url, headers=headers, params=params)
        response.raise_for_status()  # 如果请求失败,则引发异常

        # 解析JSON响应
        data = response.json()

        # 提取搜索结果
        if "webPages" in data and "value" in data["webPages"]:
            search_result = data["webPages"]["value"][0]
            print(f"标题: {search_result['name']}")
            print(f"URL: {search_result['url']}")
            print(f"描述: {search_result['snippet']}")
        else:
            print("未找到搜索结果。")

    except requests.exceptions.RequestException as e:
        print(f"请求出错: {e}")

# 设置Bing Search API密钥和搜索查询
api_key = ""  # 替换为你的API密钥
query = "什么是AI"

# 执行搜索
search_bing(api_key, query)
```
如果key没问题，会返回“什么是AI”的搜索结果
![image](https://github.com/THUDM/GLM-4/assets/15324125/68b2e2aa-9600-4623-8e75-4d74bd25b8d1)
