### ISSUE TITLE
请教关于算法原理

### ISSUE THREAD

**Issue by elesun2018** [THUDM/GLM-4#500]
请问GLM 4v是如何做到高分辨图像适配输入的？与CogVLM的区别？
![image](https://github.com/user-attachments/assets/ee3e5f1b-7a4f-4ab6-9926-1bfddef3ba83)
请问图中High-Resolution Cross-Module在项目代码哪个位置可以体现出来

谢谢！

**Comment by elesun2018** [comment]
能否空了解释一下，谢谢

**Comment by elesun2018** [comment]
models/modelscope0731-glm-4v-9b经过AutoModelForCausalLM.from_pretrained
参数量为何Total number of parameters: 13,906,320,896，为啥不是9b  ？？
![image](https://github.com/user-attachments/assets/25120fec-2d8f-4b8a-a866-c0f6374e51b0)
transformer.encoder.layers 为40层
transformer.vision.transformer.layers为63层
encoder参数量:8,158,433,280 || vision参数量:4,279,387,392  || other参数量:1,468,500,224
请问encoder采用的LLM模型是什么？
transformer.vision.linear_proj这层是什么作用？
谢谢！

**Comment by zRzRzRzRzRzRzR** [comment]
我觉得在这里或许能帮助到你查看代码
https://huggingface.co/THUDM/glm-4v-9b/blob/main/visual.py
视觉部分是EVA2CLIPModel，然后encoder采用的LLM模型是什么？这个问题没理解，这是个decoder only模型

**Comment by panzy25** [comment]
> 参数量为何Total number of parameters: 13,906,320,896，为啥不是9b ？？

GLM4V-9B的语言模型部分参数量为9B，加上视觉编码器和适配器模型的参数后总量为13B左右。

> transformer.vision.linear_proj这层是什么作用？

GLM4V-9B中使用MLP作为连接视觉编码器和LLM模型的适配器，参考这一层所在模块来理解这一层在模型中的作用。

**Comment by elesun2018** [comment]
请问GLM4V-9B预训练模型带不带定位能力，可否用GLM4V-9B finetune带有定位能力的任务。

请问GLM4V-9B中MLP是这个transformer.vision.linear_proj么？ft_config.freezeV冻结了所有model.transformer.vision.parameters()

**Comment by elesun2018** [comment]
GLM4V-9B的语言模型"vocab_size": 151552
使用语言模型是什么 chatGLM？具体版本

**Comment by elesun2018** [comment]
请问GLM4V-9B "image_size": 1120 
如一楼 原理图 上面  高分辨率部分
输入到vision部分的尺寸是多少，
有用到两个vit模型？左上方cross-att在代码哪里能体现。谢谢

**Comment by elesun2018** [comment]
![image](https://github.com/user-attachments/assets/b9925630-fab6-4edc-820d-35045e0230f5)
transformer.vision.linear_proj是否对应一楼图中MLP adapter部分？

请问transformer.embedding.word_embeddings层对应一楼原理图中word_embeddings部分，那么tokenizer也是实现text编码，这之间是什么关系，embedding层与tokenizer分词器？谢谢

**Comment by elesun2018** [comment]
请问一楼原理图中右上角decoder部分是否对应模型文件参数transformer.encoder，为啥取名encoder
![image](https://github.com/user-attachments/assets/2e5e6d9e-ed6e-460f-8ed0-97cdde39112c)
VLM输出层是否为：transformer.encoder.final_layernorm -->transformer.output_layer.weight
请问在LLMs后（LLMs内部每个tranformer单元都有两步layernorm操作）为啥还要添加一层final_layernorm 

请问transformer.rotary_pos_emb.inv_freq层不属于transformer.vision也不属于transformer.encoder，大概是在哪个位置？谢谢

**Comment by elesun2018** [comment]
请问transformer.vision模块中存在一层transformer.vision.conv，这个是在vision的输入侧吗，输入的图片先做一层卷积操作？
transformer.vision模块中存在transformer.vision.boi transformer.vision.eoi这个是图片抽取后的特征的开始结束标识，为啥要设置两层参数，即开始结束标识与vision.boi vision.eoi两层参数之间的关系？
请问transformer.vision模块层前后关系是否为：图片输入-->vision.conv --> vision.patch_embedding-->vision.transformer.layers-->vision.linear_proj，哪vision.boi vision.eoi位置应该是？谢谢

**Comment by elesun2018** [comment]
![image](https://github.com/user-attachments/assets/ad68f63d-de8b-4f3b-ae86-47e0e93a12b2)
![image](https://github.com/user-attachments/assets/1dd6ce29-e329-484f-b397-29f8a6fd6d15)
对比vision.transformer与encoder.layers
encoder.layers层结构相对于vision.transformer层结构更为简单，
encoder.layers中input_layernorm mlp post_attention_layernorm均没有偏置参数，为何这样设计？
encoder.layers中mlp.dense_4h_to_h mlp.dense_h_to_4h与vision.transformer中fc1 fc2有什么区别与联系？
encoder.layers中self_attention与vision.transformer中attention结构是一样的吧，即实现了下图操作
![image](https://github.com/user-attachments/assets/8c06cfaf-ff67-428a-8c58-502030bdcec5)
