### ISSUE TITLE
请教关于模型训练

### ISSUE THREAD

**Issue by elesun2018** [THUDM/GLM-4#501]
训练配置：单卡A6000 48G
python finetune_vision.py
per_device_train_batch_size: 1
writer_batch_size=1, 作用？
batch_size=1,
# deepspeed: configs/ds_zero_3.json 未用
generation_config:
max_new_tokens: 512
max_input_length: 512
max_output_length: 512
***** Running training *****
Num examples = 200
Num Epochs = 15
Instantaneous batch size per device = 1
Total train batch size (w. parallel, distributed & accumulation) = 1
Gradient Accumulation steps = 1
Total optimization steps = 3,000
Number of trainable parameters = 6,397,952
训练报错：
File "/root/.cache/huggingface/modules/transformers_modules/modelscope0731-glm-4v-9b/visual.py", line 24, in attention_fn_default
    attn_output = torch.nn.functional.scaled_dot_product_attention(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.22 GiB (GPU 0; 47.54 GiB total capacity; 44.83 GiB already allocated; 1.07 GiB free; 46.13 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

0821更新代码和更新模型文件没有用，仍然OutOfMemoryError
请问finetune最低显存多少？应该如何配置？这个问题还应该从何排查（环境版本？显存爆处的代码）

**Comment by zhipuch** [comment]
https://zhipu-ai.feishu.cn/wiki/QanjwjOuaiWMZ6kdVZfcNZwCnBh
4v相对于chat需要的显存更大，除了peft你可以增加一下其他轻量设置，梯度累积数......

**Comment by elesun2018** [comment]
![image](https://github.com/user-attachments/assets/b9111832-01e6-40f5-bee3-6424fdf8d605)
感谢，尝试一下deepspeed zero 多卡 or 冻结更多的层 or 梯度累积数..

**Comment by elesun2018** [comment]
![image](https://github.com/user-attachments/assets/b9111832-01e6-40f5-bee3-6424fdf8d605)
感谢，尝试一下deepspeed zero 多卡 or 冻结更多的层 or 梯度累积数..

**Comment by elesun2018** [comment]
请问可否使用Deepspeed 使用2*A100将75G显存的训练参数分配到两张卡上面，再使用Zero3进行进一步显存优化。是否可行？
有没有支持Deepspeed Zero3的finetune_vision.py

**Comment by zhipuch** [comment]
> 请问可否使用Deepspeed 使用2*A100将75G显存的训练参数分配到两张卡上面，再使用Zero3进行进一步显存优化。是否可行？ 有没有支持Deepspeed Zero3的finetune_vision.py

config文件夹里有zero3配置，不过8*A100全量微调也会爆显存，这块还在同步，后续会有8卡全量微调的方案，暂时可以冻结vision或着lora微调

**Comment by elesun2018** [comment]
zero3不好用，训练太慢
目前采用lora 冻结vit，单卡28G，可以勉强训练，看下训练后效果如何。

**Comment by elesun2018** [comment]
GLM-4/finetune_demo/finetune_vision.py微调训练时显存变化剧烈变化频率约为30S，显存不稳定，请问是什么原因
  per_device_train_batch_size: 4
![image](https://github.com/user-attachments/assets/465d0ce1-35c7-4bc9-9002-bd58783f5d4c)
请问gradient_accumulation_steps: 1如何设置，设置2 3计算loss是否存在token长度不统一的bug ？
