### ISSUE TITLE
Uncaught exception: Traceback (most recent call last) 运行web端的glm4v模型提示报错

### ISSUE THREAD

**Issue by 949418761** [THUDM/GLM-4#504]
### System Info / 系統信息

Uncaught exception: Traceback (most recent call last): File "D:\Big_model\ChatGLM\GLM-4-main\composite_demo\src\main.py", line 288, in main for response, chat_history in client.generate_stream( File "D:\Big_model\ChatGLM\GLM-4-main\composite_demo\src\clients\hf.py", line 57, in generate_stream for token_text in streamer: File "C:\Miniconda3\envs\VL_model\lib\site-packages\transformers\generation\streamers.py", line 223, in next value = self.text_queue.get(timeout=self.timeout) File "C:\Miniconda3\envs\VL_model\lib\queue.py", line 179, in get raise Empty _queue.Empty

您好我在执行glm4v - 9b模型的时候报错了，显卡是4090 24G。图片和文字一起发送返回的错误

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Uncaught exception: Traceback (most recent call last): File "D:\Big_model\ChatGLM\GLM-4-main\composite_demo\src\main.py", line 288, in main for response, chat_history in client.generate_stream( File "D:\Big_model\ChatGLM\GLM-4-main\composite_demo\src\clients\hf.py", line 57, in generate_stream for token_text in streamer: File "C:\Miniconda3\envs\VL_model\lib\site-packages\transformers\generation\streamers.py", line 223, in next value = self.text_queue.get(timeout=self.timeout) File "C:\Miniconda3\envs\VL_model\lib\queue.py", line 179, in get raise Empty _queue.Empty

您好我在执行glm4v - 9b模型的时候报错了，显卡是4090 24G。图片和文字一起发送返回的错误

### Expected behavior / 期待表现

Uncaught exception: Traceback (most recent call last): File "D:\Big_model\ChatGLM\GLM-4-main\composite_demo\src\main.py", line 288, in main for response, chat_history in client.generate_stream( File "D:\Big_model\ChatGLM\GLM-4-main\composite_demo\src\clients\hf.py", line 57, in generate_stream for token_text in streamer: File "C:\Miniconda3\envs\VL_model\lib\site-packages\transformers\generation\streamers.py", line 223, in next value = self.text_queue.get(timeout=self.timeout) File "C:\Miniconda3\envs\VL_model\lib\queue.py", line 179, in get raise Empty _queue.Empty

您好我在执行glm4v - 9b模型的时候报错了，显卡是4090 24G。图片和文字一起发送返回的错误

**Comment by zhipuch** [comment]
readme地址：https://github.com/THUDM/GLM-4/blob/main/composite_demo/README.md
多模态模式下，用户可以利用 GLM-4V 的多模态理解能力，上传图像并与 GLM-4V 进行多轮对话：
用户可以上传图片，使用 GLM-4-9B的图像理解能力，对图片进行理解。
  本模式必须使用 glm-4v-9b 模型。
  本模式下不支持工具调用和系统提示词。
  模型仅能对一张图片进行理解和联系对话，如需更换图片，需要开启一个新的对话。
  图像支持的分辨率为 1120 x 1120
