### ISSUE TITLE
能支持一下openai的非vllm版本的吗

### ISSUE THREAD

**Issue by levorge** [THUDM/GLM-4#507]
### Feature request  / 功能建议

提供非vllm版openai，内存小的可以量化加载模型，vllm不支持int4精度

### Motivation / 动机

暂无

### Your contribution / 您的贡献

暂无

**Comment by zhipuch** [comment]
INT4精度下模型表现不算很好，暂时不会提供，composite_demo/src/clients有不同启动方式，可以根据自己需要更改

**Comment by levorge** [comment]
测试了下上下文效果要比chatglm3好很多，我主要用来做知识库使用，chatglm3的上下文效果太不稳定了
