### ISSUE TITLE
basic_demo/openai_api_server.py 启动的服务通过流式接口调用没有结果返回

### ISSUE THREAD

**Issue by YassinYin** [THUDM/GLM-4#51]
### System Info / 系統信息

非流式请求有结果返回，应该不是硬件问题

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. 运行basic_demo/openai_api_server.py脚本
2. 调用/v1/chat/completions接口，传入的stream参数为true
3. 没有结果返回
<img width="1150" alt="image" src="https://github.com/THUDM/GLM-4/assets/152459711/f7a7a93f-aa89-41ae-bc65-65ccce70a1b6">
stream为false时有结果返回
<img width="1164" alt="image" src="https://github.com/THUDM/GLM-4/assets/152459711/f728092a-c00f-41df-b60b-8ef6df59dcd5">

### Expected behavior / 期待表现

正常流式返回

**Comment by Qingluan** [comment]
官方已经修改了，昨天我也是改的这个地方
https://github.com/THUDM/GLM-4/blob/1683d673d26a5ca7a82646c22e22ec9d431453e8/basic_demo/openai_api_server.py#L317
