### ISSUE TITLE
Glm4v 支持全量微调吗

### ISSUE THREAD

**Issue by molu-ggg** [THUDM/GLM-4#513]
### Feature request  / 功能建议

Glm4v 支持全量微调吗

### Motivation / 动机

Glm4v 支持全量微调吗

### Your contribution / 您的贡献

Glm4v 支持全量微调吗

**Comment by zRzRzRzRzRzRzR** [comment]
支持，我们提供的脚本就行，但是需要的GPU很多，要使用A100 或者 H100集群
