### ISSUE TITLE
glm-4-flash stop 参数

### ISSUE THREAD

**Issue by UbeCc** [THUDM/GLM-4#514]
### System Info / 系統信息

https://open.bigmodel.cn/api/paas/v4/chat/completions

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/bd2023f1-1118-418f-b57a-24dda0a3b011)

```code
curl "https://open.bigmodel.cn/api/paas/v4/chat/completions" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $ZHIPU_API_KEY" \
    -d '{
        "stream": false,
        "model": "glm-4-flash",
        "max_tokens": 1024,
        "stop": ["\n\n"],
        "messages": [
            {
                "role": "user",
                "content": "The operation $\\otimes$ is defined for all nonzero numbers by $a\\otimes b =\\frac{a^{2}}{b}$. Determine $[(1\\otimes 2)\\otimes 3]-[1\\otimes (2\\otimes 3)]$.\n$\\text{(A)}\\ -\\frac{2}{3}\\qquad\\text{(B)}\\ -\\frac{1}{4}\\qquad\\text{(C)}\\ 0\\qquad\\text{(D)}\\ \\frac{1}{4}\\qquad\\text{(E)}\\ \\frac{2}{3}$"
            }
        ]
    }'
```

### Expected behavior / 期待表现

在第一步推理后终止

**Comment by zhipuch** [comment]
没有很明白你的意思，是想让它输出'\n\n'就停止吗

**Comment by UbeCc** [comment]
> 没有很明白你的意思，是想让它输出'\n\n'就停止吗

是的

**Comment by gyhlearner** [comment]
所以stop sequence特性还没支持吗

**Comment by zhipuch** [comment]
可以到https://github.com/MetaGLM/glm-cookbook提出issue

**Comment by UbeCc** [comment]
> 可以到[https://github.com/MetaGLM/glm-cookbook提出issue](https://github.com/MetaGLM/glm-cookbook%E6%8F%90%E5%87%BAissue)

好的
