### ISSUE TITLE
图像输入问题

### ISSUE THREAD

**Issue by zfxxfeng** [THUDM/GLM-4#515]
### System Info / 系統信息

与官方建议环境一致

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

GLM4 输入porn图像后，输出（抱歉，我无法提供此类信息。如果您有其他问题或需要帮助，请告诉我！），这个限制的标志位在哪里设置呢

### Expected behavior / 期待表现

期待解决

**Comment by zRzRzRzRzRzRzR** [comment]
没有，只对输出进行限制，开源模型没有额外的审核，我们也没有提供开源模型备案服务，因此需要你自己解决
