### ISSUE TITLE
GLM-4V-9B fine-tuning error

### ISSUE THREAD

**Issue by tw-repository** [THUDM/GLM-4#516]
### System Info / 系統信息

Traceback (most recent call last):
File "/home/sa/swift/swift/cli/sft.py", line 5, in
sft_main()
File "/home/sa/swift/swift/utils/run_utils.py", line 32, in x_main
result = llm_x(args, **kwargs)
File "/home/sa/swift/swift/llm/sft.py", line 417, in llm_sft
trainer.train(training_args.resume_from_checkpoint)
File "/home/sa/swift/swift/trainers/mixin.py", line 552, in train
res = super().train(resume_from_checkpoint, *args, **kwargs)
File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/transformers/trainer.py", line 1932, in train
return inner_training_loop(
File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/transformers/trainer.py", line 2268, in _inner_training_loop
tr_loss_step = self.training_step(model, inputs)
File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/transformers/trainer.py", line 3307, in training_step
loss = self.compute_loss(model, inputs)
File "/home/sa/swift/swift/trainers/trainers.py", line 165, in compute_loss
outputs = model(**inputs)
File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1582, in _call_impl
result = forward_call(*args, **kwargs)
File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/accelerate/utils/operations.py", line 819, in forward
return model_forward(*args, **kwargs)
File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/accelerate/utils/operations.py", line 807, in call
return convert_to_fp32(self.model_forward(*args, **kwargs))
File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
return func(*args, **kwargs)
File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/peft/peft_model.py", line 1577, in forward
return self.base_model(
File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
return forward_call(*args, **kwargs)
File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 188, in forward
return self.model.forward(*args, **kwargs)
File "/home/sa/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 1198, in forward
boi_token_pos, eoi_token_pos = input_id.index(self.config.boi_token_id), input_id.index(
ValueError: 151339 is not in list

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

CUDA_VISIBLE_DEVICES=0 swift sft \
    --model_id_or_path /mnt/disk/tw_data/glm-4v-9b \
    --model_type glm4v-9b-chat \
    --dataset /mnt/disk/tw_data/finetune_mllm/SRR_train.json \
    --num_train_epochs 5 \
    --sft_type lora \
    --output_dir /mnt/disk/tw_data/finetune_output \
    --eval_steps 500 \
    --batch_size 1 \
    --max_length 4096\
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --gradient_checkpointing true \
    --weight_decay 0.1 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps $(expr 16 / 3) \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 100 \
    --save_steps 300 \
    --save_total_limit 2 \
    --logging_steps 10 \
    --deepspeed default-zero2

### Expected behavior / 期待表现

Find the cause of the error and fix it to achieve fine-tuning.

**Comment by zhipuch** [comment]
你的数据中是包含纯文本还是说每条数据都有一张图片呢

**Comment by tw-repository** [comment]
每条数据都有一张图片。

**Comment by tw-repository** [comment]
{
  "messages": [
    {
      "role": "user",
      "content": "图片中的动物是什么？",
      "image": "/root/images/0001.jpg"
    },
    {
      "role": "assistant",
      "content": "图片中有一只猫。"
    },
    {
      "role": "user",
      "content": "图片中的猫在做什么？"
    },
    {
      "role": "assistant",
      "content": "这只猫坐在或站在桌子上，桌上有很多食物。"
    }
  ]
}

**Comment by tw-repository** [comment]
每条数据都有一张图片。严格按照所提供的数据格式，形成的整个数据集。也就是和下面这个格式一模一样。两轮对话，第一个带图片，第二个不带。
{
  "messages": [
    {
      "role": "user",
      "content": "图片中的动物是什么？",
      "image": "/root/images/0001.jpg"
    },
    {
      "role": "assistant",
      "content": "图片中有一只猫。"
    },
    {
      "role": "user",
      "content": "图片中的猫在做什么？"
    },
    {
      "role": "assistant",
      "content": "这只猫坐在或站在桌子上，桌上有很多食物。"
    }
  ]
}

**Comment by tw-repository** [comment]
> 你的数据中是包含纯文本还是说每条数据都有一张图片呢

每条数据都有一张图片。严格按照所提供的数据格式，形成的整个数据集。也就是和下面这个格式一模一样。两轮对话，第一个带图片，第二个不带。
{
"messages": [
{
"role": "user",
"content": "图片中的动物是什么？",
"image": "/root/images/0001.jpg"
},
{
"role": "assistant",
"content": "图片中有一只猫。"
},
{
"role": "user",
"content": "图片中的猫在做什么？"
},
{
"role": "assistant",
"content": "这只猫坐在或站在桌子上，桌上有很多食物。"
}
]
}

**Comment by tw-repository** [comment]
> > > 你的数据中是包含纯文本还是说每条数据都有一张图片呢
> > 
> > 
> > 每条数据都有一张图片。严格按照所提供的数据格式，形成的整个数据集。也就是和下面这个格式一模一样。两轮对话，第一个带图片，第二个不带。 { "messages": [ { "role": "user", "content": "图片中的动物是什么？", "image": "/root/images/0001.jpg" }, { "role": "assistant", "content": "图片中有一只猫。" }, { "role": "user", "content": "图片中的猫在做什么？" }, { "role": "assistant", "content": "这只猫坐在或站在桌子上，桌上有很多食物。" } ] }
> 
> 看你的数据是没问题的，151339是的token id，报错原因就是没找到图片，可能是某条数据没有图片，或者图片路径不对？

我查看打印出来的数据是这样的：
[INFO:swift] system: None
[INFO:swift] args.lazy_tokenize: True
[INFO:swift] [INPUT_IDS] [151331, 151333, 151336, 198, 4340, 1657, 2155, 12823, 315, 6915, 24251, 2627, 3590, 11865, 525, 304, 279, 2168, 30, 151337, 3862, 374, 1172, 825, 6915, 24251, 2627, 3590, 5025, 11, 30899, 5625, 13, 151336, 198, 3838, 374, 279, 6915, 24251, 2627, 3590, 5025, 1948, 1817, 1697, 304, 279, 2168, 30, 151337, 785, 6109, 39934, 264, 4445, 315, 29154, 1948, 264, 41114, 323, 39625, 389, 862, 13001, 1899, 13, 2379, 525, 4363, 31456, 862, 2948, 323, 15143, 311, 1817, 1008, 11, 22804, 553, 6993, 594, 13135, 13, 220, 20165, 389, 1493, 42431, 11, 432, 646, 387, 67103, 429, 862, 6915, 24251, 2627, 3590, 5025, 374, 5625, 13, 151329]
[INFO:swift] [INPUT] [gMASK] <sop> <|user|> 
How many different kinds of fine-grained social relationships are in the image? <|assistant|> There is only one fine-grained social relationship, namely couple. <|user|>

请问这个是读取到图像了吗？

**Comment by tw-repository** [comment]
第二个<|user|>后面跟的是一个新的问题，和 <|assistant|> 的回答，最后是<|endoftext|>

**Comment by tw-repository** [comment]
> > > 你的数据中是包含纯文本还是说每条数据都有一张图片呢
> > 
> > 
> > 每条数据都有一张图片。严格按照所提供的数据格式，形成的整个数据集。也就是和下面这个格式一模一样。两轮对话，第一个带图片，第二个不带。 { "messages": [ { "role": "user", "content": "图片中的动物是什么？", "image": "/root/images/0001.jpg" }, { "role": "assistant", "content": "图片中有一只猫。" }, { "role": "user", "content": "图片中的猫在做什么？" }, { "role": "assistant", "content": "这只猫坐在或站在桌子上，桌上有很多食物。" } ] }
> 
> 看你的数据是没问题的，151339是的token id，报错原因就是没找到图片，可能是某条数据没有图片，或者图片路径不对？

这个问题解决了。又出现一个新问题：
Traceback (most recent call last):
  File "/home/sa/swift/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/home/sa/swift/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/home/sa/swift/swift/llm/sft.py", line 417, in llm_sft
    trainer.train(training_args.resume_from_checkpoint)
  File "/home/sa/swift/swift/trainers/mixin.py", line 552, in train
    res = super().train(resume_from_checkpoint, *args, **kwargs)
  File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/transformers/trainer.py", line 1948, in train
    return inner_training_loop(
  File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/transformers/trainer.py", line 2351, in _inner_training_loop
    self.optimizer.step()
AttributeError: 'DummyOptim' object has no attribute 'step'

**Comment by ldh127** [comment]
> > > > 你的数据中是包含纯文本还是说每条数据都有一张图片呢
> > > 
> > > 
> > > 每条数据都有一张图片。严格按照所提供的数据格式，形成的整个数据集。也就是和下面这个格式一模一样。两轮对话，第一个带图片，第二个不带。 { "messages": [ { "role": "user", "content": "图片中的动物是什么？", "image": "/root/images/0001.jpg" }, { "role": "assistant", "content": "图片中有一只猫。" }, { "role": "user", "content": "图片中的猫在做什么？" }, { "role": "assistant", "content": "这只猫坐在或站在桌子上，桌上有很多食物。" } ] }
> > 
> > 
> > 看你的数据是没问题的，151339是的token id，报错原因就是没找到图片，可能是某条数据没有图片，或者图片路径不对？
> 
> 这个问题解决了。又出现一个新问题： Traceback (most recent call last): File "/home/sa/swift/swift/cli/sft.py", line 5, in sft_main() File "/home/sa/swift/swift/utils/run_utils.py", line 32, in x_main result = llm_x(args, **kwargs) File "/home/sa/swift/swift/llm/sft.py", line 417, in llm_sft trainer.train(training_args.resume_from_checkpoint) File "/home/sa/swift/swift/trainers/mixin.py", line 552, in train res = super().train(resume_from_checkpoint, *args, **kwargs) File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/transformers/trainer.py", line 1948, in train return inner_training_loop( File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/transformers/trainer.py", line 2351, in _inner_training_loop self.optimizer.step() AttributeError: 'DummyOptim' object has no attribute 'step'

这个问题解决了吗

**Comment by Hysen-B** [comment]
> > > > 你的数据中是包含纯文本还是说每条数据都有一张图片呢
> > > 
> > > 
> > > 每条数据都有一张图片。严格按照所提供的数据格式，形成的整个数据集。也就是和下面这个格式一模一样。两轮对话，第一个带图片，第二个不带。 { "messages": [ { "role": "user", "content": "图片中的动物是什么？", "image": "/root/images/0001.jpg" }, { "role": "assistant", "content": "图片中有一只猫。" }, { "role": "user", "content": "图片中的猫在做什么？" }, { "role": "assistant", "content": "这只猫坐在或站在桌子上，桌上有很多食物。" } ] }
> > 
> > 
> > 看你的数据是没问题的，151339是的token id，报错原因就是没找到图片，可能是某条数据没有图片，或者图片路径不对？
> 
> 这个问题解决了。又出现一个新问题： Traceback (most recent call last): File "/home/sa/swift/swift/cli/sft.py", line 5, in sft_main() File "/home/sa/swift/swift/utils/run_utils.py", line 32, in x_main result = llm_x(args, **kwargs) File "/home/sa/swift/swift/llm/sft.py", line 417, in llm_sft trainer.train(training_args.resume_from_checkpoint) File "/home/sa/swift/swift/trainers/mixin.py", line 552, in train res = super().train(resume_from_checkpoint, *args, **kwargs) File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/transformers/trainer.py", line 1948, in train return inner_training_loop( File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/transformers/trainer.py", line 2351, in _inner_training_loop self.optimizer.step() AttributeError: 'DummyOptim' object has no attribute 'step'

请问您这个问题是如何解决的呢？我采用了和您一致的格式也出现了151339这个报错，但不知道解决方法。

> > > > 你的数据中是包含纯文本还是说每条数据都有一张图片呢
> > > 
> > > 
> > > 每条数据都有一张图片。严格按照所提供的数据格式，形成的整个数据集。也就是和下面这个格式一模一样。两轮对话，第一个带图片，第二个不带。 { "messages": [ { "role": "user", "content": "图片中的动物是什么？", "image": "/root/images/0001.jpg" }, { "role": "assistant", "content": "图片中有一只猫。" }, { "role": "user", "content": "图片中的猫在做什么？" }, { "role": "assistant", "content": "这只猫坐在或站在桌子上，桌上有很多食物。" } ] }
> > 
> > 
> > 看你的数据是没问题的，151339是的token id，报错原因就是没找到图片，可能是某条数据没有图片，或者图片路径不对？
> 
> 这个问题解决了。又出现一个新问题： Traceback (most recent call last): File "/home/sa/swift/swift/cli/sft.py", line 5, in sft_main() File "/home/sa/swift/swift/utils/run_utils.py", line 32, in x_main result = llm_x(args, **kwargs) File "/home/sa/swift/swift/llm/sft.py", line 417, in llm_sft trainer.train(training_args.resume_from_checkpoint) File "/home/sa/swift/swift/trainers/mixin.py", line 552, in train res = super().train(resume_from_checkpoint, *args, **kwargs) File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/transformers/trainer.py", line 1948, in train return inner_training_loop( File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/transformers/trainer.py", line 2351, in _inner_training_loop self.optimizer.step() AttributeError: 'DummyOptim' object has no attribute 'step'

请问您这个问题是如何解决的呢？我采用了和您一致的json格式也出现了151339这个报错，但不知道解决方法。
