### ISSUE TITLE
微调配置环境时无法安装0.12.2版本的PEFT

### ISSUE THREAD

**Issue by yuanzilin** [THUDM/GLM-4#520]
### System Info / 系統信息

使用requirements.txt配置环境时报错
ERROR: Could not find a version that satisfies the requirement peft==0.12.2 (from versions: 0.0.1, 0.0.2, 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.10.0, 0.11.0, 0.11.1, 0.12.0)
ERROR: No matching distribution found for peft==0.12.2
我用的是Python版本是3.10.14，pip版本也是最新的24.2版，所以不清楚是哪里出了问题

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

同一目录下我有个运行glm4-9B-chat demo的配置文件，所以把微调模型的配置文件改名为requirements_ft.txt了，并且保证内容没有发生改变
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements_ft.txt

### Expected behavior / 期待表现

如果能帮忙指出如何安装0.12.2版本的PEFT或者
指出搜不到对应版本的包是pip的问题还是Python版本的问题就非常感激啦！

**Comment by zhipuch** [comment]
安装0.12.0的试一下

**Comment by zRzRzRzRzRzRzR** [comment]
0.12.0兼容的，安装这个吧，我们是在官方源装的
