### ISSUE TITLE
python3.12语法问题，希望帮忙解决

### ISSUE THREAD

**Issue by AbSomeone** [THUDM/GLM-4#523]
### System Info / 系統信息

提示出错问题点：

File "finetune.py", line 61
    def training_step(self, model: nn.Module, inputs: dict[str, Any]) -> torch.Tensor:
                                 ^
SyntaxError: invalid syntax

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

进行finetunted的时候出现语法问题， python finetune.py  /usr/models/data/  /usr/models/glm-4-9b-chat/  ./configs/lora.yaml

### Expected behavior / 期待表现

python finetune.py  /usr/models/data/  /usr/models/glm-4-9b-chat/  ./configs/lora.yaml 

出现： def training_step(self, model: nn.Module, inputs: dict[str, Any]) -> torch.Tensor:
                                 ^
SyntaxError: invalid syntax

**Comment by zhipuch** [comment]
推荐使用readme环境，不过应该解决了吧
