### ISSUE TITLE
GLM4V-9B微调完成后，如何调用模型，输入一张图像进行对话

### ISSUE THREAD

**Issue by tw-repository** [THUDM/GLM-4#525]
### System Info / 系統信息

GLM4V-9B微调完成后，使用以下命令
CUDA_VISIBLE_DEVICES=0 swift export \
    --ckpt_dir output/glm4v-9b-chat/vx-xxx/checkpoint-xxx \
    --merge_lora true

CUDA_VISIBLE_DEVICES=0 swift infer \
    --ckpt_dir output/glm4v-9b-chat/vx-xxx/checkpoint-xxx-merged \
    --load_dataset_config true

得到了一个checkpoint-xxx-merged文件夹。
文件夹中内容如图：
<img width="458" alt="微信图片_20240830231518" src="https://github.com/user-attachments/assets/51075152-5436-4a80-a15e-d614630dfbfc">

如何使用这个文件夹中的模型？

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

GLM4V-9B微调完成后，使用以下命令
CUDA_VISIBLE_DEVICES=0 swift export \
    --ckpt_dir output/glm4v-9b-chat/vx-xxx/checkpoint-xxx \
    --merge_lora true

CUDA_VISIBLE_DEVICES=0 swift infer \
    --ckpt_dir output/glm4v-9b-chat/vx-xxx/checkpoint-xxx-merged \
    --load_dataset_config true

得到了一个checkpoint-xxx-merged文件夹。

### Expected behavior / 期待表现

能够调用微调后的模型实现单张图像的对话。

**Comment by zRzRzRzRzRzRzR** [comment]
学习infer的方法读入模型，然后直接用cli_vision demo解决

**Comment by tw-repository** [comment]
> 学习infer的方法读入模型，然后直接用cli_vision demo解决

请问有infer的方法读入模型的案例吗？我没有搜到相关的参考资料

**Comment by zRzRzRzRzRzRzR** [comment]
案例是？
我们现在刚准备合并了vllm lora合并

**Comment by elesun2018** [comment]
请问现在是否支持vllm加速
如何才能支持VLLM加速，谢谢  sss

**Comment by sixsixcoder** [comment]
目前已经支持vllm加速推理，暂不支持lora微调后的模型加速，请参见readme
