### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by Alan-zhong** [THUDM/GLM-4#527]
Process finished with exit code -1073741819 (0xC0000005)
启动代码加载模型时报错，请问是为啥啊？

**Comment by zRzRzRzRzRzRzR** [comment]
请给出详细错误信息，包括你的所有系统环境，cuda环境，python环境，运行代码

**Comment by Katieyyy** [comment]
内存不够
