### ISSUE TITLE
low_cpu_mem_usage=True 参数使用上可能有问题

### ISSUE THREAD

**Issue by dogvane** [THUDM/GLM-4#53]
### System Info / 系統信息

win10 系统，e5-2090v4 64G内存 2080ti 22G 显卡
系统关闭虚拟内存

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

low_cpu_mem_usage=True 
在系统已使用内存为21G时（剩余42G），无法启动。(查看系统日志，有提示：Windows 成功诊断出虚拟内存不足的情况。)
关闭一些应用，内存占用15G时，能正常启动。
注销 low_cpu_mem_usage=True 代码后
在系统已使用内存为21G时，能正常启动。

### Expected behavior / 期待表现

这个参数在glm3文档里还没有，看上去是新增的。
从名字上看，应该是降低cpu和内存的使用，但是结果是导致无法启动。
不太清楚是我这边的个例，还是这个参数使用上有什么限制，需要先占用更多的内存做一些其它什么优化。
因为这个会在启动时报错，并且命令行里无任何提示，对新手排查不方便。
如果是参数使用上的问题，建议文档最好删除该参数。

**Comment by zRzRzRzRzRzRzR** [comment]
这个参数是给int4模型搭配使用的，可以不加，无法启动的表现是？

**Comment by dogvane** [comment]
无法启动就是指，在load权重文件时在 8/10 左右时，直接退出，控制台无任何错误输出。
在任务管理器里，看到内存只使用了30G左右，GPU则基本没有使用。
一开始让我怀疑是权重文件下载错误，重新下载权重，还是不行，一次偶然启动成功才发现可能是内存问题。

**Comment by zRzRzRzRzRzRzR** [comment]
复现不了，那可能这个情况你确实不能用这个参数
