### ISSUE TITLE
docker镜像启动vllm后端后，GPU显存一直占用20G左右（不管是否在用)

### ISSUE THREAD

**Issue by WQL782795** [THUDM/GLM-4#530]
### System Info / 系統信息

[root@localhost ~]# docker exec cb001b8e5deb nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
![Uploading smi.jpg…]()

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

使用docker镜像启动vllm后端

### Expected behavior / 期待表现

用多少占多少

**Comment by WQL782795** [comment]
这是smi截图
![smi](https://github.com/user-attachments/assets/8e8e49a3-c186-457d-bdb1-2699107e6497)

**Comment by zhipuch** [comment]
你的gpu_memory_utilization设置多少？它会预分配显存
