### ISSUE TITLE
KeyError: 'messages'

### ISSUE THREAD

**Issue by yxl502** [THUDM/GLM-4#533]
### System Info / 系統信息

KeyError: 'messages'

### Who can help? / 谁可以帮助到您？

KeyError: 'messages'

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

KeyError: 'messages'

### Expected behavior / 期待表现

KeyError: 'messages'

**Comment by gitlab-bingal** [comment]
这个问题为啥关闭了？我也有这个问题
