### ISSUE TITLE
Any forword plain to support llama.cpp

### ISSUE THREAD

**Issue by SolomonLeon** [THUDM/GLM-4#54]
### Feature request  / 功能建议

Llama.cpp provides a simple way to deploy models on server and desktop environment. Looking forward to llama.cpp support.

### Motivation / 动机

-

### Your contribution / 您的贡献

 -

**Comment by panzy25** [comment]
You could refer to [issue #44](https://github.com/THUDM/GLM-4/issues/44#issuecomment-2150024565), which has been replied from the Official team in Chinese.

Here is the translation of the original Chinese text:

"The model architecture that supports GLM4 and GLM4V is different from llama. Therefore, the code of llama.cpp needs to be modified and a PR needs to be merged. This will take some time. Thank you for your attention."
