### ISSUE TITLE
微调 GLM-4-9B-chat，自制数据集，提示 ValueError: 151337 is not in list 

### ISSUE THREAD

**Issue by CradleArc** [THUDM/GLM-4#544]
### System Info / 系統信息

最新的 GLM-4 仓库，模型文件是8月23号下载的，看了近期没有更新。
cuda 12.2, 
nvidia-smi 535.183.01，
四卡4090，
python ==3..10.12，
transformers ==4.44.0，
torch ==2.4.0
datasets == 2.20.0

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

执行命令：CUDA_VISIBLE_DEVICES=0,1,2,3 OMP_NUM_THREADS=1 torchrun --standalone --nnodes=1 --nproc_per_node=4 finetune.py data/ /home/zysd/DownloadModel/glm-4-9b-chat configs/lora.yaml

### Expected behavior / 期待表现

希望能够解决！

**Comment by Lzzzii10** [comment]
请教下 如何解决的呢？

**Comment by CradleArc** [comment]
数据集的问题，文本过长，可以筛选文本过长的数据。



---- 回复的原邮件 ----
| 发件人 | Liu ***@***.***> |
| 日期 | 2024年09月13日 11:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [THUDM/GLM-4] 微调 GLM-4-9B-chat，自制数据集，提示 ValueError: 151337 is not in list  (Issue #544) |

请教下 如何解决的呢？

**Comment by li-hhhh** [comment]
请问是通过修改数据集而解决的问题吗？

**Comment by JohnYehyo** [comment]
相同的问题, 看了别的答案尝试将combine设置为false, 也不行

**Comment by li-hhhh** [comment]
> 相同的问题, 看了别的答案尝试将combine设置为false, 也不行

我将transformers换成了4.40.2版本，并且将eval_strategy屏蔽了，然后就能运行成功了

**Comment by CradleArc** [comment]
我用的是最新的 仓库和模型权重，然后你用 代码编辑器（vscode） 查看 jsonl 数据集，有没有异常的，这个错误本身就是提示数据集 值错误
