### ISSUE TITLE
想请问下glm-4v-9b支持 输入一段视频进行分析总结吗？

### ISSUE THREAD

**Issue by 948024326** [THUDM/GLM-4#549]
### System Info / 系統信息

如题

### Who can help? / 谁可以帮助到您？

@zR

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

如题

### Expected behavior / 期待表现

如题

**Comment by zRzRzRzRzRzRzR** [comment]
不支持，这是一个图片理解模型，不是视频
