### ISSUE TITLE
请教一下decoder部分

### ISSUE THREAD

**Issue by Enermy** [THUDM/GLM-4#552]
大佬，请问解码器推理部分的代码是在哪个地方啊？

**Comment by zhipuch** [comment]
是解码代码本身还是解码过程呢？解码代码是inference.py，模型文件是在下载的模型目录中

**Comment by Enermy** [comment]
> 是解码代码本身还是解码过程呢？解码代码是inference.py，模型文件是在下载的模型目录中

我希望对解码输出的时候对下一个词的预测输出概率进行修改，就是我会导入一个词表，然后在解码输出的时候优先输出词表中的词，请问大佬在哪里修改解码推理输出的过程呢？

**Comment by zhipuch** [comment]
> > 是解码代码本身还是解码过程呢？解码代码是inference.py，模型文件是在下载的模型目录中
> 
> 我希望对解码输出的时候对下一个词的预测输出概率进行修改，就是我会导入一个词表，然后在解码输出的时候优先输出词表中的词，请问大佬在哪里修改解码推理输出的过程呢？

那我觉得你要在采样的过程中进行修改，推理代码中有model.generate，这个generate函数你可以从finetune训练代码中回溯出来的，找到sample相关函数就行了

**Comment by Enermy** [comment]
> > > 是解码代码本身还是解码过程呢？解码代码是inference.py，模型文件是在下载的模型目录中
> > 
> > 
> > 我希望对解码输出的时候对下一个词的预测输出概率进行修改，就是我会导入一个词表，然后在解码输出的时候优先输出词表中的词，请问大佬在哪里修改解码推理输出的过程呢？
> 
> 那我觉得你要在采样的过程中进行修改，推理代码中有model.generate，这个generate函数你可以从finetune训练代码中回溯出来的，找到sample相关函数就行了

若下个预测输出词有词表中的词，则提高这个词所占的权重从而提高这个词输出的概率，请问这样可行吗？

**Comment by zhipuch** [comment]
> > > > 是解码代码本身还是解码过程呢？解码代码是inference.py，模型文件是在下载的模型目录中
> > > 
> > > 
> > > 我希望对解码输出的时候对下一个词的预测输出概率进行修改，就是我会导入一个词表，然后在解码输出的时候优先输出词表中的词，请问大佬在哪里修改解码推理输出的过程呢？
> > 
> > 
> > 那我觉得你要在采样的过程中进行修改，推理代码中有model.generate，这个generate函数你可以从finetune训练代码中回溯出来的，找到sample相关函数就行了
> 
> 若下个预测输出词有词表中的词，则提高这个词所占的权重从而提高这个词输出的概率，请问这样可行吗？

模型会学习输出哪个token，为什么要干扰这个过程呢没太明白

**Comment by Enermy** [comment]
> > > > > 是解码代码本身还是解码过程呢？解码代码是inference.py，模型文件是在下载的模型目录中
> > > > 
> > > > 
> > > > 我希望对解码输出的时候对下一个词的预测输出概率进行修改，就是我会导入一个词表，然后在解码输出的时候优先输出词表中的词，请问大佬在哪里修改解码推理输出的过程呢？
> > > 
> > > 
> > > 那我觉得你要在采样的过程中进行修改，推理代码中有model.generate，这个generate函数你可以从finetune训练代码中回溯出来的，找到sample相关函数就行了
> > 
> > 
> > 若下个预测输出词有词表中的词，则提高这个词所占的权重从而提高这个词输出的概率，请问这样可行吗？
> 
> 模型会学习输出哪个token，为什么要干扰这个过程呢没太明白

导安排的任务，要求生成具有地方特色的对话，多谢大佬指点。
