### ISSUE TITLE
GLM-4V-9b多GPU推理

### ISSUE THREAD

**Issue by XuJWood** [THUDM/GLM-4#554]
### System Info / 系統信息

环境都是没问题的

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

model = AutoModelForCausalLM.from_pretrained(
    "/mnt/ddata/models/glm-4v-9b",
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True
).to(device).eval() 单GPU这一部分报错

### Expected behavior / 期待表现

4090下如何设置多GPU的推理

**Comment by sixsixcoder** [comment]
请不要新开issus。quote “Originally posted by @sixsixcoder in https://github.com/THUDM/GLM-4/issues/554#issuecomment-2337733396
import torch
from PIL import Image
from transformers import AutoModelForCausalLM, AutoTokenizer

device = "cuda"

tokenizer = AutoTokenizer.from_pretrained("THUDM/glm-4v-9b", trust_remote_code=True)

query = '描述这张图片'
image = Image.open("your image").convert('RGB')
inputs = tokenizer.apply_chat_template([{"role": "user", "image": image, "content": query}],
add_generation_prompt=True, tokenize=True, return_tensors="pt",
return_dict=True) # chat mode

inputs = inputs.to(device)
model = AutoModelForCausalLM.from_pretrained(
"THUDM/glm-4v-9b",
torch_dtype=torch.bfloat16,
low_cpu_mem_usage=True,
trust_remote_code=True
).to(device).eval()

gen_kwargs = {"max_length": 2500, "do_sample": True, "top_k": 1}
with torch.no_grad():
outputs = model.generate(**inputs, **gen_kwargs)
outputs = outputs[:, inputs['input_ids'].shape[1]:]
print(tokenizer.decode(outputs[0]))

这个开始的脚本”

**Comment by sixsixcoder** [comment]
我使用你的脚本，没有做任何改动。在cuda 12.3，transformers==4.44.0, torch==2.4.0, torchvision==0.19.0测试没有出现报错，如果要设置多GPU的推理，请将部分代码按照这样修改：

**Comment by XuJWood** [comment]
谢谢,已解决！
