### ISSUE TITLE
你使用的哪个推理脚本

### ISSUE THREAD

**Issue by XuJWood** [THUDM/GLM-4#555]
你使用的哪个推理脚本

_Originally posted by @sixsixcoder in https://github.com/THUDM/GLM-4/issues/554#issuecomment-2337733396_
            import torch
from PIL import Image
from transformers import AutoModelForCausalLM, AutoTokenizer

device = "cuda"

tokenizer = AutoTokenizer.from_pretrained("THUDM/glm-4v-9b", trust_remote_code=True)

query = '描述这张图片'
image = Image.open("your image").convert('RGB')
inputs = tokenizer.apply_chat_template([{"role": "user", "image": image, "content": query}],
                                       add_generation_prompt=True, tokenize=True, return_tensors="pt",
                                       return_dict=True)  # chat mode

inputs = inputs.to(device)
model = AutoModelForCausalLM.from_pretrained(
    "THUDM/glm-4v-9b",
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True
).to(device).eval()

gen_kwargs = {"max_length": 2500, "do_sample": True, "top_k": 1}
with torch.no_grad():
    outputs = model.generate(**inputs, **gen_kwargs)
    outputs = outputs[:, inputs['input_ids'].shape[1]:]
    print(tokenizer.decode(outputs[0]))

这个开始的脚本

**Comment by sixsixcoder** [comment]
该issus已在 https://github.com/THUDM/GLM-4/issues/554 上回复，请前往查看，本issus关闭。
