### ISSUE TITLE
GLM4对长文档作为训练数据的情况

### ISSUE THREAD

**Issue by cangyizhou** [THUDM/GLM-4#557]
### Feature request  / 功能建议

您好，请问GLM4微调时每一条数据的最大长度大概是多少？比如在实体识别的微调中，如果input不是一句话而是一篇长文档可以微调成功吗？

### Motivation / 动机

希望对GLM4微调的数据形式有更多了解

### Your contribution / 您的贡献

。

**Comment by sixsixcoder** [comment]
Seq Length参数就是最大长度，我们还推出了支持 1M 上下文长度（约 200 万中文字符）的 GLM-4-9B-Chat-1M 模型，详情请看readme：[https://github.com/THUDM/GLM-4/blob/main/README.md](url)
