### ISSUE TITLE
GLM4v首token时延较长是否有优化计划？

### ISSUE THREAD

**Issue by ZhuangPeiyu** [THUDM/GLM-4#558]
目前测试了一下，在V100上面，GLM4v只要有图像输入，首token输出的时延基本上在12s左右，请问这个后续是否有优化的计划呢？

**Comment by zRzRzRzRzRzRzR** [comment]
这个是因为每次都要算第一个图像的embeding，其实token输入远远比你输入的长（ + 2307) 左右的图片embed，所以V100等老卡设备响应比较慢
