### ISSUE TITLE
执行微调文件finetune.py显示TypeError: FinetuningConfig.__init__() got an unexpected keyword argument 'freezeV'

### ISSUE THREAD

**Issue by bird2580** [THUDM/GLM-4#561]
### System Info / 系統信息

环境cuda 12.1   py3.10  显卡3090 D
![E4694F355A222BFE2312C219323F418F](https://github.com/user-attachments/assets/8450d9bb-19e4-49ad-a3f8-eafd2dd1a58f)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![E4694F355A222BFE2312C219323F418F](https://github.com/user-attachments/assets/b9867ca2-a1ec-4b87-b3d6-cd92c8c2d643)

### Expected behavior / 期待表现

成功微调

**Comment by zhipuch** [comment]
在FinetuningConfig类中添加这个参数，指定是bool类型，后续会同步一下这里
