### ISSUE TITLE
对于同一个问题，多条输出和单条输出答案不一致。

### ISSUE THREAD

**Issue by J-G-Y** [THUDM/GLM-4#564]
### System Info / 系統信息

11

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

111

### Expected behavior / 期待表现

do_sample 关闭，这时候模型对于相同问题的每次输出应该是一致的，但是实际使用中，假设只推理该问题，那么每次会得到一致的输出，但是当多条推理时，也就是这条数据前有别的问题时，模型的输出发生了变化。为了消除历史数据的影响，已经将history手动置为空。求大神们解惑。

**Comment by siaowei80** [comment]
请提供详细的环境系统信息，模型信息和推理代码

**Comment by J-G-Y** [comment]
torch :1.13.1
CUDA:11.6
python:3.8
model：ChatGLM-6B(那边Issue基本没有回复了，才来这里请教一下)
调用的model.stream_chat（）
![微信截图_20240918142743](https://github.com/user-attachments/assets/389e09a8-3601-4994-8bc1-802e0cc2643f)
![微信截图_20240918142753](https://github.com/user-attachments/assets/9b40707a-3661-4bea-91e4-233824a13a48)

**Comment by zRzRzRzRzRzRzR** [comment]
啊，那个模型我们也不太了解，我们现在维护的是GLM-4

不过，正常来说，你这个实现方法应该是对的，同时建议把seed换成一样的，top p 和temperature改成 0

**Comment by RickyLili** [comment]
固定seed应该就好了
from accelerate.utils import set_seed
set_seed(seed: int)

**Comment by J-G-Y** [comment]
> 固定seed应该就好了 from accelerate.utils import set_seed set_seed(seed: int)

尝试过from transformers import set_seed()  set_seed(seed;int) 但是没解决问题，accelerate里面的种子是设置的GPU的随机数嘛
