### ISSUE TITLE
request for gradio demo for GLM4-vision

### ISSUE THREAD

**Issue by MontaEllis** [THUDM/GLM-4#57]
### Feature request  / 功能建议

gradio demo for GLM4-vision

### Motivation / 动机

None

### Your contribution / 您的贡献

None

**Comment by zRzRzRzRzRzRzR** [comment]
可以直接基于目前的trans web demo直接改，完全一样，仅需要上传一张图片作为第一段对话的修改，这时候的image是PIL读取的图的格式

**Comment by MontaEllis** [comment]
可以麻烦您提供一个web demo吗？我修改的有bug
