### ISSUE TITLE
以 float16 加载 GLM-4-9B 模型，但是最终 dtype 为 bfloat16

### ISSUE THREAD

**Issue by condy0919** [THUDM/GLM-4#570]
### System Info / 系統信息

| 组件 | 版本 |
|-----|-----|
| cuda | 12.1 |
| transformers | 4.44.0 |
| python | 3.10.14 |

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR 

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

```python
import torch
from transformers import AutoModelForCausalLM, AutoConfig, AutoTokenizer


def load_model(path):
    config = AutoConfig.from_pretrained(path, trust_remote_code=True)
    tokenizer = AutoTokenizer.from_pretrained(path, trust_remote_code=True)
    model = AutoModelForCausalLM.from_pretrained(
        path, config=config, torch_dtype=torch.float16, trust_remote_code=True
    )

    print(f"{path}.dtype = {model.dtype}")
    return model, tokenizer


glm4, glm4_tokenizer = load_model("THUDM/glm-4-9b-chat")
llama3, llama3_tokenizer = load_model("/path/to/models--meta-llama--Llama-3.1-8b-hf")
```

运行如上代码，以 float16 类型加载模型，发现 glm4 的 dtype 为 bfloat16，而 llama3.1 的则为 float16. 两者模型的 config.json 里 torch_dtype 默认都为 bfloat16.

另外我发现，如果是在加载 config 时重写 torch_dtype，最终是能够达到都以 float16 加载的目标的。

### Expected behavior / 期待表现

输出都为 `torch.float16`.

**Comment by zhipuch** [comment]
说白了AutoModelForCausalLM.from_pretrained可以同时传dtype和config，这个config中也有dtype参数的时候优先级更高，你把config这个参数删了再打印就是你自己传的dtype了，可以看一下它的源代码。

**Comment by condy0919** [comment]
源码看过了，这里与其他 transformers 模型处理有点不一致，我相信会有其他人有同样的疑问

**Comment by zhipuch** [comment]
> 源码看过了，这里与其他 transformers 模型处理有点不一致，我相信会有其他人有同样的疑问

嗯嗯，glm4系列模型用bf16，其他fp16可能会出问题的
