### ISSUE TITLE
TypeError: AsyncEngineArgs.__init__() got an unexpected keyword argument 'engine_use_ray'

### ISSUE THREAD

**Issue by liuliwei91** [THUDM/GLM-4#573]
### System Info / 系統信息

TypeError: AsyncEngineArgs.__init__() got an unexpected keyword argument 'engine_use_ray'
![无标题](https://github.com/user-attachments/assets/89e9875b-7b7c-455f-aff6-56ea9fd477e3)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

python openai_api_server.py

### Expected behavior / 期待表现

python openai_api_server.py

**Comment by zRzRzRzRzRzRzR** [comment]
我们注意到了，现在先暂时移除这个参数。我们之后会改demo
