### ISSUE TITLE
AttributeError: 'CachedChatGLM4Tokenizer' object has no attribute 'vocab'

### ISSUE THREAD

**Issue by LuckLittleBoy** [THUDM/GLM-4#579]
### System Info / 系統信息

vllm docker cpu版本

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

使用vllm本地部署glm-4-9b-chat，使用工具调用时报错，这个是什么原因呢？

docker run -v /home/lantrack/vllm/vllm-model/modelscope:/root/.cache/modelscope --env "VLLM_USE_MODELSCOPE=True" -p 8001:8000 --ipc host -d --name vllm vllm-cpu-env --model ZhipuAI/glm-4-9b-chat --trust-remote-code --max-model-len 104848 --enable-auto-tool-choice --tool-call-parser hermes

### Expected behavior / 期待表现

需要通过--chat-template指定tokenizer_config.json吗？

**Comment by binfox1** [comment]
请问AttributeError: 'CachedChatGLM4Tokenizer' object has no attribute 'vocab' #579这个问题  最后是如何解决的

**Comment by LuckLittleBoy** [comment]
> 请问AttributeError: 'CachedChatGLM4Tokenizer' object has no attribute 'vocab' #579这个问题 最后是如何解决的

换个模型﹌

**Comment by binfox1** [comment]
我现在只想用智谱旗下的模型测试，换成哪个？还是说换了其他家的模型？ 我看你用的glm-4-9b-chat ，我这边用的GLM3_32B_Chat_BF16  一样的报错

**Comment by LuckLittleBoy** [comment]
> 我现在只想用智谱旗下的模型测试，换成哪个？还是说换了其他家的模型？ 我看你用的glm-4-9b-chat ，我这边用的GLM3_32B_Chat_BF16 一样的报错

我当时换了qwen2了，刚看了下huggingface，你可以试下用glm-4-9b-hf，具体原因可以查看：https://huggingface.co/THUDM/glm-4-9b-chat/discussions/81

**Comment by LuckLittleBoy** [comment]
希望能帮助到你

**Comment by binfox1** [comment]
好的 感谢你的解答
