### ISSUE TITLE
GLM4-9B-Chat是否支持类似system的角色定义？

### ISSUE THREAD

**Issue by WinstonCHEN1** [THUDM/GLM-4#587]
GLM4-9B-Chat，对本地模型进行请求时是否可以设置模型的system或role？如果可以，应该怎么实现？还是说，只能在user的prompt里面进行限制呢？即类似下图：
<img width="434" alt="image" src="https://github.com/user-attachments/assets/085feb31-4609-4d0d-a554-7d70ff80e506">

**Comment by sixsixcoder** [comment]
请详细说明你的问题

**Comment by WinstonCHEN1** [comment]
> 请详细说明你的问题

问题已经解决，直接使用文档中的推理方式是更快的
