### ISSUE TITLE
glm-4-9b-chat模型  RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by Kalahari18** [THUDM/GLM-4#588]
### System Info / 系統信息

cuda12.4 transformers4.45.0 torch2.4

### Who can help? / 谁可以帮助到您？

@

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.执行basic_demo/trans_web_demo.py
2.对话框输入 你好

### Expected behavior / 期待表现

希望帮忙解决

**Comment by sixsixcoder** [comment]
尝试更新gradio至5.0.2

**Comment by Andy1018** [comment]
@Kalahari18 请问问题解决了么，如何解决的？遇到了同样的问题
