### ISSUE TITLE
chatglm.cn这个链接是什么模型呢？

### ISSUE THREAD

**Issue by lucy3589** [THUDM/GLM-4#589]
链接：https://chatglm.cn/main/alltoolsdetail?lang=zh
这个链接的模型挺好用。但是不知道这个具体是什么模型？chatglm4-9b吗？但是也支持多模态
这个模型有没有开源呢？

不过glm-4v-9b不太好用（https://huggingface.co/spaces/Jimhugging/GLM-4-DOC）

**Comment by sixsixcoder** [comment]
toC端的产品问题请咨询相关客服
