### ISSUE TITLE
python3.10.8安装依赖，找不到合适的包(bitsandbytes)

### ISSUE THREAD

**Issue by lizhao-8202** [THUDM/GLM-4#590]
### System Info / 系統信息

操作系统：Centos7.9
Python:3.10.8
Pip:24.2
OpenSSL:3.0.14

当我在basic-demo目录，运行命令安装依赖包时报错。运行命令为：
pip3 install -r requirements.txt

运行结果如下（省略了其他正常找到的）
ERROR: Could not find a version that satisfies the requirement bitsandbytes>=0.43.3 (from versions: 0.31.8, 0.32.0, 0.32.1, 0.32.2, 0.32.3, 0.33.0, 0.33.1, 0.34.0, 0.35.0, 0.35.1, 0.35.2, 0.35.3, 0.35.4, 0.36.0, 0.36.0.post1, 0.36.0.post2, 0.37.0, 0.37.1, 0.37.2, 0.38.0, 0.38.0.post1, 0.38.0.post2, 0.38.1, 0.39.0, 0.39.1, 0.40.0, 0.40.0.post1, 0.40.0.post2, 0.40.0.post3, 0.40.0.post4, 0.40.1, 0.40.1.post1, 0.40.2, 0.41.0, 0.41.1, 0.41.2, 0.41.2.post1, 0.41.2.post2, 0.41.3, 0.41.3.post1, 0.41.3.post2, 0.42.0)
ERROR: No matching distribution found for bitsandbytes>=0.43.3

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

升级ssl
源码安装python3.10.8
进入代码目录的/basic_demo
运行pip3 install -r requirements.txt

### Expected behavior / 期待表现

请各位大佬帮指正下我这是出在哪儿的问题，下一步我应该怎么操作

**Comment by sixsixcoder** [comment]
你先尝试更新pip版本，`pip install --upgrade`
如果还不行的话，把这个`bitsandbytes`包注释掉再重新执行，`pip3 install -r requirements.txt`

**Comment by lizhao-8202** [comment]
通过注释对应代码解决了。不过如果真的需要用到那，bitsandbytes选择一个非requirements.txt的版本可以吗，或者直接手动下对应版本的源码或二进制文件装

**Comment by sixsixcoder** [comment]
bitsandbytes通常在int4类型量化时会用到，如果你不用int4类型推理，应该不会出问题，如果确实需要这个包，你可以参考bitsandbytes官方的一些用法

**Comment by lizhao-8202** [comment]
感谢感谢。

**Comment by lizhao-8202** [comment]
解决

**Comment by lwz1357** [comment]
出现这个问题是因为bitsandbytes 0.42.0之后的版本没有对Centos 7系统做适配
