### ISSUE TITLE
To Submit a Security Disclosure

### ISSUE THREAD

**Issue by ZihanWangKi** [THUDM/GLM-4#592]
### System Info / 系統信息

This issue is not related with an operating environment.

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Dear ChatGLM Team,

We are researchers from the University of California, San Diego (UCSD), and we would like to make a security disclosure regarding your product, ChatGLM. We have previously attempted to reach out through email and contact forms but have not received a response. As we are unsure whether our messages have been successfully delivered, we are reaching out here as a last resort in the hopes that you can direct us to the appropriate contact for this matter.

Thank you for your attention to this issue. We look forward to your guidance.

Sincerely,
Zihan Wang

### Expected behavior / 期待表现

We'd appreciate it if you can point us to the right contact for making a security disclosure.

**Comment by zRzRzRzRzRzRzR** [comment]
I apologize, we indeed did not receive the message. We have seen this issue. Could you please let us know which email address you contacted? Would it be possible to send a specific piece of information to `opensource@zhipuai.cn`, we would be very grateful.

**Comment by ZihanWangKi** [comment]
Thanks for the prompt reply! We contacted service@zhipuai.cn (Sep 18, in Pacific Time), security@zhipuai.cn (Sep 18), and chatglm@zhipuai.cn (Sep 22). We have just sent our disclosure package to the open source email account you sent above from efernandes@ucsd.edu.

**Comment by zRzRzRzRzRzRzR** [comment]
We have received this email and are processing it.
Once there is new progress, we will reply as soon as possible.

**Comment by ZihanWangKi** [comment]
Hello! I just wanted to follow-up to check if any progress has been made.
