### ISSUE TITLE
用xinference无法加载4-bit的glm-4-9b-chat

### ISSUE THREAD

**Issue by bunnieberrie** [THUDM/GLM-4#596]
### System Info / 系統信息

CUDA=12.4
transformers=4.44.2
torch=2.4.1+cu124
OS=windows 11 23H2
python=3.11.10

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

使用xinference加载4-bit的glm4时提示如下

ValueError: [address=127.0.0.1:6898, pid=35832] Only 8-bit quantization is supported if it is not linux system or cuda device

### Expected behavior / 期待表现

想了解一下是CUDA版本不对还是其他原因

**Comment by zRzRzRzRzRzRzR** [comment]
xinfer支持吗，这个我们不太清楚
