### ISSUE TITLE
hugging face transformers 4.45.0与vllm 0.6.3结果不一致

### ISSUE THREAD

**Issue by tuanhe** [THUDM/GLM-4#598]
### System Info / 系統信息

RTX3090

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

相同的参数配置，temperature都配置为0，同一张图片，相同的text promt，得到的结果不一致
图片：
![image_99](https://github.com/user-attachments/assets/d524fa89-b097-4720-ba2c-267486dde5a1)

"text": "请提取图中的文字信息",

参数：

 messages=messages,
        stream=use_stream,
        max_tokens=256,
        temperature=0.0,
        presence_penalty=1.2,
        top_p=0.8,

hf：'图片展示了一个古代建筑的大门，大门左右两边和上边各挂了三面红色旗帜，每面旗帜上都有不同的字符。大门左右两边的旗帜上写着“天龙八部”，上边的旗帜上写着“大理天龙八部影视城欢迎您”。城门左右两边和上边各挂了三串黄色小旗子。城门是拱形的，中间有一个牌匾，牌匾的背景颜色是黑色，内容是金色字体，内容为“天龙八部影视城”。城门左右两边各有一块石碑，左边的石碑写着“神书神侠倚碧”，右边的石碑写着“雪连天射白鹿”。城门里面是影视城，里面有一些建筑。
vllm: 这是一张展示古代建筑的照片。图片中，一座古老的城门巍然屹立，城门上装饰着红色的横幅和灯笼，上面写着“大理天龙八部影视城欢迎您”。城门的两侧挂着写有金色文字的红色旗帜，城门前有一位身穿传统服饰的人正在行走。\n\n整个场景给人一种庄重、神秘的感觉，仿佛穿越时空回到了古代。

### Expected behavior / 期待表现

两个结果接近一致

**Comment by sixsixcoder** [comment]
您是否能定位到问题点

**Comment by tuanhe** [comment]
> 您是否能定位到问题点

不能。。。。
