### ISSUE TITLE
glm-4v-9b支持在910B上部署么

### ISSUE THREAD

**Issue by ZXP8080** [THUDM/GLM-4#601]
### System Info / 系統信息

glm-4v-9b支持在910B上部署么

### Who can help? / 谁可以帮助到您？

@Z

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

期望实现910B上部署glm-4-9b

### Expected behavior / 期待表现

期望实现910B上部署glm-4-9b

**Comment by sixsixcoder** [comment]
可以参考https://github.com/THUDM/GLM-4/issues/568
