### ISSUE TITLE
请问可以在glm4-9b-chat上添加即插即用模块PPLM吗？

### ISSUE THREAD

**Issue by Enermy** [THUDM/GLM-4#602]
请问可以在glm4-9b-chat上添加即插即用模块PPLM吗？https://github.com/uber-research/PPLM，若可以的话应该在哪里进行修改呢？

**Comment by Enermy** [comment]
想控制LLM生成可控文本以及能够押韵的文本。最好是不用训练的，若有更好的解决方法，请大佬指点一下，十分感谢！

**Comment by sixsixcoder** [comment]
您好，GLM4暂时没有添加PPLM模块的计划，如果您使用PPLM遇到GLM4相关的问题或者报错信息，可以提新的issue，我们尽力帮您解决。
