### ISSUE TITLE
执行basic_demo\vllm_cli_demo.py报错

### ISSUE THREAD

**Issue by minglong-huang** [THUDM/GLM-4#606]
### System Info / 系統信息

显卡A100 独立创建的conda环境 直接install requirement.txt

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

问题：下载了最新版本的代码，然后执行basic_demo\vllm_cli_demo.py 出现报错
报错如下：
GLM-4: [rank0]: Traceback (most recent call last):
[rank0]:   File "/home/kelvin/nlp/GLM-4/basic_demo/vllm_cli_demo.py", line 119, in <module>
[rank0]:     asyncio.run(chat())
[rank0]:   File "/home/kelvin/anaconda3/envs/vllm/lib/python3.10/asyncio/runners.py", line 44, in run
[rank0]:     return loop.run_until_complete(main)
[rank0]:   File "/home/kelvin/anaconda3/envs/vllm/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
[rank0]:     return future.result()
[rank0]:   File "/home/kelvin/nlp/GLM-4/basic_demo/vllm_cli_demo.py", line 112, in chat
[rank0]:     async for output in vllm_gen(LORA_PATH, enable_lora, messages, top_p, temperature, max_length):
[rank0]:   File "/home/kelvin/nlp/GLM-4/basic_demo/vllm_cli_demo.py", line 77, in vllm_gen
[rank0]:     sampling_params = SamplingParams(**params_dict)
[rank0]: TypeError: Unexpected keyword argument 'use_beam_search'
我查看了类的定义 是有相关的参数在的，但是不知道为什么就报错了

### Expected behavior / 期待表现

麻烦描述下原因 帮忙解决一下 谢谢

**Comment by sixsixcoder** [comment]
可以尝试降低vllm版本，<=0.6.1

**Comment by minglong-huang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by minglong-huang** [comment]
好咧 其实我都尝试了 包括transformers的版本等等啥的 后来发现我重新拉取了hugging上除模型权重文件外的其他文件并更新到服务器之后 它又可以跑通了
