### ISSUE TITLE
ValueError: Unrecognized configuration class <class  'transformers_modules.THUDM.glm-4-9b-chat.eb55a443d66541f30869f6caac5ad0d2e95bcbaa.configuration_chatglm.ChatGLMConfig'>OSError: /tiamat-NAS/boyang/GLM4/gjm/1024/checkpoint-2000 does not appear to have a file named THUDM/glm-4-9b-chat--configuration_chatglm.py. Checkout  'https://huggingface.co//tiamat-NAS/boyang/GLM4/gjm/1024/checkpoint-2000/None' for available files.

### ISSUE THREAD

**Issue by LolerPanda** [THUDM/GLM-4#609]
### System Info / 系統信息

python inference.py /tiamat-NAS/boyang/GLM4/gjm/1024/checkpoint-6000
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [01:37<00:00, 12.15s/it]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /tiamat-vePFS/share_data/boyang/llms/GLM-4/finetune_demo/inference.py:116 in main                │
│                                                                                                  │
│   113 │   #     }                                                                                │
│   114 │   # ]                                                                                    │
│   115 │                                                                                          │
│ ❱ 116 │   model, tokenizer = load_model_and_tokenizer(model_dir)                                 │
│   117 │   inputs = tokenizer.apply_chat_template(                                                │
│   118 │   │   messages,                                                                          │
│   119 │   │   add_generation_prompt=True,                                                        │
│                                                                                                  │
│ /tiamat-vePFS/share_data/boyang/llms/GLM-4/finetune_demo/inference.py:43 in                      │
│ load_model_and_tokenizer                                                                         │
│                                                                                                  │
│    40 │   │   │   torch_dtype=torch.bfloat16                                                     │
│    41 │   │   )                                                                                  │
│    42 │   │   tokenizer_dir = model_dir                                                          │
│ ❱  43 │   tokenizer = AutoTokenizer.from_pretrained(                                             │
│    44 │   │   tokenizer_dir,                                                                     │
│    45 │   │   trust_remote_code=trust_remote_code,                                               │
│    46 │   │   encode_special_tokens=True,                                                        │
│                                                                                                  │
│ /tiamat-NAS/nicolaus/Anole-7b-v0.1/anole/transformers/src/transformers/models/auto/tokenization_ │
│ auto.py:916 in from_pretrained                                                                   │
│                                                                                                  │
│   913 │   │   │   │   │   │   "in order to use this tokenizer."                                  │
│   914 │   │   │   │   │   )                                                                      │
│   915 │   │                                                                                      │
│ ❱ 916 │   │   raise ValueError(                                                                  │
│   917 │   │   │   f"Unrecognized configuration class {config.__class__} to build an AutoTokeni   │
│   918 │   │   │   f"Model type should be one of {', '.join(c.__name__ for c in TOKENIZER_MAPPI   │
│   919 │   │   )                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Unrecognized configuration class <class 
'transformers_modules.THUDM.glm-4-9b-chat.eb55a443d66541f30869f6caac5ad0d2e95bcbaa.configuration_chatglm.ChatGLMConfig'> to build an AutoTokenizer.
Model type should be one of AlbertConfig, AlignConfig, BarkConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, 
BlenderbotConfig, BlenderbotSmallConfig, BlipConfig, Blip2Config, BloomConfig, BridgeTowerConfig, BrosConfig, CamembertConfig, CanineConfig, ChameleonConfig, 
ChineseCLIPConfig, ClapConfig, CLIPConfig, CLIPSegConfig, ClvpConfig, LlamaConfig, CodeGenConfig, CohereConfig, ConvBertConfig, CpmAntConfig, CTRLConfig, 
Data2VecAudioConfig, Data2VecTextConfig, DbrxConfig, DebertaConfig, DebertaV2Config, DistilBertConfig, DPRConfig, ElectraConfig, ErnieConfig, ErnieMConfig, EsmConfig,
FalconConfig, FastSpeech2ConformerConfig, FlaubertConfig, FNetConfig, FSMTConfig, FunnelConfig, GemmaConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, 
GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GPTSanJapaneseConfig, GroundingDinoConfig, GroupViTConfig, HubertConfig, IBertConfig, IdeficsConfig, 
Idefics2Config, InstructBlipConfig, JambaConfig, JetMoeConfig, JukeboxConfig, Kosmos2Config, LayoutLMConfig, LayoutLMv2Config, LayoutLMv3Config, LEDConfig, 
LiltConfig, LlamaConfig, LlavaConfig, LlavaNextConfig, LongformerConfig, LongT5Config, LukeConfig, LxmertConfig, M2M100Config, MambaConfig, MarianConfig, MBartConfig,
MegaConfig, MegatronBertConfig, MgpstrConfig, MistralConfig, MixtralConfig, MobileBertConfig, MPNetConfig, MptConfig, MraConfig, MT5Config, MusicgenConfig, 
MusicgenMelodyConfig, MvpConfig, NezhaConfig, NllbMoeConfig, NystromformerConfig, OlmoConfig, OneFormerConfig, OpenAIGPTConfig, OPTConfig, Owlv2Config, OwlViTConfig, 
PaliGemmaConfig, PegasusConfig, PegasusXConfig, PerceiverConfig, PersimmonConfig, PhiConfig, Phi3Config, Pix2StructConfig, PLBartConfig, ProphetNetConfig, 
QDQBertConfig, Qwen2Config, Qwen2MoeConfig, RagConfig, RealmConfig, RecurrentGemmaConfig, ReformerConfig, RemBertConfig, RetriBertConfig, RobertaConfig, 
RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, SeamlessM4TConfig, SeamlessM4Tv2Config, SiglipConfig, Speech2TextConfig, Speech2Text2Config, 
SpeechT5Config, SplinterConfig, SqueezeBertConfig, StableLmConfig, Starcoder2Config, SwitchTransformersConfig, T5Config, TapasConfig, TransfoXLConfig, TvpConfig, 
UdopConfig, UMT5Config, VideoLlavaConfig, ViltConfig, VipLlavaConfig, VisualBertConfig, VitsConfig, Wav2Vec2Config, Wav2Vec2BertConfig, Wav2Vec2ConformerConfig, 
WhisperConfig, XCLIPConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, YosoConfig.
(base) root@di-20240911164638-p9mqb:/tiamat-vePFS/share_data/boyang/llms/GLM-4/finetune_demo# python inference.py /tiamat-NAS/boyang/GLM4/gjm/1024/checkpoint-2000
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Could not locate the THUDM/glm-4-9b-chat--configuration_chatglm.py inside /tiamat-NAS/boyang/GLM4/gjm/1024/checkpoint-2000.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /tiamat-vePFS/share_data/boyang/llms/GLM-4/finetune_demo/inference.py:116 in main                │
│                                                                                                  │
│   113 │   #     }                                                                                │
│   114 │   # ]                                                                                    │
│   115 │                                                                                          │
│ ❱ 116 │   model, tokenizer = load_model_and_tokenizer(model_dir)                                 │
│   117 │   inputs = tokenizer.apply_chat_template(                                                │
│   118 │   │   messages,                                                                          │
│   119 │   │   add_generation_prompt=True,                                                        │
│                                                                                                  │
│ /tiamat-vePFS/share_data/boyang/llms/GLM-4/finetune_demo/inference.py:36 in                      │
│ load_model_and_tokenizer                                                                         │
│                                                                                                  │
│    33 │   │   )                                                                                  │
│    34 │   │   tokenizer_dir = model.peft_config['default'].base_model_name_or_path               │
│    35 │   else:                                                                                  │
│ ❱  36 │   │   model = AutoModel.from_pretrained(                                                 │
│    37 │   │   │   model_dir,                                                                     │
│    38 │   │   │   trust_remote_code=trust_remote_code,                                           │
│    39 │   │   │   device_map='auto',                                                             │
│                                                                                                  │
│ /tiamat-vePFS/share_data/minyue/miniconda3/lib/python3.9/site-packages/transformers/models/auto/ │
│ auto_factory.py:441 in from_pretrained                                                           │
│                                                                                                  │
│   438 │   │   │   if kwargs_copy.get("torch_dtype", None) == "auto":                             │
│   439 │   │   │   │   _ = kwargs_copy.pop("torch_dtype")                                         │
│   440 │   │   │                                                                                  │
│ ❱ 441 │   │   │   config, kwargs = AutoConfig.from_pretrained(                                   │
│   442 │   │   │   │   pretrained_model_name_or_path,                                             │
│   443 │   │   │   │   return_unused_kwargs=True,                                                 │
│   444 │   │   │   │   trust_remote_code=trust_remote_code,                                       │
│                                                                                                  │
│ /tiamat-vePFS/share_data/minyue/miniconda3/lib/python3.9/site-packages/transformers/models/auto/ │
│ configuration_auto.py:911 in from_pretrained                                                     │
│                                                                                                  │
│   908 │   │   │   │   )                                                                          │
│   909 │   │   │   class_ref = config_dict["auto_map"]["AutoConfig"]                              │
│   910 │   │   │   module_file, class_name = class_ref.split(".")                                 │
│ ❱ 911 │   │   │   config_class = get_class_from_dynamic_module(                                  │
│   912 │   │   │   │   pretrained_model_name_or_path, module_file + ".py", class_name, **kwargs   │
│   913 │   │   │   )                                                                              │
│   914 │   │   │   config_class.register_for_auto_class()                                         │
│                                                                                                  │
│ /tiamat-vePFS/share_data/minyue/miniconda3/lib/python3.9/site-packages/transformers/dynamic_modu │
│ le_utils.py:388 in get_class_from_dynamic_module                                                 │
│                                                                                                  │
│   385 │   cls = get_class_from_dynamic_module("sgugger/my-bert-model", "modeling.py", "MyBertM   │
│   386 │   ```"""                                                                                 │
│   387 │   # And lastly we get the class inside our newly created module                          │
│ ❱ 388 │   final_module = get_cached_module_file(                                                 │
│   389 │   │   pretrained_model_name_or_path,                                                     │
│   390 │   │   module_file,                                                                       │
│   391 │   │   cache_dir=cache_dir,                                                               │
│                                                                                                  │
│ /tiamat-vePFS/share_data/minyue/miniconda3/lib/python3.9/site-packages/transformers/dynamic_modu │
│ le_utils.py:252 in get_cached_module_file                                                        │
│                                                                                                  │
│   249 │                                                                                          │
│   250 │   try:                                                                                   │
│   251 │   │   # Load from URL or cache if already cached                                         │
│ ❱ 252 │   │   resolved_module_file = cached_file(                                                │
│   253 │   │   │   pretrained_model_name_or_path,                                                 │
│   254 │   │   │   module_file,                                                                   │
│   255 │   │   │   cache_dir=cache_dir,                                                           │
│                                                                                                  │
│ /tiamat-vePFS/share_data/minyue/miniconda3/lib/python3.9/site-packages/transformers/utils/hub.py │
│ :380 in cached_file                                                                              │
│                                                                                                  │
│    377 │   │   resolved_file = os.path.join(os.path.join(path_or_repo_id, subfolder), filename)  │
│    378 │   │   if not os.path.isfile(resolved_file):                                             │
│    379 │   │   │   if _raise_exceptions_for_missing_entries:                                     │
│ ❱  380 │   │   │   │   raise EnvironmentError(                                                   │
│    381 │   │   │   │   │   f"{path_or_repo_id} does not appear to have a file named {full_filen  │
│    382 │   │   │   │   │   f"'https://huggingface.co/{path_or_repo_id}/{revision}' for availabl  │
│    383 │   │   │   │   )                                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OSError: /tiamat-NAS/boyang/GLM4/gjm/1024/checkpoint-2000 does not appear to have a file named THUDM/glm-4-9b-chat--configuration_chatglm.py. Checkout 
'https://huggingface.co//tiamat-NAS/boyang/GLM4/gjm/1024/checkpoint-2000/None' for available files.

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

python inference.py /tiamat-NAS/boyang/GLM4/gjm/1024/checkpoint-6000

### Expected behavior / 期待表现

fix the bug

**Comment by sixsixcoder** [comment]
请问您遇到什么问题，环境配置，比如transformers、torch版本可以打印一下吗
