### ISSUE TITLE
LlamaFactory  lora微调glm4过拟合严重

### ISSUE THREAD

**Issue by zzk2021** [THUDM/GLM-4#610]
### System Info / 系統信息

3090 x4 CentOS

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

5000多数据微调，有严重过拟合现象。表现为：
1. 训练数据里有一些数据，带单位的，比如立方米，平方米这样的。微调之后生成单位后就结束了输出
2. 换成其他指令就不遵循了，比如令模型json格式输出。

### Expected behavior / 期待表现

help

**Comment by sixsixcoder** [comment]
您可以多尝试调整微调参数，并在llamafactory仓库提issue解决
