### ISSUE TITLE
使用微调后的模型报错，包括inference.py和vllm.py

### ISSUE THREAD

**Issue by JohnnyBoyzzz** [THUDM/GLM-4#62]
### System Info / 系統信息

* cuda 12.4
* python 3.10
* transformers 4.41.2

### Who can help? / 谁可以帮助到您？

ValueError: Unrecognized configuration class <class 'transformers_modules.checkpoint-8607.configuration_chatglm.ChatGLMConfig'> to build an AutoTokenizer.

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

python inference.py glm-sft/squeeze_prompt/model/checkpoint-8607

### Expected behavior / 期待表现

能正常用inference和vllm测试

**Comment by destroy-lonely** [comment]
same

**Comment by zRzRzRzRzRzRzR** [comment]
使用微调的模型需要查看vLLM相关的文档自己修改代码导入，不是换个名字就可以了
