### ISSUE TITLE
微调报错：TypeError: Seq2SeqTrainer.training_step() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by szlthu** [THUDM/GLM-4#620]
### System Info / 系統信息

torch=2.5.1
torchvision=0.20.0
transformers=4.46.1

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

用的官方数据集，也修改格式了，但是依然跑不通

### Expected behavior / 期待表现

不知道是数据集的问题，还是模型的问题，还是环境的问题

**Comment by ZornWang** [comment]
目前发现时`transformer`版本过高导致，仓库中的`transformers`版本随着`glm-4-9b-chat-hf`的发布更新到了`>4.46.0`。但是`finetune.py`并未更新，仍然停留在上一版本。可以尝试将`transformers`降级至`4.45.2`及以下，可以解决此报错

**Comment by ZornWang** [comment]
目前发现是`transformers`版本过高导致，仓库中的`transformers`版本随着`glm-4-9b-chat-hf`的发布更新到了`>4.46.0`。但是`finetune.py`并未更新，仍然停留在上一版本。可以尝试将`transformers`降级至`4.45.2`及以下，可以解决此报错
