### ISSUE TITLE
web推理demo错误Exception in ASGI application

### ISSUE THREAD

**Issue by elesun2018** [THUDM/GLM-4#622]
运行：basic_demo# python trans_web_vision_demo.py
报错如下：
![image](https://github.com/user-attachments/assets/7717c601-bc13-4a24-b4b7-411128570628)

pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ssd1/sfz/envs/glm/lib/python3.10/site-packages/pydantic/type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "/home/ssd1/sfz/envs/glm/lib/python3.10/site-packages/pydantic/type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:
没有使用vllm，问题可能出在哪里，谢谢！

**Comment by sixsixcoder** [comment]
你是自己修改的代码吗？请提供一下代码和环境

**Comment by elesun2018** [comment]
Package                           Version
--------------------------------- -------------
absl-py                           2.0.0
accelerate                        0.34.2
aiofiles                          23.2.1
aiohttp                           3.9.1
aiosignal                         1.3.1
altair                            5.2.0
annotated-types                   0.6.0
anyio                             3.7.1
apex                              0.1
appdirs                           1.4.4
async-timeout                     4.0.3
attrs                             23.1.0
bitsandbytes                      0.39.0
blinker                           1.7.0
blis                              0.7.11
boto3                             1.34.4
botocore                          1.34.4
braceexpand                       0.1.7
cachetools                        5.3.2
catalogue                         2.0.10
certifi                           2022.12.7
charset-normalizer                2.1.1
click                             8.1.7
cloudpathlib                      0.16.0
cloudpickle                       3.1.0
cmake                             3.25.0
colorama                          0.4.6
confection                        0.1.4
contourpy                         1.2.0
cpm-kernels                       1.0.11
cycler                            0.12.1
cymem                             2.0.8
datasets                          2.20.0
deepspeed                         0.14.4
dill                              0.3.7
diskcache                         5.6.3
distro                            1.9.0
docker-pycreds                    0.4.0
einops                            0.7.0
en-core-web-sm                    3.7.1
exceptiongroup                    1.2.0
fastapi                           0.115.2
ffmpy                             0.3.1
filelock                          3.13.1
Flask                             3.0.2
fonttools                         4.47.0
frozenlist                        1.4.1
fsspec                            2023.10.0
gguf                              0.10.0
gitdb                             4.0.11
GitPython                         3.1.42
google-auth                       2.25.2
google-auth-oauthlib              1.2.0
gradio                            4.3.0
gradio_client                     0.7.0
grpcio                            1.60.0
h11                               0.14.0
hjson                             3.1.0
httpcore                          1.0.2
httptools                         0.6.4
httpx                             0.26.0
huggingface-hub                   0.24.5
idna                              3.4
importlib_metadata                8.5.0
importlib-resources               6.1.1
interegular                       0.3.3
itsdangerous                      2.1.2
jieba                             0.42.1
Jinja2                            3.1.2
jiter                             0.6.1
jmespath                          1.0.1
joblib                            1.3.2
jsonlines                         4.0.0
jsonschema                        4.23.0
jsonschema-specifications         2023.11.2
kiwisolver                        1.4.5
langcodes                         3.3.0
lark                              1.2.2
latex2mathml                      3.77.0
lit                               15.0.7
llvmlite                          0.43.0
lm-format-enforcer                0.10.6
loguru                            0.7.2
Markdown                          3.5.1
markdown-it-py                    3.0.0
MarkupSafe                        2.1.3
matplotlib                        3.8.2
mdtex2html                        1.2.0
mdurl                             0.1.2
mistral_common                    1.4.4
mpi4py                            3.1.4
mpmath                            1.3.0
msgpack                           1.1.0
msgspec                           0.18.6
multidict                         6.0.4
multiprocess                      0.70.15
murmurhash                        1.0.10
mypy-extensions                   1.0.0
nest-asyncio                      1.6.0
networkx                          3.0
ninja                             1.11.1.1
nltk                              3.8.1
numba                             0.60.0
numpy                             1.26.4
nvidia-cublas-cu12                12.1.3.1
nvidia-cuda-cupti-cu12            12.1.105
nvidia-cuda-nvrtc-cu12            12.1.105
nvidia-cuda-runtime-cu12          12.1.105
nvidia-cudnn-cu12                 9.1.0.70
nvidia-cufft-cu12                 11.0.2.54
nvidia-curand-cu12                10.3.2.106
nvidia-cusolver-cu12              11.4.5.107
nvidia-cusparse-cu12              12.1.0.106
nvidia-ml-py                      12.560.30
nvidia-nccl-cu12                  2.20.5
nvidia-nvjitlink-cu12             12.6.77
nvidia-nvtx-cu12                  12.1.105
oauthlib                          3.2.2
openai                            1.51.2
opencv-python                     4.9.0.80
opencv-python-headless            4.10.0.84
orjson                            3.9.10
outlines                          0.0.46
packaging                         23.2
pandas                            2.1.4
partial-json-parser               0.2.1.1.post4
peft                              0.11.1
pillow                            10.4.0
pip                               23.3.1
preshed                           3.0.9
prometheus_client                 0.21.0
prometheus-fastapi-instrumentator 7.0.0
protobuf                          4.23.4
psutil                            5.9.7
py-cpuinfo                        9.0.0
pyairports                        2.1.1
pyarrow                           17.0.0
pyarrow-hotfix                    0.6
pyasn1                            0.5.1
pyasn1-modules                    0.3.0
pycountry                         24.6.1
pydantic                          2.9.2
pydantic_core                     2.23.4
pydub                             0.25.1
Pygments                          2.17.2
pynvml                            11.5.0
pyparsing                         3.1.1
pyre-extensions                   0.0.29
python-dateutil                   2.8.2
python-dotenv                     1.0.1
python-multipart                  0.0.6
pytz                              2023.3.post1
PyYAML                            6.0.1
pyzmq                             26.2.0
ray                               2.37.0
referencing                       0.32.0
regex                             2023.10.3
requests                          2.32.3
requests-oauthlib                 1.3.1
rich                              13.7.0
rouge-chinese                     1.0.3
rpds-py                           0.15.2
rsa                               4.9
ruamel.yaml                       0.18.6
ruamel.yaml.clib                  0.2.8
s3transfer                        0.9.0
safetensors                       0.4.5
scikit-learn                      1.4.0
scipy                             1.11.4
seaborn                           0.13.0
semantic-version                  2.10.0
sentencepiece                     0.2.0
sentry-sdk                        1.40.6
setproctitle                      1.3.3
setuptools                        68.2.2
shellingham                       1.5.4
six                               1.16.0
smart-open                        6.4.0
smmap                             5.0.1
sniffio                           1.3.0
spacy                             3.7.2
spacy-legacy                      3.0.12
spacy-loggers                     1.0.5
srsly                             2.4.8
starlette                         0.40.0
SwissArmyTransformer              0.4.11
sympy                             1.12
tensorboard                       2.15.1
tensorboard-data-server           0.7.2
tensorboardX                      2.6.2.2
thinc                             8.2.2
threadpoolctl                     3.2.0
tiktoken                          0.7.0
timm                              0.9.12
tokenizers                        0.20.1
tomlkit                           0.12.0
toolz                             0.12.0
torch                             2.4.0
torchaudio                        2.0.2+cu118
torchvision                       0.19.0
tqdm                              4.66.5
transformers                      4.45.2
transformers-stream-generator     0.0.5
triton                            3.0.0
typer                             0.9.0
typing_extensions                 4.12.2
typing-inspect                    0.9.0
tzdata                            2023.3
urllib3                           1.26.13
uvicorn                           0.24.0.post1
uvloop                            0.21.0
vllm                              0.6.3
wandb                             0.16.3
wasabi                            1.1.2
watchfiles                        0.24.0
weasel                            0.3.4
webdataset                        0.2.86
websockets                        11.0.3
Werkzeug                          3.0.1
wheel                             0.41.2
xformers                          0.0.27.post2
xxhash                            3.4.1
yarl                              1.9.4
zipp                              3.20.2

代码trans_web_vision_demo.py没有改动

**Comment by sixsixcoder** [comment]
看起来像是依赖项的问题，你可以新建一个空白环境，然后按照[requirements.txt](https://github.com/THUDM/GLM-4/blob/main/basic_demo/requirements.txt) 安装依赖项，使用命令
```
pip install -r requirements.txt
```

**Comment by elesun2018** [comment]
Package                           Version
accelerate                        0.34.2
apex                              0.1
bitsandbytes                      0.39.0
einops                            0.7.0
huggingface-hub                   0.24.5
jieba                             0.42.1
Jinja2                            3.1.2
jiter                             0.6.1
ninja                             1.11.1.1
numpy                             1.26.4
openai                            1.51.2
opencv-python                     4.9.0.80
opencv-python-headless            4.10.0.84
pandas                            2.1.4
protobuf                          4.23.4
rouge-chinese                     1.0.3
scikit-learn                      1.4.0
scipy                             1.11.4
seaborn                           0.13.0
spacy                             3.7.2
SwissArmyTransformer              0.4.11
tiktoken                          0.7.0
timm                              0.9.12
tokenizers                        0.20.1
torch                             2.4.0
torchvision                       0.19.0
transformers                      4.45.2
transformers-stream-generator     0.0.5
uvicorn                           0.24.0.post1
uvloop                            0.21.0
vllm                              0.6.3
xformers                          0.0.27.post2
代码trans_web_vision_demo.py没有改动

**Comment by sixsixcoder** [comment]
pip install gradio==4.44.1

**Comment by elesun2018** [comment]
pip install gradio==4.44.1 问题消失，感谢支持
