### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by Yxj-study** [THUDM/GLM-4#623]
### System Info / 系統信息

+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.42.02              Driver Version: 555.42.02      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-80GB          Off |   00000000:4E:00.0 Off |                    0 |
| N/A   23C    P0             59W /  400W |       4MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA A100-SXM4-80GB          Off |   00000000:9B:00.0 Off |                    0 |
| N/A   23C    P0             58W /  400W |       4MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA A100-SXM4-80GB          Off |   00000000:A1:00.0 Off |                    0 |
| N/A   26C    P0             60W /  400W |       4MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA A100-SXM4-80GB          Off |   00000000:DB:00.0 Off |                    0 |
| N/A   25C    P0             61W /  400W |       4MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                           

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

import torch
from PIL import Image
from transformers import AutoModelForCausalLM, AutoTokenizer

device = "cuda"

tokenizer = AutoTokenizer.from_pretrained("THUDM/glm-4v-9b", trust_remote_code=True)

query = '描述这张图片'
image = Image.open("your image").convert('RGB')

//我用的transformers4.38
inputs = tokenizer.apply_chat_template([{"role": "user", "image": image, "content": query}],
                                       add_generation_prompt=True, tokenize=True, return_tensors="pt",
                                       return_dict=True)  # chat mode

inputs = inputs.to(device)
model = AutoModelForCausalLM.from_pretrained(
    "THUDM/glm-4v-9b",
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True
).to(device).eval()

//运行完下面这段报错
gen_kwargs = {"max_length": 2500, "do_sample": True, "top_k": 1}
with torch.no_grad():
    outputs = model.generate(**inputs, **gen_kwargs)
    outputs = outputs[:, inputs['input_ids'].shape[1]:]
    print(tokenizer.decode(outputs[0]))

### Expected behavior / 期待表现

帮我解决一下问题：
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/opt/miniconda/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/lib/python3.12/site-packages/transformers/generation/utils.py", line 1592, in generate
    return self.sample(
           ^^^^^^^^^^^^
  File "/opt/miniconda/lib/python3.12/site-packages/transformers/generation/utils.py", line 2746, in sample
    model_kwargs = self._update_model_kwargs_for_generation(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 1087, in _update_model_kwargs_for_generation
    cache_name, cache = self._extract_past_from_model_output(outputs)
    ^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
>>> gen_kwargs = {"max_length": 2500, "do_sample": True, "top_k": 1}
>>> with torch.no_grad():
...     outputs = model.generate(**inputs, **gen_kwargs)
...     outputs = outputs[:, inputs['input_ids'].shape[1]:]
...     print(tokenizer.decode(outputs[0]))
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/opt/miniconda/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/lib/python3.12/site-packages/transformers/generation/utils.py", line 1592, in generate
    return self.sample(
           ^^^^^^^^^^^^
  File "/opt/miniconda/lib/python3.12/site-packages/transformers/generation/utils.py", line 2746, in sample
    model_kwargs = self._update_model_kwargs_for_generation(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 1087, in _update_model_kwargs_for_generation
    cache_name, cache = self._extract_past_from_model_output(outputs)
    ^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
>>> pip show transformers
  File "<stdin>", line 1
    pip show transformers
        ^^^^
SyntaxError: invalid syntax

**Comment by sixsixcoder** [comment]
建议升级到transformers==4.44，我这边复线了你的问题的，升级后可以解决

**Comment by Yxj-study** [comment]
我更改了transformers的版本，但是又出现了如下问题：
(base) ***@***.***:~# python
Python 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:12:24) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
&gt;&gt;&gt; import torch
&gt;&gt;&gt; from PIL import Image
&gt;&gt;&gt; from transformers import AutoModelForCausalLM, AutoTokenizer
&gt;&gt;&gt;&nbsp;
&gt;&gt;&gt; device = "cuda"


&gt;&gt;&gt; tokenizer = AutoTokenizer.from_pretrained("THUDM/glm-4v-9b", trust_remote_code=True)
Traceback (most recent call last):
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/urllib3/connection.py", line 196, in _new_conn
&nbsp; &nbsp; sock = connection.create_connection(
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
&nbsp; &nbsp; raise err
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
&nbsp; &nbsp; sock.connect(sa)
OSError: [Errno 101] Network is unreachable


The above exception was the direct cause of the following exception:


Traceback (most recent call last):
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
&nbsp; &nbsp; response = self._make_request(
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/urllib3/connectionpool.py", line 490, in _make_request
&nbsp; &nbsp; raise new_e
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/urllib3/connectionpool.py", line 466, in _make_request
&nbsp; &nbsp; self._validate_conn(conn)
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
&nbsp; &nbsp; conn.connect()
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/urllib3/connection.py", line 615, in connect
&nbsp; &nbsp; self.sock = sock = self._new_conn()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/urllib3/connection.py", line 211, in _new_conn
&nbsp; &nbsp; raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fa9d42b5760&gt;: Failed to establish a new connection: [Errno 101] Network is unreachable


The above exception was the direct cause of the following exception:


Traceback (most recent call last):
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/requests/adapters.py", line 589, in send
&nbsp; &nbsp; resp = conn.urlopen(
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
&nbsp; &nbsp; retries = retries.increment(
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ^^^^^^^^^^^^^^^^^^
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
&nbsp; &nbsp; raise MaxRetryError(_pool, url, reason) from reason&nbsp; # type: ignore[arg-type]
&nbsp; &nbsp; ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /THUDM/glm-4v-9b/resolve/main/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa9d42b5760&gt;: Failed to establish a new connection: [Errno 101] Network is unreachable'))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1376, in _get_metadata_or_catch_error
&nbsp; &nbsp; metadata = get_hf_file_metadata(
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
&nbsp; &nbsp; return fn(*args, **kwargs)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1296, in get_hf_file_metadata
&nbsp; &nbsp; r = _request_wrapper(
&nbsp; &nbsp; &nbsp; &nbsp; ^^^^^^^^^^^^^^^^^
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 277, in _request_wrapper
&nbsp; &nbsp; response = _request_wrapper(
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 300, in _request_wrapper
&nbsp; &nbsp; response = get_session().request(method=method, url=url, **params)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
&nbsp; &nbsp; resp = self.send(prep, **send_kwargs)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
&nbsp; &nbsp; r = adapter.send(request, **kwargs)
&nbsp; &nbsp; &nbsp; &nbsp; ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/huggingface_hub/utils/_http.py", line 93, in send
&nbsp; &nbsp; return super().send(request, *args, **kwargs)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/requests/adapters.py", line 622, in send
&nbsp; &nbsp; raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /THUDM/glm-4v-9b/resolve/main/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa9d42b5760&gt;: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: 479e63d1-37ab-4bda-ad92-f11aedcbfa13)')


The above exception was the direct cause of the following exception:


Traceback (most recent call last):
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/transformers/utils/hub.py", line 402, in cached_file
&nbsp; &nbsp; resolved_file = hf_hub_download(
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ^^^^^^^^^^^^^^^^
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
&nbsp; &nbsp; return fn(*args, **kwargs)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 862, in hf_hub_download
&nbsp; &nbsp; return _hf_hub_download_to_cache_dir(
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 969, in _hf_hub_download_to_cache_dir
&nbsp; &nbsp; _raise_on_head_call_error(head_call_error, force_download, local_files_only)
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1487, in _raise_on_head_call_error
&nbsp; &nbsp; raise LocalEntryNotFoundError(
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.


The above exception was the direct cause of the following exception:


Traceback (most recent call last):
&nbsp; File "<stdin&gt;", line 1, in <module&gt;
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/transformers/models/auto/tokenization_auto.py", line 854, in from_pretrained
&nbsp; &nbsp; config = AutoConfig.from_pretrained(
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/transformers/models/auto/configuration_auto.py", line 976, in from_pretrained
&nbsp; &nbsp; config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/transformers/configuration_utils.py", line 632, in get_config_dict
&nbsp; &nbsp; config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/transformers/configuration_utils.py", line 689, in _get_config_dict
&nbsp; &nbsp; resolved_config_file = cached_file(
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^
&nbsp; File "/opt/miniconda/lib/python3.12/site-packages/transformers/utils/hub.py", line 445, in cached_file
&nbsp; &nbsp; raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like THUDM/glm-4v-9b is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.



我想问这是怎么回事呢
&nbsp;


禹雄杰
***@***.***







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月31日(星期四) 下午4:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [THUDM/GLM-4] ValueError: too many values to unpack (expected 2) (Issue #623)














 
建议升级到transformers==4.44，我这边复现了你的问题的，升级后可以解决

**Comment by sixsixcoder** [comment]
建议你可以先把`glm-4v-9b`模型文件下载到本地，然后替换"THUDM/glm-4v-9b"为本地模型路径

**Comment by Yxj-study** [comment]
我该如何改进识别的成功率呢？
&nbsp;


禹雄杰
***@***.***







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月31日(星期四) 下午5:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [THUDM/GLM-4] ValueError: too many values to unpack (expected 2) (Issue #623)














 
建议你可以先把glm-4v-9b模型文件下载到本地，然后替换"THUDM/glm-4v-9b"为本地模型路径
