### ISSUE TITLE
requirements 安装失败

### ISSUE THREAD

**Issue by tiandaoyuxi** [THUDM/GLM-4#63]
### System Info / 系統信息

python 3.11.8
cuda 12.1
OS win10

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

(venv) D:\GLM-4>python -m pip install -r D:\GLM-4\basic_demo\requirements.txt
Collecting torch>=2.3.0 (from -r D:\GLM-4\basic_demo\requirements.txt (line 1))
  Using cached torch-2.3.1-cp311-cp311-win_amd64.whl.metadata (26 kB)
Collecting torchvision>=0.18.0 (from -r D:\GLM-4\basic_demo\requirements.txt (line 2))
  Using cached torchvision-0.18.1-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Collecting transformers==4.40.0 (from -r D:\GLM-4\basic_demo\requirements.txt (line 3))
  Using cached transformers-4.40.0-py3-none-any.whl.metadata (137 kB)
Collecting huggingface-hub>=0.23.1 (from -r D:\GLM-4\basic_demo\requirements.txt (line 4))
  Using cached huggingface_hub-0.23.3-py3-none-any.whl.metadata (12 kB)
Collecting sentencepiece>=0.2.0 (from -r D:\GLM-4\basic_demo\requirements.txt (line 5))
  Using cached sentencepiece-0.2.0-cp311-cp311-win_amd64.whl.metadata (8.3 kB)
Collecting pydantic>=2.7.1 (from -r D:\GLM-4\basic_demo\requirements.txt (line 6))
  Using cached pydantic-2.7.3-py3-none-any.whl.metadata (108 kB)
Collecting timm>=0.9.16 (from -r D:\GLM-4\basic_demo\requirements.txt (line 7))
  Using cached timm-1.0.3-py3-none-any.whl.metadata (43 kB)
Collecting tiktoken>=0.7.0 (from -r D:\GLM-4\basic_demo\requirements.txt (line 8))
  Using cached tiktoken-0.7.0-cp311-cp311-win_amd64.whl.metadata (6.8 kB)
Collecting accelerate>=0.30.1 (from -r D:\GLM-4\basic_demo\requirements.txt (line 9))
  Using cached accelerate-0.30.1-py3-none-any.whl.metadata (18 kB)
Collecting sentence_transformers>=2.7.0 (from -r D:\GLM-4\basic_demo\requirements.txt (line 10))
  Using cached sentence_transformers-3.0.0-py3-none-any.whl.metadata (10 kB)
Collecting vllm>=0.4.3 (from -r D:\GLM-4\basic_demo\requirements.txt (line 11))
  Using cached vllm-0.4.3.tar.gz (693 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "D:\GLM-4\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\GLM-4\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\GLM-4\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Win11\AppData\Local\Temp\pip-build-env-8ehg80mm\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Win11\AppData\Local\Temp\pip-build-env-8ehg80mm\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Win11\AppData\Local\Temp\pip-build-env-8ehg80mm\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 36, in <module>
      AssertionError: vLLM only supports Linux platform (including WSL).
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### Expected behavior / 期待表现

thx

**Comment by mjzcng** [comment]
“AssertionError: vLLM only supports Linux platform (including WSL).”
遇到同样问题，vLLM只支持Linux，windows上需要在WSL环境下安装

**Comment by zRzRzRzRzRzRzR** [comment]
是的，windows的话只能运行transformers后端的demo，文档也已经说明了
