### ISSUE TITLE
使用vllm启动glm-4v-9b服务，调用/v1/chat/completions报错

### ISSUE THREAD

**Issue by OliverLiy** [THUDM/GLM-4#630]
### System Info / 系統信息

vllm 0.6.3.post1
transformers 4.46.1
glm-4v-9b

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1、启动脚本：CUDA_VISIBLE_DEVICES=5,7 python -m vllm.entrypoints.openai.api_server    --model=/beeb/ap/iaf/models/modelscope/hub/glm-4v-9b    --served-model-name=glm-4v-9b   --device=cuda    --port=10085    --host=0.0.0.0    --tensor-parallel-size=2    --dtype=auto    --trust-remote-code
2、调用API：/v1/chat/completions
```json
{
    "model": "glm-4v-9b",
    "messages": [
            {"role": "system", "content": "You are a helpful assistant."}, 
            {"role": "user", "content": "如何用python读取一个文件"} 
        ]
}
```
3、出现报错
As of transformers v4.44, default chat template is no longer allowed, so you must provide a chat template if the tokenizer does not define one.

![image](https://github.com/user-attachments/assets/41f84b28-c3dd-4b1a-8d64-28bddd2e0889)

### Expected behavior / 期待表现

调用接口后回答对应的结果

**Comment by sixsixcoder** [comment]
请提供一下调用api的脚本

**Comment by OliverLiy** [comment]
> 请提供一下调用api的脚本

启动后Postman调用，也可以使用curl命令
```shell
curl --location --request POST 'http://136.1.5.93:10085/v1/chat/completions' \
--header 'Content-Type: application/json' \
--data-raw '{
    "model": "glm-4v-9b",
    "messages": [
        {
            "role": "system",
            "content": "You are a helpful assistant."
        },
        {
            "role": "user",
            "content": "如何用python读取一个文件"
        }
    ]
}'

```

**Comment by OliverLiy** [comment]
@OliverLiy  似乎需要有chat template，GLM-4v-9b模型是否有模板呢

**Comment by OliverLiy** [comment]
@sixsixcoder  似乎需要有chat template，GLM-4v-9b模型是否有模板呢

**Comment by OliverLiy** [comment]
@sixsixcoder  modelscope处提交了一个pr，添加了chat_template，修改了该问题
https://www.modelscope.cn/models/ZhipuAI/glm-4v-9b/feedback/prDetail/17590

**Comment by sixsixcoder** [comment]
感谢您的贡献

**Comment by zRzRzRzRzRzRzR** [comment]
应该是vllm一定会调用template，这个建议是好的，非常感谢，我们会验证这个template能不能在transfomers上使用，直接一并合并

**Comment by yyqqing** [comment]
有结论吗？我看 HF 和 ModelScope 上仍没有设置 chat_template。能否提供一个可用的？

**Comment by Jimmy-L99** [comment]
同问，现在`vllm0.9.1`了，还是报错`Default chat template is no longer allowed`
