### ISSUE TITLE
GLM-4-9B-int4模型的输出格式不听从prompt使唤，无论怎么调都不行，非常倔强，有解决方案吗

### ISSUE THREAD

**Issue by bolt163** [THUDM/GLM-4#636]
### System Info / 系統信息

问题如下：

【GLM-4-9B-int4的 prompt提示： 末尾还特意强调了要严格按照 example给的json格式输出】
Example 1:
Task: Find the cheapest premium economy flights from Helsinki to Stockholm on 15 March on Skyscanner. Current page: www.google.com
{"plan":"1. Go to www.skyscanner.com.
2. List the interaction options available on skyscanner page relevant for flight reservation along with their default values.
3. Select the journey option to one-way (if not default).
4. Set number of passengers to 1 (if not default).
5. Set the departure date to 15 March 2025 (since 15 March 2024 is already past).
6. Set ticket type to Economy Premium.
7. Set from airport to ""Helsinki".
8. Set destination airport to Stockhokm
9. Confirm that current values in the source airport, destination airport and departure date fields are Helsinki, Stockholm and 15 August 2024 respectively.
10. Click on the search button to get the search results.
11. Confirm that you are on the search results page.
12. Extract the price of the cheapest flight from Helsinki to Stokchol from the search results.",
"next_step": "Go to https://www.skyscanner.com",
"terminate":"no"},
After the task is completed and when terminating:
Your reply: {"terminate":"yes", "final_response": "The cheapest premium economy flight from Helsinki to Stockholm on 15 March 2025 is <flight details>."}

Notice above how there is confirmation after each step and how interaction (e.g. setting source and destination) with each element is a seperate step. Follow same pattern.
Remember: you are a very very persistent planner who will try every possible strategy to accomplish the task perfectly, the  content  need  to be json format,strictly same with the  example given**｛"plan"："1. ...。\r\n2. ...。\r\n3. if exists..., \r\n"next_step": "",\r\n"terminate":""}.**
Revise search query if needed, ask for more information if needed, and always verify the results before terminating the task.

【GLM-4-9B-int4的输出】
<img width="810" alt="企业微信截图_810e522b-bc3d-457a-93d4-99ea91ea3728" src="https://github.com/user-attachments/assets/1e8edb10-5201-4348-99e4-d6e924c785ec">

同样的prompt， GLM-4-9B输出不会有问题呢，无奈手头的机器GPU显卡吃紧，想调试下 Int4的版本
<img width="836" alt="企业微信截图_a17fa7a5-65a2-4183-b994-ba1d5303c4bf" src="https://github.com/user-attachments/assets/3af16a53-6e35-4bc7-94c3-99a2d28a775b">

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Example 1:
Task: Find the cheapest premium economy flights from Helsinki to Stockholm on 15 March on Skyscanner. Current page: www.google.com
{"plan":"1. Go to www.skyscanner.com.
2. List the interaction options available on skyscanner page relevant for flight reservation along with their default values.
3. Select the journey option to one-way (if not default).
4. Set number of passengers to 1 (if not default).
5. Set the departure date to 15 March 2025 (since 15 March 2024 is already past).
6. Set ticket type to Economy Premium.
7. Set from airport to ""Helsinki".
8. Set destination airport to Stockhokm
9. Confirm that current values in the source airport, destination airport and departure date fields are Helsinki, Stockholm and 15 August 2024 respectively.
10. Click on the search button to get the search results.
11. Confirm that you are on the search results page.
12. Extract the price of the cheapest flight from Helsinki to Stokchol from the search results.",
"next_step": "Go to https://www.skyscanner.com",
"terminate":"no"},
After the task is completed and when terminating:
Your reply: {"terminate":"yes", "final_response": "The cheapest premium economy flight from Helsinki to Stockholm on 15 March 2025 is <flight details>."}

Notice above how there is confirmation after each step and how interaction (e.g. setting source and destination) with each element is a seperate step. Follow same pattern.
Remember: you are a very very persistent planner who will try every possible strategy to accomplish the task perfectly, the  content  need  to be json format,strictly same with the  example given**｛"plan"："1. ...。\r\n2. ...。\r\n3. if exists..., \r\n"next_step": "",\r\n"terminate":""}.**
Revise search query if needed, ask for more information if needed, and always verify the results before terminating the task.

### Expected behavior / 期待表现

int4的输出严格按照 prompt的指示

**Comment by zRzRzRzRzRzRzR** [comment]
INT4 9B损失较高，目前指令和提示词调优的实验建议放在BF16精度测试。你截图的这个指令对于int4版本的9b要求可能又点高
