### ISSUE TITLE
输出数据遗漏

### ISSUE THREAD

**Issue by niniwai** [THUDM/GLM-4#642]
我在调用glm-4-air和glm-long模型对多个待处理的文件进行实体抽取时，输出总是遗漏，比如上传20个文件进行批处理，往往只有18、19个政策文件的结果输出，并且当我在提示词里加入一个example来增强提示的时候，这种输出遗漏的现象更严重了，有时只有10个结果输出，这是什么原因造成的？怎么去改善呢？我的输出结果整合在一个json文件中，每个json对象对应一个输出结果，往往不足20个json对象，当然，当我要处理的任务更多时，这种现象仍然存在，并且没有规律。

**Comment by sixsixcoder** [comment]
请提供详细的环境信息和代码
