### ISSUE TITLE
GLM-4-9B-int4版本一直输出重复

### ISSUE THREAD

**Issue by Alexkerl** [THUDM/GLM-4#643]
### System Info / 系統信息

transformers==4.40.1 量化模型从https://modelscope.cn/models/Xok135/glm-4v-9b-4-bits下载
出现如下错误：
![微信图片_20241106161705](https://github.com/user-attachments/assets/17d1b617-a280-4c89-9bd4-2de4407047d0)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

import torch
from PIL import Image
from transformers import AutoModelForCausalLM, AutoTokenizer

device = "cuda"

tokenizer = AutoTokenizer.from_pretrained("vcadillo/glm-4v-9b-4-bits", trust_remote_code=True)

query = 'discribe this image'
image = Image.open("your image").convert('RGB')
inputs = tokenizer.apply_chat_template([{"role": "user", "image": image, "content": query}],
                                       add_generation_prompt=True, tokenize=True, return_tensors="pt",
                                       return_dict=True)  # chat mode

inputs = inputs.to(device)
model = AutoModelForCausalLM.from_pretrained(
    "vcadillo/glm-4v-9b-4-bits",
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True,
    device_map='auto',
).eval()

gen_kwargs = {"max_length": 2500, "do_sample": True, "top_k": 1}
with torch.no_grad():
    outputs = model.generate(**inputs, **gen_kwargs)
    outputs = outputs[:, inputs['input_ids'].shape[1]:]
    print(tokenizer.decode(outputs[0]))

### Expected behavior / 期待表现

正常输出

**Comment by sixsixcoder** [comment]
这个模型不是我们发布的，看起来是加载模型权重的时候出了问题，你可以咨询魔塔社区这个模型的作者
