### ISSUE TITLE
模型微调后，inference 输出大量!!!!!!!!!!!

### ISSUE THREAD

**Issue by cssaudrey** [THUDM/GLM-4#645]
### System Info / 系統信息

ubutu 22.04
cuda 12.7
python 3.12.7
pytorch 2.5.0
transformers 4.44.0

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

全部使用官方脚本。模型微调后，调用inference.py,  输出大量！！！！！！！！！！！！！！！！！！！

模型调用参数如下：
    generate_kwargs = {
        "max_new_tokens": 128,
        # "do_sample": True,
        # "top_p": 0.8,
        "temperature": 0.95,
        # "repetition_penalty": 1.2,
        # "eos_token_id": model.config.eos_token_id,
    }

模型输出如下：

(glm-4-demo) olivia@DS-GPU03:~/llm/glm/GLM-4/finetune_demo$ python inference.py  /home/olivia/llm/glm/GLM-4/finetune_demo/output/checkpoint-1000
Loading checkpoint shards: 100%|█████████████████████████████████████████████| 10/10 [00:03<00:00,  2.76it/s]
/home/olivia/miniconda3/envs/glm-4-demo/lib/python3.12/site-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.95` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
========= output =========
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Expected behavior / 期待表现

正常输出

**Comment by zhipuch** [comment]
先排查一下微调有没有问题，微调的是vision还是chat，微调过程中出现loss异常等问题了吗

**Comment by sixsixcoder** [comment]
我在pytorch2.4.0和transformers4.45.0按照您的步骤可以正常运行微调后的推理

**Comment by cssaudrey** [comment]
>

**Comment by cssaudrey** [comment]
> 我在pytorch2.4.0和transformers4.45.0按照您的步骤可以正常运行微调后的推理


我不小心把这个issue close了。
按照您的说法我安装torch2.4.0失败了。请问您torchaudio和torchvision 对应的version是多少？
我的硬件A100， cuda12.7

**Comment by cssaudrey** [comment]
> 我在pytorch2.4.0和transformers4.45.0按照您的步骤可以正常运行微调后的推理

已经修复，感谢。
另外当我把batch 设置超过8时，输出为空。
