### ISSUE TITLE
请问GLM-4-9b是用了encoder-decoder架构吗？

### ISSUE THREAD

**Issue by grandxin** [THUDM/GLM-4#646]
我看transformers代码里似乎是decoder-only的架构，难道是只有大尺寸模型才有encoder加入吗？

**Comment by sixsixcoder** [comment]
感谢您的关注，原理问题可以邮件发送到论文的作者邮箱进行咨询。

**Comment by zRzRzRzRzRzRzR** [comment]
这个开源的是decoder-only
