### ISSUE TITLE
GLM-4v离线部署在jetson agx orin失败，使用的框架是xinference。可以加载模型，但是无法进行推理，报错[address=0.0.0.0:33271, pid=892267] ChatGLM4Tokenizer._pad() got an unexpected keyword argument 'padding_side'

### ISSUE THREAD

**Issue by GengyuXu** [THUDM/GLM-4#648]
### System Info / 系統信息

xinference 0.16.1
jetson agx orin jetpack6.1

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/7c5d23cf-63c4-4a13-a7d4-ed40c315ec26)

### Expected behavior / 期待表现

能正常进行推理

**Comment by zRzRzRzRzRzRzR** [comment]
HuggingFace更新一下模型的tokenizer_chatglm.py

**Comment by GengyuXu** [comment]
现在没有报padding_size的报错而是变成了这个Failed to generate chat completion, detail: [address=0.0.0.0:33659, pid=170033]

> HuggingFace更新一下模型的tokenizer_chatglm.py
