### ISSUE TITLE
模型部署后的效果？

### ISSUE THREAD

**Issue by RyanOvO** [THUDM/GLM-4#651]
基于LLaMA-Factory部署了GLM4-9B 128K的模型，但是远远没有字节扣子上,GLM4模型的效果（相同的提示词，在两个不同的平台上，相同的开源模型，效果不一样，扣子上的模型效果更好）：
![image](https://github.com/user-attachments/assets/929e323c-66e7-4587-9639-afc395207299)

请问官方，怎么能提高基于原生开源模型部署的效果？

**Comment by sixsixcoder** [comment]
有测试示例吗？您如何判断呈现的性能效果

**Comment by RyanOvO** [comment]
> 有测试示例吗？您如何评估呈现的性能效果

当时的信息删了，就是我们自己测试对比的时候，发现本地部署的效果的确是没有扣子上的好，评估的依据是人工对比，我们有专业的同事分析了下模型生成的内容。本地部署的更生硬，扣子的效果更有"灵活"

**Comment by sixsixcoder** [comment]
可以举个例子吗？另外`temperature`和`TOP P`参数是一致的吗，第三方AI平台比如扣子可能会加入一些`RAG`的方案提升原始模型的生成效果。

**Comment by RyanOvO** [comment]
> 可以举个例子吗？另外`temperature`和`TOP P`参数是一致的吗，第三方AI平台比如扣子可能会加入一些`RAG`的方案提升原始模型的生成效果。

我们的场景是心理咨询的场景；超参数是一致的，刚刚得知，扣子那边针对开源的GLM4做了精调，所以他们的效果要更好，同时开放出来的模型在扣子上调用。
我个人感觉，扣子在精调上增强了开源模型的能力——阅读理解与意图识别的能力；原生的开源模型更生硬一些

**Comment by sixsixcoder** [comment]
这不太好直接对比，精调后的模型在某些场景下能达到比原始模型更加好的效果。GLM-4 github仓库只是提供最小的使用示例demo，提供一个中英文输入的理解能力基座，更多的用法、更多的场景还需要开发者进一步微调或使用框架实现。
