### ISSUE TITLE
glm4v_server.py 可以支持视频分析吗？

### ISSUE THREAD

**Issue by hanqingwu** [THUDM/GLM-4#653]
### Feature request  / 功能建议

glm4v_server.py 可以支持视频分析吗？

### Motivation / 动机

glm4v_server.py   可以增加支持视频分析吗？ 类似 image_url 一样，支持 video_url  

### Your contribution / 您的贡献

看dify 已经可以对接到智谱AI的API了
**https://github.com/langgenius/dify/pull/9828**

**Comment by sixsixcoder** [comment]
GLM-4v不支持视频输入分析，我不清楚dify中是如何实现的，你可以使用[THUDM/CogVLM2](https://github.com/THUDM/CogVLM2)模型进行视频分析

**Comment by hanqingwu** [comment]
好的，谢谢！我仔细看了下，dify 是用glm-4v-plus .
