### ISSUE TITLE
glm-4-9b-chat模型怎么支持并发请求

### ISSUE THREAD

**Issue by sy960923** [THUDM/GLM-4#659]
### System Info / 系統信息

![image](https://github.com/user-attachments/assets/698a41ed-a1bb-4d1d-8f4a-f171c57ea7d2)
![image](https://github.com/user-attachments/assets/67abc8b4-1a29-456b-b1e1-09fef541d59a)

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Xinference 上部署的glm-4-9b-chat 现在我在并发请求，第一个请求能正常返回，第二个请求看Xinference 接口返回的结果都是[],[]
{"msg":"process_generating","event_id":"2e13d6458a7646758b23e01f07599dde","output":{"data":[[],[]],"is_generating":true,"duration":0.011235237121582031,"average_duration":0.056767572169198206},"success":true} 这样的。请问这是什么问题。

### Expected behavior / 期待表现

期待多个请求能同时返回正确输出

**Comment by Jimmy-L99** [comment]
这个之前好像见过，貌似是Xinference的问题。并发的话vllm本来就支持吧，Xinference只是一个集成框架，你可以不用Xinference直接用vllm的api serve。

**Comment by sy960923** [comment]
> 这个之前好像见过，貌似是Xinference的问题。并发的话vllm本来就支持吧，Xinference只是一个集成框架，你可以不用Xinference直接用vllm的api serve。
好的，谢谢，在Xinference里面改用vllm方式加载模型就可以了
