### ISSUE TITLE
function call调用格式化输出

### ISSUE THREAD

**Issue by cxjtju** [THUDM/GLM-4#66]
### Feature request  / 功能建议

请问使用transforer推理方式进行function call调用，
messages = [
                {
                    "role": "system", 
                    "content": system_prompt,
                    "tools": [{"type": "function", "function":i} for i in skylark_func_list],
                },
                {
                    "role": "user",
                    "content": query
                }
            ]

inputs = tokenizer.apply_chat_template(messages,
                                            add_generation_prompt=True,
                                            tokenize=True,
                                            return_tensors="pt",
                                            return_dict=True,
                                            )
        inputs = inputs.to(device)   
如何保证格式化输出，类似于下面，在某个字段里可以取到function_name和提取的参数
![image](https://github.com/THUDM/GLM-4/assets/33721779/e0340753-c5a5-4504-a089-5ef9ca0a03f4)
![image](https://github.com/THUDM/GLM-4/assets/33721779/7bc967f5-9ca9-4dd2-b28e-82a89de15240)

### Motivation / 动机

function call调用格式化输出

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
已经规范
