### ISSUE TITLE
使用lora方案进行GLM-4-9B Chat 对话模型微调后，如何在xinference平台中加载？

### ISSUE THREAD

**Issue by xuechaofei** [THUDM/GLM-4#660]
### System Info / 系統信息

操作系统centos

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

使用lora方案进行GLM-4-9B Chat 对话模型微调,已产生checkpoint-3000目录，测试推理均正常。
在xinference平台中加载微调后的模型失败。请问如何才能将结果模型在xinference中运行

### Expected behavior / 期待表现

结果模型在xinference中运行

**Comment by zRzRzRzRzRzRzR** [comment]
你可以咨询xinference开源框架，我们仅仅提供了在transformers载入的办法，对于其他框架，需要寻找对应的框架提出issue
