### ISSUE TITLE
finetune_demo目录的inference方法，怎样才能变成流式输出

### ISSUE THREAD

**Issue by xuechaofei** [THUDM/GLM-4#661]
### System Info / 系統信息

centos8

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

finetune_demo目录的inference方法，怎样才能变成流式输出

### Expected behavior / 期待表现

以流的方式输出推理结果

**Comment by sixsixcoder** [comment]
流式输出可以参考这个代码：https://github.com/THUDM/GLM-4/blob/main/basic_demo/trans_cli_demo.py
