### ISSUE TITLE
openai_api_server接收请求报错：Unexpected keyword argument 'use_beam_search'

### ISSUE THREAD

**Issue by hoofungson** [THUDM/GLM-4#663]
### System Info / 系統信息

运行环境：nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04

### Who can help? / 谁可以帮助到您？

@

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1、运行openai_api_server.py；
2、运行openai_api_request.py；

### Expected behavior / 期待表现

openai_api_server响应AI对话内容。

**Comment by sixsixcoder** [comment]
在源代码中删除该字段即可`use_beam_search`
