### ISSUE TITLE
在v100上, lora 微调完，用transformer 后端可以正常推理，用vllm推理结果全是！！

### ISSUE THREAD

**Issue by hanxiaoyuyu** [THUDM/GLM-4#665]
### System Info / 系統信息

Python 3.10,transformer4.44.0,torch 2.4.0,vllm 0.6.1

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![Snipaste_2024-11-28_15-16-43](https://github.com/user-attachments/assets/55a22d4a-74c6-4e2f-8003-3cfc8f569320)

### Expected behavior / 期待表现

lora 微调后模型能用vllm 后端正确推理

**Comment by sixsixcoder** [comment]
目前GLM-4不支持vllm 0.6.1，您可以尝试降低vllm版本

**Comment by hanxiaoyuyu** [comment]
就finetune_demo 的lora

**Comment by sixsixcoder** [comment]
openai_api_server.py 不支持lora权重加载，你可以尝试使用finetune_demo/inference.py 进行推理

**Comment by hanxiaoyuyu** [comment]
finetune_demo/inference.py 推理是没有问题的，在glm_server.py 中添加了LoRARequest
lora_request = LoRARequest(
        lora_name="lora",
        lora_int_id=1,
        lora_local_path=LORA_PATH)
    async for output in engine.generate(inputs=inputs, sampling_params=sampling_params, request_id=f"{time.time()}",lora_request=lora_request):
        output_len = len(output.outputs[0].token_ids)
        input_len = len(output.prompt_token_ids)
        print(output.outputs[0].token_ids)
        ret = {
            "text": output.outputs[0].text,
            "usage": {
                "prompt_tokens": input_len,
                "completion_tokens": output_len,
                "total_tokens": output_len + input_len
            },
            "finish_reason": output.outputs[0].finish_reason,
        }

**Comment by sixsixcoder** [comment]
你这样操作是对的
