### ISSUE TITLE
GLM-4V-9B的运行问题

### ISSUE THREAD

**Issue by mono-chen** [THUDM/GLM-4#666]
### System Info / 系統信息

我的cuda版本为12.6
pytorch                   2.5.1           py3.10_cuda12.4_cudnn9_0    pytorch
pytorch-cuda              12.4                 h3fd98bf_7    pytorch
pytorch-mutex             1.0                        cuda    pytorch
tokenizers                0.20.3                   pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tomlkit                   0.12.0                   pypi_0    pypi
torchaudio                2.5.1                    pypi_0    pypi
torchvision               0.20.1                   pypi_0    pypi
tornado                   6.4.2                    pypi_0    pypi

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

新建了环境，然后下载了requirement的内容，按照正常的进行中的话，可以进行15/15的读条，就是在进行询问并且上传图片后，出现了
2024-11-28 19:57:47.342 Examining the path of torch.classes raised: Tried to instantiate class '__path__._path', but it does not exist! Ensure that it is registered via torch::class_

GLM-4-chat是可以正常进行的，没什么问题
### Expected behavior / 期待表现

看哪一步出现了问题，谢谢

**Comment by sixsixcoder** [comment]
看起来像是torch路径的问题，你使用的哪个模型和哪个脚本
