### ISSUE TITLE
openai_api_request.py 如何调整输出最大token数

### ISSUE THREAD

**Issue by mamba824824** [THUDM/GLM-4#669]
### System Info / 系統信息

CUDA Version: 12.2

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

本地模型glm-4-9b-chat-GPTQ-Int4，运行openai_api_server.py、openai_api_request.py
如何调整输出最大token数

### Expected behavior / 期待表现

请问如何调整输出最大token数

**Comment by sixsixcoder** [comment]
在`openai_api_request.py`修改`max_tokens`即可
```
response = client.chat.completions.create(
        model="glm-4",
        messages=messages,
        stream=use_stream,
        max_tokens=256,
        temperature=0.4,
        presence_penalty=1.2,
        top_p=0.8,
    )
```

**Comment by sixsixcoder** [comment]
更多openai参数的用法可以google搜索openai sdk的文档，那里会有详细介绍https://platform.openai.com/
