### ISSUE TITLE
多卡运行trans_cli_vision_demo.py报错

### ISSUE THREAD

**Issue by YiXinChenChen** [THUDM/GLM-4#67]
### System Info / 系統信息

torch==2.1.2
transformers==4.40.0

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

CUDA_VISIBLE_DEVICES=5,6,7 python basic_demo/trans_cli_vision_demo.py
报错：
  File "/home/chenyixin03/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 866, in forward
    new_input_embeds.append(torch.cat(
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:2! (when checking argument for argument tensors in method wrapper_CUDA_cat)

### Expected behavior / 期待表现

看到了chat-9b有类似的问题，替换了也不太行，希望解决

**Comment by zRzRzRzRzRzRzR** [comment]
更新一下hf文件

**Comment by YiXinChenChen** [comment]
> 更新一下hf modeling_chatglm文件
hf上面的文件还是旧的
![image](https://github.com/THUDM/GLM-4/assets/19725109/21b79426-bd51-4f78-8071-43781badafcd)

**Comment by yangshao24** [comment]
huggingface上model_chatglm尚未更新

**Comment by zRzRzRzRzRzRzR** [comment]
9v的问题仍在调整，chat问题已经解决

**Comment by zRzRzRzRzRzRzR** [comment]
已经解决，请更新hf代码
