### ISSUE TITLE
glm4v-9b实际参数量是13b吗？

### ISSUE THREAD

**Issue by zezon-liu** [THUDM/GLM-4#673]
<img width="1042" alt="7751734334922_ pic" src="https://github.com/user-attachments/assets/f728d108-7cf6-4399-a69b-164098c79e12" />
glm4v-9b实际参数量是9b还是13b呢？ 命名后面是9b，但是看实际模型参数好像是13b? 那为啥这么命名呢？

**Comment by zhipuch** [comment]
因为有视觉模型，和语言模型加起来将近14B了
