### ISSUE TITLE
GLM-4V-9B推理及微调问题

### ISSUE THREAD

**Issue by mamba824824** [THUDM/GLM-4#680]
### System Info / 系統信息

无

### Who can help? / 谁可以帮助到您？

无

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

GLM-4V-9B有如下使用要求：`GLM-4V-9B` 不支持 `tools` 字段和 `system` 字段。并且 `image` 必须放在第一条消息中。 `image`
  字段需要放置置图片的 `绝对路径`。
由此推理和微调产生如下疑问：
1、 `image` 必须放在第一条消息中，请问任何使用场景都这么要求是不是太苛刻，假如多轮对话的过程中输入了一个图片，请问这种情况该如何处理？
2、不支持`system` 字段，这在使用上是否也有所欠缺。
谢谢。

### Expected behavior / 期待表现

请解答上述疑问。

**Comment by zRzRzRzRzRzRzR** [comment]
因为在这一代模型训练的时候，模型结构和训练数据的格式严格按照了这个格式来做，因此，无法做到上述你提到的两个场景。
这是这一代模型的局限性，我们还在继续改进。
在我们的商用模型中（最新一版），问题2已经解决。
问题1可能会在下一代模型研发的过程中尝试处理，并考虑多图的处理。
感谢你的理解
