### ISSUE TITLE
basic_demo里的glm_server在启用vllm加速推理时默认是流式输出，在某些场景下不太适合，generate_stream_glm4的218行，进处理循环的外围是不是可加一个开关控制选项？

### ISSUE THREAD

**Issue by bolt163** [THUDM/GLM-4#681]
### System Info / 系統信息

linux， 4090

### Who can help? / 谁可以帮助到您？

如题，
1)我理解流式输出应该是比较适合实时展示或交互场景，比如聊天模式，吐出来的内容快能动态快速的展示

2)但对强依赖推理结果完整性的场景，比如需等待LLM完整推理出来再去决策下一步该做什么的场景，流式输出可能并不适用

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
<img width="776" alt="企业微信截图_2f43d509-92ee-43d5-a653-d5a34c21fd55" src="https://github.com/user-attachments/assets/76c77ead-5f3f-4215-a3e7-8a020ec8af47" />

- [ ] My own modified scripts / 我自己修改的脚本和任务
- generate_stream_glm4的218行，进处理循环的外围是不是应该可加一个开关控制选项？ 如果request.stream是True即用户要求流式输出则用demo的逻辑，否则要等待完整的推理输出结果我理解应该只需取当前推理周期最后一次的？
-【我自己修改的逻辑，目前调试下来是Ok的，不知道是否严谨还有遗漏的地方】
<img width="1045" alt="企业微信截图_8493f8d4-7cdb-4065-ad9b-000e736f585a" src="https://github.com/user-attachments/assets/d5fa1d6a-e2ac-4521-960e-0e6cee75de1d" />

### Reproduction / 复现过程

1. 比如基于chatglm跑 自动化测试，先是输出一个总的Plan, 紧接着再是Plan里的每一个具体操作Operation
2. 现在跑的情况来看就是 plan里的内容是分成一个词返回一次或几个词就返回一次
3. 包括Plan里的每一个具体操作Operation里的内容是分成一个词返回一次或几个词就返回一次

### Expected behavior / 期待表现

如题，
1)我理解流式输出应该是比较适合实时展示或交互场景，比如聊天模式，吐出来的内容快能动态快速的展示

2)但对强依赖推理结果完整性的场景，比如需等待LLM完整推理出来再去决策下一步该做什么的场景，流式输出可能并不适用

**Comment by zRzRzRzRzRzRzR** [comment]
这个你可以自行加入，是否流的输出，取决于是否即刻返回，如果你不希望即刻返回，等到模型全部输出完饭回一次就行，不用改vLLM入参导致代码大幅度修改。
这里一定写成流也是这个原因，等到最后一起返回还是变生成边返回。用户只需要关注OpenAI API接口的部分调用就行
