### ISSUE TITLE
self-llm《开源大模型食用指南》更新了对GLM-4-9B-chat模型的部署教程与微调教程！

### ISSUE THREAD

**Issue by KMnO4-zx** [THUDM/GLM-4#71]
### Feature request  / 功能建议

我们更新了包括FastApi、langchain接入、webdemo部署、vLLM部署以及lora微调的全部教程，助力小白萌新也能学会！
https://github.com/datawhalechina/self-llm/tree/master/GLM-4
<img width="435" alt="image" src="https://github.com/THUDM/GLM-4/assets/77671993/7ded1c5b-b92e-49c0-8fd3-093c2ba09d33">

### Motivation / 动机

本项目旨在首先基于核心贡献者的经验，实现国内外主流开源 LLM 的部署、使用与微调教程；在实现主流 LLM 的相关部分之后，我们希望充分聚集共创者，一起丰富这个开源 LLM 的世界，打造更多、更全面特色 LLM 的教程。星火点点，汇聚成海。

**_我们希望成为 LLM 与普罗大众的阶梯，以自由、平等的开源精神，拥抱更恢弘而辽阔的 LLM 世界。_**

### Your contribution / 您的贡献

我们更新了包括FastApi、langchain接入、webdemo部署、vLLM部署以及lora微调的全部教程，助力小白萌新也能学会！
https://github.com/datawhalechina/self-llm/tree/master/GLM-4
<img width="435" alt="image" src="https://github.com/THUDM/GLM-4/assets/77671993/7ded1c5b-b92e-49c0-8fd3-093c2ba09d33">

**Comment by zRzRzRzRzRzRzR** [comment]
感谢你们提供的支持，已经将其放到首页的友情链接中！本issue关闭啦
