### ISSUE TITLE
GLM-4V-9B用bitsandbytes量化后，input错误

### ISSUE THREAD

**Issue by JoeAu** [THUDM/GLM-4#73]
### System Info / 系統信息
windows 10
python 3.10.10
torch                         2.2.1+cu121
transformers                  4.40.0.dev0
bitsandbytes                  0.43.1
accelerate                    0.28.0
RTX 2060 12G

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type='nf4',
    llm_int8_skip_modules=["output_layer"]
)
            
AutoModelForCausalLM.from_pretrained(self.config.model_name,
                                                     trust_remote_code=True,
                                                     quantization_config=quantization_config,
                                                     device_map={"": 0})

image = Image.open(image_path).convert('RGB')
prompt = {"role": "user", "image":image, "content": query}
inputs = self.tokenizer.apply_chat_template([prompt],
                                       add_generation_prompt=True,
                                       tokenize=True,
                                       return_tensors="pt",
                                       return_dict=True
                                       )
inputs = inputs.to(self.device)
outputs = self.model.generate(**inputs)
        
Traceback (most recent call last):
  File "E:\project\LLM\project\langchain\testvl.py", line 53, in <module>
    for response, history in llm.chat(query, image_path=url):
  File "E:\project\clc\glm4.py", line 66, in chat
    outputs = self.model.generate(**inputs, generation_config=self.generation_config)
  File "E:\project\LLM\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\project\LLM\venv\lib\site-packages\transformers\generation\utils.py", line 1577, in generate
    result = self._sample(
  File "E:\project\LLM\venv\lib\site-packages\transformers\generation\utils.py", line 2733, in _sample
    outputs = self(
  File "E:\project\LLM\venv\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\project\LLM\venv\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\project\LLM\venv\lib\site-packages\accelerate\hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Users\Joe\.cache\huggingface\modules\transformers_modules\glm-4v-9b\modeling_chatglm.py", line 1017, in forward
    transformer_outputs = self.transformer(
  File "E:\project\LLM\venv\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\project\LLM\venv\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\project\LLM\venv\lib\site-packages\accelerate\hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Users\Joe\.cache\huggingface\modules\transformers_modules\glm-4v-9b\modeling_chatglm.py", line 855, in forward
    images_features = self.vision(images)
  File "E:\project\LLM\venv\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\project\LLM\venv\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\project\LLM\venv\lib\site-packages\accelerate\hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Users\Joe\.cache\huggingface\modules\transformers_modules\glm-4v-9b\visual.py", line 156, in forward
    x = self.patch_embedding(images)
  File "E:\project\LLM\venv\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\project\LLM\venv\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\project\LLM\venv\lib\site-packages\accelerate\hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Users\Joe\.cache\huggingface\modules\transformers_modules\glm-4v-9b\visual.py", line 42, in forward
    x = self.proj(images)
  File "E:\project\LLM\venv\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\project\LLM\venv\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\project\LLM\venv\lib\site-packages\accelerate\hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "E:\project\LLM\venv\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "E:\project\LLM\venv\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (struct c10::BFloat16) and bias type (struct c10::Half) should be the same

### Expected behavior / 期待表现

同样的量化代码， GLM-4-9B-Chat没问题

**Comment by Nukepayload2** [comment]
I've the same problem. I've added `BitsAndBytesConfig` to `composite_demo\src\clients\hf.py` before running the demo. The chat model works fine. But the VQA model throws `RuntimeError: Input type (struct c10::BFloat16) and bias type (struct c10::Half) should be the same`

**Comment by zRzRzRzRzRzRzR** [comment]
try this?
```
model = AutoModel.from_pretrained(
    MODEL_PATH,
    trust_remote_code=True,
    quantization_config=BitsAndBytesConfig(load_in_4bit=True),
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True
).eval()
```

**Comment by Nukepayload2** [comment]
I've added `low_cpu_mem_usage=True` and restarted the demo, but the problem still exists.
```
  File "F:\GLM-4\env\Lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Input type (struct c10::BFloat16) and bias type (struct c10::Half) should be the same
```

**Comment by zRzRzRzRzRzRzR** [comment]
emm, I am working fine...
Are you sure you using bloat16 ?
try to print(model.dtype)

**Comment by Cuiyn** [comment]
RTX 2060 doesn't support bfloat16. Maybe you can set dtype to `torch.float16`.

**Comment by Nukepayload2** [comment]
@Cuiyn 
My GPU supports `torch.bfloat16`. It has compute capability 8.9. But this problem also happens on my computer.

**Comment by zRzRzRzRzRzRzR** [comment]
I have update it, it work on my service, still not working?

**Comment by Nukepayload2** [comment]
I've pulled the latest commits from both this repo and the glm-4v-9b repo and reapplied the following quant code: 
```python
quant_config4 = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type='nf4',
    llm_int8_skip_modules=["output_layer"]
)
self.model = AutoModelForCausalLM.from_pretrained(
    model_path,
    trust_remote_code=True,
    device_map="cuda", 
    quantization_config=quant_config4,
    low_cpu_mem_usage=True
).eval()
print(f"Model loaded as {self.model.dtype}")
```

But the error message didn't change. It's probably an environment issue or a package compatibility problem. 

**System information**
```
Microsoft Windows 10 x64 (10.0.19045.4412)
NVIDIA Driver Version 551.86
Max CUDA Version: 12.4
Compute capability 8.9
Python 3.11 (from Microsoft Store)
venv
```

`pip list`
```
Package                   Version
------------------------- --------------
accelerate                0.30.1
aiohttp                   3.9.5
aiosignal                 1.3.1
altair                    5.3.0
annotated-types           0.7.0
anyio                     4.4.0
asttokens                 2.4.1
attrs                     23.2.0
bitsandbytes              0.43.1
blinker                   1.8.2
cachetools                5.3.3
certifi                   2024.6.2
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
comm                      0.2.2
contourpy                 1.2.1
cycler                    0.12.1
dataclasses-json          0.6.6
debugpy                   1.8.1
decorator                 5.1.1
einops                    0.8.0
executing                 2.0.1
filelock                  3.14.0
flash_attn                2.5.9.post1
fonttools                 4.53.0
frozenlist                1.4.1
fsspec                    2024.6.0
gitdb                     4.0.11
GitPython                 3.1.43
greenlet                  3.0.3
h11                       0.14.0
httpcore                  1.0.5
httpx                     0.27.0
huggingface-hub           0.23.2
idna                      3.7
intel-openmp              2021.4.0
ipykernel                 6.29.4
ipython                   8.25.0
jedi                      0.19.1
Jinja2                    3.1.4
jsonpatch                 1.33
jsonpointer               2.4
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
jupyter_client            8.6.2
jupyter_core              5.7.2
kiwisolver                1.4.5
langchain                 0.2.1
langchain-community       0.2.1
langchain-core            0.2.3
langchain-text-splitters  0.2.0
langsmith                 0.1.69
lxml                      5.2.2
markdown-it-py            3.0.0
MarkupSafe                2.1.5
marshmallow               3.21.2
matplotlib                3.9.0
matplotlib-inline         0.1.7
mdurl                     0.1.2
mkl                       2021.4.0
mpmath                    1.3.0
multidict                 6.0.5
mypy-extensions           1.0.0
nest-asyncio              1.6.0
networkx                  3.3
numpy                     1.26.4
orjson                    3.10.3
packaging                 23.2
pandas                    2.2.2
parso                     0.8.4
pillow                    10.3.0
pip                       24.0
platformdirs              4.2.2
prompt_toolkit            3.0.45
protobuf                  4.25.3
psutil                    5.9.8
pure-eval                 0.2.2
pyarrow                   16.1.0
pydantic                  2.7.3
pydantic_core             2.18.4
pydeck                    0.9.1
Pygments                  2.18.0
PyJWT                     2.8.0
PyMuPDF                   1.24.5
PyMuPDFb                  1.24.3
pyparsing                 3.1.2
python-dateutil           2.9.0.post0
python-docx               1.1.2
python-pptx               0.6.23
pytz                      2024.1
pywin32                   306
PyYAML                    6.0.1
pyzmq                     26.0.3
referencing               0.35.1
regex                     2024.5.15
requests                  2.32.3
rich                      13.7.1
rpds-py                   0.18.1
safetensors               0.4.3
sentencepiece             0.2.0
setuptools                65.5.0
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.1
SQLAlchemy                2.0.30
stack-data                0.6.3
streamlit                 1.35.0
sympy                     1.12.1
tbb                       2021.12.0
tenacity                  8.3.0
tiktoken                  0.7.0
tokenizers                0.19.1
toml                      0.10.2
toolz                     0.12.1
torch                     2.3.0+cu121
torchvision               0.18.0+cu121
tornado                   6.4
tqdm                      4.66.4
traitlets                 5.14.3
transformers              4.40.0
typing_extensions         4.12.1
typing-inspect            0.9.0
tzdata                    2024.1
urllib3                   2.2.1
watchdog                  4.0.1
wcwidth                   0.2.13
XlsxWriter                3.2.0
yarl                      1.9.4
zhipuai                   2.1.0.20240521
```

**Comment by JoeAu** [comment]
找到解决办法了，AutoModelForCausalLM.from_pretrained要明确torch_dtype=torch.float16

`        quantization_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type='nf4',
            llm_int8_skip_modules=["output_layer"]
        )

        self.model = AutoModelForCausalLM.from_pretrained(self.config.model_name,
                                                          torch_dtype=torch.float16,
                                                     quantization_config=quantization_config,
                                                     trust_remote_code=True,
                                                     device_map={"": 0})`
