### ISSUE TITLE
composite_demo/main.py处理docx有bug

### ISSUE THREAD

**Issue by inorixu** [THUDM/GLM-4#74]
### System Info / 系統信息

不涉及

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. streamlit run ./main.py
2. 上传docx文件
3. 随便问点什么
4. 可以看到 content 是空

### Expected behavior / 期待表现

正确获取content内容
-----------------------------------------------
问题原自：composite_demo/src/utils.py line:21
缺少return content

**Comment by zRzRzRzRzRzRzR** [comment]
fix this，谢谢提出
