### ISSUE TITLE
`inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by cmx4869** [THUDM/GLM-4#76]
### System Info / 系統信息

Ubuntu22.04
cuda12.2
python3.11
所有包都按basic_demo中的requirments进行按爪昂

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

import io
import torch
from PIL import Image
from transformers import AutoModelForCausalLM, AutoTokenizer
from flask import Flask, request, jsonify
import base64

app = Flask(__name__)

device = "cuda"
tokenizer = AutoTokenizer.from_pretrained("/home/administrator/llm_model/glm-4v-9b", trust_remote_code=True)

model = AutoModelForCausalLM.from_pretrained(
    "/home/administrator/llm_model/glm-4v-9b",
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True,
    load_in_4bit=True
).eval()

gen_kwargs = {"max_length": 1000, "do_sample": True, "top_k": 1}

@app.route('/upload', methods=['POST'])
def process_image():
    if not request.is_json:
        return jsonify({"error": "Invalid request format, JSON expected"}), 400

    data = request.get_json()
    if 'image' not in data:
        return jsonify({"error": "No image data provided"}), 400

    base64_data_uri = data['image']
    
    # 移除 data:image/jpeg;base64, 前缀
    if base64_data_uri.startswith("data:image"):
        base64_data_uri = base64_data_uri.split(",")[1]

    try:
        # 解码 base64 数据
        image_data = base64.b64decode(base64_data_uri)
        # 使用PIL读取图像文件
        image = Image.open(io.BytesIO(image_data)).convert('RGB')
    except Exception as e:
        return jsonify({"error": "Invalid image data"}), 400

    query = '提取图片中的文字'

    inputs = tokenizer.apply_chat_template(
        [{"role": "user", "image": image, "content": query}],
        add_generation_prompt=True, tokenize=True, return_tensors="pt",
        return_dict=True
    )  # chat mode

    inputs = inputs.to(device)

    with torch.no_grad():
        outputs = model.generate(**inputs, **gen_kwargs)
        outputs = outputs[:, inputs['input_ids'].shape[1]:]
        result = tokenizer.decode(outputs[0])
        result = result.strip("<|endoftext|>")
        result = [result]

    return jsonify({"text": result})

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5079)

上面是将官方示例改成了flask接口，从接口中获取一个二进制流的图片文件

### Expected behavior / 期待表现

(glm4v) administrator@admin:~/llm_model/GLM-4$ tail test_api_request.log
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/administrator/anaconda3/envs/glm4v/lib/python3.11/site-packages/transformers/generation/utils.py", line 1622, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/home/administrator/anaconda3/envs/glm4v/lib/python3.11/site-packages/transformers/generation/utils.py", line 2829, in _sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
10.3.0.232 - - [06/Jun/2024 06:22:42] "POST /upload HTTP/1.1" 500 -

**Comment by cmx4869** [comment]
随机出现，并不固定哪一张图片文件会产生这种情况

**Comment by vicissitude2000** [comment]
兄弟，我遇到了同样的报错`(GLM4) speak@speech-RTX4090:~/icbc/csdn_glm4/GLM-4-main/basic_demo$ python trans_batch_demo.py
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████| 10/10 [00:05<00:00,  1.73it/s]
We've detected an older driver with an RTX 4000 series GPU. These drivers have issues with P2P. This can affect the multi-gpu inference when using accelerate device_map.Please make sure to update your driver to the latest version which resolves this.
Traceback (most recent call last):
  File "/home/lianghr/icbc/csdn_glm4/GLM-4-main/basic_demo/trans_batch_demo.py", line 87, in <module>
    batch_responses = batch(model, tokenizer, batch_inputs, **gen_kwargs)
  File "/home/lianghr/icbc/csdn_glm4/GLM-4-main/basic_demo/trans_batch_demo.py", line 54, in batch
    batched_outputs = model.generate(**batched_inputs, **gen_kwargs)
  File "/home/lianghr/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/lianghr/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1719, in generate
    return self.sample(
  File "/home/lianghr/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 2837, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0`；
想问一下您是怎么解决的啊

**Comment by wuhaoyu010** [comment]
近2日用A800的卡，多卡多用户并发流式输出一直遇到这个报错，将torch_dtype=torch.float32或torch_dtype=torch.float64 错误就消失了
看的下面的帖子，大概是A系列显卡对BF16  F16支持的不太好
https://github.com/yangjianxin1/Firefly/issues/272
