### ISSUE TITLE
Proper prompt to invoke tool use.

### ISSUE THREAD

**Issue by Fanjia-Yan** [THUDM/GLM-4#79]
Hi team, 

Thank you for the work. What's the right way to invoke function calls? There are some attempts in [demo](https://github.com/THUDM/GLM-4/blob/8102212b9f5f4d418a9f1d4bc773047dabb19366/composite_demo/src/conversation.py#L27) but I did not see the official documentations.

Thanks,

Fanjia

**Comment by CharlieJCJ** [comment]
+1

**Comment by zRzRzRzRzRzRzR** [comment]
在我们的代码中，你可以直接用openai的message格式调用，模型选择的tools会在metadata中填充。这些操作都是在我们tokenizer_chatglm.py中的apply_chat_template的功能构建。
在你说的demo中，工具调用能力是根据已经注册好的工具来做的，你可以搜到 register tools的代码。然后模型的系统提示词中会出现所有的工具，这样模型就能自己调用。
当用户输入请求的时候，assistant会选择对应的工具并构建成response，之后工具调用的内容封装成了observation给assistant，如此循环直到得到答案

**Comment by Fanjia-Yan** [comment]
想问一下怎么通过tool use一次inference invoke多个 tools？感谢！

**Comment by zRzRzRzRzRzRzR** [comment]
只能invoke一个，多个工具输入，选择调用一个工具
