### ISSUE TITLE
官方能出一个底层不是vllm的，支持int4的 openai_api_server_2  demo 程序吗？谢谢

### ISSUE THREAD

**Issue by triumph** [THUDM/GLM-4#82]
### Feature request  / 功能建议

官方能出一个底层不是vllm的，支持int4的 openai_api_server_2  demo 程序吗？谢谢

### Motivation / 动机

官方能出一个底层不是vllm的，支持int4的 openai_api_server_2  demo 程序吗？谢谢

### Your contribution / 您的贡献

官方能出一个底层不是vllm的，支持int4的 openai_api_server_2  demo 程序吗？谢谢

**Comment by zRzRzRzRzRzRzR** [comment]
你说的是transofmers 底座的是吗，然后支持int4读取？

**Comment by triumph** [comment]
就是 我们硬件有限，大概只有10-12G的显存， 我们想本地测试下GLM4的 opeapi模式，

**Comment by RichardFans** [comment]
> openapi

确实亟需一个可量化版本的openai_api_server.py，是否可以利用 #15  [这里](https://github.com/THUDM/GLM-4/issues/15#issuecomment-2149523565) 的方式先量化，再 用于现在的openai_api_server.py？

**Comment by zRzRzRzRzRzRzR** [comment]
那仍然是需要bnb支持的吧，现在vLLM就不支持bnb，应该要自己写一个导入hf模型的入口

**Comment by shaofanqi** [comment]
glm3的apiserver改了一下。https://github.com/shaofanqi/CHATGLM4_Server
