### ISSUE TITLE
glm4v里面的huggingface issue的bug可以修复一下吗

### ISSUE THREAD

**Issue by lucasjinreal** [THUDM/GLM-4#83]
跑不抬起来，另外，啥时候能支持一下flashattn? 目前这个模型显存占用比Qwen14B还大。

**Comment by 1049451037** [comment]
安装torch2就会自动调用flash attn。

**Comment by zRzRzRzRzRzRzR** [comment]
另外，由于具有视觉部分，你需要按照13B的量级进行估算，具体的显存消耗已经在basic demo提到。

**Comment by lucasjinreal** [comment]
不是的，我对比的便是Qwen14B+LLava 和 chatglm9b + LLava，后者bs还不到前者一半，还会OOM。

另外我是torch2的环境，而且flasshattn一直在用，但是跑chatglm会说flashatten不支持。

**Comment by zRzRzRzRzRzRzR** [comment]
flashatten不支持的警告错误发一下
然后，你是在微调还是batch 推理 看你提到了bs

**Comment by lucasjinreal** [comment]
![image](https://github.com/THUDM/GLM-4/assets/21303438/20682176-54c1-41b6-8492-63345c140330)

咋zhi'ch支持的？

报错直接就是ChatGLMForConditionalGeneate doesn't support Flash Attention 2 yet..

**Comment by lucasjinreal** [comment]
@zRzRzRzRzRzRzR 可否帮忙看一下

**Comment by zRzRzRzRzRzRzR** [comment]
是怎么运行的呢，是说 rom_pretrained载入的时候加上attn_implementation="flash_attention_2"这种吗

**Comment by lucasjinreal** [comment]
首先你们代码是自定义的，Attention自己写的，我甚至没有看到flash这个字眼，就想问一下如何enable
flashattention。。

**Comment by 1049451037** [comment]
https://huggingface.co/THUDM/glm-4v-9b/blob/7bcdc71255f32040f2ac5a21cf959b1b4b27cd66/modeling_chatglm.py#L237-L240

使用pytorch2自动就会用flash attention。

**Comment by liuweie** [comment]
@zRzRzRzRzRzRzR 您好，我也遇到了使用flash attention 不支持的问题，我的torch环境是2.3.0， 我是在加载模型的时候传参使用了flash attn,例如：XXX.from_pretrained（attn_implementation=“flash_attention_2”）

**Comment by lucasjinreal** [comment]
我初步推测，是这个模型不支持显示的传入flash2，他是自己根据pytorhc判断的，但是transformers那层逻辑他过不去，应该要实现某个方法，告知transformers可以这么传。

不过，BTW，这种强制根据pytorch判断的也不太科学，万一是V100的torch2.3呢，还是交给用户手动指定更合理一点。不然为什么人家transformers不这么搞？
