### ISSUE TITLE
vllm docker 部署模型无法停止、乱说话的问题

### ISSUE THREAD

**Issue by sycamore792** [THUDM/GLM-4#85]
### System Info / 系統信息

vllm docker 版

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

vllm docker  部署服务端后模型无法输出无法停止以及乱说话

### Expected behavior / 期待表现

何时可以提供该环境下（vllm docker）模型正确使用的支持

**Comment by zRzRzRzRzRzRzR** [comment]
在文档已经写到了，现在不能用docker直接部署。需要定制模板
需要等vLLM官方支持后才能适配。

**Comment by AlphaINF** [comment]
在模型参数的文件中，增加generation_config.json文件，设置以下内容:
{
"eos_token_id": [151329, 151336, 151338]
}
