### ISSUE TITLE
多GPU记载有问题，按照指示更新了modeling chatglm，还是不行的

### ISSUE THREAD

**Issue by xbsdsongnan** [THUDM/GLM-4#86]
### System Info / 系統信息

cuda:11.7
torch:2.0.1

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

每次还是只加载一个GPU

### Expected behavior / 期待表现

怎么修改才可以加载多GPU

**Comment by HysysRobert** [comment]
我的也不行 不知道怎么解决 glm-4-9b-chat代码和模型都是最新的

**Comment by Qingluan** [comment]
> 我的也不行 不知道怎么解决 glm-4-9b-chat代码和模型都是最新的

https://github.com/THUDM/GLM-4/issues/86
这里改成2就好了啊

**Comment by zRzRzRzRzRzRzR** [comment]
我刚才已经测试了是支持多卡的，你更新是hugging face的吗？
