### ISSUE TITLE
GLM-4-9B官方的例子base_demo/openai_api_request.py流式输出内容为空

### ISSUE THREAD

**Issue by zhoumz123** [THUDM/GLM-4#87]
### System Info / 系統信息

CUDA Version: 12.2,
torch==2.3.0
torchvision>=0.18.0
transformers==4.40.0
huggingface-hub>=0.23.1
sentencepiece>=0.2.0
pydantic>=2.7.1
timm>=0.9.16
tiktoken>=0.7.0
accelerate>=0.30.1
sentence_transformers>=2.7.0
vllm>=0.4.3

# web demo
gradio>=4.31.5

# openai demo
openai>=1.30.3
einops>=0.7.0
sse-starlette>=2.1.0

# Int4

bitsandbytes>=0.43.1

打印结果：

ChatCompletionChunk(id='', choices=[Choice(delta=ChoiceDelta(content='{"model":"glm-4","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":"","function_call":null},"finish_reason":null,"index":0}],"created":1717666579}', function_call=None, role='assistant', tool_calls=None), finish_reason=None, index=0, logprobs=None)], created=None, model='glm-4', object='chat.completion.chunk', system_fingerprint=None, usage=None)
{"model":"glm-4","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":"","function_call":null},"finish_reason":null,"index":0}],"created":1717666579}
ChatCompletionChunk(id='', choices=[Choice(delta=ChoiceDelta(content=None, function_call=None, role=None, tool_calls=None), finish_reason='stop', index=0, logprobs=None)], created=None, model='glm-4', object='chat.completion.chunk', system_fingerprint=None, usage=None)
None

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

将openai_api_request.py代码中simple_chat 设置参数use_stream=True
python3 ./openai_api_request.py

### Expected behavior / 期待表现

流式返回正常

**Comment by zRzRzRzRzRzRzR** [comment]
你是用刚才更新的github代码吗，有后台报错吗

**Comment by zhoumz123** [comment]
没有报错，非流式的方法是可以正常返回的，但是流式接口的返回是空

**Comment by zRzRzRzRzRzRzR** [comment]
<img width="1733" alt="image" src="https://github.com/THUDM/GLM-4/assets/93239683/9da35279-afea-4e74-a7f3-645d79b87216">
刚跑的，似乎没有出现你这个问题，你确定是刚才最新的代码吗

**Comment by zhoumz123** [comment]
哦，我的代码是昨天的，刚刚更新最新代码，没有这个问题了，谢谢回复，么么答

**Comment by jiaolongxue** [comment]
我的还有这个问题，

**Comment by jiaolongxue** [comment]
2024-06-06 10:39:53.936 | INFO     | __main__:create_chat_completion:338 - ==== request ====
model='glm-4' messages=[ChatMessage(role='system', content='你是 GLM-4，请你热情回答用户的问题。', name=None, function_call=None), ChatMessage(role='us
er', content='你好，请你用生动的话语给我讲一个小故事吧', name=None, function_call=None)] temperature=0.8 top_p=0.8 max_tokens=1024 stream=True tools=No
ne tool_choice='None' repetition_penalty=1.1
2024-06-06 10:39:53.937 | INFO     | __main__:create_chat_completion:353 - ==== request ====
{'messages': [ChatMessage(role='system', content='你是 GLM-4，请你热情回答用户的问题。', name=None, function_call=None), ChatMessage(role='user', conte
nt='你好，请你用生动的话语给我讲一个小故事吧', name=None, function_call=None)], 'temperature': 0.8, 'top_p': 0.8, 'max_tokens': 1024, 'echo': False, 's
tream': True, 'repetition_penalty': 1.1, 'tools': None, 'tool_choice': 'None'}
2024-06-06 10:39:54.183 | INFO     | __main__:create_chat_completion:360 - First result output：
{"model":"glm-4","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":"","function_call":null},"finish_reason":nu
ll,"index":0}],"created":1717670394}

**Comment by chuangzhidan** [comment]
> <img alt="image" width="1733" src="https://private-user-images.githubusercontent.com/93239683/337221393-9da35279-afea-4e74-a7f3-645d79b87216.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NzEyMTUsIm5iZiI6MTcxNzY3MDkxNSwicGF0aCI6Ii85MzIzOTY4My8zMzcyMjEzOTMtOWRhMzUyNzktYWZlYS00ZTc0LWE3ZjMtNjQ1ZDc5Yjg3MjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDEwNDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNjM1YTE4MDUwNmEzYTE1Y2RjZTRjNzg0OTViNDU1Njc2YzljYTY4MThkNzY2YWVhNzBhYTJhZmUxN2UzMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7iCcRfXzhQAuOVW68tBfmEbDEc0eJxCEZb1c8Mv_U4Q"> 刚跑的，似乎没有出现你这个问题，你确定是刚才最新的代码吗

这种不是一般理解的流式，因为占了整个屏幕内容。

对了，问下作者大大，我用服务器跑9b的时候（运行官方库里的示例）发现下面的名字model怎么改都不影响服务输出。
model = 'glm-4-9b-chat'
base_url = "http://10.0.13.15:8008/v1/"

**服务器运行function call时，报错，但本地结果如下：**
PS D:\repo\GLM-4\basic_demo> python .\openai_api_request.py
在一个遥远的国度里，有一个名叫绿野的小村庄。这里四季如春，山清水秀，风景宜人。村子里的人们勤劳善良，和睦相处。                                                                              
                                                                                                                                                                                            
有一天，村里来了一位神秘的老人。他身穿一袭青衣，头戴斗笠，手持一根拐杖。老人口中念念有词，仿佛在施展着某种神奇的魔法。村民们好奇地围了上来，纷纷询问老人的来历和目的。                      
                                                                                                                                                                                            
老人微笑着告诉他们：“我是来自远方的旅者，路过此地。听说你们村子风调雨顺、民风淳朴，特来拜访。”说完，他从袖子中取出一颗晶莹剔透的宝石，说：“这颗宝石拥有神奇的力量，能够驱除邪恶，带来好运。”

村民们闻言纷纷惊叹不已，认为这是上天的恩赐。于是，他们将老人当作尊贵的客人款待，为他准备了丰盛的食物和美酒。临走时，老人将那颗宝石赠予了村子。

从此，绿野村的村民过上了幸福美满的生活。然而，好景不长，一场突如其来的灾难降临到这个美丽的村落。一股黑雾笼罩了整个村庄，村民们惊慌失措，四处逃散。

就在这时，那位神秘的老者再次出现在村口。只见他手持那颗宝石，口中念动咒语。瞬间，黑雾消散，天空恢复了晴朗。原来，那股黑雾是邪恶势力所为，企图吞噬这片美好的土地。

为了守护家园，村民们决定寻找传说中的神剑——青龙剑。据说，只有持有青龙剑的人才能击败邪恶势力，拯救绿野村。

历经千辛万苦，村民们终于找到了青龙剑。正当大家欣喜若狂之际，却发现那颗宝石已经消失不见。原来，邪恶势力偷走了宝石，试图用它控制神剑。

勇敢的青年阿强挺身而出，誓要夺回宝石，保卫家乡。经过一番激战，阿强成功地将邪恶势力打败，夺回了宝石。此时，天空突然出现一道闪电，将宝石击碎成无数碎片。

每一片碎片都化作了光芒四射的神石，散落在绿野村四周的山川河流之中。这些神石不仅为村庄带来了无尽的福祉，还赋予了村民们强大的力量。

自此，绿野村成为了人间仙境。村民们铭记着神秘老人的恩情，继续传承着正义与和平的信念。而那个关于青龙剑和宝石的传说，也流传千古，成为了一代又一代人心中的传奇故事。
get_current_weather
**{"location": "San Francisco, CA"}**

这里的结果是不是错误，因为用户问的是"content": "What's the weather like in **San Francisco, Tokyo, and Paris?**

**Comment by zRzRzRzRzRzRzR** [comment]
model 这个字段本身只是凑 openai 接口用的，没有实际的实现

**Comment by zRzRzRzRzRzRzR** [comment]
1M 模型长度的问题可以尝试增加惩罚系数那个参数（调整到1.1-1.2就行了）

**Comment by chuangzhidan** [comment]
> 1M 模型长度的问题可以尝试增加惩罚系数那个参数（调整到1.1-1.2就行了）

好的，谢谢。从输出看agent这个能力不甚理想，可以支持吗，主要是支持openai风格和chatopenai。目前这两种都不能调用工具

**Comment by zhoumz123** [comment]
问题解决，谢谢大家

**Comment by chuangzhidan** [comment]
> 1M 模型长度的问题可以尝试增加惩罚系数那个参数（调整到1.1-1.2就行了）

看了demo的例子的就是1.1：presence_penalty=1.1
