### ISSUE TITLE
运行streamlit run src/main.py,然后用多模态问答，报错，问题：RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat)

### ISSUE THREAD

**Issue by qihanghou726** [THUDM/GLM-4#93]
我遇到了相同的问题，我是通过修改GLM-4/composite_demo/src/clients/hf.py文件夹中:

class HFClient(Client):
def init(self, model_path: str):
self.tokenizer = AutoTokenizer.from_pretrained(
model_path, trust_remote_code=True,
)
self.model = AutoModelForCausalLM.from_pretrained(
model_path,
trust_remote_code=True,
torch_dtype=torch.bfloat16,

#device_map="cuda",
#修改成可以多卡跑
device_map="auto",
).eval()

这一段将device_map="cuda",=>device_map="auto"，然后模型就可以在多张GPU上加载，然后我通过网页端来进行多模态的问答，会给我报以上错误。
所以说是我让GLM4在多张GPU上加载的方式不对，还是什么问题？

**Comment by xbsdsongnan** [comment]
我也是这样。遇到这个问题

**Comment by vcadillog** [comment]
I solved the issue by moving the tensor to the image device, just replace in the file modeling_chatglm.py:

This:
                    new_input_embeds.append(torch.cat(
                        (inputs_embeds[i, :boi_token_pos], images_features[i], inputs_embeds[i, eoi_token_pos + 1:])))
With this:

                    new_input_embeds.append(torch.cat(
                        (inputs_embeds[i, :boi_token_pos], images_features[i].to(inputs_embeds.device), inputs_embeds[i, eoi_token_pos + 1:])))

With that it works in multiple gpu's.

**Comment by qihanghou726** [comment]
我发现了 是显存问题....换了INT4精度就可以正确出结果了，具体怎么换的 请看这个网页
https://zhipu-ai.feishu.cn/wiki/RuMswanpkiRh3Ok4z5acOABBnjf

**Comment by ZengYanshan** [comment]
我也遇到了这个报错，把`device_map='auto'`改成`device_map='cuda'`可解（前提是单卡跑得起来）
