### ISSUE TITLE
感谢开源，HF 和 魔搭 上没看到 glm-4v-9b-int4 的量化模型，是没发布，还是要自己量化？

### ISSUE THREAD

**Issue by heuet** [THUDM/GLM-4#94]
glm-4v-9b 比 cogvlm2 性能提升很多。效果也不错。在A800上跑 cogvlm2 识别一张图要10s， glm-4v-9b 2-3秒多。

**Comment by zRzRzRzRzRzRzR** [comment]
需要自己量化哦

**Comment by RichardFans** [comment]
> 需要自己量化哦
是否直接这样也能量化使用模型？
```
tokenizer = AutoTokenizer.from_pretrained("THUDM/glm-4-9b-chat", trust_remote_code=True).quantize(4).cuda()
```

**Comment by genius0182** [comment]
model = AutoPeftModelForCausalLM.from_pretrained(
            model_dir, trust_remote_code=trust_remote_code, device_map='auto',load_in_4bit=True
        )
加load_in_4bit=True 这样量化成int4.

**Comment by heuet** [comment]
> model = AutoPeftModelForCausalLM.from_pretrained( model_dir, trust_remote_code=trust_remote_code, device_map='auto',load_in_4bit=True ) 加load_in_4bit=True 这样量化成int4.

还是 占了 28G 显存。没有降低呢。

**Comment by zRzRzRzRzRzRzR** [comment]
不是的，建议看demo中的具体读入方法

**Comment by garmanwu** [comment]
https://github.com/THUDM/GLM-4/blob/main/basic_demo/trans_web_vision_demo.py
