### ISSUE TITLE
GLM4 模型测试报错

### ISSUE THREAD

**Issue by chenjf2015103095** [THUDM/GLM-4#95]
### System Info / 系統信息

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

device = "cuda"

tokenizer = AutoTokenizer.from_pretrained("/media/data/media/LangChain-ChatGLM-Webui/model/glm-4-9b-chat",trust_remote_code=True)
print(tokenizer)

query = "你好"

inputs = tokenizer.apply_chat_template([{"role": "user", "content": query}],
                                       add_generation_prompt=True,
                                       tokenize=True,
                                       return_tensors="pt",
                                       return_dict=True
                                       )

inputs = inputs.to(device)
model = AutoModelForCausalLM.from_pretrained(
    "/media/data/media/LangChain-ChatGLM-Webui/model/glm-4-9b-chat",
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True
).to(device).eval()

gen_kwargs = {"max_length": 2500, "do_sample": True, "top_k": 1}
with torch.no_grad():
    outputs = model.generate(**inputs, **gen_kwargs)
    outputs = outputs[:, inputs['input_ids'].shape[1]:]
    print(tokenizer.decode(outputs[0], skip_special_tokens=True))

这是modelscope社区的测试代码，模型从modelscope社区下载到本地，但是运行脚本一直报错：
Traceback (most recent call last):
  File "/datum/slifeai/windows195/GLM-4/basic_demo/test.py", line 7, in <module>
    tokenizer = AutoTokenizer.from_pretrained("/datum/slifeai/windows195/glm-4-9b-chat",trust_remote_code=True) #trust_remote_code=True
  File "/home/slifeai/.conda/envs/llama3/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 847, in from_pretrained
    return tokenizer_class.from_pretrained(
  File "/home/slifeai/.conda/envs/llama3/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2089, in from_pretrained
    return cls._from_pretrained(
  File "/home/slifeai/.conda/envs/llama3/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2311, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/slifeai/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/tokenization_chatglm.py", line 35, in __init__
    rank = int(rank)
ValueError: invalid literal for int() with base 10: 'https://git-lfs.github.com/spec/v1'

### Who can help? / 谁可以帮助到您？

Who can help?

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

device = "cuda"

tokenizer = AutoTokenizer.from_pretrained("/media/data/media/LangChain-ChatGLM-Webui/model/glm-4-9b-chat",trust_remote_code=True)
print(tokenizer)

query = "你好"

inputs = tokenizer.apply_chat_template([{"role": "user", "content": query}],
                                       add_generation_prompt=True,
                                       tokenize=True,
                                       return_tensors="pt",
                                       return_dict=True
                                       )

inputs = inputs.to(device)
model = AutoModelForCausalLM.from_pretrained(
    "/media/data/media/LangChain-ChatGLM-Webui/model/glm-4-9b-chat",
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True
).to(device).eval()

gen_kwargs = {"max_length": 2500, "do_sample": True, "top_k": 1}
with torch.no_grad():
    outputs = model.generate(**inputs, **gen_kwargs)
    outputs = outputs[:, inputs['input_ids'].shape[1]:]
    print(tokenizer.decode(outputs[0], skip_special_tokens=True))

### Expected behavior / 期待表现

希望能尽快解决，谢谢

**Comment by xbsdsongnan** [comment]
我运行加载的时候，出错，OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /home/GLM-4/glm-4-9b-chat.

**Comment by xbsdsongnan** [comment]
pytorch_model.bin, tf_model.h5, model.ckpt.index这几个模型是怎么回事

**Comment by chenjf2015103095** [comment]
你这是从哪里下载的模型哦，这个测试代码如此的简单，不知道为啥会一直报错，然后也没人解决

**Comment by xbsdsongnan** [comment]
我从huggingfac下载的

**Comment by chenjf2015103095** [comment]
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

device = "cuda"

tokenizer = AutoTokenizer.from_pretrained("/datum/slifeai/windows195/glm-4-9b-chat")
print(tokenizer)
就这段代码加载分词器都报错:
The repository for /datum/slifeai/windows195/glm-4-9b-chat contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co//datum/slifeai/windows195/glm-4-9b-chat.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] Traceback (most recent call last):
  File "/home/slifeai/.conda/envs/llama3/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 600, in resolve_trust_remote_code
    answer = input(
  File "/home/slifeai/.conda/envs/llama3/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 581, in _raise_timeout_error
    raise ValueError(
ValueError: Loading this model requires you to execute custom code contained in the model repository on your local machine. Please set the option `trust_remote_code=True` to permit loading of this model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/datum/slifeai/windows195/GLM-4/basic_demo/test_local.py", line 6, in <module>
    tokenizer = AutoTokenizer.from_pretrained("/datum/slifeai/windows195/glm-4-9b-chat")
  File "/home/slifeai/.conda/envs/llama3/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 834, in from_pretrained
    trust_remote_code = resolve_trust_remote_code(
  File "/home/slifeai/.conda/envs/llama3/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 613, in resolve_trust_remote_code
    raise ValueError(
ValueError: The repository for /datum/slifeai/windows195/glm-4-9b-chat contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co//datum/slifeai/windows195/glm-4-9b-chat.
Please pass the argument `trust_remote_code=True` to allow custom code to be run.
这还没入门就报错，之前llama3 也没出现这种问题呀

**Comment by xbsdsongnan** [comment]
我的是找不到几个不存在的模型

**Comment by chenjf2015103095** [comment]
The repository for /datum/slifeai/windows195/glm-4-9b-chat contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co//datum/slifeai/windows195/glm-4-9b-chat.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] Traceback (most recent call last):
  File "/home/slifeai/.conda/envs/glm/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 600, in resolve_trust_remote_code
    answer = input(
  File "/home/slifeai/.conda/envs/glm/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 581, in _raise_timeout_error
    raise ValueError(
ValueError: Loading this model requires you to execute custom code contained in the model repository on your local machine. Please set the option `trust_remote_code=True` to permit loading of this model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/datum/slifeai/windows195/GLM-4/basic_demo/trans_cli_demo.py", line 43, in <module>
    tokenizer = AutoTokenizer.from_pretrained(
  File "/home/slifeai/.conda/envs/glm/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 834, in from_pretrained
    trust_remote_code = resolve_trust_remote_code(
  File "/home/slifeai/.conda/envs/glm/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 613, in resolve_trust_remote_code
    raise ValueError(
ValueError: The repository for /datum/slifeai/windows195/glm-4-9b-chat contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co//datum/slifeai/windows195/glm-4-9b-chat.
 /datum/slifeai/windows195/glm-4-9b-chat是我本地模型的路径，为什么会变成https://hf.co//datum/slifeai/windows195/glm-4-9b-chat.

**Comment by chenjf2015103095** [comment]
linux不就是这样的路径吗？我这就是绝对路径





------------------ 原始邮件 ------------------
发件人: mingyue0094 ***@***.***&gt;
发送时间: 2024年6月7日 11:55
收件人: THUDM/GLM-4 ***@***.***&gt;
抄送: chenjf2015103095 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [THUDM/GLM-4] GLM4 模型测试报错 (Issue #95)





 
要写为 c:/文件/datum/slifeai/windows195/glm-4-9b-chat  带盘符的全路径。 你的写法，代码会自动拉去 hf.co 路径上的模型，

**Comment by xbsdsongnan** [comment]
[OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /root/.cache/modelscope/hub/qwen/Qwen-14B-Chat.](https://www.cnblogs.com/dhcn/p/18034075)
      问题场景，对模型做微调任务，下载模型文件时，报如标题所示的错误，

      错误发生原因，下载时在远程模型目录里面寻找以上文件不可得，就会报错，具体原因是modelscope的模型文件目录里面没有以上文件，但实际上 这个目录下面的模型描述文件是model.safetensors.index.json，不是以上列表中的文件。可以用推理任务先把模型库文件完整下载至本地缓存目录，启动微调任务，就可以解决这个问题。

**Comment by wangyuwei92** [comment]
检查下你的tokenizer.model 下载的是否有问题

**Comment by chenjf2015103095** [comment]
可以了 感谢





------------------ 原始邮件 ------------------
发件人: wangyuwei92 ***@***.***&gt;
发送时间: 2024年6月12日 10:54
收件人: THUDM/GLM-4 ***@***.***&gt;
抄送: chenjf2015103095 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [THUDM/GLM-4] GLM4 模型测试报错 (Issue #95)





 
检查下你的tokenizer.model 下载的是否有问题
