### ISSUE TITLE
glm4的微调一定要使用bf16的类型吗？可以换成其他的吗？

### ISSUE THREAD

**Issue by Alexzhibin** [THUDM/GLM-4#96]
我的卡是v100，不支持bf16。glm4的微调一定要使用bf16的类型吗？可以换成其他数据类型吗？
如果可以支持的话，只需要改图上的地方吗？还有哪些地方需要修改的呢？ 感谢大佬的回答

![1](https://github.com/THUDM/GLM-4/assets/12455562/11007357-be49-4561-b3c2-0d1b88146534)

**Comment by zRzRzRzRzRzRzR** [comment]
一定，不然会出现loss 为nan

**Comment by Alexzhibin** [comment]
谢谢
