### ISSUE TITLE
多卡微调报错

### ISSUE THREAD

**Issue by chengfusheng-code** [THUDM/GLM-4#97]
### System Info / 系統信息

cuda11.8，，python3.10.6

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
C:\Users\leihao\LLM\LLaMA-Factory\src\llamafactory\launcher.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-06-07_10:49:21
  host      : DESKTOP-HL8N0FI.lan
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 21680)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-07_10:49:21
  host      : DESKTOP-HL8N0FI.lan
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 6972)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

### Expected behavior / 期待表现

是

**Comment by zRzRzRzRzRzRzR** [comment]
或许你应该到llama factory 的仓库提问，不是这个仓库
