### ISSUE TITLE
GLM4 训练显存以及网络结构疑问

### ISSUE THREAD

**Issue by Tendo33** [THUDM/GLM-4#99]
### System Info / 系統信息

- Platform: Linux-4.19.72-300.el7.x86_64-x86_64-with-glibc2.35
- Python version: 3.10.14
- PyTorch version: 2.3.0+cu121 (GPU)
- Transformers version: 4.41.2
- Datasets version: 2.19.1
- Accelerate version: 0.30.1
- PEFT version: 0.11.1
- TRL version: 0.8.6
- GPU type: NVIDIA A100-SXM4-80GB
- DeepSpeed version: 0.14.0
- vLLM version: 0.4.3

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

- 其中蓝色跟橙色是 GLM4-9B 训练过程的显存占用
- 红色是 YI-9B 的显存占用
![image](https://github.com/THUDM/GLM-4/assets/86536994/4c72522c-866a-446b-8683-691d1441d9de)

为什么yi 训练过程的显存占用是一个恒定值，而 glm4 是一个波动的。

<img width="840" alt="bc4d4db909e5aba79f126453f32393d" src="https://github.com/THUDM/GLM-4/assets/86536994/e5275b8e-20e8-4a15-8875-ae4b3fa93294">

这里的网络结构我也有点疑问，output_layer，在forward里好像没用上啊，是需要的时候再用。

### Expected behavior / 期待表现

希望大佬解答一下

**Comment by zRzRzRzRzRzRzR** [comment]
这个是生成的时候用的呀，然后训练中显存有变化应该是在训练嗲吗中释放了input
